### ISSUE TITLE
Duplicati 2.0 - Error restoring "An entry with the same key already exists"

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1014]
_From [gilles.f...@gmail.com](https://code.google.com/u/104786025713085796135/) on May 05, 2014 13:57:08_

What steps will reproduce the problem? 1. Restore latest backup with no db What is the expected output? What do you see instead? I made tests making a complete restore a > 200GB Backup directly on the server where backups are stored (Windows server). Restore runs and builds local database but just after that fails at some point with an error "an entry with the same key already exists" What version of Duplicati are you using? On what operating system? 2.0 What backend (destination) are you using? FTP (local) Please provide any additional information below. Command used : 
"Duplicati.CommandLine.exe" restore "ftp://xxx:zzz@yyy.nanoxi.com/Nanoxi/Projets --restore-path=D:/temp/duplicatirestore --verbose --log-file=D:\temp\logfile.txt --log-level=profiling

Detailed error :
Profiling: Recreate temporary database for restore took 07:09.040
Profiling: Running Restore took took 07:53.160
Error: Terminated with error: An entry with the same key already exists.
System.ArgumentException: An entry with the same key already exists.
   at System.Collections.Generic.SortedList`2.Add(TKey key, TValue value)
   at Duplicati.Library.Main.Database.LocalRecreateDatabase.FindMissingBlocklistHashes(Int64 hashsize, IDbTransaction transaction)
   at Duplicati.Library.Main.Operation.RecreateDatabaseHandler.DoRun(LocalDatabase dbparent, IFilter filter, NumberedFilterFilelistDelegate filelistfilter, BlockVolumePostProcessor blockprocessor)
   at Duplicati.Library.Main.Operation.RestoreHandler.Run(String[] paths, IFilter filter)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, Action`1 method)

**Attachment:** [logfile.txt](http://code.google.com/p/duplicati/issues/detail?id=987)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=987_
##

**Comment by kenkendk** [comment]
I think this is fixed.
