### ISSUE TITLE
Duplicati 2: exception on include/exclude filter mix

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1016]
_From [xxk...@gmail.com](https://code.google.com/u/115022481794450078028/) on May 12, 2014 17:37:29_

What steps will reproduce the problem? Duplicati.CommandLine.exe  backup  --include="C:\logs**.txt"  --include="C:\logs*\"  --include="C:\logs\"  --exclude="C:\logs*"  --exclude="C:\Users\ugarov\AppData\Roaming\Skype*"  --google-username=***\* --google-password=***\* --passphrase=***\* googledocs://duplicati2/  --verbose --dry-run  "C:\Users\ugarov"  "C:\logs"

What is the expected output? 
Should backup everything under C:\Users\ugarov\ except AppData\Roaming\Skype\ and only .txt files under c:\logs

What do you see instead?
Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'Duplicati.Library.Utility.JoinedFilterExpression' to type 'Duplicati.Library.Utility.FilterExpression'.
   at Duplicati.Library.Utility.FilterExpression.Matches(IFilter filter, String path)
   at Duplicati.Library.Main.Operation.BackupHandler.AttributeFilter(String rootpath, String path, FileAttributes attributes)
   at Duplicati.Library.Utility.Utility.<EnumerateFileSystemEntries>c__Iterator0.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at Duplicati.Library.Main.Operation.BackupHandler.CountFilesThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart() What version of Duplicati are you using? On what operating system? Version: 2.0-exp-2013-11-20 - DEBUG What backend (destination) are you using? google drive

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=989_
##

**Comment by kenkendk** [comment]
I think this has been fixed.
