### ISSUE TITLE
Cant read file list from a backup

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1018]
_From [tun...@rbm.tv](https://code.google.com/u/104628945756113309990/) on May 14, 2014 16:27:55_

What steps will reproduce the problem? 1. try to restore a previous backup
2. On the "Select restore folder" screen check the "Restore only the items selected below" option.
3. It tries to read the file list and 3-5 seconds later gives:

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Duplicati.GUI.HelperControls.BackupFileList.NodeSorter.Compare(Object x, Object y)
   at System.Windows.Forms.TreeNode.AddSorted(TreeNode node)
   at System.Windows.Forms.TreeNodeCollection.AddInternal(TreeNode node, Int32 delta)
   at Duplicati.GUI.HelperControls.BackupFileList.backgroundWorker_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e) What is the expected output? What do you see instead? The file list of backup What version of Duplicati are you using? On what operating system? 1.3.4 with windows 7 Home Premium 64 bit What backend (destination) are you using? A folder on local drive.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=991_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
