### ISSUE TITLE
Duplicati will not run back ups, since 5/19/14, scheduled or requested as immediate back up

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1025]
_From [o...@mail.nfls.lib.wi.us](https://code.google.com/u/117729986744365526809/) on May 22, 2014 18:40:07_

What steps will reproduce the problem? 1.requesting an immediate back up 2. 3. What is the expected output? What do you see instead? expected output would be an immediate back up

this error message appears instead:

Error: The server certificate had the error RemoteCertificateNameMismatch and the hash 50BAB94D2D30F9B49D68A3A291FF4D0457116A30 Use the commandline option --accept-specified-ssl-hash= 50BAB94D2D30F9B49D68A3A291FF4D0457116A30 to accept the server certificate anyway

Error: Duplicati.Library.Utility.SslCertificateValidator+InvalidCertificateException: The server certificate had the error RemoteCertificateNameMismatch and the hash 50BAB94D2D30F9B49D68A3A291FF4D0457116A30 Use the commandline option --accept-specified-ssl-hash= 50BAB94D2D30F9B49D68A3A291FF4D0457116A30 to accept the server certificate anyway
   at Duplicati.Library.Utility.SslCertificateValidator.Deactivate()
   at Duplicati.Library.Utility.SslCertificateValidator.Dispose()
   at Duplicati.Library.Modules.Builtin.HttpOptions.Dispose()
   at Duplicati.Library.Main.Interface.Dispose()
   at Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
Cleanup output:
Error: Duplicati.Library.Utility.SslCertificateValidator+InvalidCertificateException: The server certificate had the error RemoteCertificateNameMismatch and the hash 50BAB94D2D30F9B49D68A3A291FF4D0457116A30 Use the commandline option --accept-specified-ssl-hash= 50BAB94D2D30F9B49D68A3A291FF4D0457116A30 to accept the server certificate anyway
   at Duplicati.Library.Utility.SslCertificateValidator.Deactivate()
   at Duplicati.Library.Utility.SslCertificateValidator.Dispose()
   at Duplicati.Library.Modules.Builtin.HttpOptions.Dispose()
   at Duplicati.Library.Main.Interface.Dispose()
   at Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
Cleanup output:
Error: Duplicati.Library.Utility.SslCertificateValidator+InvalidCertificateException: The server certificate had the error RemoteCertificateNameMismatch and the hash 50BAB94D2D30F9B49D68A3A291FF4D0457116A30 Use the commandline option --accept-specified-ssl-hash= 50BAB94D2D30F9B49D68A3A291FF4D0457116A30 to accept the server certificate anyway
   at Duplicati.Library.Utility.SslCertificateValidator.Deactivate()
   at Duplicati.Library.Utility.SslCertificateValidator.Dispose()
   at Duplicati.Library.Modules.Builtin.HttpOptions.Dispose()
   at Duplicati.Library.Main.Interface.Dispose()
   at Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task) What version of Duplicati are you using? On what operating system? 1.3.4       Windows 7 Professional What backend (destination) are you using? OneDrive +50 Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=998_

**Comment by kenkendk** [comment]
This is fixed with the new OneDrive OAuth based login.
