### ISSUE TITLE
Incremental won't restore - two modes of error output

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1028]
_From [leland.s...@gmail.com](https://code.google.com/u/116081393478600508328/) on June 09, 2014 06:15:06_

What steps will reproduce the problem? 1. Attempt to restore my incremental from Google Drive using direct files access method.
2. Using primary option of all files
OR
3. Using dialog to select particular items from the incremental What is the expected output? What do you see instead? (2) above has a reasonable error response that:
"The restore operation failed: The backup contains 5 folders but 2 target folders were supplied."

(3) above gives a stack dump of one of two forms:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Duplicati.GUI.HelperControls.BackupFileList.NodeSorter.Compare(Object x, Object y)
   at System.Windows.Forms.TreeNode.AddSorted(TreeNode node)
   at System.Windows.Forms.TreeNodeCollection.AddInternal(TreeNode node, Int32 delta)
   at Duplicati.GUI.HelperControls.BackupFileList.backgroundWorker_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e)

OR

System.NullReferenceException: Object reference not set to an instance of an object.
   at Duplicati.GUI.HelperControls.BackupFileList.RefreshRootDisplay(Boolean sort)
   at Duplicati.GUI.HelperControls.BackupFileList.get_CheckedFiles()
   at Duplicati.GUI.Wizard_pages.Restore.TargetFolder.TargetFolder_PageLeave(Object sender, PageChangedArgs args)
   at System.Windows.Forms.Wizard.WizardControl.System.Windows.Forms.Wizard.IWizardControl.Leave(IWizardForm owner, PageChangedArgs args)
   at System.Windows.Forms.Wizard.Dialog.BackBtn_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) What version of Duplicati are you using? On what operating system? Duplicati 1.3.4.0
Windoz 8.1 Pro x64 What backend (destination) are you using? Google Drive Please provide any additional information below.

**Attachment:** [NET error.txt](http://code.google.com/p/duplicati/issues/detail?id=1001)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=1001_
##

**Comment by kenkendk** [comment]
We are no longer maintaining 1.3.x
