### ISSUE TITLE
Compression 7z

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1073]
_From [ulic...@gmail.com](https://code.google.com/u/103035830080726123524/) on August 02, 2014 17:36:54_

What steps will reproduce the problem? 1.Server with option --compression-module=7z What is the expected output? What do you see instead? 2. 8. 2014 17:29:16
Failed while executing "Backup" with id: 1
System.Threading.ThreadAbortException: Thread was being aborted.
at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(String path, FileAttributes attributes)
at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, Action`1 method)
at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue) What version of Duplicati are you using? On what operating system? latest What backend (destination) are you using? Folder Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=1046_

**Comment by YasharF** [comment]
--compression-module=7z  seems to be working fine on the latest builds.  Can we close this issue?

**Comment by renestach** [comment]
Yes, I think this is solved and furthermore the original reporter does not seem to care...
