### ISSUE TITLE
Crashing while performing backup

### ISSUE THREAD

**Issue by slauber** [duplicati/duplicati#1086]
Duplicati crashes while backing up 53371 files to OneDrive (192,41) via an 5MBit/s uplink at an early stage. 57 parts (50MB each) were uploaded, restarting the host and backup didn't change anything.

Windows crash report:
Problem signature:
  Problem Event Name:   CLR20r3
  Problem Signature 01: Duplicati.GUI.TrayIcon.exe
  Problem Signature 02: 2.0.0.57
  Problem Signature 03: 53e9daf3
  Problem Signature 04: Duplicati.Library.Compression
  Problem Signature 05: 2.0.0.57
  Problem Signature 06: 53e9dad5
  Problem Signature 07: 18
  Problem Signature 08: 15
  Problem Signature 09: System.InvalidOperationException
  OS Version:   6.3.9600.2.0.0.256.48
  Locale ID:    1031
  Additional Information 1: 5861
  Additional Information 2: 5861822e1919d7c014bbb064c64908b2
  Additional Information 3: 4754
  Additional Information 4: 47547fafc9a3073a5bbe8e69322a8db5

Last log entries:
Dienstag, 12. August 2014 16:52:13
Failed to delete temp file: C:\Users\xyz\AppData\Local\Temp\dup-47504c3f-4a9d-402d-b4cf-834fc095fc37
System.IO.IOException: The process cannot access the file 'C:\Users\xyz\AppData\Local\Temp\dup-47504c3f-4a9d-402d-b4cf-834fc095fc37' because it is being used by another process.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.File.InternalDelete(String path, Boolean checkHost)
at System.IO.File.Delete(String path)
at Duplicati.Library.Utility.TempFile.RemoveOldApplicationTempFiles(Action`2 errorcallback)
Dienstag, 12. August 2014 16:52:13
Failed to delete temp file: C:\Users\xyz\AppData\Local\Temp\dup-72f41bef-a483-4d65-b610-da36fb47663d
System.IO.IOException: The process cannot access the file 'C:\Users\xyz\AppData\Local\Temp\dup-72f41bef-a483-4d65-b610-da36fb47663d' because it is being used by another process.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.File.InternalDelete(String path, Boolean checkHost)
at System.IO.File.Delete(String path)
at Duplicati.Library.Utility.TempFile.RemoveOldApplicationTempFiles(Action`2 errorcallback)
Dienstag, 12. August 2014 16:52:13
Failed to delete temp file: C:\Users\xyz\AppData\Local\Temp\dup-91c18d37-157b-4795-936b-8d1c5b083aa6
System.IO.IOException: The process cannot access the file 'C:\Users\xyz\AppData\Local\Temp\dup-91c18d37-157b-4795-936b-8d1c5b083aa6' because it is being used by another process.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.File.InternalDelete(String path, Boolean checkHost)
at System.IO.File.Delete(String path)
at Duplicati.Library.Utility.TempFile.RemoveOldApplicationTempFiles(Action`2 errorcallback)
Dienstag, 12. August 2014 16:52:13
Failed to delete temp file: C:\Users\xyz\AppData\Local\Temp\dup-d97d8377-825a-44fe-be81-5d82ec3663ac
System.IO.IOException: The process cannot access the file 'C:\Users\xyz\AppData\Local\Temp\dup-d97d8377-825a-44fe-be81-5d82ec3663ac' because it is being used by another process.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.File.InternalDelete(String path, Boolean checkHost)
at System.IO.File.Delete(String path)
at Duplicati.Library.Utility.TempFile.RemoveOldApplicationTempFiles(Action`2 errorcallback)
##

**Comment by Pectojin** [comment]
I'm sorry this was never addressed.

It looks like it's a temporary issue that probably went away by itself a long time ago, but if you're still experiencing this or similar problems can you open a new issue? 

That way it's much more likely to get attention as it won't be burried below 700 newer open issues.
