### ISSUE TITLE
No Such File

### ISSUE THREAD

**Issue by dragon2611** [duplicati/duplicati#1126]
I have a backup over a remote WAN using SSH, due to the speed of the connection it's taking a fairly long time, and due to the fact it's from a home machine the PC isn't on 24x7

Anyway I think I've managed to get it in a state where Duplicati has deleted a file that wasn't properly uploaded but it now tries to delete the file again every time the backup is run which causes a failure with "No such file"

removing incomplete remote file listed as Uploading: duplicati-b22cb36c16d574e9580e777541e17c66b.dblock.zip.aes

Operation Delete with file duplicati-b22cb36c16d574e9580e777541e17c66b.dblock.zip.aes attempt 5 of 5 failed with message: No such file
Renci.SshNet.Common.SftpPathNotFoundException: No such file
at Duplicati.Library.Main.BackendManager.Delete(String remotename, Int64 size, Boolean synchronous)
at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
##

**Comment by Pectojin** [comment]
I'm sorry this was never addressed. 

If you're still experiencing this or similar problems can you open a new issue? That way it's much more likely to get attention as it won't be burried below 700 newer open issues.
