### ISSUE TITLE
Duplicati 2 fails to restart/repair backup after it was terminated

### ISSUE THREAD

**Issue by rryk** [duplicati/duplicati#1175]
It seems that it's trying to remove files that do not exist on backend (verified manually). Each time I try to restart the backup again, the file name is different.

For example:

```
11/2/2014, 3:30:34 PM Message
Fatal error
System.IO.FileNotFoundException: duplicati-b7709993381b8498394e7fe85a59731f4.dblock.zip.aes
at Duplicati.Library.Main.BackendManager.Delete(String remotename, Int64 size, Boolean synchronous)
at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
```

```
11/2/2014, 3:30:34 PM Retry
Operation Delete with file duplicati-b7709993381b8498394e7fe85a59731f4.dblock.zip.aes attempt 5 of 5 failed with message: duplicati-b7709993381b8498394e7fe85a59731f4.dblock.zip.aes
System.IO.FileNotFoundException: duplicati-b7709993381b8498394e7fe85a59731f4.dblock.zip.aes
at Duplicati.Library.Main.BackendManager.Delete(String remotename, Int64 size, Boolean synchronous)
at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
```

Other files that it has tried to delete include:

```
duplicati-idb5d9a88ec1b458d88d734e61f4d25cd.dindex.zip.aes
duplicati-b2c896751def04fe680084d2c5f929b6d.dblock.zip.aes
duplicati-be108730855ba4b16a4a0213e7de9bc21.dblock.zip.aes
```

Repairing local database doesn't work either:

```
11/2/2014, 3:36:32 PM Message
removing incomplete remote file listed as Uploading: duplicati-ife0c885dff9349af868b38299f2e0940.dindex.zip.aes
11/2/2014, 3:36:29 PM Message
removing file listed as Deleting: duplicati-b7709993381b8498394e7fe85a59731f4.dblock.zip.aes
```
##

**Comment by Pectojin** [comment]
I believe this issue should have been closed with #1214 as many commits were added early 2015 to address these problems.
