### ISSUE TITLE
Cannot backup files on a windows server

### ISSUE THREAD

**Issue by xeg12** [duplicati/duplicati#1202]
I have the same issue with all versions of Duplicati (1.x and 2) and have tried again today with today.s update.
I have a share on a Windows 2012 server which contains all my raw photos. I want to backup to OneDrive. I have tried accessing the folders to be backed up by server share and by mapping the share - no difference.
I created a bug report today but do not see where to attach it on this issue but this is a sample of the errors:

Failed to process path: Z:\Raw Pictures\APB\2006_01_04\IMG_0110.CR2
Alphaleonis.Win32.Filesystem.UnrecognizedReparsePointException: I/O error occurred.
at Alphaleonis.Win32.Filesystem.DeviceIo.GetLinkTargetInfo(SafeHandle device)
at Alphaleonis.Win32.Filesystem.File.GetLinkTargetInfo(String sourceFile)
at Duplicati.Library.Snapshots.NoSnapshotWindows.GetSymlinkTarget(String file)
at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(String path, FileAttributes attributes)
11/14/2014, 12:25:36 PM Message
11/14/2014, 12:25:36 PM Message
##

**Comment by rocifier** [comment]
This looks the same as https://github.com/duplicati/duplicati/issues/1213
