### ISSUE TITLE
GDrive in v2 uses old API

### ISSUE THREAD

**Issue by millun** [duplicati/duplicati#1225]
Failed to connect: Execution of request failed: https://docs.google.com/feeds/default/private/full/-/folder

**Comment by charleswcole** [comment]
My backups have stopped working as of today.  I have made no changes.  Stopped on my Ubuntu and Windows boxes.  Getting same error as above.

```
Error: Failed to retrieve file listing: Execution of request failed: https://docs.google.com/feeds/default/private/full/-/folder

Error: System.Exception: Failed to retrieve file listing: Execution of request failed: https://docs.google.com/feeds/default/private/full/-/folder ---> Google.GData.Client.GDataRequestException: Execution of request failed: https://docs.google.com/feeds/default/private/full/-/folder ---> System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at System.Net.HttpWebRequest.GetResponse()
   at Google.GData.Client.GDataRequest.Execute()
   --- End of inner exception stack trace ---
   at Google.GData.Client.GDataRequest.Execute()
   at Google.GData.Client.GDataGAuthRequest.Execute(Int32 retryCounter)
   at Google.GData.Client.Service.Query(Uri queryUri, DateTime ifModifiedSince, String etag, Int64& contentLength)
   at Google.GData.Client.Service.Query(FeedQuery feedQuery)
   at Google.GData.Client.Feed`1.get_AtomFeed()
   at Google.GData.Client.Feed`1.<get_Entries>d__0.MoveNext()
   at Duplicati.Library.Backend.GoogleDocs.ParseFolderTree(IEnumerable`1 data)
   at Duplicati.Library.Backend.GoogleDocs.GetFolder()
   at Duplicati.Library.Backend.GoogleDocs.GetFileList()
   at Duplicati.Library.Backend.GoogleDocs.List()
   at Duplicati.Library.Main.BackendWrapper.ListInternal()
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.BackendWrapper.ProtectedInvoke(String methodname, Object[] arguments)
   at Duplicati.Library.Main.BackendWrapper.List(Boolean filter)
   at Duplicati.Library.Main.BackendWrapper.GetBackupSets()
   at Duplicati.Library.Main.Interface.Backup(String[] sources)
   at Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
InnerError: Google.GData.Client.GDataRequestException: Execution of request failed: https://docs.google.com/feeds/default/private/full/-/folder ---> System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at System.Net.HttpWebRequest.GetResponse()
   at Google.GData.Client.GDataRequest.Execute()
   --- End of inner exception stack trace ---
   at Google.GData.Client.GDataRequest.Execute()
   at Google.GData.Client.GDataGAuthRequest.Execute(Int32 retryCounter)
   at Google.GData.Client.Service.Query(Uri queryUri, DateTime ifModifiedSince, String etag, Int64& contentLength)
   at Google.GData.Client.Service.Query(FeedQuery feedQuery)
   at Google.GData.Client.Feed`1.get_AtomFeed()
   at Google.GData.Client.Feed`1.<get_Entries>d__0.MoveNext()
   at Duplicati.Library.Backend.GoogleDocs.ParseFolderTree(IEnumerable`1 data)
   at Duplicati.Library.Backend.GoogleDocs.GetFolder()
   at Duplicati.Library.Backend.GoogleDocs.GetFileList()
   at Duplicati.Library.Backend.GoogleDocs.List()
   at Duplicati.Library.Main.BackendWrapper.ListInternal()
InnerError: System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at System.Net.HttpWebRequest.GetResponse()
   at Google.GData.Client.GDataRequest.Execute()
Cleanup output:
Error: System.Exception: Failed to retrieve file listing: Execution of request failed: https://docs.google.com/feeds/default/private/full/-/folder ---> Google.GData.Client.GDataRequestException: Execution of request failed: https://docs.google.com/feeds/default/private/full/-/folder ---> System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at System.Net.HttpWebRequest.GetResponse()
   at Google.GData.Client.GDataRequest.Execute()
   --- End of inner exception stack trace ---
   at Google.GData.Client.GDataRequest.Execute()
   at Google.GData.Client.GDataGAuthRequest.Execute(Int32 retryCounter)
   at Google.GData.Client.Service.Query(Uri queryUri, DateTime ifModifiedSince, String etag, Int64& contentLength)
   at Google.GData.Client.Service.Query(FeedQuery feedQuery)
   at Google.GData.Client.Feed`1.get_AtomFeed()
   at Google.GData.Client.Feed`1.<get_Entries>d__0.MoveNext()
   at Duplicati.Library.Backend.GoogleDocs.ParseFolderTree(IEnumerable`1 data)
   at Duplicati.Library.Backend.GoogleDocs.GetFolder()
   at Duplicati.Library.Backend.GoogleDocs.GetFileList()
   at Duplicati.Library.Backend.GoogleDocs.List()
   at Duplicati.Library.Main.BackendWrapper.ListInternal()
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.BackendWrapper.ProtectedInvoke(String methodname, Object[] arguments)
   at Duplicati.Library.Main.BackendWrapper.List(Boolean filter)
   at Duplicati.Library.Main.BackendWrapper.GetBackupSets()
   at Duplicati.Library.Main.Interface.DeleteAllButNFull()
   at Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
InnerError: Google.GData.Client.GDataRequestException: Execution of request failed: https://docs.google.com/feeds/default/private/full/-/folder ---> System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at System.Net.HttpWebRequest.GetResponse()
   at Google.GData.Client.GDataRequest.Execute()
   --- End of inner exception stack trace ---
   at Google.GData.Client.GDataRequest.Execute()
   at Google.GData.Client.GDataGAuthRequest.Execute(Int32 retryCounter)
   at Google.GData.Client.Service.Query(Uri queryUri, DateTime ifModifiedSince, String etag, Int64& contentLength)
   at Google.GData.Client.Service.Query(FeedQuery feedQuery)
   at Google.GData.Client.Feed`1.get_AtomFeed()
   at Google.GData.Client.Feed`1.<get_Entries>d__0.MoveNext()
   at Duplicati.Library.Backend.GoogleDocs.ParseFolderTree(IEnumerable`1 data)
   at Duplicati.Library.Backend.GoogleDocs.GetFolder()
   at Duplicati.Library.Backend.GoogleDocs.GetFileList()
   at Duplicati.Library.Backend.GoogleDocs.List()
   at Duplicati.Library.Main.BackendWrapper.ListInternal()
InnerError: System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at System.Net.HttpWebRequest.GetResponse()
   at Google.GData.Client.GDataRequest.Execute()
```

**Comment by kenkendk** [comment]
This has been fixed by moving to the GoogleDrive API
