### ISSUE TITLE
Unable to connect to google docs/drive -UPDATE: Solved

### ISSUE THREAD

**Issue by Lukibe** [duplicati/duplicati#1231]
Installed, followed the wizard and when testing the connection, I get an error that there are too many xxx folders. Strangely enough I do not have folders named xxxx

Log follows:

Error: Failed to retrieve file listing: There are multiple folders named "1981", please rename them manually

Error: System.Exception: Failed to retrieve file listing: There are multiple folders named "1981", please rename them manually ---> System.Exception: There are multiple folders named "1981", please rename them manually
   at Duplicati.Library.Backend.GoogleDocs.ParseFolderTree(IEnumerable`1 data)
   at Duplicati.Library.Backend.GoogleDocs.GetFolder()
   at Duplicati.Library.Backend.GoogleDocs.GetFileList()
   at Duplicati.Library.Backend.GoogleDocs.List()
   at Duplicati.Library.Main.BackendWrapper.ListInternal()
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.BackendWrapper.ProtectedInvoke(String methodname, Object[] arguments)
   at Duplicati.Library.Main.BackendWrapper.List(Boolean filter)
   at Duplicati.Library.Main.BackendWrapper.GetBackupSets()
   at Duplicati.Library.Main.Interface.Backup(String[] sources)
   at Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
InnerError: System.Exception: There are multiple folders named "1981", please rename them manually
   at Duplicati.Library.Backend.GoogleDocs.ParseFolderTree(IEnumerable`1 data)
   at Duplicati.Library.Backend.GoogleDocs.GetFolder()
   at Duplicati.Library.Backend.GoogleDocs.GetFileList()
   at Duplicati.Library.Backend.GoogleDocs.List()
   at Duplicati.Library.Main.BackendWrapper.ListInternal()
Cleanup output:
Error: System.Exception: Failed to retrieve file listing: There are multiple folders named "1981", please rename them manually ---> System.Exception: There are multiple folders named "1981", please rename them manually
   at Duplicati.Library.Backend.GoogleDocs.ParseFolderTree(IEnumerable`1 data)
   at Duplicati.Library.Backend.GoogleDocs.GetFolder()
   at Duplicati.Library.Backend.GoogleDocs.GetFileList()
   at Duplicati.Library.Backend.GoogleDocs.List()
   at Duplicati.Library.Main.BackendWrapper.ListInternal()
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.BackendWrapper.ProtectedInvoke(String methodname, Object[] arguments)
   at Duplicati.Library.Main.BackendWrapper.List(Boolean filter)
   at Duplicati.Library.Main.BackendWrapper.GetBackupSets()
   at Duplicati.Library.Main.Interface.DeleteAllButNFull()
   at Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
InnerError: System.Exception: There are multiple folders named "1981", please rename them manually
   at Duplicati.Library.Backend.GoogleDocs.ParseFolderTree(IEnumerable`1 data)
   at Duplicati.Library.Backend.GoogleDocs.GetFolder()
   at Duplicati.Library.Backend.GoogleDocs.GetFileList()
   at Duplicati.Library.Backend.GoogleDocs.List()
   at Duplicati.Library.Main.BackendWrapper.ListInternal()

**Comment by Lukibe** [comment]
The issue seems to be solved: I had to empty the trash can in Google Drive. Not an elegant solution but somehow Duplicati chokes on the content of the trash can ......

**Comment by kenkendk** [comment]
Great that you found a workaround.
The long-term solution is to use the GDrive API instead of the GDocs API.

**Comment by Lukibe** [comment]
You mean using GDrive API from the developers side or is that some setting I can tick in the settings?

**Comment by kenkendk** [comment]
From the developer side. Some new code has to be written before it can work.

**Comment by Lukibe** [comment]
Ah,  ok.  Tnx!
