### ISSUE TITLE
2.0.0.81 Still having unresolved VSS issue on Win2003 Server

### ISSUE THREAD

**Issue by OMEN79** [duplicati/duplicati#1285]
Duplicati 2.0.0.81
Windows Server 2003 R2
Installed: Microsoft VC++ 2005 and 2008 x86.

System.IO.FileNotFoundException: Could not load file or assembly 'AlphaVSS.52.x86.dll' or one of its dependencies. Не найден указанный модуль.
 File name: 'AlphaVSS.52.x86.dll'
 at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
 at System.Reflection.Assembly.LoadFile(String path)
 at Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Dictionary 2 options) at Duplicati.Library.Snapshots.SnapshotUtility.CreateSnapshot(String[] folders, Dictionary 2 options)
 at Duplicati.Library.Main.Operation.BackupHandler.GetSnapshot(String[] sources, Options options, ILogWriter log)
 at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
 at Duplicati.Library.Main.Controller.c__AnonStorey0.<>m__0(BackupResults result)
 at Duplicati.Library.Main.Controller.RunActionT
 at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
 at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

**Comment by HaraldOnline** [comment]
Duplicati 2.0.0.81 requires the **VC++2010** redistributable when using VSS snapshots ... https://www.facebook.com/CarecomConsulting/posts/10152561898700981

**Comment by OMEN79** [comment]
Thanks! I'll give it a try

**Comment by OMEN79** [comment]
Thanks! It works now!

**Comment by HaraldOnline** [comment]
Great! Glad I could help.

Maybe you can close the issue? ;) (And mark my comment as an answer if possible on github)
