### ISSUE TITLE
2.0.0.81- 2.0.0.81_preview_2015-02-06: adding backup job fails with "Failed to get server setup..."

### ISSUE THREAD

**Issue by huste** [duplicati/duplicati#1295]
as noted. Just "add backup" and be persented with the error message popup
"Failed to get server setup..." Restaring duplicaty tray does not cure anything.

This happens on Win7 and Win8.1

**Comment by kenkendk** [comment]
Is this with Internet Explorer ?

**Comment by since1868** [comment]
Having the same issue after updating today. On Chrome. Here's error log:

    2/11/2015, 3:13:33 PM Request for get-backup-defaults gave error
    System.ArgumentException: Could not determine JSON object type for type       Duplicati.Server.Database.Setting.
    at Newtonsoft.Json.Linq.JValue.GetValueType(Nullable`1 current, Object value)
    at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipParentCheck)
    at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipParentCheck)
    at Duplicati.Server.WebServer.ControlHandler.GetBackupDefaults(IHttpRequest request, IHttpResponse response, IHttpSession session, BodyWriter bw)
    at Duplicati.Server.WebServer.ControlHandler.Process(IHttpRequest request, IHttpResponse response, IHttpSession session)
    2/11/2015, 3:13:33 PM Reporting error gave error
    System.ObjectDisposedException: Cannot write to a closed TextWriter.
    at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
    at Duplicati.Server.WebServer.ControlHandler.Process(IHttpRequest request, IHttpResponse response, IHttpSession session)

**Comment by huste** [comment]
No, both computers have the lastest Firefox version installed. And Opera 12.17 (yes, I know, the old one) shows the same.

**Comment by commerxchef** [comment]
I'm having the same problem.

I created a backup and it failed to save many options. I edited the backup and it then was able to save the options.

I ran the backup for the first time and noticed it complain that having no encryption was not recognized but it still continued without it.

The next day I tired to add a new backup and I encountered the same error. I've since deleted that backup in hopes of resolving the problem but nothing changed. My logs show the same errors as above.

I'll try the work around posted by since1868.

**Comment by since1868** [comment]
@commerxchef In case you aren't aware already, here's some info to save you some time. The sqlite database (on windows) is saved in %AppData%. The sqlite db is encrypted, so use a utility that supports it. The key can be found here on this v1 wiki: https://code.google.com/p/duplicati/wiki/Security

**Comment by m2tek** [comment]
After some debugging it is indeed what @since1868 says: after deleting all %appdata% the new backup that i try to create is saved with backupID = -1 (which is a special id for app wide backup settings) and later when trying to add new backup program fails when trying to serialize the settings saved under that ID to json.
