### ISSUE TITLE
Database is locked

### ISSUE THREAD

**Issue by ulicky** [duplicati/duplicati#1348]
Hi, Im running Dulicati as a service: Duplicati.Server.exe --portable-mode

But in logs there is this every day:

Failed: database is locked
database is locked
Details: System.Data.SQLite.SQLiteException (0x80004005): database is locked database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at Duplicati.Library.Main.Database.LocalDatabase.LogRemoteOperation(String operation, String path, String data, IDbTransaction transaction)
   at Duplicati.Library.Main.BackendManager.DatabaseCollector.FlushDbMessages(LocalDatabase db, IDbTransaction transaction)
   at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, Action`1 method)

**Comment by ulicky** [comment]
Same here:
2015-04-14 22:52:16Z - Error: Failed to access file: D:\Duplicati\Duplicati\data\localdb\xxx.sqlite
System.IO.IOException: The process cannot access the file 'D:\Duplicati\Duplicati\data\localdb\xxx.sqlite' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at Duplicati.Library.Main.Operation.RepairHandler.RunRepairRemote()

**Comment by ulicky** [comment]
![dup](https://cloud.githubusercontent.com/assets/2264442/7147435/3ab34f1c-e2fb-11e4-8582-5836869cf70d.png)
