### ISSUE TITLE
Google Drive backup fails

### ISSUE THREAD

**Issue by MitaineDomise** [duplicati/duplicati#1377]
Hello, I've had an automatic backup set up with Duplicati 2.0 on Google Drive; it worked well for months but now fails every time with the following log : 

9/5/2015 09:19:49 Message
Backend verification failed, attempting automatic cleanup
System.Exception: Invalid size value: true mb
at Duplicati.Library.Utility.Sizeparser.ParseSize(String size)
at Duplicati.Library.Main.Options.get_QuotaSize()
at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)

I tried freeing up some space as my drive was getting quite full, and updating to the latest Duplicati version. Note : I couldn't use the commandline version to delete older backups (commands were not recognized - did syntax change for 2.0 ?) so I manually deleted some older files. Nohting changed.

I would like to avoid starting a new backup set from scratch as I'm currently on a very weak internet connection.

Thanks for any suggestions or pointers !

**Comment by kenkendk** [comment]
It looks like the commandline parsing fails.
Try using --verbose on the commandline.

**Comment by MitaineDomise** [comment]
Thank you for your reply; while trying to add that option I realized that at some point *I* stupidly added the option --quota-size=True (what was I thinking). My own damn fault ! Now it works.
Thanks again, I probably wouldn't have found it by myself !
