### ISSUE TITLE
Meta-data retrieval fails for long paths

### ISSUE THREAD

**Issue by laurensb** [duplicati/duplicati#1379]
When retrieving meta-data for a file which total path is 260 characters or longer the lookup fails with an Invalid name error.

This is most likely related to a known Windows API limitation regarding long paths:

https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx#maxpath

Although the file could be backed up properly before meta-data was added to Duplicati, so apparently not all Windows API functions suffer from this limitation. If I had to guess the problem does not occur when traversing a directory, but does occur when attempting to access a file through its full path.

Stacktrace:
Failed to process path: I:\2014\05 Portal\themeforest-7414997-industrix-joomla-responsive-business-template\th_industrix_tf_bundle_v1.2\industrix_quickstart_j3(recommended)__MACOSX\industrix_quickstart_j3(recommended)\administrator\components\com_admin\postinstall._eaccelerator.php
System.ArgumentException: Invalid name.
Parameter name: name
at System.Security.AccessControl.NativeObjectSecurity.CreateInternal(ResourceType resourceType, Boolean isContainer, String name, SafeHandle handle, AccessControlSections includeSections, Boolean createByName, ExceptionFromErrorCode exceptionFromErrorCode, Object exceptionContext)
at System.Security.AccessControl.NativeObjectSecurity..ctor(Boolean isContainer, ResourceType resourceType, String name, AccessControlSections includeSections, ExceptionFromErrorCode exceptionFromErrorCode, Object exceptionContext)
at System.Security.AccessControl.DirectorySecurity..ctor(String name, AccessControlSections includeSections)
at Duplicati.Library.Snapshots.SystemIOWindows.GetAccessControlFile(String path)
at Duplicati.Library.Snapshots.SystemIOWindows.GetMetadata(String path)
at Duplicati.Library.Main.Operation.BackupHandler.GenerateMetadata(String path, FileAttributes attributes)
at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(String path, FileAttributes attributes)
##

**Comment by ts678** [comment]
I think long paths are working currently. You can see some recent history in [changelog.txt](https://github.com/duplicati/duplicati/blob/master/changelog.txt), including the fix for an obscure edge case

> Fixed an edge case where paths longer than 258 characters and short than 260 characters produced errors, thanks @drwtsn32x

The investigation took quite a bit of backup testing on both sides of the transition between two different methods of handling files...

[Filepath longer than 256 bytes cause FileAccessError under Windows 7](https://forum.duplicati.com/t/filepath-longer-than-256-bytes-cause-fileaccesserror-under-windows-7/8390/10?u=ts678)

then it changed plan in a major way, but this is not yet in any Beta as of today:

> Switched to the new built-in .Net support for long paths, thanks @dferreyra

so I suspect that this issue can be closed as no longer relevant for current code.

**Comment by warwickmm** [comment]
Long path support was added in pull request #4256.
