### ISSUE TITLE
Backup using VSS fails on Windows 10

### ISSUE THREAD

**Issue by rryk** [duplicati/duplicati#1445]
I run a backup with "--snapshot-policy=required" option. Prior to upgrade to Windows 10, it worked as intended. Now, however, I get the following error:
```
Alphaleonis.Win32.Vss.VssProviderVetoException: Expected provider error. Check the event log for details.
at Alphaleonis.Win32.Vss.WaitCheckAndReleaseVssAsyncOperation(IVssAsync* pAsync)
at Alphaleonis.Win32.Vss.VssBackupComponents.DoSnapshotSet()
at Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Dictionary`2 options)
at Duplicati.Library.Snapshots.SnapshotUtility.CreateSnapshot(String[] folders, Dictionary`2 options)
at Duplicati.Library.Main.Operation.BackupHandler.GetSnapshot(String[] sources, Options options, ILogWriter log)
at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, Action`1 method)
at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
```

**Comment by kenkendk** [comment]
Was this resolved?

There is a new version of AlphaVSS included in the latest 2.0.1.20 release.

**Comment by rryk** [comment]
Honestly, I am not sure. I have stopped using Duplicati in favor of another proprietary free app. I think this issue can be closed, but if someone experiences this again, they can reopen it.

**Comment by kenkendk** [comment]
Thanks for commenting :)

**Comment by filippobottega** [comment]
This is my error:

Fatal error
Alphaleonis.Win32.Vss.VssProviderVetoException: Expected provider error. Check the event log for details.
   in Alphaleonis.Win32.Vss.WaitCheckAndReleaseVssAsyncOperation(IVssAsync* pAsync)
   in Alphaleonis.Win32.Vss.VssBackupComponents.DoSnapshotSet()
   in Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Dictionary`2 options)
   in Duplicati.Library.Snapshots.SnapshotUtility.CreateWindowsSnapshot(String[] folders, Dictionary`2 options)
   in Duplicati.Library.Main.Operation.BackupHandler.GetSnapshot(String[] sources, Options options, ILogWriter log)
   in Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)

Event Viewer:

Errore del servizio Copia Shadow del volume: errore imprevisto durante la ricerca dell'interfaccia IVssWriterCallback. hr = 0x80070005, Accesso negato.
. L'errore è spesso causato da impostazioni di sicurezza non corrette nel processo di scrittura o richiedente. 

Operazione:
   Raccolta dei dati del processo di scrittura

Contesto:
   ID della classe del processo di scrittura: {e8132975-6f93-4464-a53e-1050253ae220}
   Nome del processo di scrittura: System Writer
   ID dell'istanza del processo di scrittura: {833b5d6b-9e65-4a02-b119-3b3529bddd65}

I suppose that Duplicate has to be running with Administration privileges.

Regards,
  Filippo.
