### ISSUE TITLE
Backup run failed on windows with "Persian Calendar" as system default

### ISSUE THREAD

**Issue by aghajani** [duplicati/duplicati#1449]
System.FormatException: The DateTime represented by the string is not supported in calendar System.Globalization.PersianCalendar.
at System.DateTimeParse.ParseExact(String s, String format, DateTimeFormatInfo dtfi, DateTimeStyles style)
at Duplicati.Library.Main.Volumes.VolumeBase.ParsedVolume.Parse(String filename, IFileEntry file)
at Duplicati.Library.Main.Operation.FilelistProcessor.<RemoteListAnalysis>m__0(IFileEntry n)
at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, Action`1 method)
at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

**Comment by kenkendk** [comment]
I have merged in 9ae7ea2 to master and tester tested with the fa-IR locale, which I assume has Persian calendar.

**Comment by kenkendk** [comment]
Could you try the build here:
http://updates.duplicati.com/preview/duplicati-2.0.0.90_preview_2015-09-15.zip

**Comment by aghajani** [comment]
Yep it works and the issue is resolved. 
But why you just didn't merge my codes and re-coded all the changes again?

**Comment by kenkendk** [comment]
I was worried that there were other places where the time formating was used, which would cause similar issues.
I was also seeking to consolidate all time-strings that were being serialized into the same format.
I think I ended up concluding that you had found all the spots :).

Btw. I also added `--force-locale` which will enforce InvariantCulture throughout (can also do `--force-locale=en-US`), in case someone prefers using another calendar system than their system default.

**Comment by kenkendk** [comment]
Btw. if you would like to be credited for fixing this, feel free to create a PR with your name in acknowledgements: 
https://github.com/duplicati/duplicati/blob/fc29aacff8764920f291b6b8ffcd1507ce8a2180/Duplicati/License/acknowledgements.txt
