### ISSUE TITLE
googledrive --no-encryption fails (Unsupported removal of passphrase)

### ISSUE THREAD

**Issue by Pledkae** [duplicati/duplicati#1450]
Duplicati Version: 2.0.0.89_preview_2015-08-24
OS: Win 7 Pro x86
Command line: `Duplicati.CommandLine.exe backup googledrive://remote_folder?authid=AUTHID C:\local_folder --no-encryption`
Result (from log):
Failed while executing "Backup" with id: 1
System.Exception: **Unsupported removal of passphrase**
at Duplicati.Library.Main.Utility.VerifyParameters(LocalDatabase db, Options options, IDbTransaction transaction)
at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, Action`1 method)
at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

Passing an empty --passphrase gives the same result. Does anyone have an idea how to circumvent this?

**Comment by kenkendk** [comment]
In you %APP_DATA% folder there is a database from a previous backup to that folder.
Either remove the database, or use --dbpath to point to a new location.

**Comment by Pledkae** [comment]
Thank you very much, that worked flawlessly!
