### ISSUE TITLE
Windows 8.1: Failed to create a snapshot

### ISSUE THREAD

**Issue by David-Pa** [duplicati/duplicati#1453]
Warnings: [Failed to create a snapshot: System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
at Alphaleonis.Win32.Vss.VssBackupComponents..ctor()
at Alphaleonis.Win32.Vss.VssImplementation.CreateVssBackupComponents()
at Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Dictionary'2 options)
at Duplicati.Library.Main.Operation.BackupHandler.GetSnapshot(String[] sources, Options options, ILogWriter log) => System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
at Alphaleonis.Win32.Vss.VssBackupComponents..ctor()
at Alphaleonis.Win32.Vss.VssImplementation.CreateVssBackupComponents()
at Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Dictionary'2 options)
at Duplicati.Library.Main.Operation.BackupHandler.GetSnapshot(String[] sources, Options options, ILogWriter log)]

**Comment by kenkendk** [comment]
You need to run Duplicati with a user account that has administrative permissions, otherwise Windows does not allow you to create snapshots.

**Comment by urbanhop** [comment]
same problem here, win 8.1. 
my user has administrative permissions.

(just starting with duplicati, great work, thx for providing this)
