### ISSUE TITLE
Backups to Google are failing yet again.

### ISSUE THREAD

**Issue by g1ps** [duplicati/duplicati#1484]
This has been happening for the last week or so:

Fatal error
System.Exception: Failed to authorize using the OAuth service: Proxy Authentication Required. If the problem persists, try generating a new authid token from: https://duplicati-oauth-handler.appspot.com/type=googledrive ---> System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
at Duplicati.Library.Utility.AsyncHttpRequest.AsyncWrapper.GetResponseOrStream()
at Duplicati.Library.Utility.AsyncHttpRequest.GetResponse()
at Duplicati.Library.JSONWebHelper.GetResponse(AsyncHttpRequest req, Object requestdata)
at Duplicati.Library.JSONWebHelper.ReadJSONResponse[T](AsyncHttpRequest req, Object requestdata)
at Duplicati.Library.OAuthHelper.get_AccessToken()
--- End of inner exception stack trace ---
at Duplicati.Library.Main.BackendManager.List()
at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)

Generating a new token got it going for a day or two but that doesn't work now. Are Google messing us about again? This is very annoying. Does anyone have a better free option to suggest?

Cheers.
##

**Comment by kenkendk** [comment]
I am not seeing any errors on the OAuth service.

The error message leads me to think that you are using some kind of proxy, which stops working.
When you navigate to the OAuth service and create a new token, the proxy probably starts working again and so does the backup.

You can run your own OAuth service if you prefer.

**Comment by kenkendk** [comment]
Is this resolved?

**Comment by g1ps** [comment]
No. It still happens on and off. It's been OK for the last week or so. Prior to that there were probably a few weeks of it happening. I'm currently running 2.0.0.91- 2.0.0.91_preview_2015-11-18 according to About, although I would have said I'd updated this recently, definitely this year. Thanks.
