### ISSUE TITLE
Recovery error - misleading success message (hubiC)

### ISSUE THREAD

**Issue by grinsted** [duplicati/duplicati#1558]
I have tried to make a test recovery from backup of a single file from hubiC.  I get a big green success box with donate links, but at the same time I get a smaller red 401 error box in the bottom and no recovered file. 

running Duplicati 2.0.0.91- 2.0.0.91_preview_2015-11-18

Here are some lines from my log:

```
1/28/2016, 5:22:06 PM Request for http://127.0.0.1:8200/control.cgi?action=test-backend&url=hubic://default/duplicati/aslaks-xps13?authid=[redacted]
System.Exception: Failed to authorize using the OAuth service: Server error. If the problem persists, try generating a new authid token from: https://duplicati-oauth-handler.appspot.com?type=hubic ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
at Duplicati.Library.Utility.AsyncHttpRequest.AsyncWrapper.GetResponseOrStream()
at Duplicati.Library.Utility.AsyncHttpRequest.GetResponse()
at Duplicati.Library.JSONWebHelper.GetResponse(AsyncHttpRequest req, Object requestdata)
at Duplicati.Library.JSONWebHelper.ReadJSONResponse[T](AsyncHttpRequest req, Object requestdata)
at Duplicati.Library.OAuthHelper.GetTokenResponse[T]()
at Duplicati.Library.OAuthHelper.get_AccessToken()
--- End of inner exception stack trace ---
at Duplicati.Library.OAuthHelper.get_AccessToken()
at Duplicati.Library.OAuthHelper.CreateRequest(String url, String method)
at Duplicati.Library.JSONWebHelper.ReadJSONResponse[T](String url, Object requestdata, String method)
at Duplicati.Library.Backend.HubiC.HubiCBackend.OpenStackHelper.get_AuthToken()
at Duplicati.Library.Backend.HubiC.HubiCBackend.OpenStackHelper.get_SimpleStorageEndPoint()
at Duplicati.Library.Backend.OpenStack.OpenStackStorage.List()
at Duplicati.Library.Backend.HubiC.HubiCBackend.Test()
at Duplicati.Server.WebServer.RESTMethods.RemoteOperation.TestConnection(String url, RequestInfo info)
at Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)
1/28/2016, 5:22:06 PM Reporting error gave error
System.ObjectDisposedException: Cannot write to a closed TextWriter.
at System.IO.__Error.WriterClosed()
at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
at Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)
1/28/2016, 5:20:54 PM Failed while executing "Backup" with id: 2
System.Exception: Failed to authorize using the OAuth service: Server error. If the problem persists, try generating a new authid token from: https://duplicati-oauth-handler.appspot.com?type=hubic ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
at Duplicati.Library.Utility.AsyncHttpRequest.AsyncWrapper.GetResponseOrStream()
at Duplicati.Library.Utility.AsyncHttpRequest.GetResponse()
at Duplicati.Library.JSONWebHelper.GetResponse(AsyncHttpRequest req, Object requestdata)
at Duplicati.Library.JSONWebHelper.ReadJSONResponse[T](AsyncHttpRequest req, Object requestdata)
at Duplicati.Library.OAuthHelper.GetTokenResponse[T]()
at Duplicati.Library.OAuthHelper.get_AccessToken()
--- End of inner exception stack trace ---
at Duplicati.Library.Main.BackendManager.List()
at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, Action`1 method)
at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
1/28/2016, 11:34:28 AM Failed while executing "Backup" with id: 1
Duplicati.Library.Interface.FolderMissingException: The folder D:\DuplicatiBackups\Documents\ does not exist
at Duplicati.Library.Main.BackendManager.List()
at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, Action`1 method)
at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
1/27/2016, 10:45:39 AM Failed while executing "Backup" with id: 1
System.Threading.ThreadAbortException: Thread was being aborted.
at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(String path, FileAttributes attributes)
at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, Action`1 method)
at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
1/27/2016, 10:45:39 AM Error in worker
System.Threading.ThreadAbortException: Thread was being aborted.
at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
at Duplicati.Library.Utility.WorkerThread`1.Runner()
```

and the profiling log as well while trying again. 

```
[...]
1/29/2016, 2:08:59 PM ExecuteScalar: SELECT COUNT(*) FROM "Block" WHERE "Size" > ? took 00:00:00.246
1/29/2016, 2:08:59 PM Starting - RemoteOperationList
1/29/2016, 2:08:59 PM Backend event: List - Started: ()
1/29/2016, 2:08:59 PM RemoteOperationList took 00:00:00.395
1/29/2016, 2:08:59 PM Operation List with file attempt 1 of 5 failed with message: The remote server returned an error: (401) Unauthorized.
[SNIP]
1/29/2016, 2:09:30 PM Backend event: List - Retrying: ()
1/29/2016, 2:09:40 PM Starting - RemoteOperationList
1/29/2016, 2:09:40 PM Backend event: List - Started: ()
1/29/2016, 2:09:40 PM RemoteOperationList took 00:00:00.241
1/29/2016, 2:09:40 PM Operation List with file attempt 5 of 5 failed with message: The remote server returned an error: (401) Unauthorized.
[object Object]
1/29/2016, 2:09:40 PM Backend event: List - Failed: ()
1/29/2016, 2:09:40 PM Running Restore took 00:00:42.155
1/29/2016, 2:09:40 PM Terminated with error: The remote server returned an error: (401) Unauthorized.
[object Object]
```
##

**Comment by grinsted** [comment]
I created a new authid, and tested it . It reported that the connection worked. I still get 401 errors though when i try to recover.

**Comment by grinsted** [comment]
I managed to get around the 401 error by revoking the authid used by duplicati from the hubic web-interface, and then making a new one. So i guess this issue is really only about the confusing message that the recovery succeeded when it really didn't.

**Comment by ethauvin** [comment]
I'm getting the 401 at least once a day. I have 4 different backups going to HubiC at different times throughout the day. The error rotates between backups.

```
Failed: The remote server returned an error: (401) Unauthorized.
Details: System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at Duplicati.Library.Main.BackendManager.List()
   at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)
   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass15_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
```
Regenerating the AuthID always fixes the problem, but it is pretty annoying and quite incovenient.

I have noticed that I can reproduce the error every time if a backup is running at 5:00am; it will undoubtelly fail with a 401 at 5:00am on the nose. I don't know if HubiC reset tokens at 5:00am, or something. They're in France so that's 2:00pm for them, seems unlikely they would do that in the middle of the afternoon.

Let me know if you need more info.

**Comment by ts678** [comment]
hubiC closed in August 2022, and its support is removed in the latest Canary release. Is there any reason to keep this open?

**Comment by grinsted** [comment]
I don't think there is.
