### ISSUE TITLE
V 2.0.1.7 Local database not created properly from backup data during Restore

### ISSUE THREAD

**Issue by chris-cashin** [duplicati/duplicati#1657]
When restoring using 2.0.1.7- without the backup database files are randomly excluded.
An error message indicating that the metadata could not be applied and that the file is not found is generated. If the backup database is provided the process works correctly and no files are excluded.

This seems to be a fairly consistent issue.
No back-end was involved in testing just local process
Sample Command line without --dbpath that fails follows: 
"C:\duplicati\Duplicati.CommandLine.exe" restore "file://C:\SOURCE\\" --passphrase="1234" --overwrite="TRUE" --time=now --restore-path=D:\RESTORED --dbpath="" --Prefix="PPL" --full-block-verification="true" --no-local-blocks="TRUE" --disable-module="console-password-input"

**Comment by FootStark** [comment]
@chris-cashin That seems strange. Can you provide some more information on your issue:

* Can you give an example of the filenames and the file sizes of the files that failed to restore? 
* Did you check that the files were really missing on the HD, or were they just not accessible to Duplicati? 
* Have there already been files present in the target folder? 
* Do the folders backed up contain files with long filenames and some that correspond to the old (8+3)-DOS-Format (I assume you're on Win)?
* Furthermore, did you try it again with an older version of Duplicati?
* And, is there a log available / can you reproduce the error with a verbose log to make sure there are no other errors involved?

**Comment by chris-cashin** [comment]
Stefan the environment in server 2012 R2
The source and destination are local
I did a simple test to replicate the problem
The file names are simple names like GLTRX or CPORDL with no extensions.
[log.txt](https://github.com/duplicati/duplicati/files/190396/log.txt)

Files are large 500MB+
There is only one backup and restore cycle to empty directories
If I use the database the restore works with 2.0.1.7
If I use the 2.0.0.91 version restore works correctly without database.
Log snippet attached in log file.txt and follows:

2016-03-26 01:19:15Z - Information: Backend event: Get - Completed: TEST-bfb299c5e711e43adacbcf596d4685627.dblock.zip.aes (2.51 MB)
2016-03-26 01:19:15Z - Profiling: RemoteOperationGet took 00:00:00.074
2016-03-26 01:19:15Z - Information: Recording metadata from remote data: D:\RESTORE\
2016-03-26 01:19:15Z - Information: Recording metadata from remote data: D:\RESTORE\CPORDL
2016-03-26 01:19:15Z - Profiling: Starting - CommitBlockMarker
2016-03-26 01:19:15Z - Profiling: CommitBlockMarker took 00:00:00.002
2016-03-26 01:19:16Z - Information: Recording metadata from remote data: D:\RESTORE\HSTCPH
2016-03-26 01:19:16Z - Profiling: Starting - CommitBlockMarker
2016-03-26 01:19:16Z - Profiling: CommitBlockMarker took 00:00:00.000
2016-03-26 01:19:16Z - Profiling: The metadata storage file has 4 entries and takes up 1.12 KB
2016-03-26 01:19:16Z - Profiling: Starting - Read metadata from file
2016-03-26 01:19:16Z - Information: Patching metadata with remote data: D:\RESTORE\GLTRX
2016-03-26 01:19:16Z - Warning: Failed to apply metadata to file: "D:\RESTORE\GLTRX", message: Could not find file 'D:\RESTORE\GLTRX'.
System.IO.FileNotFoundException: Could not find file 'D:\RESTORE\GLTRX'.
File name: 'D:\RESTORE\GLTRX'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle& handle)
   at System.IO.File.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)
   at Duplicati.Library.Snapshots.SystemIOWindows.FileSetLastWriteTimeUtc(String path, DateTime time)
   at Duplicati.Library.Main.Operation.RestoreHandler.ApplyMetadata(String path, Stream stream, Boolean restorePermissions)
   at Duplicati.Library.Main.Operation.RestoreHandler.ApplyStoredMetadata(LocalRestoreDatabase database, Options options, RestoreResults result, RestoreHandlerMetadataStorage metadatastorage)

2016-03-26 01:19:16Z - Information: Patching metadata with remote data: D:\RESTORE\
2016-03-26 01:19:16Z - Information: Patching metadata with remote data: D:\RESTORE\CPORDL
2016-03-26 01:19:16Z - Warning: Failed to apply metadata to file: "D:\RESTORE\CPORDL", message: Could not find file 'D:\RESTORE\CPORDL'.
System.IO.FileNotFoundException: Could not find file 'D:\RESTORE\CPORDL'.
File name: 'D:\RESTORE\CPORDL'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle& handle)
   at System.IO.File.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)
   at Duplicati.Library.Snapshots.SystemIOWindows.FileSetLastWriteTimeUtc(String path, DateTime time)
   at Duplicati.Library.Main.Operation.RestoreHandler.ApplyMetadata(String path, Stream stream, Boolean restorePermissions)
   at Duplicati.Library.Main.Operation.RestoreHandler.ApplyStoredMetadata(LocalRestoreDatabase database, Options options, RestoreResults result, RestoreHandlerMetadataStorage metadatastorage)

2016-03-26 01:19:16Z - Information: Patching metadata with remote data: D:\RESTORE\HSTCPH
2016-03-26 01:19:16Z - Warning: Failed to apply metadata to file: "D:\RESTORE\HSTCPH", message: Could not find file 'D:\RESTORE\HSTCPH'.
System.IO.FileNotFoundException: Could not find file 'D:\RESTORE\HSTCPH'.
File name: 'D:\RESTORE\HSTCPH'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle& handle)
   at System.IO.File.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)
   at Duplicati.Library.Snapshots.SystemIOWindows.FileSetLastWriteTimeUtc(String path, DateTime time)
   at Duplicati.Library.Main.Operation.RestoreHandler.ApplyMetadata(String path, Stream stream, Boolean restorePermissions)
   at Duplicati.Library.Main.Operation.RestoreHandler.ApplyStoredMetadata(LocalRestoreDatabase database, Options options, RestoreResults result, RestoreHandlerMetadataStorage metadatastorage)

2016-03-26 01:19:16Z - Profiling: Read metadata from file took 00:00:00.247
2016-03-26 01:19:16Z - Profiling: Starting - RestoreVerification
2016-03-26 01:19:16Z - Profiling: Starting - ExecuteReader: SELECT "Fileset-87BE65319CEB33409A63A616CE664DAA"."ID", "Fileset-87BE65319CEB33409A63A616CE664DAA"."TargetPath", "Blockset"."FullHash", "Blockset"."Length" FROM "Fileset-87BE65319CEB33409A63A616CE664DAA","Blockset" WHERE "Fileset-87BE65319CEB33409A63A616CE664DAA"."BlocksetID" = "Blockset"."ID" AND "Fileset-87BE65319CEB33409A63A616CE664DAA"."DataVerified" <= ?
2016-03-26 01:19:16Z - Profiling: ExecuteReader: SELECT "Fileset-87BE65319CEB33409A63A616CE664DAA"."ID", "Fileset-87BE65319CEB33409A63A616CE664DAA"."TargetPath", "Blockset"."FullHash", "Blockset"."Length" FROM "Fileset-87BE65319CEB33409A63A616CE664DAA","Blockset" WHERE "Fileset-87BE65319CEB33409A63A616CE664DAA"."BlocksetID" = "Blockset"."ID" AND "Fileset-87BE65319CEB33409A63A616CE664DAA"."DataVerified" <= ? took 00:00:00.000
2016-03-26 01:19:16Z - Information: Testing restored file integrity: D:\RESTORE\CPORDL
2016-03-26 01:19:16Z - Warning: Could not find file 'D:\RESTORE\CPORDL'.
System.IO.FileNotFoundException: Could not find file 'D:\RESTORE\CPORDL'.
File name: 'D:\RESTORE\CPORDL'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Duplicati.Library.Snapshots.SystemIOWindows.FileOpenRead(String path)
   at Duplicati.Library.Main.Operation.RestoreHandler.DoRun(LocalDatabase dbparent, IFilter filter, RestoreResults result)

2016-03-26 01:19:16Z - Information: Testing restored file integrity: D:\RESTORE\GLTRX
2016-03-26 01:19:16Z - Warning: Could not find file 'D:\RESTORE\GLTRX'.
System.IO.FileNotFoundException: Could not find file 'D:\RESTORE\GLTRX'.
File name: 'D:\RESTORE\GLTRX'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Duplicati.Library.Snapshots.SystemIOWindows.FileOpenRead(String path)
   at Duplicati.Library.Main.Operation.RestoreHandler.DoRun(LocalDatabase dbparent, IFilter filter, RestoreResults result)

2016-03-26 01:19:16Z - Information: Testing restored file integrity: D:\RESTORE\HSTCPH
2016-03-26 01:19:16Z - Warning: Could not find file 'D:\RESTORE\HSTCPH'.
System.IO.FileNotFoundException: Could not find file 'D:\RESTORE\HSTCPH'.
File name: 'D:\RESTORE\HSTCPH'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Duplicati.Library.Snapshots.SystemIOWindows.FileOpenRead(String path)
   at Duplicati.Library.Main.Operation.RestoreHandler.DoRun(LocalDatabase dbparent, IFilter filter, RestoreResults result)

2016-03-26 01:19:16Z - Profiling: RestoreVerification took 00:00:00.007
2016-03-26 01:19:16Z - Information: Failed to restore 3 files
2016-03-26 01:19:16Z - Profiling: Starting - RemoteOperationTerminate
2016-03-26 01:19:16Z - Profiling: RemoteOperationTerminate took 00:00:00.000

**Comment by FootStark** [comment]
Thanks for the bug report, I will have a look.
Judging from the log you tried to restore into existing files, is this correct?
Furthermore, I guess the files that were not restored are exact copies of other files in the backup. Can you confirm this?

**Comment by kenkendk** [comment]
In case there are some more hints, here is the original report of the issue:
https://groups.google.com/d/msg/duplicati/jRGRWU-0sP0/jDZBZA0GDwAJ

**Comment by chris-cashin** [comment]
Just to make sure I recreated the scenario and did the restore again.
I deleted the original files so only the backup exists
There is only one backup cycle
in this simple repeatable scenario and no files are restored.
log attached.

[log.txt](https://github.com/duplicati/duplicati/files/190552/log.txt)

**Comment by kenkendk** [comment]
Thanks for that. I am fairly sure that @FootStark found the source of the problem. There was a central SQL query for recreating the database that used a fixed blocksize of 10kb instead of the user chosen value.
A new build will be available soon to verify this.

**Comment by kenkendk** [comment]
This should be fixed in the latest canary build:
https://github.com/duplicati/duplicati/releases

**Comment by chris-cashin** [comment]
Thanks guys this fixed the problem

**Comment by chris-cashin** [comment]
Thanks guys this fixed the problem
