### ISSUE TITLE
Backup fails: Unexpected number of remote volumes detected: 0!

### ISSUE THREAD

**Issue by Kroesss** [duplicati/duplicati#1702]
When running a backup-task, it ends with the message:

> Error while running Personal Files
> Unexpected number of remote volumes detected: 0!

When the details are viewed, I get the following information:

> Rollback error: unknown error
> No transaction is active on this connection
> System.Data.SQLite.SQLiteException (0x80004005): unknown error
> No transaction is active on this connection
>    at System.Data.SQLite.SQLiteTransaction.IsValid(Boolean throwError)
>    at System.Data.SQLite.SQLiteTransaction.Rollback()
>    at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)

I'm running version 2.0.1.11, and I'm backing up to a webdav-share.
The backup also does not appear as succesfull. Before I updated I did not receive this error (coming from 2.0.1.7)
##

**Comment by j33433** [comment]
This happened to me today with 2.0.1.53_experimental_2017-03-13 and Google cloud nearline.

**Comment by maciozo** [comment]
This also happened to me today. 2.0.1.61_experimental_2017-05-30. Backing up to Google Drive.

**Comment by OronDF343** [comment]
This happened to me several times on 2.0.1.53_experimental_2017-03-13 as well as 2.0.2.8_canary_2017-09-20 today.
Three stack traces from today:
```
System.Exception (0x80131500): Unexpected number of remote volumes detected: 0!
at Duplicati.Library.Main.Database.LocalDatabase.UpdateRemoteVolume(String name, RemoteVolumeState state, Int64 size, String hash, Boolean suppressCleanup, TimeSpan deleteGraceTime, IDbTransaction transaction)
at Duplicati.Library.Main.Database.LocalDatabase.UpdateRemoteVolume(String name, RemoteVolumeState state, Int64 size, String hash, Boolean suppressCleanup, IDbTransaction transaction)
at Duplicati.Library.Main.Operation.BackupHandler.FinalizeRemoteVolumes(BackendManager backend)
at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
at Duplicati.Library.Main.Controller.<>c__DisplayClass16_0.<Backup>b__0(BackupResults result)
at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
```
```
System.Data.SQLite.SQLiteException (0x80004005): unknown error
No transaction is active on this connection
at System.Data.SQLite.SQLiteTransactionBase.IsValid(Boolean throwError)
at System.Data.SQLite.SQLiteTransactionBase.Rollback()
at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
```
```
System.InvalidOperationException (0x80131509): Attempted to dispose an index volume that was being written
at Duplicati.Library.Main.Volumes.IndexVolumeWriter.Dispose()
at Duplicati.Library.Main.Operation.BackupHandler.Dispose()
```

**Comment by bozzmedia** [comment]
Same issue here backing up to Amazon S3

**Comment by bozzmedia** [comment]
If anyone is using CrashPlan at the same time, it may be the culprit:

https://forum.duplicati.com/t/disk-i-o-error-from-sqlite-most-likely-crashplan-locking-the-file/917/8

**Comment by ts678** [comment]
There seem to be no reports of this after 2017. Maybe it got fixed. Is anyone still seeing these? If not, this will eventually close.
