### ISSUE TITLE
Stuck on "verifying..." on first backup

### ISSUE THREAD

**Issue by kingudk** [duplicati/duplicati#1735]
Duplicati seems to be stuck while running the first backup. The state it's set in is "Verifying...". 
It seem to be stuck there for four hours this morning. Stuck meaning, that no cpu, disk or network activity. 
No processes running in the receiving end (destination is via ssh). The host is running Windows 7, and using the GUI of Duplicati.

The last log entry at 3:15 said: "No remote filesets were deleted" 
And the logentry prior to that said: 

```
System.DivideByZeroException: Attempted to divide by zero.
   at SharpCompress.Compressor.BZip2.CBZip2OutputStream.MainSort()
   at SharpCompress.Compressor.BZip2.CBZip2OutputStream.DoReversibleTransformation()
   at SharpCompress.Compressor.BZip2.CBZip2OutputStream.EndBlock()
   at SharpCompress.Compressor.BZip2.CBZip2OutputStream.Finish()
   at SharpCompress.Compressor.BZip2.CBZip2OutputStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at SharpCompress.Compressor.BZip2.BZip2Stream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at SharpCompress.Writer.Zip.ZipWriter.ZipWritingStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at Duplicati.Library.Main.Volumes.BlockVolumeWriter.AddBlock(String hash, Byte[] data, Int32 offset, Int32 size, CompressionHint hint)
   at Duplicati.Library.Main.Operation.BackupHandler.AddBlockToOutput(BackendManager backend, String key, Byte[] data, Int32 offset, Int32 len, CompressionHint hint, Boolean isBlocklistData)
   at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes)
```

Did a bug in the bzip compresse cause the verification to get stuck? 

The version is the latest experimental (I belive it's from April 8 2016). 
##

**Comment by kingudk** [comment]
The newest canary build (2016-05-14) also have the samme issue. That is it gets stuck in the state "Verifying...". 
There still seem to be no activity, and this time no errors related to the backup can be found in the log. 

Annoyingly Windows Update enforced a reboot, and the state of the backup gets reset to never being run. 

Is there no one who have any idea what's going on here?

**Comment by huste** [comment]
My backu p"hangs" upon verification, too. The reason is simple, though: Duplicati fetches a .dblock.7z file which is 1,9GB in size from a remote server...What exactly makes this file so big?

**Comment by binarybum** [comment]
I'm having the same issue. I have let it run for days. It is definitely stuck.  This is not a new backup though. I am trying to run a backup that has worked fine on previous versions.  Hugely frustrating.  Clicking stop does not abort it either.

**Comment by afalout** [comment]
Very similar looking issue here: https://github.com/duplicati/duplicati/issues/2335

Also posed on Google Groups, but there was no response.

Completely stuck - can anyone suggest what to try?

Much appreciated, Andrej

**Comment by kenkendk** [comment]
@binarybum The "abort does not stop" should be fixed in the latest canary. The query that hangs for @afalout has also been removed, so I assume this has been fixed for you as well.

@huste You probably had a really large `--dblock-size` value. Also, 7z has a number of issues, and we are debating how to solve that.

@kingudk I have not tested the bzip2, but that does look like a bug in BZip2. It has not been fixed as there are no updates to that file: https://github.com/adamhathcock/sharpcompress/blob/master/src/SharpCompress/Compressors/BZip2/CBZip2OutputStream.cs

**Comment by allen111** [comment]
i resolved in linux adding the option to accept any ssl .

**Comment by alexbarnsley** [comment]
@kingudk you mentioned you saw that as the last log entry. Where can I find this log? Thanks

**Comment by SamiLehtinen** [comment]
Seems to hang with sftp / ssh too. While verifying, download is in someway broken. Setting ssh timeout, whatever won't help. Hangs forever even with files which are just a few kilobytes in size. Definitely something is seriously broken.

**Comment by kenkendk** [comment]
All items listed here appears to be fixed in current builds
