### ISSUE TITLE
AWS S3 command line backup fails with "The request signature we calculated does not match the signature you provided"

### ISSUE THREAD

**Issue by Zero3** [duplicati/duplicati#1756]
I have set up a backup to AWS S3 which works fine when run through the GUI. But when running the exported command line, I get the following error:

```
Backup started at 09-05-2016 00:42:59
Checking remote backup ...
  Listing remote folder ...
Operation List with file  attempt 1 of 5 failed with message: The request signat
ure we calculated does not match the signature you provided. Check your key and
signing method. => The request signature we calculated does not match the signat
ure you provided. Check your key and signing method.
```

The (censored) command line that Duplicati generated is:

```
"C:\Program Files\Duplicati\Duplicati.CommandLine.exe" backup "s3s://<bucket name>?auth-username=<username>&auth-password=<password>&s3-server-name=s3.amazonaws.com" "C:\Users\Zero3\\" --backup-name="S3-Profile" --dbpath="C:\Users\Zero3\AppData\Roaming\Duplicati\JGKRSQLMRG.sqlite" --encryption-module="aes" --keep-time="6M" --passphrase="<passphrase>" --dblock-size="128mb" --exclude-files-attributes="system,temporary" --disable-module="console-password-input" --exclude="C:\Users\Zero3\AppData\Local\\" --exclude="C:\Users\Zero3\.m2\\"`
```
##

**Comment by vdenisov** [comment]
I'm getting the same error. Backup works fine from the GUI, but when ran from the command line, I get the following exception:
```
c:\Program Files (x86)\hMailServer>"C:\Program Files\Duplicati 2\Duplicati.Comma
ndLine.exe" backup "s3://[redacted]/?s3-server-name=s3.amazonaws.com&s3-
location-constraint=&s3-storage-class=GLACIER&auth-username=[redacted]
&auth-password=[redacted]" "C:\Program Files (x86)
\hMailServer\\" --backup-name=hMailServer --dbpath="C:\Users\Administrator\AppDa
ta\Local\Duplicati\79657566658985678890.sqlite" --encryption-module= --compressi
on-module=zip --dblock-size=100MB --keep-time=1M --no-encryption=true --force-lo
cale=en-us --disable-module=console-password-input
Backup started at 09.01.2019 12:04:36
Checking remote backup ...
  Listing remote folder ...
  Listing remote folder ...
  Listing remote folder ...
  Listing remote folder ...
  Listing remote folder ...
Fatal error => The request signature we calculated does not match the signature
you provided. Check your key and signing method.

Amazon.S3.AmazonS3Exception: The request signature we calculated does not match
the signature you provided. Check your key and signing method. ---> Amazon.Runti
me.Internal.HttpErrorResponseException: The remote server returned an error: (40
3) Forbidden. ---> System.Net.WebException: The remote server returned an error:
 (403) Forbidden.
   at System.Net.HttpWebRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executi
onContext)
   at Amazon.Runtime.Internal.RedirectHandler.InvokeSync(IExecutionContext execu
tionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executio
nContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeSync(IExecutionContext ex
ecutionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executio
nContext)
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.BackendManager.List()
   at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(Back
endManager backend, Options options, LocalDatabase database, IBackendWriter log,
 String protectedfile)
   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(Backen
dManager backend, Options options, LocalDatabase database, IBackendWriter log, S
tring protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendMana
ger backend, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__19.MoveNext()
```
I strongly suspect it's because the original secret key contains a slash (`/`), which gets escaped as `%2F`, and then Windows strips the percent sign. You should probably output `%%` instead of `%` in any escape sequence to make it work. I'll verify it now and report back in a minute.

**Comment by vdenisov** [comment]
...Aaand it worked as expected with `%%2F`. Fixing this would be appreciated, out of ~10 keys I have, 4 contain slashes - so it should be a pretty widespread issue.

**Comment by kenkendk** [comment]
All destination parameters must be URL encoded. Attempting to bypass this for AWS keys, will likely create other issues.
