### ISSUE TITLE
Error: Configuration system failed to initialize

### ISSUE THREAD

**Issue by ghost** [duplicati/duplicati#1761]
New user here, just installed today. I went to run a backup I had just created and it spat out this error.

 Error: Configuration system failed to initialize

Error: System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: Unrecognized configuration section runtime. (C:\Users\3ntropy\Downloads\Duplicati 1.3.4\Duplicati.exe.Config line 2)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.PrivilegedConfigurationManager.GetSection(String sectionName)
   at System.Net.Configuration.SettingsSectionInternal.get_Section()
   at System.Net.ServicePointManager.set_UseNagleAlgorithm(Boolean value)
   at Duplicati.Library.Modules.Builtin.HttpOptions.Dispose()
   at Duplicati.Library.Main.Interface.Dispose()
   at Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
InnerError: System.Configuration.ConfigurationErrorsException: Unrecognized configuration section runtime. (C:\Users\3ntropy\Downloads\Duplicati 1.3.4\Duplicati.exe.Config line 2)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
Cleanup output:
Error: System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: Unrecognized configuration section runtime. (C:\Users\3ntropy\Downloads\Duplicati 1.3.4\Duplicati.exe.Config line 2)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.PrivilegedConfigurationManager.GetSection(String sectionName)
   at System.Net.Configuration.SettingsSectionInternal.get_Section()
   at System.Net.ServicePointManager.set_UseNagleAlgorithm(Boolean value)
   at Duplicati.Library.Modules.Builtin.HttpOptions.Dispose()
   at Duplicati.Library.Main.Interface.Dispose()
   at Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
InnerError: System.Configuration.ConfigurationErrorsException: Unrecognized configuration section runtime. (C:\Users\3ntropy\Downloads\Duplicati 1.3.4\Duplicati.exe.Config line 2)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
Cleanup output:
Error: System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: Unrecognized configuration section runtime. (C:\Users\3ntropy\Downloads\Duplicati 1.3.4\Duplicati.exe.Config line 2)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.PrivilegedConfigurationManager.GetSection(String sectionName)
   at System.Net.Configuration.SettingsSectionInternal.get_Section()
   at System.Net.ServicePointManager.set_UseNagleAlgorithm(Boolean value)
   at Duplicati.Library.Modules.Builtin.HttpOptions.Dispose()
   at Duplicati.Library.Main.Interface.Dispose()
   at Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
InnerError: System.Configuration.ConfigurationErrorsException: Unrecognized configuration section runtime. (C:\Users\3ntropy\Downloads\Duplicati 1.3.4\Duplicati.exe.Config line 2)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)

Any ideas what's going on?

Thanks

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
