### ISSUE TITLE
Amazon S3  - connection forcibly closed

### ISSUE THREAD

**Issue by NickPyz** [duplicati/duplicati#1792]
I created a new backup to Amazon S3 for a Thunderbird profile. 
Approx 1000 files, 800MB
snapshot policy = on 
AES encryption
Max. Backup File Size = 30MB

The job opens the "Running Task" window. It starts the encryption .. and then seems to stall after a few minutes, and finally crashes after 40-45 minutes with the following error message:

_"Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host."_

I checked the S3 bucket using a separate browser, and no data was transferred to the new folder I created.

I created another job, same specs ... but this time to box.com. It took 2 hours to process the 1st backup, but it was successful.

Duplicati - 2.0.1.17_canary_2016-05-14
Thanks
##

**Comment by NickPyz** [comment]
Part 2.

Tried the same backup spec to Google Drive and was successful
Then OneDrive, and it failed:

System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes)
   at Duplicati.Library.Main.Operation.BackupHandler.RunMainOperation(ISnapshotService snapshot, BackendManager backend)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)


Tried MEGA, and it failed:

System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at CG.Web.MegaApiClient.WebClient.PostRequest(Uri url, Stream dataStream, String contentType)
   at CG.Web.MegaApiClient.WebClient.PostRequestJson(Uri url, String jsonData)
   at CG.Web.MegaApiClient.MegaApiClient.Request[TResponse](RequestBase request, Object context)
   at CG.Web.MegaApiClient.MegaApiClient.Login(AuthInfos authInfos)
   at Duplicati.Library.Backend.Mega.MegaBackend.get_Client()
   at Duplicati.Library.Backend.Mega.MegaBackend.GetCurrentFolder(Boolean autocreate)
   at Duplicati.Library.Backend.Mega.MegaBackend.ResetFileCache(IEnumerable`1 list)
   at Duplicati.Library.Backend.Mega.MegaBackend.List()
   at Duplicati.Server.WebServer.RESTMethods.RemoteOperation.TestConnection(String url, RequestInfo info)
   at Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)


Not sure what's going on.

**Comment by NickPyz** [comment]
So I appear to have several issues, and haven't been able to sort them all out yet. My clues come from the Windows 10 event viewer:

**(1) Event 513 CAPI2 error -**  

Application Event Log:
Cryptographic Services failed while processing the OnIdentity() call in the System Writer Object.

Details:
AddLegacyDriverFiles: Unable to back up image of binary Microsoft Link-Layer Discovery Protocol.

System Error:
Access is denied.

I found a method to repair this here, and the CAPI2 errors stopped:
http://justworks.ca/blog/fix-event-513-capi2-errors-during-windows-backup

Unfortunately, my duplicati job to OneDrive still crashed.


**(2) Event 13, VSS**

Event viewer identified a faulty writer. I included the vss-exclude-writers option pointing to the writer. Once again, backup job still crashes.

**(3) Run without VSS**

One of the volumes that I am backing up files from is a mounted encrypted container (VeraCrypt). When I run from the terminal: _vssadmin list volumes_, this volume isn't shown. So, I assume VSS can't work with this volume .... and decided to re-run the job to OneDrive endpoint without VSS. It also fails.

I have exhausted my knowledge of options to get this to work. Any advice will be appreciated, including the possibility that I am struggling to overcome a bug.

Thanks.

**Comment by ts678** [comment]
Searching the open and closed issues, this is the only one to mention capi2, but maybe nobody has looked that deeply since.
The word forcibly got a few mentions in later issues, mostly in posts from me, but I think an occasional one is to be expected. Internet glitches happen, and sometimes a server may decide it's had enough, and leave. That's what the retries are there for.

> So I appear to have several issues, and haven't been able to sort them all out yet.

I doubt anyone else can, at this point. Unless there's something more, it's probably best to let this one close, if it remains idle.
