### ISSUE TITLE
2.0.1.17 No filesets found on remote target 

### ISSUE THREAD

**Issue by fafikulus** [duplicati/duplicati#1864]
After 1.3.4 stopped working I tried to use the most recent version, but it doesn't read my backup. I end up with "No filesets found on remote target". Windows 8.1 64 bit.

2016-07-25 18:23: Request for http://127.0.0.1:8200/api/v1/backup/4a38dc22-abef-4a67-a9f3-d4e70b41e347/filesets gave error
System.Exception: No filesets found on remote target

   at Duplicati.Library.Main.Operation.ListFilesHandler.Run(IEnumerable`1 filterstrings, IFilter compositefilter)

   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)

   at Duplicati.Library.Main.Controller.List(IEnumerable`1 filterstrings, IFilter filter)

   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

   at Duplicati.Server.WebServer.RESTMethods.Backup.ListFileSets(IBackup backup, RequestInfo info)

   at Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)

2016-07-25 18:23: Reporting error gave error
System.ObjectDisposedException: Cannot write to a closed TextWriter.

   at System.IO.__Error.WriterClosed()

   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)

   at Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)
##

**Comment by agrajaghh** [comment]
did you try to restore files from the duplicati 1.3 backup with duplicati 2? Thats not possible because duplicati 2 is using a taotally different backup/storage mechanism which is not compatible to the one in 1.3...

**Comment by nerumo** [comment]
I ran into this too. I'd be nice to get a message in the 2.* version that you have to use 1.3. Without any technical knowledge, you'll never find out whats going wrong.

**Comment by rafiks** [comment]
I ran into this but it was a PEBCAK. I thought the Path folder is local but its suppose to be the remote folder on the backblaze B2 bucket.
