### ISSUE TITLE
Invalid size value: nullkb

### ISSUE THREAD

**Issue by herrbasan** [duplicati/duplicati#2099]
400GB initial Backup fails around 70%, cant't seem to get past that point:

System.Exception: Invalid size value: nullkb
   at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes)
   at Duplicati.Library.Main.Operation.BackupHandler.RunMainOperation(ISnapshotService snapshot, BackendManager backend)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

Version: 2.0.1.22
Windows 10 x64

**Comment by kenkendk** [comment]
Do you get other errors?
Can you try to export as commandline, and see if there are some options that look strange?
I think that the error is caused by an option like `--size=` being interpreted as `null` and then suffixed with `kb`, but I cannot guess where that happens.

**Comment by herrbasan** [comment]
This is the only error i get, after that it starts the backup again ... up to the point where it throws the same error. That "export as commandline" .. please elaborate .. i'm new to duplicati :)

**Comment by herrbasan** [comment]
Figured it out: Here it is: 
"C:\Program Files\Duplicati 2\Duplicati.CommandLine.exe" backup "googledrive://Main Backup/?authid=e0a24602c59847951df93ef25a0282b7%3ANdY8Bb0S6cLhSz1QdDeR!" "H:\# Backup\dave\\" --backup-name="Main Backup" --dbpath="C:\Users\dave\AppData\Roaming\Duplicati\CKNAUHKKIC.sqlite" --encryption-module="aes" --compression-module="zip" --dblock-size="100MB" --keep-time="3M" --passphrase="xxxxxxx" --throttle-upload="nullkb" --disable-module="console-password-input"

**Comment by herrbasan** [comment]
![sketch](https://cloud.githubusercontent.com/assets/15235331/20042360/10195382-a479-11e6-9227-13e8450b1444.png)

Not really sure how to disable the throttle ..

**Comment by herrbasan** [comment]
sorry for the spam, i guess having this option up, means when i don't want it to apply i just "close" it right ? Imma do that and let it run. Sorry for making it an issue, i could have figured the whole thing out by myself. The only "bug" would be that it could be smart enough to allow the field to be empty without creating an error.

**Comment by kenkendk** [comment]
I agree that you should not get weird errors like `nullkb` when setting an option that does not work.

And yes, just remove the option to have no throttle applied.
