### ISSUE TITLE
Object does not exist.

### ISSUE THREAD

**Issue by saviodsouza** [duplicati/duplicati#2137]
I have:
- [X ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.0.32 cannary
**Operating System:*Windows Server 2008*
**Backend:**

### Bug description
Describe here the issue that you are experiencing.

'Fatal error
Alphaleonis.Win32.Vss.VssObjectNotFoundException: The requested object does not exist.

   at Alphaleonis.Win32.Vss.WaitCheckAndReleaseVssAsyncOperation(IVssAsync* pAsync)

   at Alphaleonis.Win32.Vss.VssBackupComponents.DoSnapshotSet()

   at Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Dictionary`2 options)

   at Duplicati.Library.Snapshots.SnapshotUtility.CreateWindowsSnapshot(String[] folders, Dictionary`2 options)

   at Duplicati.Library.Main.Operation.BackupHandler.GetSnapshot(String[] sources, Options options, ILogWriter log)

   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)'

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Everything was working fine till the database got corrupted for for some unknown reasons and repair was not working.

Looks like it is something to do with Snapshots. I don't know what went wrong. 

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Clicking run backup should run normally.

**Comment by saviodsouza** [comment]
Closing this issues.

VSS was not working correctly, even Duliicati 1.3 gave some similar error.

Sorry for raising a false bug.
