### ISSUE TITLE
Reporting error

### ISSUE THREAD

**Issue by RightOnTrack** [duplicati/duplicati#2160]
I have:
- [ ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.34 Canary
**Operating System:** Windows 10 v1607
**Backend:** Backblaze B2

### Bug description
Not getting a report after backup job. Only get a "Reporting Error". Could this be related to the ongoing sendmail issue that still exists?

### Steps to reproduce
Just let backup run on schedule.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### debug log

Dec 5, 2016 2:55 PM: Reporting error gave error
System.ObjectDisposedException: Cannot write to a closed TextWriter.
   at System.IO.__Error.WriterClosed()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)
Dec 5, 2016 2:55 PM: Reporting error gave error
System.ObjectDisposedException: Cannot write to a closed TextWriter.
   at System.IO.__Error.WriterClosed()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)
Dec 5, 2016 2:55 PM: Request for http://127.0.0.1:8200/api/v1/serverstate/?lasteventid=214&longpoll=true&duration=299s gave error
System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.WaitHandle.WaitOneNative(SafeHandle waitableSafeHandle, UInt32 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout, Boolean exitContext)
   at Duplicati.Server.EventPollNotify.Wait(Int64 eventId, Int32 milliseconds)
   at Duplicati.Server.WebServer.RESTMethods.RequestInfo.LongPollCheck(EventPollNotify poller, Int64& id, Boolean& isError)
   at Duplicati.Server.WebServer.RESTMethods.ServerState.GET(String key, RequestInfo info)
   at Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)
Dec 5, 2016 2:55 PM: Request for http://127.0.0.1:8200/api/v1/notification/1 gave error
System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Data.SQLite.UnsafeNativeMethods.sqlite3_step(IntPtr stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteTransaction.Commit()
   at Duplicati.Server.Database.Connection.SetSettings(IEnumerable`1 values, Int64 id, IDbTransaction transaction)
   at Duplicati.Server.Database.ServerSettings.SaveSettings()
   at Duplicati.Server.Database.ServerSettings.set_UnackedWarning(Boolean value)
   at Duplicati.Server.Database.Connection.DismissNotification(Int64 id)
   at Duplicati.Server.WebServer.RESTMethods.Notification.DELETE(String key, RequestInfo info)
   at Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)

**Comment by wezlar** [comment]
I am also receiving this error. All connection tests were ok, left it to backup overnight, but it failed with the same error. Opened up Duplicati this morning to check status and the backup started and seems to be running fine.

**Comment by bobkous** [comment]
Same error here. After successful backup:

Apr 17, 2017 9:06 PM: Request for http://127.0.0.1:8200/api/v1/remoteoperation/create gave error
System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at Duplicati.Library.Utility.AsyncHttpRequest.AsyncWrapper.GetResponseOrStream()
   at Duplicati.Library.Utility.AsyncHttpRequest.GetResponse()
   at Duplicati.Library.Backend.OneDrive.FindFolders(Boolean autocreate)
   at Duplicati.Server.WebServer.RESTMethods.RemoteOperation.CreateFolder(String uri, RequestInfo info)
   at Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)
Apr 17, 2017 9:06 PM: Reporting error gave error
System.ObjectDisposedException: Cannot write to a closed TextWriter.
   at System.IO.__Error.WriterClosed()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)

Running Duplicati 2.0.1.53_experimental_2017-03-13 on Windows 10 v1703 with OneDrive destination.

**Comment by ts678** [comment]
This might have been fixed at some point. Is anyone still seeing this on a current Duplicati release?
