### ISSUE TITLE
Can't change time settings.

### ISSUE THREAD

**Issue by RoffeEklund** [duplicati/duplicati#2161]
I have:
- [x ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.30_experimental_2016-11-03
**Operating System:** windows 10 x64
**Backend:**

### Bug description
I have completed my first backup successfully. But I wanted to change my Schedule from 02:00 PM to 02:00 AM. But it just won't change. Tried different time settings and it's still set to 02:00 PM. Will I have to create a new backup job set a new time? 

I got back to setting it and when I edit the backup it says 02:00 AM In the settings.
But it doesn't reflect the settings in the main list.

Also get the error in the log file:
Dec 7, 2016 6:37 PM: Request for http://127.0.0.1:8200/api/v1/hyperv gave error
System.ObjectDisposedException: Cannot write to a closed TextWriter.
   at System.IO.__Error.WriterClosed()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(Char value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteObjectStart(JsonWriter writer, Object value, JsonContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Duplicati.Server.Serialization.Serializer.SerializeJson(TextWriter sw, Object o, Boolean preventDispose)
   at Duplicati.Server.WebServer.BodyWriter.WriteJsonObject(Object o)
   at Duplicati.Server.WebServer.RESTMethods.HyperV.GET(String key, RequestInfo info)
   at Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)

**Comment by kenkendk** [comment]
The time-issue should be fixed in the latest canary.
The other issue is partially fixed, but it depends on your setup.
We are working on a fix: https://github.com/duplicati/duplicati/pull/2156

**Comment by kenkendk** [comment]
I think this is now fixed.
