### ISSUE TITLE
Errors on symlinks created with WSL

### ISSUE THREAD

**Issue by marceldev89** [duplicati/duplicati#2171]
I have:
- [X] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.30_experimental_2016-11-03
**Operating System:** Windows 10 Pro
**Backend:** WebDAV

### Bug description
Symlinks created with WSL (Bash on Windows) cause Duplicati to throw errors like below:
```
Failed to process path: C:\Users\marcel\Projects\R3-Web\node_modules\.bin\which
Alphaleonis.Win32.Filesystem.UnrecognizedReparsePointException: I/O error occurred.
   at Alphaleonis.Win32.Filesystem.Device.GetLinkTargetInfoInternal(SafeFileHandle safeHandle)
   at Alphaleonis.Win32.Filesystem.File.GetLinkTargetInfoInternal(KernelTransaction transaction, String path, PathFormat pathFormat)
   at Duplicati.Library.Snapshots.WindowsSnapshot.GetSymlinkTarget(String file)
   at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes)
```
Those symlinks show up as a junction on the Windows filesystem but don't point to anything. Also see https://github.com/Microsoft/BashOnWindows/issues/353 for more information.

### Steps to reproduce
- Setup WSL
- Create a symlink on a mounted Windows filesystem (e.g. /mnt/c/)
- Let Duplicati do it's thing

**Actual result:** Popup saying: "Warning while running <backup name>"
**Expected result:** No errors/popup

**Comment by kmwoley** [comment]
**Duplicati Version:** 2.0.3.3_beta_2018-04-02
**Operating System:** Windows 10 Pro
**Backend:** Local Folder or Drive

Seeing what I think is related to WSL-created files/links:
```
Error reported while accessing file: C:\Users\xxxxxx\xxxxx\xxxxx\.tox\lint\bin\python3.4
System.OverflowException: Arithmetic operation resulted in an overflow.
   at Alphaleonis.Win32.Filesystem.Device.GetLinkTargetInfoCore(SafeFileHandle safeHandle)
   at Alphaleonis.Win32.Filesystem.File.GetLinkTargetInfoCore(KernelTransaction transaction, String path, PathFormat pathFormat)
   at Duplicati.Library.Snapshots.SystemIOWindows.GetSymlinkTarget(String file)
   at Duplicati.Library.Snapshots.WindowsSnapshot.GetSymlinkTarget(String file)
   at Duplicati.Library.Snapshots.SnapshotUtility.IsSymlink(ISnapshotService snapshot, String path, FileAttributes attributes)
   at Duplicati.Library.Main.Operation.BackupHandler.FilterHandler.AttributeFilter(String rootpath, String path, FileAttributes attributes)
   at Duplicati.Library.Utility.Utility.<EnumerateFileSystemEntries>d__22.MoveNext()

**Comment by aletus** [comment]
I have the same issue on Windows and WSL symlinks.  It is really annoying since it pop up errors every time your back up is runn. 

Is there a way to suppress/ignore this error?   

BTW, you can manually recreate the link on the Windows side to remove the error but I have too many symlinks created automatically on the WSL side it's not feasible to do that.

**Comment by Fealthas** [comment]
Note sure if related, but I get this error
![image](https://user-images.githubusercontent.com/25716039/72493458-165b1200-37ef-11ea-91cf-d5a1edee808f.png)
on an in-WSL created venv, on this file and the other 0 kb ones.
![image](https://user-images.githubusercontent.com/25716039/72493509-499da100-37ef-11ea-8ef2-428f400b2616.png)
Its not a major problem, but it keeps spamming up the logs.

**Comment by geonanorch** [comment]
@Fealthas exact same issue here (with 2.0.5.1_beta_2020-01-18), and like @musikele mentioned, trying to ignore symlinks (core option "symlink-policy") did not help.
Of course this looks rather like a Windows problem, but a workaround (an ignore mode, which also ignores those errors) would be welcome.

**Comment by Fealthas** [comment]
Note that the warning occurs for symlinks that have a different pointing structure/path than the file system you are backing up on.

So the symlink may point to /usr/bin/python, but this isn't a valid path on the windows machine I am running duplicati on. This is why the path doesn't get processed.

**Comment by tom7** [comment]
On Windows 10 Duplicati 2.0.5.1_beta_2020-01-18 I get the PathProcessingFailed error for symlinks (to a destination like "../level.h") created with bash. This is even with --symlink-policy = ignore, which is the surprising part.

This error looks to be from a catch-all exception handler in FileBlockProcessor.cs so it's hard to see where it might be coming from. One fishy thing I found is that in FileEnumerationProcess, the call to snapshot.GetSymlinkTarget is wrapped with an exception handler:
https://github.com/duplicati/duplicati/blob/c5b91503b8ede912863d641d79f8c383f5b08a85/Duplicati/Library/Main/Operation/Backup/FileEnumerationProcess.cs#L355

But in MetadataPreProcess.cs it is not:
https://github.com/duplicati/duplicati/blob/c5b91503b8ede912863d641d79f8c383f5b08a85/Duplicati/Library/Main/Operation/Backup/MetadataPreProcess.cs#L177

if this function throws an exception on a symlink to a path like "../level.h", it doesn't matter whether symlink-policy is "ignore", which would explain the issue?
