### ISSUE TITLE
 System.Exception: Found 2381 files that are missing from the remote storage, please run repair

### ISSUE THREAD

**Issue by Athep** [duplicati/duplicati#2198]
I have:
- [x] searched open and closed issues for duplicates. Some seems similar.

### Version info
**Duplicati Version: 2.0.1.36_canary_2016-12-24
**Operating System: Windows server 2012 R2
**Backend: Google Drive

### Bug description

Backup has been running every night for a long time without any big issues. But suddenly:

Failed: Found 2381 files that are missing from the remote storage, please run repair
Details: System.Exception: Found 2381 files that are missing from the remote storage, please run repair

MainOperation: Repair
RecreateDatabaseResults: null
EndTime: 2016-12-25 20:33:00
BeginTime: 2016-12-25 20:32:29
Duration: 00:00:31.3245547
Messages: [
    Destination and database are synchronized, not making any changes

And also, running verify does not find any problems.

But it is not possible to restore any files. I get the same error on missing files as when running backup.

When looking manually on Google Drive, all files is there. None is missing.

**Comment by Athep** [comment]
Same problem appears now even with verify. But it is random.

`27 dec 2016 08:42: Failed while executing "Verify" with id: 1
System.Exception: Found 2380 files that are missing from the remote storage, please run repair
   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
   at Duplicati.Library.Main.Operation.TestHandler.Run(Int64 samples)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Test(Int64 samples)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
`
Trying again right after the failed run, it completes with no error. Next time, failing again.

**Comment by Athep** [comment]
Still same issue. Any idea of what the problem could be ? 
Maybe Google Drive can't handle the size ?
Backup size is 255.80 GB / 502 Versions. File count: 3294

**Comment by Athep** [comment]
I have now downloaded the whole backup set from google drive and placed it on o local network share. 
Problem is now gone and it seems that it is something with the backend that is causing the failure.
The internet connection speed is 100 Mbit/s and very stable. So this is not the reason. Any ideas ?
