### ISSUE TITLE
Repair - SQL Logic Error and Locked File

### ISSUE THREAD

**Issue by stellarpower** [duplicati/duplicati#2265]
I have:
- [ x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.35_experimental_2016-12-13
**Operating System:** Windows 10 AMD64.
**Backend:** LAN OpenSSH

### Bug description
I made a series of large backups last night and as part of expanding my own personal scripts that use the console client, and then reorganised the files on my backup server to a different folder, e.g. the url went from

ssh://192.168.0.x:port/home/backup/UserSpace

to

ssh://192.168.0.x:port/home/backup2/UserSpace

I was backing up the same files in both cases. After moving the files, I ran the following:

`Duplicati.CommandLine.exe backup ssh://192.168.0.x:port/home/backup2/UserSpace/ --auth-username=... --no-encryption --ssh-keyfile="..." --ssh-fingerprint="..." Folder`

and the output was

`Backup started at 18/01/2017 14:45:49`
`Checking remote backup ...`
`  Listing remote folder ...`
`Extra unknown file: duplicati-ba3bd4f8375384433b9d437a37ac70947.dblock.zip`
`Extra unknown file: duplicati-ief83d25878504b6eb6492e47ba13d907.dindex.zip`
`Extra unknown file: duplicati-bd40ef83368f94e67afa00bf47fc73378.dblock.zip`
`Extra unknown file: duplicati-iaeac152ea5a94e6794ee806489b6b51f.dindex.zip`
`Extra unknown file: duplicati-20170117T230406Z.dlist.zip`
`Extra unknown file: duplicati-20170117T224412Z.dlist.zip`
`Extra unknown file: duplicati-20170117T225733Z.dlist.zip`
`Found 7 remote files that are not recorded in local storage, please run repair`
`Fatal error => Found 7 remote files that are not recorded in local storage, please run repair`

`Found 7 remote files that are not recorded in local storage, please run repair`

I therefore went to repair the system, so that the previous backups would be incorporated into the local db as residing in the new path:

`duplicati.commandline.exe repair ssh://192.168.0.x:port/home/backup2/UserSpace/ --auth-username=... --no-encryption --ssh-keyfile=... --ssh-fingerprint=...`

`Failed to read local db C:\Users\name\AppData\Roaming\Duplicati\QXNRUBRWMR.sqlite, error: SQL logic error or missing database`
`table "Operation" already exists => SQL logic error or missing database`
`table "Operation" already exists`
`Renaming existing db from C:\Users\nameAppData\Roaming\Duplicati\QXNRUBRWMR.sqlite to C:\Users\name\AppData\Roaming\Duplicati\QXNRUBRWMR.backup-1`

`The process cannot access the file because it is being used by another process.`

I have used both handle and ProcessExplorer to search for processes with a handle on the database and its backup and it doesn't return any, so presumably Duplicati is locking itself up.

### Steps to reproduce
- Move the backups on the target
- Run the command line client with the new folder as the destination
- Attempt to repair the local database, the system complains about a SQL logic error and then a locked file when no other processes are accessing it. Based on the stack trace it looks like two differing errors.

### debug log
Failed to read local db C:\Users\name\AppData\Roaming\Duplicati\QXNRUBRWMR.sqlite, error: SQL logic error or missing database
table "Operation" already exists => System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
table "Operation" already exists
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at Duplicati.Library.SQLiteHelper.DatabaseUpgrader.UpgradeDatabase(IDbConnection connection, String sourcefile, String schema, IList`1 versions)
   at Duplicati.Library.SQLiteHelper.DatabaseUpgrader.UpgradeDatabase(IDbConnection connection, String sourcefile, Type eltype)
   at Duplicati.Library.Main.Database.LocalDatabase.CreateConnection(String path)
   at Duplicati.Library.Main.Operation.RepairHandler.Run(IFilter filter)
Renaming existing db from C:\Users\name\AppData\Roaming\Duplicati\QXNRUBRWMR.sqlite to C:\Users\name\AppData\Roaming\Duplicati\QXNRUBRWMR.backup-1

System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Duplicati.Library.Main.Operation.RepairHandler.Run(IFilter filter)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Repair(IFilter filter)
   at Duplicati.CommandLine.Commands.Repair(List`1 args, Dictionary`2 options, IFilter filter)
   at Duplicati.CommandLine.Program.RealMain(String[] args)

Thanks for all your efforts, it's a good piece of software.

**Comment by kenkendk** [comment]
When you change the destination, Duplicati thinks it is a new backup, and then points to a fresh local database. This is why it said "Extra unknown file".

If you look in the folder `C:\Users\name\AppData\Roaming\Duplicati\` you can see a file called `dbconfig.json`, which you can edit with Notepad or similar.

Inside the file is the mapping from destination to local database names. You can edit this file so that the two destinations point to the correct file.

You can also use the option `--dbpath=...path-to-db...` to explicitly choose the local database without relying on `dbconfig.json`.

I think the issue here is that the initial backup has created a database that is faulty in some manner. When you attempt the repair, it sees that the database is there, and attempts to use it.
I think you can also get the `repair` command to work if you remove (or rename) the database being mentioned, and then run repair.

**Comment by stellarpower** [comment]
Thanks for getting back to me.

Would you like the databases for analysis? I'm guessing this isn't high-priority right now but if you'd like them I'll try and get them to you, or alternatively can try and dissect them myself if you're looking for anything in particular.

For now, as you said, I've just pointed Duplicati to the old databases in the JSON.

Thanks!
