### ISSUE TITLE
Corrupted data after restoring a newly created backup

### ISSUE THREAD

**Issue by nacaal** [duplicati/duplicati#2275]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.35
**Operating System:** Windows 10
**Backend:** MEGA

### Bug description
1. Created a new backup on MEGA with 677 files.
2. Started a restore task on another machine to test the integrity of the backup.
3. After 20 minutes the restore task stopped with the following error:
> The version(s) being updated to, already exists

4. Started a new restore task on the same machine with the same settings as before.
5. The restore task finished without any errors this time.
6. After diffing the files with WinMerge against the originals, it shows that 5 of 677 files are corrupt and have a size of **0 bytes**.
7. Started another restore task again, the same as before on the same machine.
8. The restore task finished without any errors and this time all the restored files are okay.
9. Two more tries of restoring this backup worked without any corrupted files.

### Steps to reproduce
Not sure how to reproduce it. I basically did the same thing 5 times without any alteration as described above. One time it produced 5 corrupted files without warning.

### debug log
- Jan 21, 2017 1:01 PM: Failed while executing "RepairUpdate" with id: c62n71d1-544e-14ce-8d09-17362df5aeb4
```
System.Exception: The version(s) being updated to, already exists
   at Duplicati.Library.Main.Operation.RecreateDatabaseHandler.RunUpdate(IFilter filter, NumberedFilterFilelistDelegate filelistfilter, BlockVolumePostProcessor blockprocessor)
   at Duplicati.Library.Main.Controller.<UpdateDatabaseWithVersions>c__AnonStorey7.<>m__0(RecreateDatabaseResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.UpdateDatabaseWithVersions(IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

```

**Comment by JonMikelV** [comment]
Reported again by another user doing a restore.
https://forum.duplicati.com/t/the-version-s-being-updated-to-already-exists/6192?u=jonmikelv
