### ISSUE TITLE
Failed while executing "Backup" with id: 1

### ISSUE THREAD

**Issue by kxcooper** [duplicati/duplicati#2290]
How do I troubleshoot this please? I'm an end user first time with duplicati installing on Mum's Windows 8 laptop trying to backup to new folder in Box account.

There's over 7GB to back up one time but fails with just 500MB ending up in the box folder.

Please tell me how I can give you the information to investiage and narrow down the cause of the error.

I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.35
**Operating System:** Windows 8 64 bit
**Backend:** box.com

### Bug description
Describe here the issue that you are experiencing.
Failed while executing "Backup" with id: 1

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug
- first time installation of backup of documents, music, pictures, videos to box account fails repeatedly

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- Failed while executing "Backup" with id: 1

### debug log
How do I obtain this please?
28 Jan 2017 15:33: Failed while executing "Backup" with id: 1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes)
   at Duplicati.Library.Main.Operation.BackupHandler.RunMainOperation(ISnapshotService snapshot, BackendManager backend)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

**Comment by kxcooper** [comment]
Can someone help me with this please.

**Comment by kxcooper** [comment]
I guess that'll be a no then!

Looks like not the software for end users.

Shame.

**Comment by kenkendk** [comment]
Maybe this is the same as #2295 ?

**Comment by kenkendk** [comment]
Closing as duplicate of #2349
