### ISSUE TITLE
Backup to Amazon S3 eu-west-2 bucket fails due to lack of AWS4-HMAC-SHA256 authorization

### ISSUE THREAD

**Issue by dominicsayers** [duplicati/duplicati#2296]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.35_experimental_2016-12-13
**Operating System:** Windows 10 64-bit
**Backend:** Amazon S3

### Bug description
As of last night (UTC), a backup that has been running OK started failing with the error

```
Amazon.S3.AmazonS3Exception: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256
```

### Steps to reproduce
- Create an Amazon S3 bucket in the region `eu-west-2`
- Create a Duplicati backup that backs up to that bucket using legitimate credentials
- Run the backup

**Actual result:** The backup fails with the above error
**Expected result:** The backup succeeds (as it did prior to last night)

### Backup configuration
```json
{
  "CreatedByVersion": "2.0.1.35",
  "Schedule": {
    "ID": 1,
    "Tags": [
      "ID=1"
    ],
    "Time": "2017-01-28T00:00:30Z",
    "Repeat": "1D",
    "LastRun": "2017-01-28T10:27:37Z",
    "Rule": "AllowedWeekDays=Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday",
    "AllowedDays": [
      "mon",
      "tue",
      "wed",
      "thu",
      "fri",
      "sat",
      "sun"
    ]
  },
  "Backup": {
    "ID": "1",
    "Name": "Example",
    "Tags": [],
    "TargetURL": "s3://examplebucket/backups/example?s3-server-name=s3.amazonaws.com&s3-location-constraint=&s3-storage-class=REDUCED_REDUNDANCY&auth-username=<AWS username>&auth-password=<aws secret key>",
    "DBPath": "C:\\Users\\Example\\AppData\\Roaming\\Duplicati\\TJLZFAFLGV.sqlite",
    "Sources": [
      "D:\\Users\\Example\\"
    ],
    "Settings": [
      {
        "Filter": "",
        "Name": "encryption-module",
        "Value": "",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "compression-module",
        "Value": "zip",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "dblock-size",
        "Value": "50MB",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "--no-encryption",
        "Value": "true",
        "Argument": null
      }
    ],
    "Filters": [],
    "Metadata": {
      "LastErrorDate": "20170127T142652Z",
      "LastErrorMessage": "GLACIER is not allowed.",
      "LastDuration": "00:00:00.9905377",
      "LastStarted": "20170128T103718Z",
      "LastFinished": "20170128T103719Z",
      "LastBackupDate": "00010101T000000Z",
      "BackupListCount": "0",
      "TotalQuotaSpace": "0",
      "FreeQuotaSpace": "0",
      "AssignedQuotaSpace": "0",
      "TargetFilesSize": "0",
      "TargetFilesCount": "0",
      "TargetSizeString": "0 bytes"
    },
    "IsTemporary": false
  },
  "DisplayNames": {
    "D:\\Users\\example": "Example"
  }
}
```

### debug log
```
Amazon.S3.AmazonS3Exception: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256. ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RedirectHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.BackendManager.List()
   at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
```

**Comment by dominicsayers** [comment]
I just created an identical backup to a bucket in the the `us-east-1` region and it works OK. Looks like this has become a problem for regions that only support `AWS4-HMAC-SHA256`.

**Comment by dominicsayers** [comment]
Heh :-/

After checking diligently to make sure this was a real issue, the backups then started working again today.

I'll close the issue but not delete it in case other people suffer this temporary problem.

**Comment by dominicsayers** [comment]
For anybody else experiencing this issue (which happened again to me today): I set the `Use SSL` check box in the backup settings and it seemed to fix it.
