### ISSUE TITLE
Amazon Drive: The remote server returned an error: (400) Bad Request. [$20]

### ISSUE THREAD

**Issue by rdae** [duplicati/duplicati#2297]
I have:
- [x ] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.44_canary_2017-01-24
**Operating System:** Windows 8.1 Enterprise N
**Backend:** Amazon Drive

### Bug description
During backup, error popped up then stopped.
The remote server returned an error: (400) Bad Request.

### Steps to reproduce
- manual run backup

**Actual result:** 
Error followed by "Found 1 remote files that are not recorded in local storage, please run repair" error after re-run

**Expected result:** 
Backup continuation and completion.

### Screenshots
N/A

### debug log
**Jan 31, 2017 8:54 PM: Failed while executing "Backup" with id: 28**
```
System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes)
   at Duplicati.Library.Main.Operation.BackupHandler.RunMainOperation(ISnapshotService snapshot, BackendManager backend)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
```

**Jan 31, 2017 8:54 PM: Fatal error**

```
{"ClassName":"System.Net.WebException","Message":"The remote server returned an error: (400) Bad Request.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes)\r\n   at Duplicati.Library.Main.Operation.BackupHandler.RunMainOperation(ISnapshotService snapshot, BackendManager backend)\r\n   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)\r\n   at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)\r\n   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)\r\n   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)\r\n   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nHandleFilesystemEntry\nDuplicati.Library.Main, Version=2.0.1.44, Culture=neutral, PublicKeyToken=null\nDuplicati.Library.Main.Operation.BackupHandler\nBoolean HandleFilesystemEntry(Duplicati.Library.Snapshots.ISnapshotService, Duplicati.Library.Main.BackendManager, System.String, System.IO.FileAttributes)","HResult":-2146233079,"Source":"Duplicati.Library.Main","WatsonBuckets":null}
```

**Jan 31, 2017 8:54 PM: Failed disposing index volume**
```
{"ClassName":"System.InvalidOperationException","Message":"Attempted to dispose an index volume that was being written","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at Duplicati.Library.Main.Volumes.IndexVolumeWriter.Dispose()\r\n   at Duplicati.Library.Main.Operation.BackupHandler.Dispose()","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nDispose\nDuplicati.Library.Main, Version=2.0.1.44, Culture=neutral, PublicKeyToken=null\nDuplicati.Library.Main.Volumes.IndexVolumeWriter\nVoid Dispose()","HResult":-2146233079,"Source":"Duplicati.Library.Main","WatsonBuckets":null}
```

**Jan 31, 2017 9:01 PM: Failed while executing "Backup" with id: 28**
```
Duplicati.Library.Interface.UserInformationException: Found 1 remote files that are not recorded in local storage, please run repair
   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
```

**Jan 31, 2017 9:01 PM: Message**
```
Extra unknown file: prefix-b78ab3...43ed9.dblock.zip.gpg
```

**Jan 31, 2017 9:01 PM: Message**
```
Found 1 remote files that are not recorded in local storage, please run repair
```

**Jan 31, 2017 9:01 PM: Message**
```
Fatal error
Duplicati.Library.Interface.UserInformationException: Found 1 remote files that are not recorded in local storage, please run repair
   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
```

**Jan 31, 2017 9:01 PM: Fatal error**
```
{"ClassName":"Duplicati.Library.Interface.UserInformationException","Message":"Found 1 remote files that are not recorded in local storage, please run repair","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)\r\n   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend, String protectedfile)\r\n   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)\r\n   at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)\r\n   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)\r\n   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)\r\n   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nVerifyRemoteList\nDuplicati.Library.Main, Version=2.0.1.44, Culture=neutral, PublicKeyToken=null\nDuplicati.Library.Main.Operation.FilelistProcessor\nVoid VerifyRemoteList(Duplicati.Library.Main.BackendManager, Duplicati.Library.Main.Options, Duplicati.Library.Main.Database.LocalDatabase, Duplicati.Library.Main.IBackendWriter, System.String)","HResult":-2146233088,"Source":"Duplicati.Library.Main","WatsonBuckets":null}
```

**Comment by gruselglatz** [comment]
Same issue here, but restore works, and the backup seems to be complete.

**Comment by ElRico** [comment]
I'm seeing the same issue with version 2.0.1.53_experimental_2017-03-13. Duplicati interrupts my initial backup of when it encounters the 400 error, when I would expect it to retry. When I manually re-start the backup, Duplicati deletes a bunch of files (I've configured with the auto-cleanup flag) and aborts with an error that remote files are present that are not listed in the local database, requiring a database repair. After the database repair, the backup resumes but Duplicati seems to hash every file in the source. That is why I'm hoping the backup will be complete and restorable when it is finished.

I've included the log output below:

- Initial error:

```
Failed: The remote server returned an error: (400) Bad Request.
Details: System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes)
   at Duplicati.Library.Main.Operation.BackupHandler.RunMainOperation(ISnapshotService snapshot, BackendManager backend)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
```

- When I resume the backup, I see the following messages:

```
Apr 9, 2017 7:26 AM: Result
DeletedFiles: 0

DeletedFolders: 0

ModifiedFiles: 0

ExaminedFiles: 0

OpenedFiles: 0

AddedFiles: 0

SizeOfModifiedFiles: 0

SizeOfAddedFiles: 0

SizeOfExaminedFiles: 0

SizeOfOpenedFiles: 0

NotProcessedFiles: 0

AddedFolders: 0

TooLargeFiles: 0

FilesWithError: 0

ModifiedFolders: 0

ModifiedSymlinks: 0

AddedSymlinks: 0

DeletedSymlinks: 0

PartialBackup: False

Dryrun: False

MainOperation: Backup

CompactResults: null

DeleteResults: null

RepairResults:

    MainOperation: Repair

    RecreateDatabaseResults: null

    ParsedResult: Success

    EndTime: 01/01/0001 00:00:00

    BeginTime: 09/04/2017 05:26:06

    Duration: 00:00:00

    BackendStatistics:

        RemoteCalls: 13

        BytesUploaded: 0

        BytesDownloaded: 0

        FilesUploaded: 0

        FilesDownloaded: 0

        FilesDeleted: 11

        FoldersCreated: 0

        RetryAttempts: 0

        UnknownFileSize: 0

        UnknownFileCount: 0

        KnownFileCount: 5222

        KnownFileSize: 1268825635310

        LastBackupDate: 04/04/2017 07:20:50

        BackupListCount: 3

        TotalQuotaSpace: 0

        FreeQuotaSpace: 0

        AssignedQuotaSpace: -1

        ParsedResult: Success

TestResults: null

ParsedResult: Error

EndTime: 09/04/2017 05:26:42

BeginTime: 09/04/2017 05:23:32

Duration: 00:03:10.5294559

Messages: [

    removing file listed as Temporary: duplicati-20170406T052916Z.dlist.zip.aes,

    removing file listed as Deleting: duplicati-bad8f46f9a94848388023223f4ce009e5.dblock.zip.aes,

    removing remote file listed as Deleting: duplicati-bffa817a8fe794b43887f37aa784bba9f.dblock.zip.aes,

    removing file listed as Deleting: duplicati-i8e26a4e9dd4b46c59bbd09cf6d4968ff.dindex.zip.aes,

    removing file listed as Deleting: duplicati-bc27a3febc4534b79b1763f41f0f2468d.dblock.zip.aes,

...

]

Warnings: [

    Extra unknown file: duplicati-ba19a2af577974191b82beebac8b2a235.dblock.zip.aes,

    Extra unknown file: duplicati-b69d5cc277c684890896bc2784a45d5c4.dblock.zip.aes,

    Backend verification failed, attempting automatic cleanup => Found 2 remote files that are not recorded in local storage, please run repair

]

Errors: [

    Found 2 remote files that are not recorded in local storage, please run repair

]
Apr 9, 2017 7:26 AM: Message
Backend verification failed, attempting automatic cleanup
Duplicati.Library.Interface.UserInformationException: Found 2 remote files that are not recorded in local storage, please run repair

   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)

   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend, String protectedfile)
Apr 9, 2017 7:26 AM: Message
Found 2 remote files that are not recorded in local storage, please run repair
Apr 9, 2017 7:26 AM: Message
Extra unknown file: duplicati-b69d5cc277c684890896bc2784a45d5c4.dblock.zip.aes
Apr 9, 2017 7:26 AM: Message
Extra unknown file: duplicati-ba19a2af577974191b82beebac8b2a235.dblock.zip.aes
Apr 9, 2017 7:26 AM: Message
scheduling missing file for deletion, currently listed as Uploading: duplicati-i313ec4262c0c4769b7667841f4bb5520.dindex.zip.aes
Apr 9, 2017 7:26 AM: Message
scheduling missing file for deletion, currently listed as Uploading: duplicati-bab28624d23524cdd9bb49c645d44d020.dblock.zip.aes
Apr 9, 2017 7:26 AM: Message
scheduling missing file for deletion, currently listed as Uploading: duplicati-i945ef333ba2b4ca8810956b87e9b313b.dindex.zip.aes
Apr 9, 2017 7:26 AM: Message
scheduling missing file for deletion, currently listed as Uploading: duplicati-b1f844c6a3769400e8fb44db0b687a454.dblock.zip.aes
Apr 9, 2017 7:26 AM: Message
scheduling missing file for deletion, currently listed as Uploading: duplicati-i5b299c2bd2894c99960d0f65bef690d1.dindex.zip.aes
Apr 9, 2017 7:26 AM: Message
promoting uploaded complete file from Uploading to Uploaded: duplicati-b92b7ca3d61054f23849cfd67ca4b0fc3.dblock.zip.aes
Apr 9, 2017 7:26 AM: Message
removing file listed as Deleting: duplicati-b8ba9e4a1d3ab40f5999aa3410e04f530.dblock.zip.aes
Apr 9, 2017 7:26 AM: Message
removing file listed as Deleting: duplicati-b81835bc64ad148e0b4bc725ca4ba9812.dblock.zip.aes
Apr 9, 2017 7:25 AM: Message
removing remote file listed as Deleting: duplicati-ba6a106b3b223459b8854ba2a2fd6aefc.dblock.zip.aes
Apr 9, 2017 7:25 AM: Message
removing file listed as Deleting: duplicati-i8e721014c57d474aa6c8d51df3d5dd70.dindex.zip.aes
Apr 9, 2017 7:25 AM: Message
removing file listed as Deleting: duplicati-b4d661b48236c4c13ba8eda02ac34af6c.dblock.zip.aes
Apr 9, 2017 7:25 AM: Message
removing file listed as Deleting: duplicati-bcfdd30072f7640209614eabb6d6fac38.dblock.zip.aes
Apr 9, 2017 7:25 AM: Message
removing file listed as Deleting: duplicati-i0eb157b4fc2d4c8ab998bb66dbd49e4f.dindex.zip.aes
Apr 9, 2017 7:25 AM: Message
removing file listed as Deleting: duplicati-b8bd0ff95312a43acb05a4b07e23ae746.dblock.zip.aes
Apr 9, 2017 7:25 AM: Message
removing file listed as Deleting: duplicati-be6531fe14cb840c4b63b20cfe8c2b833.dblock.zip.aes
Apr 9, 2017 7:25 AM: Message
removing file listed as Deleting: duplicati-b0047d9ef61124c9c996c86c3391ccb50.dblock.zip.aes
Apr 9, 2017 7:25 AM: Message
removing file listed as Deleting: duplicati-b962919d6d18c4dd7b8000a664b12931a.dblock.zip.aes
Apr 9, 2017 7:25 AM: Message
removing file listed as Deleting: duplicati-b7177f749201842239e615846fd0e55b7.dblock.zip.aes
Apr 9, 2017 7:25 AM: Message
removing remote file listed as Deleting: duplicati-babdbcaff987c4dc5bfd9d316631b34af.dblock.zip.aes
Apr 9, 2017 7:25 AM: Message
removing remote file listed as Deleting: duplicati-be2bc5684ede941f38b13383b98ff0b23.dblock.zip.aes
Apr 9, 2017 7:25 AM: Message
removing remote file listed as Deleting: duplicati-b71afd765fee34e18aa74ed4686f3bd7c.dblock.zip.aes
Apr 9, 2017 7:25 AM: Message
removing file listed as Deleting: duplicati-b4ad620e412b247319fd72e5a55461022.dblock.zip.aes
Apr 9, 2017 7:25 AM: Message
removing file listed as Deleting: duplicati-bc6cee110cec2490fa7bb91f7c4c954c2.dblock.zip.aes
Apr 9, 2017 7:25 AM: Message
removing file listed as Deleting: duplicati-b2441f89992b44fb2b49c6f33022ea38a.dblock.zip.aes
Apr 9, 2017 7:24 AM: Message
removing remote file listed as Deleting: duplicati-b3417d000fdd543718dd741f82f0a6327.dblock.zip.aes
Apr 9, 2017 7:24 AM: Message
removing remote file listed as Deleting: duplicati-b737a7c5f53c446209b949dbe18ba998f.dblock.zip.aes
Apr 9, 2017 7:24 AM: Message
removing file listed as Deleting: duplicati-b5ad40fa3f19a48b4b096471faeb5c499.dblock.zip.aes
Apr 9, 2017 7:24 AM: Message
removing file listed as Deleting: duplicati-bb9edf17d06734c7aae107057756442ac.dblock.zip.aes
Apr 9, 2017 7:24 AM: Message
removing file listed as Deleting: duplicati-b961b4d20361d4992aa578056bb73bc2a.dblock.zip.aes
Apr 9, 2017 7:24 AM: Message
removing file listed as Deleting: duplicati-b7c13b38097454bb59c8d954138544690.dblock.zip.aes
Apr 9, 2017 7:24 AM: Message
removing file listed as Deleting: duplicati-bbeee0d316c4242249735fd37f04c86cd.dblock.zip.aes
Apr 9, 2017 7:24 AM: Message
removing remote file listed as Deleting: duplicati-bf3abfa0aa40047b7932663c37f41c00b.dblock.zip.aes
Apr 9, 2017 7:24 AM: Message
removing remote file listed as Deleting: duplicati-b343daa12e7ed4173b5aa64a86a39eab6.dblock.zip.aes
Apr 9, 2017 7:24 AM: Message
removing file listed as Deleting: duplicati-b3d313aacc41b49478bcbe8097a7efa6d.dblock.zip.aes
Apr 9, 2017 7:24 AM: Message
removing file listed as Deleting: duplicati-bc27a3febc4534b79b1763f41f0f2468d.dblock.zip.aes
Apr 9, 2017 7:24 AM: Message
removing file listed as Deleting: duplicati-i8e26a4e9dd4b46c59bbd09cf6d4968ff.dindex.zip.aes
Apr 9, 2017 7:24 AM: Message
removing remote file listed as Deleting: duplicati-bffa817a8fe794b43887f37aa784bba9f.dblock.zip.aes
Apr 9, 2017 7:24 AM: Message
removing file listed as Deleting: duplicati-bad8f46f9a94848388023223f4ce009e5.dblock.zip.aes
Apr 9, 2017 7:24 AM: Message
removing file listed as Temporary: duplicati-20170406T052916Z.dlist.zip.aes
```

- Result of the repair operation:

```
Apr 9, 2017 7:32 AM: Result
MainOperation: Repair

RecreateDatabaseResults: null

ParsedResult: Success

EndTime: 09/04/2017 05:32:50

BeginTime: 09/04/2017 05:32:29

Duration: 00:00:20.8961988

Messages: [

    Destination and database are synchronized, not making any changes

]

Warnings: []

Errors: []

BackendStatistics:

    RemoteCalls: 1

    BytesUploaded: 0

    BytesDownloaded: 0

    FilesUploaded: 0

    FilesDownloaded: 0

    FilesDeleted: 0

    FoldersCreated: 0

    RetryAttempts: 0

    UnknownFileSize: 0

    UnknownFileCount: 0

    KnownFileCount: 5220

    KnownFileSize: 1267850678100

    LastBackupDate: 04/04/2017 07:20:50

    BackupListCount: 3

    TotalQuotaSpace: 0

    FreeQuotaSpace: 0

    AssignedQuotaSpace: -1

    ParsedResult: Success
Apr 9, 2017 7:32 AM: Message
Destination and database are synchronized, not making any changes
```

**Comment by ElRico** [comment]
Just had the issue again overnight. @kenkendk is there any logging that I could turn on to see what request triggers the 400 response?

**Comment by attspa** [comment]
Similar issue.

Front End is Server 2012
Duplicati 2.0.1.53
Backend is Box.com

I've uploaded 1.2 TB of data, trying to get 1.8 TB uploaded. Connected via WebDav, and then I get this error. 

System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at Duplicati.Library.Main.BackendManager.List()
   at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)
   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

**Comment by NamxiCl** [comment]
Same problem here,

Duplicati Version 2.0.1.53_experimental.

Problem does not occur when I run an allready finished backup job again. However, it does occur with backup jobs greater than 100GB. I don't have smaller jobs to test wether its also with smaller jobs.

Is there any solution in sight? I'm in the process of uploading 5+ TB to my Amazon Cloud Drive and at the moment the error occurs after 1 or 2 files. Thats just anoying!

**Comment by NamxiCl** [comment]
Ok, I tried the solution from here now:

https://github.com/duplicati/duplicati/issues/2462

but with that, only 1/3 of the upload is stored in my folder. I uploaded 33GB (Looked it up in the Fritzbox), but only 11GB are found in the folder. The rest of the data is just doubled and trippled uploads because of transfer errors. This can't be the solution!

Edit: I just looked into the logs, some files are retried up to 9 times! (I set the retry count to 25, like in the solution on the linked page)

26. Mai 2017 10:35: Operation Put with file duplicati-*.dblock.zip.aes attempt 9 of 25 failed with message: Der Remoteserver hat einen Fehler zurückgegeben: (400) Ungültige Anforderung.

**Comment by vectors56** [comment]
I had the same problem with 2.0.1.53_experimental, my backups used to stop after 10 minutes to 1 hour with this error message.
Today I updated to 2.0.1.60_canary_2017-05-23 and so far about 120 GB of data have been uploaded without a single error. It looks some recent changes did fix this problem.

**Comment by NamxiCl** [comment]
My problems have magically disappeared one week or so ago.. Every upload I start pulls through over days, nearly no errors whatsoever. Did Amazon change anything? Because I didn't install a newer version of duplicati, so it can't have been duplicatis fault, could it?

**Comment by ttait1** [comment]
Seeing this issue also on Wasabi S3 on a 270GB backup. I created another backup job that was almost the same (different bucket name, and only on folder deep (ie host_backup rather than host/backup) and that succeeded. Failed job gets about 1/3rd of the way done. Restarting it seems to send  1/3rd of dataset and fail again, etc.

Thankfully I am still in the Wasabi free trial stage because I have written teraybytes at this point and they a 90day min storage fee.


`Amazon.S3.AmazonS3Exception: The request body terminated unexpectedly ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RedirectHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes)
   at Duplicati.Library.Main.Operation.BackupHandler.RunMainOperation(ISnapshotService snapshot, BackendManager backend)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass16_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)`

**Comment by warwickmm** [comment]
Closing this since the Amazon Cloud Drive API has been discontinued.

https://forum.duplicati.com/t/amazon-cloud-drive-discontinued/7391
