### ISSUE TITLE
Duplicati cannot access any files

### ISSUE THREAD

**Issue by Pingperfect** [duplicati/duplicati#2345]
I have:
- [x ] searched open and closed issues for duplicates

----------------------------------------

### Version info

Duplicati - 2.0.1.45_experimental_2017-02-03
Windows Server 2012 R2

### Bug description
After installing duplicati 2 in the following way 
Duplicati.WindowsService.exe install --portable-mode --webservice-interface=loopback --log-retention=3M 

Duplicati is unable to backup any files, folders go up but no files of any kind whatsoever. I get the following errors 

`DeletedFiles: 0
DeletedFolders: 1
ModifiedFiles: 7
ExaminedFiles: 11925
OpenedFiles: 7
AddedFiles: 0
SizeOfModifiedFiles: 680089
SizeOfAddedFiles: 0
SizeOfExaminedFiles: 13545304096
SizeOfOpenedFiles: 680428
NotProcessedFiles: 0
AddedFolders: 1
TooLargeFiles: 0
FilesWithError: 0
ModifiedFolders: 0
ModifiedSymlinks: 0
AddedSymlinks: 0
DeletedSymlinks: 0
PartialBackup: False
Dryrun: False
MainOperation: Backup
CompactResults:
    DeletedFileCount: 0
    DownloadedFileCount: 0
    UploadedFileCount: 0
    DeletedFileSize: 0
    DownloadedFileSize: 0
    UploadedFileSize: 0
    Dryrun: False
    MainOperation: Compact
    ParsedResult: Success
    EndTime: 2/03/2017 8:56:00 AM
    BeginTime: 2/03/2017 8:55:59 AM
    Duration: 00:00:01.0360741
    BackendStatistics:
        RemoteCalls: 8
        BytesUploaded: 1017079
        BytesDownloaded: 1016679
        FilesUploaded: 3
        FilesDownloaded: 3
        FilesDeleted: 0
        FoldersCreated: 0
        RetryAttempts: 0
        UnknownFileSize: 0
        UnknownFileCount: 0
        KnownFileCount: 62
        KnownFileSize: 1056873542
        LastBackupDate: 2/03/2017 7:55:27 PM
        BackupListCount: 8
        TotalQuotaSpace: 1099511627776
        FreeQuotaSpace: 342008905262
        AssignedQuotaSpace: -1
        ParsedResult: Success
DeleteResults:
    DeletedSets: []
    Dryrun: False
    MainOperation: Delete
    ParsedResult: Success
    EndTime: 2/03/2017 8:56:00 AM
    BeginTime: 2/03/2017 8:55:59 AM
    Duration: 00:00:01.5380867
RepairResults: null
TestResults:
    MainOperation: Test
    Verifications: [
        Key: duplicati-20170302T085527Z.dlist.zip.aes
        Value: [],
        Key: duplicati-i83cba1265e73446d8a34b85fc16e067e.dindex.zip.aes
        Value: [],
        Key: duplicati-bddc93449abe849feb207587e2886dea8.dblock.zip.aes
        Value: []
    ]
    ParsedResult: Success
    EndTime: 2/03/2017 8:56:12 AM
    BeginTime: 2/03/2017 8:56:07 AM
    Duration: 00:00:05.3776603
ParsedResult: Warning
EndTime: 2/03/2017 8:56:13 AM
BeginTime: 2/03/2017 8:55:27 AM
Duration: 00:00:45.6542367
Messages: [
    No remote filesets were deleted,
    Compacting not required
]
Warnings: [
    Failed to create a snapshot: System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at Alphaleonis.Win32.Vss.VssBackupComponents..ctor()
   at Alphaleonis.Win32.Vss.VssImplementation.CreateVssBackupComponents()
   at Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Dictionary`2 options)
   at Duplicati.Library.Snapshots.SnapshotUtility.CreateWindowsSnapshot(String[] folders, Dictionary`2 options)
   at Duplicati.Library.Snapshots.SnapshotUtility.CreateSnapshot(String[] folders, Dictionary`2 options)
   at Duplicati.Library.Main.Operation.BackupHandler.GetSnapshot(String[] sources, Options options, ILogWriter log) => Attempted to perform an unauthorized operation.,
    Failed to process metadata for "C:\Path\to\folder\StevenW\12425\", storing empty metadata => Attempted to perform an unauthorized operation.,
    Error reported while accessing file: C:\Path\to\folder\StevenW\12425\ => Access to the path 'C:\Path\to\folder\StevenW\12425' is denied.,
    Error reported while accessing file: C:\Path\to\folder\StevenW\12425\ => Access to the path 'C:\Path\to\folder\StevenW\12425' is denied.,
    Failed to process metadata for "C:\Path\to\folder\RyanL\15514\", storing empty metadata => Attempted to perform an unauthorized operation.,
...
]
Errors: [] `

`Error reported while accessing file: C:\Path\to\folder\BarisT\13533\
System.UnauthorizedAccessException: Access to the path 'C:\Path\to\folder\BarisT\13533' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path)
   at Duplicati.Library.Snapshots.NoSnapshotWindows.ListFiles(String folder)
   at Duplicati.Library.Utility.Utility.<EnumerateFileSystemEntries>c__Iterator0.MoveNext()
`

`Failed to process metadata for "C:\Path\to\folder\BarisT\13533\", storing empty metadata
System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at System.Security.AccessControl.Win32.GetSecurityInfo(ResourceType resourceType, String name, SafeHandle handle, AccessControlSections accessControlSections, RawSecurityDescriptor& resultSd)
   at System.Security.AccessControl.NativeObjectSecurity.CreateInternal(ResourceType resourceType, Boolean isContainer, String name, SafeHandle handle, AccessControlSections includeSections, Boolean createByName, ExceptionFromErrorCode exceptionFromErrorCode, Object exceptionContext)
   at System.Security.AccessControl.FileSystemSecurity..ctor(Boolean isContainer, String name, AccessControlSections includeSections, Boolean isDirectory)
   at System.Security.AccessControl.DirectorySecurity..ctor(String name, AccessControlSections includeSections)
   at Duplicati.Library.Snapshots.SystemIOWindows.GetAccessControlDir(String path)
   at Duplicati.Library.Snapshots.SystemIOWindows.GetMetadata(String path, Boolean isSymlink, Boolean followSymlink)
   at Duplicati.Library.Main.Operation.BackupHandler.GenerateMetadata(ISnapshotService snapshot, String path, FileAttributes attributes)
`

The errors occur for all files in all folders, the above is just an example of the 2 errors that show for everyone.

### Steps to reproduce

- Install duplicati as a service 
- Leave it to run when the machine is not logged in
- errors occur

**Actual result:** We get backed up folders but not a single file
**Expected result:** We should get folders and all files

**Comment by Pingperfect** [comment]
any ideas?

**Comment by Pingperfect** [comment]
I believe I have resolved this. Duplicati does not play well with UAC

**Comment by numa00009** [comment]
Hi Ragonz2. How did you solve the UAC issue?

**Comment by ryanbrownell** [comment]
I too am experiencing this whenever I try to backup C:\Users\. All folders belonging to other accounts are simply blocked.

I've experienced this problem with CrashPlan before and the solution there was to set up the Window Service for CrashPlan to run as the SYSTEM user.

I have set up the Windows Service component (https://www.duplicati.com/articles/Way-To-Make-A-Backup/#service-component), specifically selecting the service to run as the SYSTEM user but it appears that this does not start the server as SYSTEM. (I am not using NSSM though it says it should work without it in the instructions.)

**Comment by kees-z** [comment]
The tray icon has a built-in webserver. You should disable this by adding `--no-hosted-server` to the shortcut.
You can read more information about changing from local user to Windows service here:
https://forum.duplicati.com/t/migrating-from-user-to-service-install-on-windows/660

**Comment by ryanbrownell** [comment]
Thanks kees-z! The article you linked to should be in the documentation. Any idea on how we can get this on there?

**Comment by ts678** [comment]
> Thanks kees-z! The article you linked to should be in the documentation. Any idea on how we can get this on there?

[Duplicati User's Manual](https://duplicati.readthedocs.io/en/latest/) says

> Corrections/changes/additions may be submitted as a pull request at Github: https://github.com/kees-z/DuplicatiDocs

which is a high bar for most users. I guess you could try filing an issue there to see if it gets action. At least it's tracked.
[Duplicati Tutorial 02 Install Duplicati as a Service](https://www.youtube.com/watch?v=fZ_ukxbEyG0) is an old but helpful video for initial installs. Doing migration is harder.

There are also issues filed to make it easier to do things like a Windows service setup. I'm not sure about general UAC...
People may think that Administrator account would be enough, but it's not enough until the user elevates, e.g. in UAC.
That's the Windows way. It'd be nice to have a little more access without going all the way to (riskier) Windows service.
Currently I (who has a somewhat odd setup) start manually and answer the UAC prompt every Duplicati start. I set up:

![image](https://github.com/duplicati/duplicati/assets/40771998/b8c231d1-cf96-45c4-a3ad-3565c42c7e13)
