### ISSUE TITLE
Box.com: "Object reference not set to an instance of an object" error

### ISSUE THREAD

**Issue by arafel** [duplicati/duplicati#2349]
I have:
- [x ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.49_experimental_2017-02-23
**Operating System:** Windows 7
**Backend:** Box.com

### Bug description
I've just (yesterday) added a backup targeting box.com. I already have two other backups, one to Google Drive and one to an SFTP server; both those are running fine. The Google Drive backup is backing up the same data (at a different time).

### Steps to reproduce
- run the backup

**Actual result:** The backup shows an error and doesn't show "successful run".
**Expected result:** Backup completes successfully

### debug log
System.NullReferenceException: Object reference not set to an instance of an object.
   at Duplicati.Library.Main.BackendManager.WaitForComplete(LocalDatabase db, IDbTransaction transation)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

[bugreport.zip](https://github.com/duplicati/duplicati/files/814329/bugreport.zip)

**Comment by kenkendk** [comment]
Unfortunately, the origin of the error is lost due to the way I handle the failure.
It just shows that the `BackendManager` sees the error, but it should report where the error really happens.
I will need to fix the error reporting, before I can figure out where this error happens.

**Comment by arafel** [comment]
Ah, okay. Thanks for the update. Any idea when/if you'll get chance to fix the error reporting...?

[Not trying to add pressure, just asking so I know. :)]

**Comment by jpelayo** [comment]
Same problem here. Please, let me know how to provide a debug. [Duplicati 2.0.1.49 with Mono 4.8.0.495 on MacOS 10.12.3 uploading to Box.com].

**Comment by billkrauss3** [comment]
Same issue. 2.0.1.53_experimental_2017-03-13 / Ubuntu 14.04.5 LTS / Mono 4.8.0.520-0xamarin3

**Comment by gillesgagniard** [comment]
Still there in duplicati 2.0.1.61 (macOS 10.12.5, mono 5.0.1.1)

**Comment by gilgolan** [comment]
any updates on that?

**Comment by jmpaz** [comment]
same problem here, 2.0.2.1_beta_2017-08-01

`Fatal error
SharpCompress.Common.InvalidFormatException: Invalid compression method: Rar
  at SharpCompress.Writers.Zip.ZipWriter.ToZipCompressionMethod (SharpCompress.Common.CompressionType compressionType) [0x00046] in <20afbe34b18d4bdda049db0f59cd5db0>:0 
  at SharpCompress.Writers.Zip.ZipWriter.WriteToStream (System.String entryPath, SharpCompress.Writers.Zip.ZipWriterEntryOptions options) [0x00020] in <20afbe34b18d4bdda049db0f59cd5db0>:0 
  at Duplicati.Library.Compression.FileArchiveZip.CreateFile (System.String file, Duplicati.Library.Interface.CompressionHint hint, System.DateTime lastWrite) [0x0008d] in <b049db475a4e429f87e7c9e1c0fbe31d>:0 
  at Duplicati.Library.Main.Volumes.VolumeWriterBase.AddManifestfile () [0x00011] in <118ad25945a24a3991f7b65e7a45ea1e>:0 
  at Duplicati.Library.Main.Volumes.VolumeWriterBase..ctor (Duplicati.Library.Main.Options options, System.DateTime timestamp) [0x000a8] in <118ad25945a24a3991f7b65e7a45ea1e>:0 
  at Duplicati.Library.Main.Volumes.FilesetVolumeWriter..ctor (Duplicati.Library.Main.Options options, System.DateTime timestamp) [0x00000] in <118ad25945a24a3991f7b65e7a45ea1e>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.Run (System.String[] sources, Duplicati.Library.Utility.IFilter filter) [0x002ad] in <118ad25945a24a3991f7b65e7a45ea1e>:0 `

I had originally selected to use rar but changed it to zip after getting an error

**Comment by kenkendk** [comment]
@gilgolan No updates yet, we are implementing a new backend manager, and I will make sure the improved error reporting goes into that.

@jmpaz That is another error entirely. I think you have set something like `--zip-compression-method=rar` in the advanced options that you need to remove.

**Comment by CottonEaster** [comment]
So, backup to Box is just . . broken? On the beta as well as the stable version?

(By the way: like at least one of the previous posters, the OS on which I encouter this problem is Linux.)

**Comment by hwharrison** [comment]
Still encountering the same error. 2.0.2.1 on Windows.

**Comment by weslowsk** [comment]
I also get this error on 2.0.2.1_beta_2017-08-01 on Linux and only with Box.
After every error, I try to start the backup again and it fails anywhere from a few minutes later to an hour or 2 later. I have about 40GB of video files that I'm trying to backup and this error is preventing me from using Box as a backend for that data.

**Comment by taferris** [comment]
Any update on this bug?

I am seeing it on 2.0.2.1 on Mac as well as 2.0.2.15_experimental_2018-01-03 on Mac.  It seems to occur during a "ExecuteScalarInt65" command.

Having worked with Box API a little bit, my suspicion was an unexpected response from the API, but in looking through BoxBackend.cs, it appears those should be caught.

Still getting my head around how things work, but noticed that when an exception is caught during a put, the m_filecache is set to null.  Is this what is causing the Null Reference Exception?

Any thoughts on ways to get to more details of the cause of the error?  I would be happy to run a version with debug statements in it.

Here is the details from my log on 2.0.2.15:
```
Jan 11, 2018 11:06 AM: Running Backup took 01:03:28.423
Jan 11, 2018 11:06 AM: Failed disposing index volume

{"ClassName":"System.InvalidOperationException","Message":"Attempted to dispose an index volume that was being written","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"  at Duplicati.Library.Main.Volumes.IndexVolumeWriter.Dispose () [0x00010] in <ab07a85a74244406aaefc2202f7e530f>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.Dispose () [0x00039] in <ab07a85a74244406aaefc2202f7e530f>:0 ","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233079,"Source":"Duplicati.Library.Main"}

Jan 11, 2018 11:06 AM: Fatal error

{"ClassName":"System.NullReferenceException","Message":"Object reference not set to an instance of an object","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"  at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry (Duplicati.Library.Snapshots.ISnapshotService snapshot, Duplicati.Library.Main.BackendManager backend, System.String path, System.IO.FileAttributes attributes) [0x0000e] in <ab07a85a74244406aaefc2202f7e530f>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.RunMainOperation (Duplicati.Library.Snapshots.ISnapshotService snapshot, Duplicati.Library.Main.BackendManager backend) [0x0018a] in <ab07a85a74244406aaefc2202f7e530f>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.Run (System.String[] sources, Duplicati.Library.Utility.IFilter filter) [0x008a5] in <ab07a85a74244406aaefc2202f7e530f>:0 
  at Duplicati.Library.Main.Controller+<>c__DisplayClass17_0.<Backup>b__0 (Duplicati.Library.Main.BackupResults result) [0x00036] in <ab07a85a74244406aaefc2202f7e530f>:0 
  at Duplicati.Library.Main.Controller.RunAction[T] (T result, System.String[]& paths, Duplicati.Library.Utility.IFilter& filter, System.Action`1[T] method) [0x0014b] in <ab07a85a74244406aaefc2202f7e530f>:0 
  at Duplicati.Library.Main.Controller.Backup (System.String[] inputsources, Duplicati.Library.Utility.IFilter filter) [0x00068] in <ab07a85a74244406aaefc2202f7e530f>:0 
  at Duplicati.Server.Runner.Run (Duplicati.Server.Runner+IRunnerData data, System.Boolean fromQueue) [0x00458] in <4ae48e3a966d42fc9f076d711f6c033b>:0 ","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2147467261,"Source":"Duplicati.Library.Main"}

Jan 11, 2018 11:06 AM: ExecuteScalarInt64: INSERT INTO "Remotevolume" ("OperationID", "Name", "Type", "State", "Size", "VerificationCount", "DeleteGraceTime") VALUES (?, ?, ?, ?, ?, ?, ?); SELECT last_insert_rowid(); took 00:00:00.000
Jan 11, 2018 11:06 AM: Starting - ExecuteScalarInt64: INSERT INTO "Remotevolume" ("OperationID", "Name", "Type", "State", "Size", "VerificationCount", "DeleteGraceTime") VALUES (?, ?, ?, ?, ?, ?, ?); SELECT last_insert_rowid();
Jan 11, 2018 11:06 AM: ExecuteScalar: SELECT "Type" FROM "Remotevolume" WHERE "Name" = ? took 00:00:00.000
Jan 11, 2018 11:06 AM: Starting - ExecuteScalar: SELECT "Type" FROM "Remotevolume" WHERE "Name" = ?

```

**Comment by weslowsk** [comment]
I switched to using 2.0.2.19_canary_2018-02-12 because that release is even more recent than the release that has the fix in it:
https://github.com/duplicati/duplicati/releases/tag/v2.0.2.18-2.0.2.18_canary_2018-02-11
"Fixed a bug in the box.com backend that prevented backups"

However, I'm still seeing the same behaviour/error when backing up to Box. So far, I've tried the backup 2 nights in a row and, both times, after 1-2 hours of the backup running, I get the red popup error at the bottom of the Duplicati UI:

"Object reference not set to an instance of an object"

Do I have a different issue or is the issue still lingering in the latest Canary release?

**Comment by arafel** [comment]
I noticed in the git commit it just says “may fix” rather than “will fix”. :-/
  

  
  

  
  
>

**Comment by weslowsk** [comment]
@arafel can you confirm the issue still exists for you? Are you able to re-open this issue if you're still experiencing the issue?

**Comment by arafel** [comment]
Hi - not today but I can check on Monday. If it’s still there I’ll let you know. Thanks!
  

  
  

  
  
>

**Comment by arafel** [comment]
@weslowsk 
Hi

I've checked, and I don't seem to get any "object reference" messages. However - I re-tested before upgrading (to check I could reproduce before confirming it was gone), and I didn't see it then either. So it looks good but I can't 100% confirm it's gone. Sorry. :/

Cheers
Paul

**Comment by archon810** [comment]
Same issue with 2.0.3.3_beta_2018-04-02, which is the latest rpm release.

**Comment by Pectojin** [comment]
@archon810, That's the latest beta release, although a new one is upcoming.

**Comment by archon810** [comment]
I ended up giving up on this project after multiple backup errors. Upgraded to the latest experimental from Github, but there are still too many issues.

Trying out rclone and restic next.
