### ISSUE TITLE
previous volume not finished

### ISSUE THREAD

**Issue by saviodsouza** [duplicati/duplicati#2358]
I have:
- [ ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.0.51
**Operating System:**Windows server 2008 r2
**Backend:**FTP

### Bug description
Describe here the issue that you are experiencing

Failed: Previous volume not finished, call FinishVolume before starting a new volume
Details: System.InvalidOperationException: Previous volume not finished, call FinishVolume before starting a new volume
   at Duplicati.Library.Main.Volumes.IndexVolumeWriter.StartVolume(String filename)
   at Duplicati.Library.Main.Operation.BackupHandler.UpdateIndexVolume()
   at Duplicati.Library.Main.Operation.BackupHandler.FinalizeRemoteVolumes(BackendManager backend)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

Configure a new backup with FTP back end

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Backup should run normal

**Comment by saviodsouza** [comment]
First Incremental Backup

Messages: [
    keeping protected incomplete remote file listed as Temporary: duplicati-20170306T042214Z.dlist.zip.aes,
    removing remote file listed as Deleting: duplicati-b61e82ff653a04094902d6bfa1fa595f5.dblock.zip.aes,
    scheduling missing file for deletion, currently listed as Uploading: duplicati-b5a725bca059b4c4a8dee0322817885b9.dblock.zip.aes,
    scheduling missing file for deletion, currently listed as Uploading: duplicati-ibddb541d5afa4e2a83648a3fec9d73dd.dindex.zip.aes,
    Uploading filelist from previous interrupted backup,
    removing file listed as Temporary: duplicati-20170306T042214Z.dlist.zip.aes,
    No remote filesets were deleted

Now is the backup complete or possibly some corruption exist?

**Comment by kenkendk** [comment]
There should be no corruption from this.
You can run the "Verify" command to check.

I think it hits a corner case where the volume is created and filled, and then immediately closes.

**Comment by ETNY-Y** [comment]
I run "Verify" nothing better : 
System.InvalidOperationException: Previous volume not finished, call FinishVolume before starting a new volume
  at Duplicati.Library.Main.Volumes.IndexVolumeWriter.StartVolume (System.String filename) [0x00000] in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.UpdateIndexVolume () [0x00000] in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.FinalizeRemoteVolumes (Duplicati.Library.Main.BackendManager backend) [0x00000] in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.Run (System.String[] sources, IFilter filter) [0x00000] in <filename unknown>:0

**Comment by ETNY-Y** [comment]
15 mars 2017 14:01: Failed disposing index volume
{"ClassName":"System.InvalidOperationException","Message":"Attempted to dispose an index volume that was being written","InnerException":null,"HelpURL":null,"StackTraceString":"  at Duplicati.Library.Main.Volumes.IndexVolumeWriter.Dispose () [0x00000] in <filename unknown>:0 \n  at Duplicati.Library.Main.Operation.BackupHandler.Dispose () [0x00000] in <filename unknown>:0 ","RemoteStackTraceString":null,"RemoteStackIndex":0,"HResult":-2146233079,"Source":"Duplicati.Library.Main","ExceptionMethod":null,"Data":null}
15 mars 2017 14:01: Fatal error
{"ClassName":"System.InvalidOperationException","Message":"Previous volume not finished, call FinishVolume before starting a new volume","InnerException":null,"HelpURL":null,"StackTraceString":"  at Duplicati.Library.Main.Volumes.IndexVolumeWriter.StartVolume (System.String filename) [0x00000] in <filename unknown>:0 \n  at Duplicati.Library.Main.Operation.BackupHandler.UpdateIndexVolume () [0x00000] in <filename unknown>:0 \n  at Duplicati.Library.Main.Operation.BackupHandler.FinalizeRemoteVolumes (Duplicati.Library.Main.BackendManager backend) [0x00000] in <filename unknown>:0 \n  at Duplicati.Library.Main.Operation.BackupHandler.Run (System.String[] sources, IFilter filter) [0x00000] in <filename unknown>:0 ","RemoteStackTraceString":null,"RemoteStackIndex":0,"HResult":-2146233079,"Source":"Duplicati.Library.Main","ExceptionMethod":null,"Data":null}
15 mars 2017 14:01: Operation Put with file duplicati-bde7e5021e6b944739bda880c24c7743d.dblock.zip.aes attempt 4 of 5 failed with message: The object was used after being disposed.
{"ClassName":"System.ObjectDisposedException","Message":"The object was used after being disposed.","InnerException":null,"HelpURL":null,"StackTraceString":"  at System.Net.WebConnection.BeginWrite (System.Net.HttpWebRequest request, System.Byte[] buffer, Int32 offset, Int32 size, System.AsyncCallback cb, System.Object state) [0x00000] in <filename unknown>:0 \n  at System.Net.WebConnectionStream.WriteRequestAsync (System.AsyncCallback cb, System.Object state) [0x00000] in <filename unknown>:0 \n  at System.Net.WebConnectionStream.BeginWrite (System.Byte[] buffer, Int32 offset, Int32 size, System.AsyncCallback cb, System.Object state) [0x00000] in <filename unknown>:0 ","RemoteStackTraceString":null,"RemoteStackIndex":0,"HResult":-2146233079,"Source":"System","ExceptionMethod":null,"Data":null,"ObjectName":"System.Net.Sockets.NetworkStream"}
15 mars 2017 14:01: Operation Put with file duplicati-bad369620bb054db2ada852518967a8ec.dblock.zip.aes attempt 3 of 5 failed with message: The object was used after being disposed.
{"ClassName":"System.ObjectDisposedException","Message":"The object was used after being disposed.","InnerException":null,"HelpURL":null,"StackTraceString":"  at System.Net.WebConnection.BeginWrite (System.Net.HttpWebRequest request, System.Byte[] buffer, Int32 offset, Int32 size, System.AsyncCallback cb, System.Object state) [0x00000] in <filename unknown>:0 \n  at System.Net.WebConnectionStream.WriteRequestAsync (System.AsyncCallback cb, System.Object state) [0x00000] in <filename unknown>:0 \n  at System.Net.WebConnectionStream.BeginWrite (System.Byte[] buffer, Int32 offset, Int32 size, System.AsyncCallback cb, System.Object state) [0x00000] in <filename unknown>:0 ","RemoteStackTraceString":null,"RemoteStackIndex":0,"HResult":-2146233079,"Source":"System","ExceptionMethod":null,"Data":null,"ObjectName":"System.Net.Sockets.NetworkStream"

**Comment by wintersolutions** [comment]
Having the same issue, seems not to be a corner case.

**Comment by mneiger** [comment]
I believe I'm meeting that same case with 2.0.2.1 beta uploading on Hubic a large 400Gb set.

**Comment by DavidJameson** [comment]
Just happened to me with latest beta, while testing Duplicati as a replacement for Crashplan

![screenshot_2546](https://user-images.githubusercontent.com/5974355/30113090-8709a81e-92e1-11e7-97f5-81cb9bd004a2.png)

**Comment by TheCycoONE** [comment]
I seem to have hit this too; very early in the first backup I've run with this software (except for a couple early failures where I didn't have a unique bucket name for B2).

Version: 2.0.3.2
System: Arch Linux x86_64 

Error:
```
1 Apr 2018 20:08: Failed while executing "Backup" with id: 1
System.InvalidOperationException: Previous volume not finished, call FinishVolume before starting a new volume
  at Duplicati.Library.Main.Volumes.IndexVolumeWriter.StartVolume (System.String filename) [0x00010] in <cad7b2bda0054aeb8800ccf4b5d3bb31>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.UpdateIndexVolume () [0x00043] in <cad7b2bda0054aeb8800ccf4b5d3bb31>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.FinalizeRemoteVolumes (Duplicati.Library.Main.BackendManager backend) [0x0018e] in <cad7b2bda0054aeb8800ccf4b5d3bb31>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.Run (System.String[] sources, Duplicati.Library.Utility.IFilter filter) [0x00965] in <cad7b2bda0054aeb8800ccf4b5d3bb31>:0 
  at Duplicati.Library.Main.Controller+<>c__DisplayClass17_0.<Backup>b__0 (Duplicati.Library.Main.BackupResults result) [0x00035] in <cad7b2bda0054aeb8800ccf4b5d3bb31>:0 
  at Duplicati.Library.Main.Controller.RunAction[T] (T result, System.String[]& paths, Duplicati.Library.Utility.IFilter& filter, System.Action`1[T] method) [0x001e3] in <cad7b2bda0054aeb8800ccf4b5d3bb31>:0 
  at Duplicati.Library.Main.Controller.Backup (System.String[] inputsources, Duplicati.Library.Utility.IFilter filter) [0x00068] in <cad7b2bda0054aeb8800ccf4b5d3bb31>:0 
  at Duplicati.Server.Runner.Run (Duplicati.Server.Runner+IRunnerData data, System.Boolean fromQueue) [0x00511] in <ffc12c0247864a30950a40182d2107b6>:0 
```

**Comment by TheCycoONE** [comment]
I got the same error the second time I tried to run the backup too:
```
1 Apr 2018 22:31: Failed while executing "Backup" with id: 1
System.InvalidOperationException: Previous volume not finished, call FinishVolume before starting a new volume
  at Duplicati.Library.Main.Volumes.IndexVolumeWriter.StartVolume (System.String filename) [0x00010] in <cad7b2bda0054aeb8800ccf4b5d3bb31>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.UpdateIndexVolume () [0x00043] in <cad7b2bda0054aeb8800ccf4b5d3bb31>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.FinalizeRemoteVolumes (Duplicati.Library.Main.BackendManager backend) [0x0018e] in <cad7b2bda0054aeb8800ccf4b5d3bb31>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.Run (System.String[] sources, Duplicati.Library.Utility.IFilter filter) [0x00965] in <cad7b2bda0054aeb8800ccf4b5d3bb31>:0 
  at Duplicati.Library.Main.Controller+<>c__DisplayClass17_0.<Backup>b__0 (Duplicati.Library.Main.BackupResults result) [0x00035] in <cad7b2bda0054aeb8800ccf4b5d3bb31>:0 
  at Duplicati.Library.Main.Controller.RunAction[T] (T result, System.String[]& paths, Duplicati.Library.Utility.IFilter& filter, System.Action`1[T] method) [0x001e3] in <cad7b2bda0054aeb8800ccf4b5d3bb31>:0 
  at Duplicati.Library.Main.Controller.Backup (System.String[] inputsources, Duplicati.Library.Utility.IFilter filter) [0x00068] in <cad7b2bda0054aeb8800ccf4b5d3bb31>:0 
  at Duplicati.Server.Runner.Run (Duplicati.Server.Runner+IRunnerData data, System.Boolean fromQueue) [0x00511] in <ffc12c0247864a30950a40182d2107b6>:0 
```

 Remote log:
```
1 Apr 2018 22:00: put duplicati-bab1efe8b183441528bf242afdace33ce.dblock.zip.aes
1 Apr 2018 21:55: put duplicati-20180401T233302Z.dlist.zip.aes
1 Apr 2018 21:55: list
1 Apr 2018 19:37: put duplicati-bd039c1aced9e47e28977699c7797ac71.dblock.zip.aes
1 Apr 2018 19:33: list
```
In both cases it was before putting the second dblock.

**Comment by ts678** [comment]
These reports (and others in forum and issues) were largely in 2017, with above 2018 one on 2.0.3.2 which predates [2.0.3.6_canary_2018-04-23](https://github.com/duplicati/duplicati/releases/tag/v2.0.3.6-2.0.3.6_canary_2018-04-23) which was a massive design change, so possibly fixed whatever issue was going on here.

Did anyone update to a release where problem went away? Is anybody seeing the problem with the current releases?
