### ISSUE TITLE
System.Data.SQLite.SQLiteException (0x80004005): database or disk is full database or disk is full

### ISSUE THREAD

**Issue by damian123** [duplicati/duplicati#2382]
I am getting these errors. Where does Duplicati stored its temp files?

Fatal error
System.Data.SQLite.SQLiteException (0x80004005): database or disk is full
database or disk is full
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at Duplicati.Library.Main.Database.ExtensionMethods.ExecuteNonQuery(IDbCommand self, String cmd, Object[] values)
   at Duplicati.Library.Main.Database.LocalDatabase.Vacuum()
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)

**Comment by Aurabolt** [comment]
Check Home > Advanced > Manage database...
By default, looks like it's here on Windows 10: C:\Users\USERNAME\AppData\Roaming\Duplicati\

**Comment by kenkendk** [comment]
On Linux, the `TMPDIR` controls the temp folder.
On Windows, the `TEMPDIR` environment variable controls it.

Does this answer the question?

**Comment by damian123** [comment]
Yes!!

**Comment by crazy4chrissi** [comment]
I have the same issue. The drive has 20 GB free, the sqlite db is 68gb, so vacuum does not work as it needs ~68gb of temp space. As discussed with @kenkendk on Gitter, maybe the vacuum is not necessary at all? I guess it should only be triggered manually. Also, VACUUM on such a big database will take some cpu and IO time which is mostly wasted as only a few megs are usually safed by the VACUUM.
