### ISSUE TITLE
Failed to connect to S3: InvalidArgument and Http Status Code BadRequest

### ISSUE THREAD

**Issue by mishaklomp** [duplicati/duplicati#2398]
I have:
- [X] searched open and closed issues for duplicates
- [X] tested on two servers
- [X] Forced using s3-ext-signatureversion 2: My S3 compatible service only supports version 2 signatures.
----------------------------------------

### Version info
Duplicati Version: 2.0.1.53_experimental_2017-03-13
Operating System: Windows NT 6.2.9200.0
Backend: S3 Compatible

### Bug description
Everything was working fine til the update form version 2.0.1.49_experimental_2017-02-23 to 2.0.1.53_experimental_2017-03-13. Now I can not connect to the my S3 service.
(got a server running version 2.0.1.49 witch is working just fine).

### Steps to reproduce
- Add backup
- No encryption
- Select S3 Compatible service
- Test connection: "Failed to connect: Error making request with Error Code InvalidArgument and Http Status Code BadRequest. No further error information was returned by the service."

### Screenshots
![img](https://cloud.githubusercontent.com/assets/4741823/24194248/9f180b50-0ef5-11e7-96aa-4aa77002211f.JPG)

### debug log
Amazon.S3.AmazonS3Exception: Error making request with Error Code InvalidArgument and Http Status Code BadRequest. No further error information was returned by the service. ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RedirectHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.BackendManager.List()
   at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)
   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

**Comment by kenkendk** [comment]
This is probably caused by the updated S3 libraries:
https://github.com/duplicati/duplicati/releases/tag/v2.0.1.50-2.0.1.50_canary_2017-02-28

**Comment by sinshaamagi** [comment]
I am getting below error while test connection on s3
Duplicati Version : 2.0.2.1-1
OS : Ubuntu 16.04
How can I resolve this?

Failed to connect: Invalid type System.Net.HttpWebRequest for instance field Amazon.Runtime.Internal.HttpRequest:_request

**Comment by rinatio** [comment]
Having same issue on OSX with same version. Any advice on how to find latest `.dmg` release for Mac?

**Comment by ts678** [comment]
> This is probably caused by the updated S3 libraries

S3 libraries have been updated numerous times, and new reports here seem to have stopped coming. Is this still an issue?

If there's no more news, issue will automatically close.
