### ISSUE TITLE
Duplicati.GUI.TrayIcon has stopped working

### ISSUE THREAD

**Issue by harald14** [duplicati/duplicati#2430]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.53_experimental_2017_03_13
**Operating System:** Windows 10 64 bit
**Backend:** Networkdrive

### Bug description
After boot the system or starting the TrayIcon, windows is showing within 15-30 seconds the message the the TrayIcon has stopped. In case I'm fast enough I can open the GUI shortly before it does crash.
This is happening from one day to the other and since that all the time. 

### Steps to reproduce
Just start Duplicati GUI.TrayIcon from the startmenu

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots

![image](https://cloud.githubusercontent.com/assets/26137104/25004721/04ec652c-2056-11e7-9382-b8f28a7cd0c6.png)

From Event log:
![image](https://cloud.githubusercontent.com/assets/26137104/25004931/05bdc562-2057-11e7-932a-04a06f1bfc94.png)

From Event log:
![image](https://cloud.githubusercontent.com/assets/26137104/25005029/70bd6fca-2057-11e7-8ceb-c4254b93de84.png)

**Comment by harald14** [comment]
**Tried the following:**

```
C:\Program Files\Duplicati 2>Duplicati.Server.exe
Server gestartet und hört auf 127.0.0.1, Port 8200


Unhandled Exception: Unhandled Exception: System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
   at System.Threading.Tasks.TaskCompletionSource`1.SetResult(TResult result)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
   at System.Threading.Tasks.TaskCompletionSource`1.SetResult(TResult result)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Unhandled Exception: System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
   at System.Threading.Tasks.TaskCompletionSource`1.SetResult(TResult result)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Unhandled Exception: System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
   at System.Threading.Tasks.TaskCompletionSource`1.SetResult(TResult result)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

C:\Program Files\Duplicati 2>

```
**Found in Eventlog related to the above:**

```
Application: Duplicati.Server.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Threading.Tasks.TaskCompletionSource`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(Boolean)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by kenkendk** [comment]
I am guessing this is related to the usage reporter somehow.

Can you try to run:
```
> set USAGEREPORTER_Duplicati_LEVEL=none
> Duplicati.Server.exe
```

**Comment by harald14** [comment]
Hi, thank you very much. Using this approach did help fix the problem, but obviously the server process stops after CTRL-C or closing the command line box.

How can I make this setting permanent, so that it becomes effective while starting the service at boot time?

**Comment by kenkendk** [comment]
@harald14 You can set it as an environment variable:
https://www.computerhope.com/issues/ch000549.htm

Add a new "System variable" called `USAGEREPORTER_Duplicati_LEVEL` and set the value to `none`.

**Comment by harald14** [comment]
Thank you very much, Solutions could be so simple :-) 

This does perfectly work.

**Comment by steph643** [comment]
Got the same issue. The workaround works. Any news about a fix?

**Comment by steph643** [comment]
Issue seems to relate to https://github.com/duplicati/duplicati/issues/2632.

**Comment by kenkendk** [comment]
Also related to #3020
