### ISSUE TITLE
GetRequestStream timed out

### ISSUE THREAD

**Issue by mmiat** [duplicati/duplicati#2462]
after previous issues (#2449, #2453 )
I deleted all, re-launch backup, it works
I added some new files, and this is the new error:

> Failed: GetRequestStream timed out
Details: System.Net.WebException: GetRequestStream timed out ---> System.Net.WebException: The request was aborted: The request was canceled.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult)
   at Duplicati.Library.Utility.AsyncHttpRequest.AsyncWrapper.OnAsync(IAsyncResult r)
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes)
   at Duplicati.Library.Main.Operation.BackupHandler.RunMainOperation(ISnapshotService snapshot, BackendManager backend)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)

maybe it's related with #2289 and #2129 ?
it's unbelievable, I can't do this backup, I'm trying since a month !

**Comment by mmiat** [comment]
after setting 

`--number-of-retries=25
--retry-delay=30s`

it seems ok
stay tuned
