### ISSUE TITLE
VSS problems after last update.

### ISSUE THREAD

**Issue by Athep** [duplicati/duplicati#2480]
2.0.1.57_canary_2017-05-17

```
Fatal error
System.IO.FileNotFoundException: Could not load file or assembly 'AlphaVSS.x64.dll' or one of its dependencies. The specified module could not be found.

File name: 'AlphaVSS.x64.dll'
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Dictionary`2 options)
   at Duplicati.Library.Snapshots.SnapshotUtility.CreateWindowsSnapshot(String[] folders, Dictionary`2 options)
   at Duplicati.Library.Main.Operation.BackupHandler.GetSnapshot(String[] sources, Options options, ILogWriter log)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
```

**Comment by jonyrh** [comment]
Me to:

Fatal Error, used snapshot-policy=Required, VC++ 2010 x64 & NetFramework3.5 installed, shadow copy is on and work. System: Win10 x64 1703, Duplicati v2.0.1.57_canary_2017-05-17 x64

I'm try run as admin or user. Always fatal error....

Please help me!

LOG:
System.IO.FileNotFoundException","Message":"Could not load file or assembly 'AlphaVSS.x64.dll' or one of its dependencies. The specified module could not be found.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)\r\n   at System.Reflection.Assembly.LoadFile(String path)\r\n   at Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Dictionary`2 options)\r\n   at Duplicati.Library.Snapshots.SnapshotUtility.CreateWindowsSnapshot(String[] folders, Dictionary`2 options)\r\n   at Duplicati.Library.Main.Operation.BackupHandler.GetSnapshot(String[] sources, Options options, ILogWriter log)\r\n   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)\r\n   at Duplicati.Library.Main.Controller.<>c__DisplayClass16_0.<Backup>b__0(BackupResults result)\r\n   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)\r\n   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)\r\n   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nnLoadFile\nmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Reflection.RuntimeAssembly\nSystem.Reflection.RuntimeAssembly nLoadFile(System.String, System.Security.Policy.Evidence)","HResult":-2147024770,"Source":"mscorlib","WatsonBuckets":null,"FileNotFound_FileName":"AlphaVSS.x64.dll","FileNotFound_FusionLog":""}

**Comment by jonyrh** [comment]
Probleme is gone after install Visual C++ Redistributable Packages for Visual Studio x86 and  x64!!!

**Comment by kenkendk** [comment]
@jonyrh Can you give a link to the redist package you used?

**Comment by kenkendk** [comment]
I updated AlphaVSS, so maybe it was built with a newer version of the C++ redist package.

**Comment by jonyrh** [comment]
https://www.microsoft.com/en-us/download/details.aspx%3Fid%3D48145

**Comment by kenkendk** [comment]
Thanks, I have added it to the FAQ:
https://github.com/duplicati/duplicati/wiki/FAQ#user-content-windows-vss

**Comment by dimejo** [comment]
Unfortunately the link doesn't work for me. Getting an 404 Error.

**Comment by Mapel** [comment]
The link in the FAQ works:

https://www.microsoft.com/en-us/download/details.aspx?id=52685

**Comment by kenkendk** [comment]
Yes, I updated the link yesterday, MS has an annoying habit of using non-descriptive URLs and moving stuff around all the time :/.

**Comment by dimejo** [comment]
Thanks, this link is working for me.

**Comment by Germs2004** [comment]
I had this error too on the latest version.  May I suggest adding the required files to the Windows installer so it installs automatically with Duplicati?  Or at least add a sentence to the "snapshot-policy" help text and the log's error message that tells the user about the prerequisite.  Having to search forums for the solution is much more difficult that just having the information right in the error.  Thanks!

**Comment by ts678** [comment]
> May I suggest adding the required files to the Windows installer so it installs automatically with Duplicati?

[Universal CRT deployment](https://learn.microsoft.com/en-us/cpp/windows/universal-crt-deployment) possibly avoids this need, per claim that it's preinstalled with Windows 10 or later.
Now that earlier versions of Windows are out of support, we can see if issue slows. I'm not a Visual C++ dev.
[Upgrade your code to the Universal CRT](https://learn.microsoft.com/en-us/cpp/porting/upgrade-your-code-to-the-universal-crt) and other information may help, if we can find the people to review.
