### ISSUE TITLE
Fatal Error: sending to FTP auth login/password, but button 'check connection' say is all fine!

### ISSUE THREAD

**Issue by jonyrh** [duplicati/duplicati#2484]
Fatal Error: sending to FTP auth login/password, but button 'check connection' say is all fine!

System:
VC++ 2010 x64 and x86, VC++ 2015 x64 and x86, Win10 x64 1703, Duplicati v2.0.1.57_canary_2017-05-17 x64 (as Administrator)

Error message:
Unable to cast object of type 'System.Net.FtpWebRequest' to type 'System.Net.HttpWebRequest'.

LOG:
System.InvalidCastException: Unable to cast object of type 'System.Net.FtpWebRequest' to type 'System.Net.HttpWebRequest'.
   at Duplicati.Library.Main.BackendManager.WaitForComplete(LocalDatabase db, IDbTransaction transation)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass16_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

![2017-05-18 22 52 35](https://cloud.githubusercontent.com/assets/28771126/26216744/a48c226e-3c1e-11e7-9a03-06537e8c9033.png)

**Comment by kenkendk** [comment]
Yes, same problem as #2483
