### ISSUE TITLE
Failed: Size mismatch problem for block

### ISSUE THREAD

**Issue by matjazpotocnik** [duplicati/duplicati#2486]
Suddenly I get this error for one of my backup jobs:

Failed: Size mismatch problem for block X7KP0FDPYFm4aIRpXLHGgTP00Sb1NxTxlZE9EDyxkkM=, 102395 vs 102400
Details: System.Exception: Size mismatch problem for block X7KP0FDPYFm4aIRpXLHGgTP00Sb1NxTxlZE9EDyxkkM=, 102395 vs 102400
   at Duplicati.Library.Main.Operation.CompactHandler.DoCompact(LocalDeleteDatabase db, Boolean hasVerifiedBackend, IDbTransaction& transaction)
   at Duplicati.Library.Main.Operation.DeleteHandler.DoRun(LocalDeleteDatabase db, IDbTransaction& transaction, Boolean hasVerifiedBacked, Boolean forceCompact)
   at Duplicati.Library.Main.Operation.BackupHandler.CompactIfRequired(BackendManager backend, Int64 lastVolumeSize)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)

Other backups are ok.

Duplicati: 2.0.1.55

**Comment by kenkendk** [comment]
It is possible that this is a genuine hash collision, where you have two blocks with the same hash value, but different lengths. But it is more likely that it is a bug in Duplicati :).

Can you make a bugreport for this backup, so I can examine the database and maybe figure out what is causing the problem?

**Comment by matjazpotocnik** [comment]
https://www.dropbox.com/s/fz4p2suw2kke7mz/bugreport.zip

**Comment by kenkendk** [comment]
Thanks! I have it downloaded now.

**Comment by matejart** [comment]
If it makes any difference, I am on 2.0.1.64_canary_2017-06-02 and am getting the same error (with a different block and expected size number). I am using an sftp/ssh destination for backup, and it is possible that during some of the backup runs I put the computer to sleep.

**Comment by tve** [comment]
Same issue here, 2.0.2.4_canary_2017-09-09.
Is there a work-around?

**Comment by ts678** [comment]
This bug never had good steps to reproduce, although that's not unusual for intermittent bugs such as this one tends to be. Sometimes it's a Destination problem that Duplicati can detect but can't prevent. If nobody has more to say, I propose close.
Even attempting to study a destination problem manually needs help from the user of the system that can sometimes see it.
This one somehow stopped getting reports in 2017, and it's possible that some other unidentifiable fix has somehow helped.
