### ISSUE TITLE
Make SFTP backend resilient to no space problems with CoW file systems

### ISSUE THREAD

**Issue by suuchan** [duplicati/duplicati#2499]
**Duplicati Version:** 2.0.1.53
**Operating System:** Any
**Backend:** SFTP

### Bug description
The SFTP backend issues a simple delete command to the remote server to delete a file. If the remote storage is completely full and a CoW file system such as ZFS or Btrfs is used, the delete will always fail because of the way CoW file systems work. When doing a rollback or repair, this becomes a problem.

I got the following when I tried to do another backup on a full ZFS backend throgh SFTP:

> Failed: Failure
> Details: Renci.SshNet.Common.SshException: Failure
>    at Duplicati.Library.Main.BackendManager.Delete(String remotename, Int64 size, Boolean synchronous)
>    at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)
>    at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)
>    at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend, String protectedfile)
>    at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
>    at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
>    at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method) 

This is ultimately an issue of the SFTP client, however this is not easy to fix, especially when using SFTP storage from a service provider that are conservative with updates.

### Steps to reproduce
- Set up a server with a small ZFS volume and enable SSH/SFTP
- try to back up more thata that would fit.

**Actual result:** The backup hangs. Aborting the thread works but after that the remote backup is in a state where rolling back the transaction is not possible.

**Expected result:** The failed backup should be rolled back and a new one started.

### Fix
An easy way to fix would be to check if the delete fails in **SSHv2Backend.cs**, method **Delete()**. If it fails, doing a put for a zero byte file to the same path will cause a truncate of the file, effectively freeing disk space. Then a second delete will succeed.
 
The fix should be easy and because Duplicati has ownership of the files, additional concerns like hard link count can be neglected.

**Comment by kenkendk** [comment]
I think this could be used for all backends, with an option like `--truncate-before-delete`. If the delete fails, the `BackendManager` can then try to put with an empty file, and delete again.

This is a bit complicated because Duplicati does not generally update files, but we can possibly support it by ignoring zero-length files to some extent.
