### ISSUE TITLE
Duplicati.CommandLine.exe with --snapshot-policy gives Could not load file or assembly AlphaVSS.x64

### ISSUE THREAD

**Issue by pjannesen** [duplicati/duplicati#2519]
I have:
- [x] searched open and closed issues for duplicates

### Version info
**Duplicati Version: 2.0.1.61
**Operating System: Windows 10 (64 bits)
**Backend: file

### Bug description
Error while starting Duplicati CommandLine with VSS snapshot.

I think it is a build error.
Some executables are  'Architecture: AnyCPU (32-bit preferred) ' other are 'Architecture: AnyCPU (64-bit preferred)'

Duplicati.CommandLine.exe is AnyCPU (32-bit preferred) and it tries to load a x64 assembly. 

### Steps to reproduce
"C:\Program Files\Duplicati 2\Duplicati.CommandLine.exe" backup --snapshot-policy=required 

### debug log
Fatal error => Could not load file or assembly 'AlphaVSS.x64, Version=1.4.0.0, Culture=neutral, PublicKeyToken=959d3993561034e3'. This assembly was compiled for a different processor.

System.BadImageFormatException: Could not load file or assembly 'AlphaVSS.x64, Version=1.4.0.0, Culture=neutral, PublicKeyToken=959d3993561034e3'. This assembly was compiled for a different processor.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Dictionary`2 options)
   at Duplicati.Library.Snapshots.SnapshotUtility.CreateWindowsSnapshot(String[] folders, Dictionary`2 options)
   at Duplicati.Library.Snapshots.SnapshotUtility.CreateSnapshot(String[] folders, Dictionary`2 options)
   at Duplicati.Library.Main.Operation.BackupHandler.GetSnapshot(String[] sources, Options options, ILogWriter log)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass16_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.CommandLine.Commands.Backup(TextWriter outwriter, Action`1 setup, List`1 args, Dictionary`2 options, IFilter filter)
   at Duplicati.CommandLine.Program.RunCommandLine(TextWriter outwriter, TextWriter errwriter, Action`1 setup, String[] args)

**Comment by kenkendk** [comment]
Yes, you are quite right, the "Prefer32Bit" is set to true by default. I will make a new canary that has the flag turned off.
