### ISSUE TITLE
error in updater

### ISSUE THREAD

**Issue by binarybum** [duplicati/duplicati#2530]
I have:
- [ x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.53
**Operating System:** Win10 64
**Backend:**

### Bug description
Does not update, log shows following errors:

Jun 8, 2017 12:14 PM: Error in updater
System.UnauthorizedAccessException: Access to the path 'acknowledgements.txt' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Duplicati.Library.AutoUpdater.UpdaterManager.DownloadAndUnpackUpdate(UpdateInfo version, Action`1 progress)
Jun 8, 2017 12:14 PM: Error in updater
System.Net.WebException: The remote name could not be resolved: 'alt.updates.duplicati.com'
   at Duplicati.Library.Utility.AsyncHttpRequest.AsyncWrapper.GetResponseOrStream()
   at Duplicati.Library.Utility.AsyncHttpRequest.GetResponse()
   at Duplicati.Library.AutoUpdater.UpdaterManager.DownloadAndUnpackUpdate(UpdateInfo version, Action`1 progress)
Jun 8, 2017 12:13 PM: Error in updater
System.UnauthorizedAccessException: Access to the path 'acknowledgements.txt' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Duplicati.Library.AutoUpdater.UpdaterManager.DownloadAndUnpackUpdate(UpdateInfo version, Action`1 progress)
Jun 8, 2017 12:13 PM: Error in updater
System.Net.WebException: The remote name could not be resolved: 'alt.updates.duplicati.com'
   at Duplicati.Library.Utility.AsyncHttpRequest.AsyncWrapper.GetResponseOrStream()
   at Duplicati.Library.Utility.AsyncHttpRequest.GetResponse()
   at Duplicati.Library.AutoUpdater.UpdaterManager.DownloadAndUnpackUpdate(UpdateInfo version, Action`1 progress)
Jun 8, 2017 12:13 PM: Error in updater
System.UnauthorizedAccessException: Access to the path 'acknowledgements.txt' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Duplicati.Library.AutoUpdater.UpdaterManager.DownloadAndUnpackUpdate(UpdateInfo version, Action`1 progress)
Jun 8, 2017 12:13 PM: Error in updater
System.Net.WebException: The remote name could not be resolved: 'alt.updates.duplicati.com'
   at Duplicati.Library.Utility.AsyncHttpRequest.AsyncWrapper.GetResponseOrStream()
   at Duplicati.Library.Utility.AsyncHttpRequest.GetResponse()
   at Duplicati.Library.AutoUpdater.UpdaterManager.DownloadAndUnpackUpdate(UpdateInfo version, Action`1 progress)
Jun 8, 2017 12:12 PM: Error in updater
System.UnauthorizedAccessException: Access to the path 'acknowledgements.txt' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Duplicati.Library.AutoUpdater.UpdaterManager.DownloadAndUnpackUpdate(UpdateInfo version, Action`1 progress)
Jun 8, 2017 12:12 PM: Error in updater
System.Net.WebException: The remote name could not be resolved: 'alt.updates.duplicati.com'
   at Duplicati.Library.Utility.AsyncHttpRequest.AsyncWrapper.GetResponseOrStream()
   at Duplicati.Library.Utility.AsyncHttpRequest.GetResponse()
   at Duplicati.Library.AutoUpdater.UpdaterManager.DownloadAndUnpackUpdate(UpdateInfo version, Action`1 progress)

### Steps to reproduce
Attempt to update through app.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Doesn't update.  
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Should update. Has previously.

**Comment by kenkendk** [comment]
It looks like something has locked the `acknowledgements.txt` file in the update folder.
Maybe you can use something like LockHunter to see who locked it:
http://lockhunter.com/

**Comment by binarybum** [comment]
​Thanks for the advice.  That app says nothing is locked in my duplicati
folder.  Interestingly now I am able to get Duplicati to say: "You are
currently running Duplicati - 2.0.1.53_experimental_2017-03-13
Update 2.0.1.61_experimental_2017-05-30 is available, download now
Update 2.0.1.61_experimental_2017-05-30 is installed, activate now
​"

When I click activate now it waits and then reconnects to duplicati but the
version is not upgraded.  Log shows this:​

   - Request for
   http://127.0.0.1:8200/api/v1/serverstate?longpoll=true&lasteventid=2&format=json&duration=5m
   gave error
   System.Threading.ThreadAbortException: Thread was being aborted. at
   System.Threading.WaitHandle.WaitOneNative(SafeHandle waitableSafeHandle,
   UInt32 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.InternalWaitOne(SafeHandle
   waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity,
   Boolean exitContext) at System.Threading.WaitHandle.WaitOne(Int32
   millisecondsTimeout, Boolean exitContext) at
   Duplicati.Server.EventPollNotify.Wait(Int64 eventId, Int32 milliseconds) at
   Duplicati.Server.WebServer.RESTMethods.RequestInfo.LongPollCheck(EventPollNotify
   poller, Int64& id, Boolean& isError) at
   Duplicati.Server.WebServer.RESTMethods.ServerState.GET(String key,
   RequestInfo info) at
   Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String
   method, String module, String key)

​
Thank you.

**Comment by kenkendk** [comment]
I think you have some stale data lurking. Try looking in the folder `%APPDATA%Duplicati\updates` If  see a `2.0.1.61` folder in there, then delete it and try the update again.

**Comment by binarybum** [comment]
Interesting.  Don't even have an updates folder.

**Comment by kenkendk** [comment]
What about the installation folder (where you start Duplicati from) ?

**Comment by binarybum** [comment]
Yes, ok found it and this did it thank you!
