### ISSUE TITLE
Getting "Completing Backup" for several days now.

### ISSUE THREAD

**Issue by lynndixon** [duplicati/duplicati#2544]
I created a new backup that is about 400GB in size and thousands upon thousands of files.

Destination: Google Drive
Duplicati Version: 2.0.1.61_experimental_2017-05-30

Issue: This is the first run of this particular backup.  It appears all the files have uploaded to Google Drive, as the last time the files were touched were on June 16th around noon Eastern Time.  However, Duplicati is still doing *something* for the last 30 hours as its showing "Completing Backup" and not progressing: 
![image](https://user-images.githubusercontent.com/14202086/27256047-e0c492fe-5378-11e7-9b76-60d7c658ab4f.png)

Trying to look at the logs for this specific backup returns "Database locked", and then in the Show Log, Stored selection I see these entries:

> Mono.Data.Sqlite.SqliteException (0x80004005): The database file is locked
> database is locked
>   at Mono.Data.Sqlite.SQLite3.Prepare (Mono.Data.Sqlite.SqliteConnection cnn, System.String strSql, Mono.Data.Sqlite.SqliteStatement previous, System.UInt32 timeoutMS, System.String& strRemain) [0x001ba] in <57adb2e791674bcbb44d88d61fd4f287>:0 
>   at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand () [0x000d3] in <57adb2e791674bcbb44d88d61fd4f287>:0 
>   at Mono.Data.Sqlite.SqliteCommand.GetStatement (System.Int32 index) [0x00008] in <57adb2e791674bcbb44d88d61fd4f287>:0 
>   at (wrapper remoting-invoke-with-check) Mono.Data.Sqlite.SqliteCommand:GetStatement (int)
>   at Mono.Data.Sqlite.SqliteDataReader.NextResult () [0x000b3] in <57adb2e791674bcbb44d88d61fd4f287>:0 
>   at Mono.Data.Sqlite.SqliteDataReader..ctor (Mono.Data.Sqlite.SqliteCommand cmd, System.Data.CommandBehavior behave) [0x0004e] in <57adb2e791674bcbb44d88d61fd4f287>:0 
>   at (wrapper remoting-invoke-with-check) Mono.Data.Sqlite.SqliteDataReader:.ctor (Mono.Data.Sqlite.SqliteCommand,System.Data.CommandBehavior)
>   at Mono.Data.Sqlite.SqliteCommand.ExecuteReader (System.Data.CommandBehavior behavior) [0x00006] in <57adb2e791674bcbb44d88d61fd4f287>:0 
>   at Mono.Data.Sqlite.SqliteCommand.ExecuteNonQuery () [0x00000] in <57adb2e791674bcbb44d88d61fd4f287>:0 
>   at Mono.Data.Sqlite.SqliteConnection.Open () [0x00543] in <57adb2e791674bcbb44d88d61fd4f287>:0 
>   at Duplicati.Library.SQLiteHelper.SQLiteLoader.LoadConnection (System.String targetpath, System.String tempdir) [0x0009f] in <71eb3c9080a34fefba8dda4ed19b6fe4>:0 
>   at Duplicati.Server.WebServer.RESTMethods.Backup.FetchLogData (Duplicati.Server.Serialization.Interface.IBackup backup, Duplicati.Server.WebServer.RESTMethods.RequestInfo info) [0x00006] in <ee7f4101bcfe4729adf8920cf8d9f9e7>:0 
>   at Duplicati.Server.WebServer.RESTMethods.Backup.GET (System.String key, Duplicati.Server.WebServer.RESTMethods.RequestInfo info) [0x001e4] in <ee7f4101bcfe4729adf8920cf8d9f9e7>:0 
>   at Duplicati.Server.WebServer.RESTHandler.DoProcess (Duplicati.Server.WebServer.RESTMethods.RequestInfo info, System.String method, System.String module, System.String key) [0x00140] in <ee7f4101bcfe4729adf8920cf8d9f9e7>:0 

Jun 17, 2017 4:21 PM: Reporting error gave error
> System.ObjectDisposedException: Cannot write to a closed TextWriter.
>   at System.IO.StreamWriter.Flush (System.Boolean flushStream, System.Boolean flushEncoder) [0x00008] in <8e4c7b80ba0942cb8aa6c8f9f3e5b12d>:0 
>   at System.IO.StreamWriter.Flush () [0x00006] in <8e4c7b80ba0942cb8aa6c8f9f3e5b12d>:0 
>   at Duplicati.Server.WebServer.RESTHandler.DoProcess (Duplicati.Server.WebServer.RESTMethods.RequestInfo info, System.String method, System.String module, System.String key) [0x003aa] in <ee7f4101bcfe4729adf8920cf8d9f9e7>:0 

Looking at the Profiling section I see these log entries:

>Jun 16, 2017 11:44 PM: Starting - ExecuteScalarInt64: SELECT COUNT(*) FROM "TmpFileList-7AF31EFC6E5BEF4D8062B16D1A8D2091" A, "TmpFileList-3CEA815EA063AA40B7D8E1FEEF6BD6BD" B WHERE "A"."Path" = "B"."Path" AND ("A"."Filehash" != "B"."Filehash" OR "A"."Metahash" != "B"."Metahash")

And:

>Jun 16, 2017 11:44 PM: ExecuteScalarInt64: SELECT COUNT(*) FROM "TmpFileList-7AF31EFC6E5BEF4D8062B16D1A8D2091" WHERE "TmpFileList-7AF31EFC6E5BEF4D8062B16D1A8D2091"."Path" NOT IN (SELECT "Path" FROM "File" INNER JOIN "FilesetEntry" ON "File"."ID" = "FilesetEntry"."FileID" WHERE "FilesetEntry"."FilesetID" = ?) took 00:00:06.106

As well as several other very similar ones:

![image](https://user-images.githubusercontent.com/14202086/27256099-f74f9eaa-5379-11e7-909f-8706643f9fd7.png)

I hope all that information is somewhat helpful.  Please let me know if there is anything else I can collect or look at to help out.

**Comment by kenkendk** [comment]
The "Database is locked" message happens because the logs from the database cannot be shown while the backup is in progress (should be fixed, but not related to the issue here).

The queries you found in the other log are counting how many files were changed. This is not expected to take any time, which is why the display is not updating here.

How many files (appx.) are in the backup?

**Comment by lynndixon** [comment]
Ken,
There are many many thousands of files in this backup set, possibly over 100k or more.

**Comment by TeeKay2000** [comment]
I also have this problem, mine has been running for over 50 hours now.
I'm on version 2.0.2.19_canary_2018-02-12 and the destination is Google Drive.

I got the following error from Google Drive:

> 15 feb 2018 00:51: Failed while executing "Backup" with id: 5
> System.Net.WebException: The remote server returned an error: (403) Forbidden.
>    at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes)
>    at Duplicati.Library.Main.Operation.BackupHandler.RunMainOperation(ISnapshotService snapshot, BackendManager backend)
>    at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
>    at Duplicati.Library.Main.Controller.<>c__DisplayClass17_0.<Backup>b__0(BackupResults result)
>    at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
>    at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
>    at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

This was due to reaching the 750GB daily limit.

And after restarting the backup the last message i got was:

> 15 feb 2018 07:25: Message
> Re-creating missing index file for duplicati-b7e0c48829fda47cdbb0b681a9c756621.dblock.zip.aes

and the only activity from duplicati is the CPU usage that is holidng on 12-13% and a very slow database read.
![image](https://user-images.githubusercontent.com/28218536/36341002-b0f20c8e-13e7-11e8-993a-05ca3f88b739.png)

The backup set is about 1350 files which i upload with a volume size of 4GB, totalling about 3TB.
It was about 90% complete before the error from Google.

Any ideas on why this is taking so long? Is i stuck?
Is there any way to see the progress other than logs, 'cause it's not logging anything?

**Comment by TeeKay2000** [comment]
I have this problem too.

Mine has been going on for well over 50 hours now.

My Duplicati version is 2.0.2.19_canary_2018-02-12 and the destination is Google Drive.

The first error I got was:
> 15 feb 2018 00:51: Failed while executing "Backup" with id: 5
> System.Net.WebException: The remote server returned an error: (403) Forbidden.
>    at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes)
>    at Duplicati.Library.Main.Operation.BackupHandler.RunMainOperation(ISnapshotService snapshot, BackendManager backend)
>    at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
>    at Duplicati.Library.Main.Controller.<>c__DisplayClass17_0.<Backup>b__0(BackupResults result)
>    at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
>    at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
>    at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

That was due to Googles 750GB/day uploadlimit that was reached.

When I restarted the backup, the last message i got was:

> 15 feb 2018 07:25: Message
> Re-creating missing index file for duplicati-b7e0c48829fda47cdbb0b681a9c756621.dblock.zip.aes
> 
> 15 feb 2018 07:25: Message
> removing file listed as Temporary: duplicati-20180208T093421Z.dlist.zip.aes
> 
> 15 feb 2018 07:25: Message
> Uploading filelist from previous interrupted backup
From then on I'm stuck at "Completing previous backup ..."

The backup set is about 1350 files which i upload with a volume size of 4GB, totalling about 3TB.
It was about 90% complete before the error from Google.

The only activity in Duplicati is the CPU that is constantly around 12-13% and a very low database read.
![image](https://user-images.githubusercontent.com/28218536/36343563-0061c6d0-140e-11e8-8776-6367abd3811b.png)

There are no more logs saying what is going on. Is it stuck?

Is there a way to see the progress? It would be a good idea if there were more detailed progress bars for the different statuses, like Veifying backup, Completing backup, etc.

**Comment by kenkendk** [comment]
> Any ideas on why this is taking so long? Is i stuck?

Since you have a 4GB file, I think this is simply because the database query that recreates the index file is really slow. I think you just have to wait, and it will eventually create the index file and move on.

> Is there any way to see the progress other than logs, 'cause it's not logging anything?

If I am guessing correctly, it is currently running inside the SQLite3 code, so there is nothing to report other than "building index file".

**Comment by TeeKay2000** [comment]
Would having smaller volume sizes speed up the process?
