### ISSUE TITLE
[HubiC] Error: "Failed to connect: The remote server...(500) Internal Server Error"

### ISSUE THREAD

**Issue by Marsnk** [duplicati/duplicati#2547]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.61_experimental_2017-05-30
**Operating System:** Windows 10 x64
**Backend:** HubiC backup destination

### Bug description
Receiving a 500 Internal Server Error when using "Test connection" after successful OAuth authentication. This is using HubiC as the backup destination.

### Steps to reproduce
- Select Storage Type: HubiC
- Click on AuthID, log in using credentials
- Click on Test connection

**Actual result:** After following the above steps, a modal showing the attached 500 error appears.
**Expected result:** The expected result should be a successful message.

### Screenshots

![hubic](https://user-images.githubusercontent.com/15512395/27263768-3ac858ce-5425-11e7-8855-57ed25ee7efd.jpg)
### debug log

> Jun 18, 2017 12:42 PM: Request for http://127.0.0.1:8200/api/v1/remoteoperation/test gave error

System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at Duplicati.Library.Utility.AsyncHttpRequest.AsyncWrapper.GetResponseOrStream()
   at Duplicati.Library.Utility.AsyncHttpRequest.GetResponse()
   at Duplicati.Library.JSONWebHelper.GetResponse(AsyncHttpRequest req, Object requestdata)
   at Duplicati.Library.JSONWebHelper.ReadJSONResponse[T](AsyncHttpRequest req, Object requestdata)
   at Duplicati.Library.Backend.OpenStack.OpenStackStorage.List()
   at Duplicati.Library.Backend.HubiC.HubiCBackend.Test()
   at Duplicati.Server.WebServer.RESTMethods.RemoteOperation.TestConnection(String url, RequestInfo info)
   at Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)

> Jun 18, 2017 12:42 PM: Reporting error gave error

System.ObjectDisposedException: Cannot write to a closed TextWriter.
   at System.IO.__Error.WriterClosed()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)

**Comment by kenkendk** [comment]
Try to use the path `default/Backups` instead. HubiC has some strange naming rules.

**Comment by Marsnk** [comment]
Confirming that changing the "Path on server" field to "default/<Folder Name>" fixes the Test connection error. Thanks.
![hubic_02](https://user-images.githubusercontent.com/15512395/27292936-ce45cc4a-54c9-11e7-911e-4758be3c8b99.jpg)

**Comment by kenkendk** [comment]
There was supposed to be a dialog that said "you need the default/ prefix", but due to a bug it was not shown. I will fix this so the dialog is shown.
