### ISSUE TITLE
Recreate (delete and repair) task fails repeatedly

### ISSUE THREAD

**Issue by ghost** [duplicati/duplicati#2559]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.61_experimental_2017-05-30
**Operating System:** Windows 10
**Backend:** Amazon Drive

### Bug description
Have repeatedly attempted to recreate database (delete and repair) after numerous failed backups to receive the same error.

22 Jun 2017 12:59: Failed while executing "Repair" with id: 1
System.NullReferenceException: Object reference not set to an instance of an object.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

- From database maintenance select "Recreate (delete and repair)"
- After several hours of processing the task eventually fails with above error,

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

22 Jun 2017 12:59: Failed while executing "Repair" with id: 1

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

The database maintenance task should complete successfully (and did previously many months ago)

### debug log

22 Jun 2017 12:59: Failed while executing "Repair" with id: 1
System.NullReferenceException: Object reference not set to an instance of an object.

   at Duplicati.Library.Main.Volumes.VolumeReaderBase.<ReadBlocklist>d__8.MoveNext()

   at Duplicati.Library.Main.Database.LocalRecreateDatabase.UpdateBlockset(String hash, IEnumerable`1 blocklisthashes, IDbTransaction transaction)

   at Duplicati.Library.Main.Operation.RecreateDatabaseHandler.DoRun(LocalDatabase dbparent, Boolean updating, IFilter filter, NumberedFilterFilelistDelegate filelistfilter, BlockVolumePostProcessor blockprocessor)

   at Duplicati.Library.Main.Operation.RecreateDatabaseHandler.Run(String path, IFilter filter, NumberedFilterFilelistDelegate filelistfilter, BlockVolumePostProcessor blockprocessor)

   at Duplicati.Library.Main.Operation.RepairHandler.RunRepairLocal(IFilter filter)

   at Duplicati.Library.Main.Operation.RepairHandler.Run(IFilter filter)

   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)

   at Duplicati.Library.Main.Controller.Repair(IFilter filter)

   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

**Comment by ts678** [comment]
Did a manual search of open and closed issues for the final Repair failure and message. Didn't come up with an exact fit for that.
Did a Google search for "LocalRecreateDatabase.UpdateBlockset" "NullReferenceException", but this is the only thing that it had.

I doubt this is going to get solved unless something more reproducible can be actively debugged. Last call for further comment. otherwise this issue will automatically close.
