### ISSUE TITLE
Failure while invoking GnuPG, program won't flush output

### ISSUE THREAD

**Issue by keystrike** [duplicati/duplicati#2566]
Current canary build on Windows 8.1. I don't see any issues related to this issue. I receive the below in the log:

System.Security.Cryptography.CryptographicException: Failure while invoking GnuPG, program won't flush output
   at Duplicati.Library.Encryption.GPGStreamWrapper.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at Duplicati.Library.Encryption.EncryptionBase.Encrypt(Stream input, Stream output)
   at Duplicati.Library.Encryption.EncryptionBase.Encrypt(String inputfile, String outputfile)
   at Duplicati.Library.Main.BackendManager.FileEntryItem.Encrypt(IEncryption encryption, IBackendWriter stat)
   at Duplicati.Library.Main.BackendManager.Put(VolumeWriterBase item, IndexVolumeWriter indexfile, Boolean synchronous)
   at Duplicati.Library.Main.Operation.BackupHandler.FinalizeRemoteVolumes(BackendManager backend)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass16_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

**Comment by kenkendk** [comment]
Most likely there are some options or similar that causes an error or another state with GPG.
The error happens because Duplicati has closed the GPG input data, but GPG has not completed after 5 seconds.

**Comment by Luke1410** [comment]
Is there a way to troubleshoot the issue? I just spotted this issue here while googling for the error "Failure while invoking GnuPG, program won't flush output." which just occurred to me with Duplicati 1.3.4. I do understand that this issue report and your (@kenkendk) suggestion is assuming Duplicati 2.x, and won't apply to Duplicati 1.3.4, or would it?

**Comment by rdae** [comment]
Any updates since 2017? I keeps happening on one of my backups. Using 
**GNU Privacy Guard, external**
--blocksize=10MB
--gpg-encryption-command=--symmetric
--gpg-encryption-switches=--cipher-algo AES256

```
System.Security.Cryptography.CryptographicException: Failure while invoking GnuPG, program won't flush output
   at Duplicati.Library.Encryption.GPGStreamWrapper.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at Duplicati.Library.Encryption.EncryptionBase.Encrypt(Stream input, Stream output)
   at Duplicati.Library.Encryption.EncryptionBase.Encrypt(String inputfile, String outputfile)
   at Duplicati.Library.Main.Operation.Common.BackendHandler.FileEntryItem.Encrypt(Options options)
   at Duplicati.Library.Main.Volumes.VolumeWriterBase.CreateFileEntryForUpload(Options options)
   at Duplicati.Library.Main.Operation.Backup.DataBlockProcessor.<>c__DisplayClass0_0.<<Run>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Duplicati.Library.Main.Operation.Backup.DataBlockProcessor.<>c__DisplayClass0_0.<<Run>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CoCoL.AutomationExtensions.<RunTask>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.BackupHandler.<RunMainOperation>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CoCoL.ChannelExtensions.WaitForTaskOrThrow(Task task)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass14_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
```

Windows 10

**Comment by gregewing** [comment]
I get this when Disk IO is being hammered by other processes.   might that be a contributory factor ?
