### ISSUE TITLE
errors wne use --include

### ISSUE THREAD

**Issue by xor256** [duplicati/duplicati#2581]
Traceback (most recent call last):
  File "/usr/bin/duplicity", line 1540, in <module>
    with_tempdir(main)
  File "/usr/bin/duplicity", line 1534, in with_tempdir
    fn()
  File "/usr/bin/duplicity", line 1372, in main
    action = commandline.ProcessCommandLine(sys.argv[1:])
  File "/usr/lib64/python2.7/site-packages/duplicity/commandline.py", line 1154, in ProcessCommandLine
    set_selection()
  File "/usr/lib64/python2.7/site-packages/duplicity/commandline.py", line 978, in set_selection
    sel.ParseArgs(select_opts, select_files)
  File "/usr/lib64/python2.7/site-packages/duplicity/selection.py", line 258, in ParseArgs
    for sf in self.filelist_globbing_get_sfs(filelists[filelists_index], 0, arg):
  File "/usr/lib64/python2.7/site-packages/duplicity/selection.py", line 371, in filelist_globbing_get_sfs
    yield self.glob_get_sf(line, include)
  File "/usr/lib64/python2.7/site-packages/duplicity/selection.py", line 434, in glob_get_sf
    sel_func = self.glob_get_filename_sf(glob_str, include)
  File "/usr/lib64/python2.7/site-packages/duplicity/selection.py", line 502, in glob_get_filename_sf
    raise FilePrefixError(filename)
FilePrefixError: /home/user/destination-dir

---
duplicity --archive-dir=~/.duplicity.data incremental --full-if-older-than 3M (here --include= --exclude-filelist etc) /home/user/files file:///home/cos/cos
fedora

**Comment by kenkendk** [comment]
This is the Duplicati project; your bug is for the [duplicity](https://launchpad.net/duplicity) project
