### ISSUE TITLE
Unable to exclude "C:\$WINDOWS.~BT" from backup

### ISSUE THREAD

**Issue by Jimbly** [duplicati/duplicati#2593]
### Version info
**Duplicati Version:** 2.0.1.61_experimental_2017-05-30
**Operating System:** Windows 10 Pro

### Bug description
My backups started erroring a few days ago with a bunch of errors along the lines of:
```
Failed to process metadata for "C:\$WINDOWS.~BT\Sources\Panther\windlp.state.xml", storing empty metadata
System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
```

I attempted to add C:\$WINDOWS.~BT\ as an exclude to my filters, and the UI indicates it was added successfully, however I continue getting the error.
![bug](https://user-images.githubusercontent.com/774383/28020965-195202ae-653b-11e7-83bf-c0d71d5780ee.png)

If I export the configuration as a command line, I see `--exclude="C:\$WINDOWS.~BT\\"`

### Debug log
The first entry in the debug log referencing the folder is just the error that shows up above.
```
2017-07-07 03:13:48Z - Warning: Failed to process metadata for "C:\$WINDOWS.~BT\Sources\Panther\diagerr.xml", storing empty metadata
System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at System.Security.AccessControl.Win32.GetSecurityInfo(ResourceType resourceType, String name, SafeHandle handle, AccessControlSections accessControlSections, RawSecurityDescriptor& resultSd)
   at System.Security.AccessControl.NativeObjectSecurity.CreateInternal(ResourceType resourceType, Boolean isContainer, String name, SafeHandle handle, AccessControlSections includeSections, Boolean createByName, ExceptionFromErrorCode exceptionFromErrorCode, Object exceptionContext)
   at System.Security.AccessControl.FileSystemSecurity..ctor(Boolean isContainer, String name, AccessControlSections includeSections, Boolean isDirectory)
   at System.Security.AccessControl.FileSecurity..ctor(String fileName, AccessControlSections includeSections)
   at Duplicati.Library.Snapshots.SystemIOWindows.GetAccessControlFile(String path)
   at Duplicati.Library.Snapshots.SystemIOWindows.GetMetadata(String path, Boolean isSymlink, Boolean followSymlink)
   at Duplicati.Library.Main.Operation.BackupHandler.GenerateMetadata(ISnapshotService snapshot, String path, FileAttributes attributes)
```

From some similar bugs, I'm assuming this is because of the "~" in the path somehow getting expanded to %HOME% or something.  Is there a way to work around that?

**Comment by Jimbly** [comment]
Doing a little more digging, it looks like I can mostly work around this by not using the GUI to deselect folders, and changing the exclude filter to be `C:\$WINDOWS.?BT`, and then it excludes it as desired, but this might be worth fixing in some way (can we escape the `~`, that the GUI could insert automatically when unchecking folders, etc?)

**Comment by kenkendk** [comment]
There is an explanation/workaround in issue #2342 

But yes, I should figure out how to deal with this in a better way.
