### ISSUE TITLE
After upgrade to latest version 

### ISSUE THREAD

**Issue by alexanderfitu** [duplicati/duplicati#2634]
I have:
- [ x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.69
**Operating System:** Windows server 2012 R2 Standard
**Backend:** FTP

### Bug description
After upgrading to this version, I get the message "Duplicati.Gui.Trayicon has stopped working".

### Steps to reproduce
run Run Duplicati.GUI.Trayicon.exe

**Actual result:** error as above 
**Expected result:** Program stars in the tray. 

### debug log
Log Name:      Application
Source:        .NET Runtime
Date:          8/11/2017 10:21:25 AM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:     xxxxxxxxxxxxxxxxxxx
Description:
Application: Duplicati.GUI.TrayIcon.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException
Stack:
   at Duplicati.Library.AutoUpdater.UpdaterManager.set_RequiresRespawn(Boolean value)
   at Duplicati.GUI.TrayIcon.Program.Main(String[] args)
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssemblyByName(System.String, System.String[])
   at Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent(System.Reflection.MethodInfo, System.String[], Duplicati.Library.AutoUpdater.AutoUpdateStrategy)
   at Duplicati.GUI.TrayIcon.Program.Main(System.String[])

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-08-11T09:21:25.000000000Z" />
    <EventRecordID>4503</EventRecordID>
    <Channel>Application</Channel>
    <Computer>xxxxxxxxxxxxxxx</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: Duplicati.GUI.TrayIcon.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException
Stack:
   at Duplicati.Library.AutoUpdater.UpdaterManager.set_RequiresRespawn(Boolean value)
   at Duplicati.GUI.TrayIcon.Program.Main(String[] args)
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssemblyByName(System.String, System.String[])
   at Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent(System.Reflection.MethodInfo, System.String[], Duplicati.Library.AutoUpdater.AutoUpdateStrategy)
   at Duplicati.GUI.TrayIcon.Program.Main(System.String[])
</Data>
  </EventData>
</Event>

AND

Faulting application name: Duplicati.GUI.TrayIcon.exe, version: 2.0.1.69, time stamp: 0x5954fa75
Faulting module name: KERNELBASE.dll, version: 6.3.9600.18666, time stamp: 0x58f33794
Exception code: 0xe0434352
Fault offset: 0x00000000000095fc
Faulting process id: 0x13d8
Faulting application start time: 0x01d31283333b9c84
Faulting application path: C:\Program Files\Duplicati 2\Duplicati.GUI.TrayIcon.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 725d1c7d-7e76-11e7-80c1-9418820abc1f
Faulting package full name: 
Faulting package-relative application ID:

**Comment by kenkendk** [comment]
Please try the latest version, this should be fixed in the beta:
https://www.duplicati.com/download
