### ISSUE TITLE
'System.IO.FileNotFoundException: Could not find file' during backup

### ISSUE THREAD

**Issue by plavrenko** [duplicati/duplicati#2642]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.2.1
**Operating System:** Windows 10 
**Backend:**

### Bug description
'System.IO.FileNotFoundException: Could not find file' during Backup each time after several hours of execution

### Steps to reproduce
- Configure backup task under Windows 10
- Wait till task starts
- After a long period (several hours) of operation it abruptly ends with the error mentioned above 

**Actual result:** Backup job stops with Erorr
**Expected result:** No error in Job execution

### debug log
14 авг. 2017 г., 06:43: Failed while executing "Backup" with id: 1
System.IO.FileNotFoundException: Could not find file 'C:\Users\Andrey\AppData\Local\Temp\dup-ed5ab54c-6b71-49e2-bdd1-a895ebf9f737'.
File name: 'C:\Users\Andrey\AppData\Local\Temp\dup-ed5ab54c-6b71-49e2-bdd1-a895ebf9f737'
   at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes)
   at Duplicati.Library.Main.Operation.BackupHandler.RunMainOperation(ISnapshotService snapshot, BackendManager backend)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass16_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

11 авг. 2017 г., 05:14: Failed while executing "Backup" with id: 1
System.IO.FileNotFoundException: Could not find file 'C:\Users\Andrey\AppData\Local\Temp\dup-c51d0ad1-bd9f-4ffd-82b3-706a1257b854'.
File name: 'C:\Users\Andrey\AppData\Local\Temp\dup-c51d0ad1-bd9f-4ffd-82b3-706a1257b854'
   at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes)
   at Duplicati.Library.Main.Operation.BackupHandler.RunMainOperation(ISnapshotService snapshot, BackendManager backend)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass16_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

**Comment by kenkendk** [comment]
It looks like this happens because you are attempting to make a backup of the temp folder.
You can get the error if you change the filesystem during the backup.
In this case I think the file listing is made, and then the file is deleted before processing of the file starts (other files are being processed first).
I recommend that you exclude the temporary folder from the backup, but you can also opt for using VSS to make sure you get actual disk snapshots.
