### ISSUE TITLE
Missing file error

### ISSUE THREAD

**Issue by Kamul-PL** [duplicati/duplicati#2658]
### Version info

**Duplicati Version:** 2.0.2.1_beta_2017-08-01
**Operating System:** Windows 10
**Backend:**

### Bug description
Right after updating to  2.0.2.1_beta_2017-08-01 version Duplicati stopped work. I even couldn't load its page (http://localhost:8200/). So I decided to uninstall it and install again. Than I restored settings (imported from file). When I managed to run Duplicati, it started to inform me about an error:

24 sie 2017 21:00: Message
Fatal error
Duplicati.Library.Interface.UserInformationException: Found 1 files that are missing from the remote storage, please run repair
   w Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)
   w Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend, String protectedfile)
   w Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
24 sie 2017 21:00: Message
Found 1 files that are missing from the remote storage, please run repair
24 sie 2017 21:00: Message
Missing file: duplicati-b5e09a4a878404ba28a9eb36fc9993af1.dblock.zip

I was trying to repair or delete and rebuilt local database, as it was suggested, but with no positive result. I'm afraid in my case the only solution could be to delete the main database and start from the beginning... Am I right? I'm a bit concerned, because such a things shouldn't happened in the case of backup program. Are such a problems typical or I have really bad luck?

**Comment by flexbrane** [comment]
Almost the same problem for me, on Duplicati - 2.0.2.2_canary_2017-08-30. I have `Found 8 files that are missing from the remote storage, please run repair`, even after a DB repair.

**Comment by Penryn** [comment]
I've encountered the same issue.

After running an initial backup, if the remote server permanently loses some/all of my backup files, it results in a message similar to: 

    Found 10 files that are missing from the remote storage, please run repair
       at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)
       at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend, String protectedfile)
       at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)

If I run a local database repair or recreate, I end up with the same message.
If I export, delete, re-import, and then run the backup, I end up with a different error message:

    Duplicati.Library.Interface.UserInformationException: No filelists found on the remote destination
       at Duplicati.Library.Main.Operation.RecreateDatabaseHandler.DoRun(LocalDatabase dbparent, Boolean updating, IFilter filter, NumberedFilterFilelistDelegate filelistfilter, BlockVolumePostProcessor blockprocessor)
       at Duplicati.Library.Main.Operation.RecreateDatabaseHandler.Run(String path, IFilter filter, NumberedFilterFilelistDelegate filelistfilter, BlockVolumePostProcessor blockprocessor)
       at Duplicati.Library.Main.Operation.RepairHandler.RunRepairLocal(IFilter filter)
       at Duplicati.Library.Main.Operation.RepairHandler.Run(IFilter filter)
       at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
       at Duplicati.Library.Main.Controller.Repair(IFilter filter)
       at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

Successive attempts to repair the local database fail.

So the only way to recover is to completely recreate the backup. I had some success in importing the config.json after deleting the `Metadata` tag and changing the name of the backup.

If some or all remote files are lost there should be a way to completely reset the backup so the user can force it to "recover" by effectively starting fresh, or attempt to repair missing blocks.

**Comment by flexbrane** [comment]
I have deleted all my backups and profiles and re-created them and now I don't have any problem anymore.
But in production for a company this is not likely the best solution :-s

**Comment by Rubyjunk** [comment]
Experiencing the same issue on 2.0.2.1_beta_2017-08-01 - repairing database fails as well. This is sort of scary for a backup software

**Comment by jpschewe** [comment]
I'm seeing this problem as well with both the previous and current beta (2.0.5.1_beta_2020-01-18).

Tonight I'm finding that duplicati is deleting a file in one run and in the next run is looking for that very file. Below are the logs
```
2020-02-01 20:49:37 -06 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Backup has started
2020-02-01 20:49:37 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  ()
2020-02-01 20:49:38 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (381 bytes)
2020-02-01 20:50:01 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-b157b779c67ff4d649b435cd7c73290b7.dblock.zip.aes (49.92 MB)
2020-02-01 20:50:02 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-b51938a94145c47eea26646e31b497a1f.dblock.zip.aes (49.95 MB)
2020-02-01 20:50:02 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-bf7da4425d903436f925adade8bb5dff3.dblock.zip.aes (49.95 MB)
2020-02-01 20:50:02 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-b85cf5662a70a4bb793a0a9124172c2ab.dblock.zip.aes (49.94 MB)
2020-02-01 20:50:21 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-b157b779c67ff4d649b435cd7c73290b7.dblock.zip.aes (49.92 MB)
2020-02-01 20:50:21 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-if8837fcdb55a4dbbaf6c803c066e8242.dindex.zip.aes (33.84 KB)
2020-02-01 20:50:22 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-if8837fcdb55a4dbbaf6c803c066e8242.dindex.zip.aes (33.84 KB)
2020-02-01 20:50:22 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-b3700fa6358ad41079f57127f98c34062.dblock.zip.aes (49.94 MB)
2020-02-01 20:50:23 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-b51938a94145c47eea26646e31b497a1f.dblock.zip.aes (49.95 MB)
2020-02-01 20:50:23 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-i58434be3adb34e76bc955bbf35c93558.dindex.zip.aes (34.00 KB)
2020-02-01 20:50:23 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-b85cf5662a70a4bb793a0a9124172c2ab.dblock.zip.aes (49.94 MB)
2020-02-01 20:50:23 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-i2f00236889cd4d52b526a85ae1f4ab38.dindex.zip.aes (34.09 KB)
2020-02-01 20:50:24 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-i58434be3adb34e76bc955bbf35c93558.dindex.zip.aes (34.00 KB)
2020-02-01 20:50:24 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-b3a7a8b2ee06c4187a2a6cbc9fc368628.dblock.zip.aes (49.94 MB)
2020-02-01 20:50:24 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-bf7da4425d903436f925adade8bb5dff3.dblock.zip.aes (49.95 MB)
2020-02-01 20:50:24 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-i7aed3942b5714f5c8d8550c499c1e16a.dindex.zip.aes (234.25 KB)
2020-02-01 20:50:25 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-i2f00236889cd4d52b526a85ae1f4ab38.dindex.zip.aes (34.09 KB)
2020-02-01 20:50:27 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-i7aed3942b5714f5c8d8550c499c1e16a.dindex.zip.aes (234.25 KB)
2020-02-01 20:50:32 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-b3700fa6358ad41079f57127f98c34062.dblock.zip.aes (49.94 MB)
2020-02-01 20:50:32 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-iac248da91fc842d3b5ab061ffb59da63.dindex.zip.aes (34.33 KB)
2020-02-01 20:50:33 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-b3a7a8b2ee06c4187a2a6cbc9fc368628.dblock.zip.aes (49.94 MB)
2020-02-01 20:50:33 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-i7279a49f824d4b35a890f20259f97299.dindex.zip.aes (34.28 KB)
2020-02-01 20:50:33 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-iac248da91fc842d3b5ab061ffb59da63.dindex.zip.aes (34.33 KB)
2020-02-01 20:50:34 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-i7279a49f824d4b35a890f20259f97299.dindex.zip.aes (34.28 KB)
2020-02-01 20:50:37 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-b3f07616debbe42ac86fe403bbbdb4119.dblock.zip.aes (49.93 MB)
2020-02-01 20:50:43 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-b3f07616debbe42ac86fe403bbbdb4119.dblock.zip.aes (49.93 MB)
2020-02-01 20:50:43 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-i4938332746db4a9eb272ade9be4bbf7d.dindex.zip.aes (145.73 KB)
2020-02-01 20:50:44 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-i4938332746db4a9eb272ade9be4bbf7d.dindex.zip.aes (145.73 KB)
2020-02-01 20:50:53 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-b436cc015437f46f3966140c5d3672a2a.dblock.zip.aes (49.94 MB)
2020-02-01 20:50:59 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-b436cc015437f46f3966140c5d3672a2a.dblock.zip.aes (49.94 MB)
2020-02-01 20:50:59 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-i185474a7c98c4d36adcb1c3c467b87d8.dindex.zip.aes (182.89 KB)
2020-02-01 20:51:00 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-i185474a7c98c4d36adcb1c3c467b87d8.dindex.zip.aes (182.89 KB)
2020-02-01 20:51:05 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-b986b9cb01ebf4841b9240857374dfc87.dblock.zip.aes (15.59 MB)
2020-02-01 20:51:05 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-20200202T024937Z.dlist.zip.aes (1.93 KB)
2020-02-01 20:51:06 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-20200202T024937Z.dlist.zip.aes (1.93 KB)
2020-02-01 20:51:07 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-b986b9cb01ebf4841b9240857374dfc87.dblock.zip.aes (15.59 MB)
2020-02-01 20:51:07 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-i3c49c757c179484bbf604426f1dd0ba4.dindex.zip.aes (15.87 KB)
2020-02-01 20:51:08 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-i3c49c757c179484bbf604426f1dd0ba4.dindex.zip.aes (15.87 KB)
2020-02-01 20:51:08 -06 - [Information-Duplicati.Library.Main.Operation.DeleteHandler:RetentionPolicy-StartCheck]: Start checking if backups can be removed
2020-02-01 20:51:08 -06 - [Information-Duplicati.Library.Main.Operation.DeleteHandler:RetentionPolicy-FramesAndIntervals]: Time frames and intervals pairs: 7.00:00:00 / 1.00:00:00, 28.00:00:00 / 7.00:00:00, 365.00:00:00 / 31.00:00:00
2020-02-01 20:51:08 -06 - [Information-Duplicati.Library.Main.Operation.DeleteHandler:RetentionPolicy-BackupList]: Backups to consider: 1/31/2020 6:15:00 PM, 1/30/2020 6:15:00 PM, 1/29/2020 6:15:00 PM, 1/28/2020 6:15:00 PM, 1/27/2020 6:15:00 PM, 1/26/2020 6:15:00 PM, 1/25/2020 6:15:00 PM, 1/20/2020 6:27:38 PM, 1/12/2020 8:03:46 PM, 1/4/2020 6:27:50 PM, 12/3/2019 6:06:23 PM, 10/30/2019 9:55:43 PM, 9/22/2019 5:31:05 PM
2020-02-01 20:51:08 -06 - [Information-Duplicati.Library.Main.Operation.DeleteHandler:RetentionPolicy-BackupsToDelete]: Backups outside of all time frames and thus getting deleted: 
2020-02-01 20:51:08 -06 - [Information-Duplicati.Library.Main.Operation.DeleteHandler:RetentionPolicy-AllBackupsToDelete]: All backups to delete: 1/25/2020 6:15:00 PM
2020-02-01 20:51:08 -06 - [Information-Duplicati.Library.Main.Operation.DeleteHandler-DeleteRemoteFileset]: Deleting 1 remote fileset(s) ...
2020-02-01 20:51:09 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Delete - Started: duplicati-20200126T001500Z.dlist.zip.aes (1.93 KB)
2020-02-01 20:51:10 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Delete - Completed: duplicati-20200126T001500Z.dlist.zip.aes (1.93 KB)
2020-02-01 20:51:10 -06 - [Information-Duplicati.Library.Main.Operation.DeleteHandler-DeleteResults]: Deleted 1 remote fileset(s)
2020-02-01 20:51:10 -06 - [Information-Duplicati.Library.Main.Database.LocalDeleteDatabase-CompactReason]: Compacting because there are 1 fully deletable volume(s)
2020-02-01 20:51:10 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Delete - Started: duplicati-b7f3824760e014ed78df3aa698f2e430f.dblock.zip.aes (49.91 MB)
2020-02-01 20:51:11 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Delete - Completed: duplicati-b7f3824760e014ed78df3aa698f2e430f.dblock.zip.aes (49.91 MB)
2020-02-01 20:51:11 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Delete - Started: duplicati-ie88fb39038594821a504de1f08b31a96.dindex.zip.aes (38.22 KB)
2020-02-01 20:51:13 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Delete - Completed: duplicati-ie88fb39038594821a504de1f08b31a96.dindex.zip.aes (38.22 KB)
2020-02-01 20:51:13 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b9af87d59ff6240169d81f708d68cd329.dblock.zip.aes (49.90 MB)
2020-02-01 20:51:18 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Completed: duplicati-b9af87d59ff6240169d81f708d68cd329.dblock.zip.aes (49.90 MB)
2020-02-01 20:51:18 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b9841d3f578ee47d988a2dceb0cd419d5.dblock.zip.aes (30.50 MB)
2020-02-01 20:51:22 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Completed: duplicati-b9841d3f578ee47d988a2dceb0cd419d5.dblock.zip.aes (30.50 MB)
2020-02-01 20:51:22 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b1f34dde3ac844c4297e835a74b7e7777.dblock.zip.aes (50.03 MB)
2020-02-01 20:51:27 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Completed: duplicati-b1f34dde3ac844c4297e835a74b7e7777.dblock.zip.aes (50.03 MB)
2020-02-01 20:51:27 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b5c571c10bda14882b09f2b18aea728fd.dblock.zip.aes (50.01 MB)
2020-02-01 20:51:32 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Completed: duplicati-b5c571c10bda14882b09f2b18aea728fd.dblock.zip.aes (50.01 MB)
2020-02-01 20:52:06 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b1500687061c447e38a6110646128b6c8.dblock.zip.aes (15.02 MB)
2020-02-01 20:52:09 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Completed: duplicati-b1500687061c447e38a6110646128b6c8.dblock.zip.aes (15.02 MB)
2020-02-01 20:52:09 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-be8791a8193cb4e6bb5ed8e9ad9a08f7b.dblock.zip.aes (49.91 MB)
2020-02-01 20:52:14 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Completed: duplicati-be8791a8193cb4e6bb5ed8e9ad9a08f7b.dblock.zip.aes (49.91 MB)
2020-02-01 20:52:14 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b4aacc2191e504763bf950414535cac5a.dblock.zip.aes (49.91 MB)
2020-02-01 20:52:19 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Completed: duplicati-b4aacc2191e504763bf950414535cac5a.dblock.zip.aes (49.91 MB)
2020-02-01 20:52:19 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-ba964105ba3fa4765b4b865d8b97466e4.dblock.zip.aes (49.91 MB)
2020-02-01 20:52:25 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Completed: duplicati-ba964105ba3fa4765b4b865d8b97466e4.dblock.zip.aes (49.91 MB)
2020-02-01 20:52:25 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b4aca1f411e2e48cc86bbf48bdda7ddc2.dblock.zip.aes (49.91 MB)
2020-02-01 20:52:30 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Completed: duplicati-b4aca1f411e2e48cc86bbf48bdda7ddc2.dblock.zip.aes (49.91 MB)
2020-02-01 20:52:30 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-bd88d99815a97449fab6f60d36f682d6d.dblock.zip.aes (49.92 MB)
2020-02-01 20:52:35 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Completed: duplicati-bd88d99815a97449fab6f60d36f682d6d.dblock.zip.aes (49.92 MB)
2020-02-01 20:52:35 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b94419bae74ef468fae6f1c56edfced57.dblock.zip.aes (49.93 MB)
2020-02-01 20:52:40 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Completed: duplicati-b94419bae74ef468fae6f1c56edfced57.dblock.zip.aes (49.93 MB)
2020-02-01 20:52:40 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b5bee86bf9c1c4a2888d7dd8788d66aea.dblock.zip.aes (10.04 MB)
2020-02-01 20:52:42 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Completed: duplicati-b5bee86bf9c1c4a2888d7dd8788d66aea.dblock.zip.aes (10.04 MB)
2020-02-01 20:52:42 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-bccdd08e18bf74a85992b665b76004c7f.dblock.zip.aes (49.93 MB)
2020-02-01 20:52:43 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Retrying: duplicati-bccdd08e18bf74a85992b665b76004c7f.dblock.zip.aes (49.93 MB)
2020-02-01 20:52:53 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-bccdd08e18bf74a85992b665b76004c7f.dblock.zip.aes (49.93 MB)
2020-02-01 20:52:54 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Retrying: duplicati-bccdd08e18bf74a85992b665b76004c7f.dblock.zip.aes (49.93 MB)
2020-02-01 20:53:04 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-bccdd08e18bf74a85992b665b76004c7f.dblock.zip.aes (49.93 MB)
2020-02-01 20:53:05 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Retrying: duplicati-bccdd08e18bf74a85992b665b76004c7f.dblock.zip.aes (49.93 MB)
2020-02-01 20:53:15 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-bccdd08e18bf74a85992b665b76004c7f.dblock.zip.aes (49.93 MB)
2020-02-01 20:53:16 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Retrying: duplicati-bccdd08e18bf74a85992b665b76004c7f.dblock.zip.aes (49.93 MB)
2020-02-01 20:53:26 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-bccdd08e18bf74a85992b665b76004c7f.dblock.zip.aes (49.93 MB)
2020-02-01 20:53:26 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Failed: duplicati-bccdd08e18bf74a85992b665b76004c7f.dblock.zip.aes (49.93 MB)
2020-02-01 20:53:26 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b92d4edd086d54dcc93fc79e3704baafc.dblock.zip.aes (49.93 MB)
2020-02-01 20:53:32 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Completed: duplicati-b92d4edd086d54dcc93fc79e3704baafc.dblock.zip.aes (49.93 MB)
2020-02-01 20:53:32 -06 - [Error-Duplicati.Library.Main.Operation.BackupHandler-FatalError]: Fatal error
System.Net.WebException: The remote server returned an error: (503) Service Unavailable.
  at System.Net.HttpWebRequest.GetResponseFromData (System.Net.WebResponseStream stream, System.Threading.CancellationToken cancellationToken) [0x00146] in <4d8f95b7df544b3fa1a27dda924b4424>:0 
  at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts) [0x000f8] in <4d8f95b7df544b3fa1a27dda924b4424>:0 
  at Duplicati.Library.Main.AsyncDownloader+AsyncDownloaderEnumerator+AsyncDownloadedFile.get_TempFile () [0x00008] in <8f1de655bd1240739a78684d845cecc8>:0 
  at Duplicati.Library.Main.Operation.CompactHandler.DoCompact (Duplicati.Library.Main.Database.LocalDeleteDatabase db, System.Boolean hasVerifiedBackend, System.Data.IDbTransaction& transaction, Duplicati.Library.Main.BackendManager sharedBackend) [0x00264] in <8f1de655bd1240739a78684d845cecc8>:0 
  at Duplicati.Library.Main.Operation.DeleteHandler.DoRun (Duplicati.Library.Main.Database.LocalDeleteDatabase db, System.Data.IDbTransaction& transaction, System.Boolean hasVerifiedBacked, System.Boolean forceCompact, Duplicati.Library.Main.BackendManager sharedManager) [0x00397] in <8f1de655bd1240739a78684d845cecc8>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.CompactIfRequired (Duplicati.Library.Main.BackendManager backend, System.Int64 lastVolumeSize) [0x000a5] in <8f1de655bd1240739a78684d845cecc8>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.RunAsync (System.String[] sources, Duplicati.Library.Utility.IFilter filter, System.Threading.CancellationToken token) [0x00d9f] in <8f1de655bd1240739a78684d845cecc8>:0 
2020-02-01 20:56:40 -06 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Backup has started
2020-02-01 20:56:40 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  ()
2020-02-01 20:56:41 -06 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (397 bytes)
2020-02-01 20:56:41 -06 - [Information-Duplicati.Library.Main.Operation.FilelistProcessor-RemoteUnwantedMissingFile]: removing file listed as Deleting: duplicati-b7f3824760e014ed78df3aa698f2e430f.dblock.zip.aes
2020-02-01 20:56:41 -06 - [Information-Duplicati.Library.Main.Operation.FilelistProcessor-RemoteUnwantedMissingFile]: removing file listed as Temporary: duplicati-b059a62eef71d4a56a228df788068818c.dblock.zip.aes
2020-02-01 20:56:41 -06 - [Information-Duplicati.Library.Main.Operation.FilelistProcessor-RemoteUnwantedMissingFile]: removing file listed as Temporary: duplicati-i0a3297f1d5dd4fd0a0ca266c96bcd7ab.dindex.zip.aes
2020-02-01 20:56:41 -06 - [Warning-Duplicati.Library.Main.Operation.FilelistProcessor-MissingFile]: Missing file: duplicati-ie88fb39038594821a504de1f08b31a96.dindex.zip.aes
2020-02-01 20:56:41 -06 - [Error-Duplicati.Library.Main.Operation.FilelistProcessor-MissingRemoteFiles]: Found 1 files that are missing from the remote storage, please run repair
2020-02-01 20:56:41 -06 - [Error-Duplicati.Library.Main.Operation.BackupHandler-FatalError]: Fatal error
Duplicati.Library.Interface.UserInformationException: Found 1 files that are missing from the remote storage, please run repair
  at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList (Duplicati.Library.Main.BackendManager backend, Duplicati.Library.Main.Options options, Duplicati.Library.Main.Database.LocalDatabase database, Duplicati.Library.Main.IBackendWriter log, System.String protectedfile) [0x001fd] in <8f1de655bd1240739a78684d845cecc8>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify (Duplicati.Library.Main.BackendManager backend, System.String protectedfile) [0x0010b] in <8f1de655bd1240739a78684d845cecc8>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.RunAsync (System.String[] sources, Duplicati.Library.Utility.IFilter filter, System.Threading.CancellationToken token) [0x004ce] in <8f1de655bd1240739a78684d845cecc8>:0 
```

**Comment by ts678** [comment]
> Tonight I'm finding that duplicati is deleting a file in one run and in the next run is looking for that very file. Below are the logs

Thanks. This is the only one with enough information to recognize it, and the other ones are really ancient, whatever they were...

[Error during compact forgot a dindex file deletion, getting Missing file error next run. #4129](https://github.com/duplicati/duplicati/issues/4129) is what happened per the log above.

[2.0.7.100_canary_2023-12-27](https://github.com/duplicati/duplicati/releases/tag/v2.0.7.100-2.0.7.100_canary_2023-12-27) (and upcoming Beta) have the fix, described as:

> Fix missing file error caused by interrupted compact, thanks @Jojo-1000 and @warwickmm

As for the 2.0.2.1 (first Beta) users, anything more to say? If this still happens, a new issue with plenty of details would help debug. Having explained the better-described problem, I'm thinking this should be closed as not actionable without further info. Last call?
