### ISSUE TITLE
Valid SSL certificate is not accepted from Minio S3 backup target when running as LocalSystem

### ISSUE THREAD

**Issue by belidzs** [duplicati/duplicati#2704]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Windows 10 x64
- **Backend**: Amazon S3 (self-hosted Minio 2017-08-05T00:00:53Z with valid LetsEncrypt certificate)

## Description

I have installed Duplicati with the wizard and set up a backup task to a self-hosted, (valid) SSL-protected Minio. I have checked the SSL checkbox and added `s3-ext-forcepathstyle` for compatibility.

The connection test and the actual backup was successful.

Since Duplicati couldn't access some system files I decided to install it as a service. I have followed the guide [here](https://www.duplicati.com/articles/Way-To-Make-A-Backup/): modified the shortcuts and installed the service running `Duplicati.WindowService.exe install`

The service starts up without problem but after importing the settings I was unable to test the connection or to successfully run the backup. I have deleted the settings and manually recreated the job without any success.  

I have also tried adding `accept-any-ssl-certificate`.

It seems that for some reason valid SSL certificates aren't accepted when running as `LocalSystem`. 

## Debug log

```
Amazon.Runtime.AmazonServiceException: A WebException with status SecureChannelFailure was thrown. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RedirectHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.WebExceptionHandler.HandleException(IExecutionContext executionContext, WebException exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest request, IMarshaller`2 marshaller, ResponseUnmarshaller unmarshaller)
   at Amazon.S3.AmazonS3Client.ListObjects(ListObjectsRequest request)
   at Duplicati.Library.Backend.S3Wrapper.ListBucket(String bucketName, String prefix)
   at Duplicati.Library.Backend.S3.List()
   at Duplicati.Server.WebServer.RESTMethods.RemoteOperation.TestConnection(String url, RequestInfo info)
   at Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)
```

**Comment by davegold24** [comment]
I've been troubleshooting similar issue, and the solution I ended up with was to set TLS to version 1.2 only. Edit your job, add the advanced option "allowed-ssl-versions", then save the job; edit the job again, set to TLS12 only, save again. Then go back a third time and "Test Connection"
I posted something on the forum that may help with a process to troubleshoot this, see https://forum.duplicati.com/t/windows-service-minio-with-ssl-error/527/2

Let me know if this helps.

**Comment by belidzs** [comment]
@davegold24 thanks for your valuable input, I did what you have suggested and now SSL connection is working again!

I'm not closing the ticket however because this behavior needs to be at least documented. A fix would be even better.

**Comment by dgold9670** [comment]
I think the only technical issue is that the Duplicati GUI hung when it received a rejection of the TLS version. Otherwise this isn't a github/code issue.

```7 2  0.0074 (0.0007)  S>CV3.1(2)  Alert
    level           fatal
    value           protocol_version
TCP: 192.168.2.216(50002) -> 192.168.2.162(50736) Seq 3457317158.(0) ACK 3280480                                                                                        703 FIN
7    0.0081 (0.0006)  S>C  TCP FIN
TCP: 192.168.2.162(50736) -> 192.168.2.216(50002) Seq 3280480703.(0) ACK 3457317                                                                                        158 FIN
7    0.0085 (0.0004)  C>S  TCP FIN```

Any thoughts on changing this to "rejected TLS version hangs GUI when testing connection"?

**Comment by kenkendk** [comment]
If someone would do a wiki-style How-To on the forum for Minio, I think that would be great:
https://forum.duplicati.com/c/howto

Related thread:
https://forum.duplicati.com/t/windows-service-minio-with-ssl-error/527

And the fix source:
http://blog.quindorian.org/2017/08/diy-cloud-backup-installing-configuring-server.html/

**Comment by dgold9670** [comment]
I'll volunteer. No promise on timeline. 
But since I've been working with Duplicati for just over a week, and I'm really really impressed, its the least I can do to give back.

**Comment by belidzs** [comment]
@dgold9670 Thanks a lot! I literally saw just a minute ago that you have already started a topic on this. To be honest, I thought it's gonna take much longer (due to mentioning the timeline thing), so I decided to go on and write a complete guide on minio with SSL. 

I should've checked before but I didn't, so there's some redundancy now. But hey, I guess the more is better!

Anyways, here is my finished guide written in Markdown which I'm unable to post yet, because apparently it has too many links for a new user like me: https://seafile.belidzs.hu/f/bb7ffe8415294f06add3/

It would be great if this limitation would go away so I could post my version too.

**Comment by dgold9670** [comment]
@belidzs Our are different enough that I think both are valuable. Yours is really well detailed, mine is much more of a cheatsheet. I updated my title to reflect that mine is for Minio on Linux and Duplicati as a Windows service using TLS.
Anyways, my compliments!
