### ISSUE TITLE
VSS failure with snapshot-policy=Off

### ISSUE THREAD

**Issue by robdplatt** [duplicati/duplicati#2720]
I just started testing Duplicati (coming from CrashPlan), and so far I think it's really a great alternative. Having some automation between friends would be nice. 

One issue I'm running into is backing up virtual drives. Backing up my C:\ was no problem. Once I added my F:\ (my DrivePool drive from StableBit) VSS started throwing errors.

From the eventviewer
"The shadow copy of volume F: could not be created because volume F:, which is specified as the location for shadow copy storage, is not an NTFS volume or an error was encountered while trying to determine the file system type of this volume."

I get that VSS can't snap a virtual drive. I don't care. But I don't understand why VSS is even being invoked in the first place. The snapshot-policy=Off.

I'm logged in with full rights and I've ran Duplicati as both normal and elevated (run as admin).

Currently on build 2.0.2.1_beta_2017-08-01

Any help would be greatly appreciated.

Thank you.

**Comment by kenkendk** [comment]
Can you provide a stack trace for the error? From the WebUI, you can go to the "Log" error and see the message. I have no idea why Duplicati would attempt to create a VSS snapshot when you have `--snapshot-policy=off`, but maybe the stack trace can tell where it tries to do this.

**Comment by robdplatt** [comment]
Alphaleonis.Win32.Vss.VssProviderVetoException: Expected provider error. Check the event log for details.
   at Alphaleonis.Win32.Vss.WaitCheckAndReleaseVssAsyncOperation(IVssAsync* pAsync)
   at Alphaleonis.Win32.Vss.VssBackupComponents.DoSnapshotSet()
   at Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Dictionary`2 options)
   at Duplicati.Library.Snapshots.SnapshotUtility.CreateWindowsSnapshot(String[] folders, Dictionary`2 options)
   at Duplicati.Library.Main.Operation.BackupHandler.GetSnapshot(String[] sources, Options options, ILogWriter log)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass16_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

**Comment by kenkendk** [comment]
Looking at that code:
https://github.com/duplicati/duplicati/blob/9141ccfd4155b18aa6a760da4a4cd3f39fa00c03/Duplicati/Library/Main/Operation/BackupHandler.cs#L250

It must be something with the settings not being applied correctly, if you say that the setting is `Off`. If this is from the WebUI, try using the "Export" and then "As commandline" and see if you only see `--snapshot-policy=off`.

**Comment by robdplatt** [comment]
The policy is off for sure. I exported the command and see that it's in there as well. I blanked out my password and took a screenshot of the config --

https://i.gyazo.com/9fa7892eda67bfe3eead54cf9031439e.png
(there was only one reference for 'snapshot' in the text.

and here is a screenshot of my backup options

https://i.gyazo.com/8a16dd3ade9960d24cd9f1d0a9849340.png

There is only 1 backup job.
I have tried leaving it to auto too.

**Comment by robdplatt** [comment]
Like to mention that this happened right out of the gate. Before I started playing around with it. My job initially had C:\ only, which was successful. I went back in and added F:\ (DrivePool), and the errors started. The log and Microsoft event log pointed me to the VSS failure. Which is what resulted in me attempting to set it "Off".

**Comment by robdplatt** [comment]
Update -

Found that by removing my %MSSQL% backup paths, the backup job no longer fails with the snapshot error. If I leave Snapshot off, there is no error (other than locked files). If I set snapshot to On, I get an error creating snapshot on my F:\ but the backup process continues.

I have't had a chance yet to look through your code to see if I could determine why MSSQL backups are failing the entire job.

That said, I did get an error that a file was in use, on my C:, even though I expected VSS to provide access to it. I'll continue looking through your code and testing.

**Comment by robdplatt** [comment]
Guessing it's this... Would it be possible to force it to Auto, instead? I don't mind the snap-shot policy failing on the F:\, but I'd rather the failure not cause a hard fault.

`            if (!commandlineOptions.Keys.Contains("snapshot-policy") || !commandlineOptions["snapshot-policy"].Equals("required", StringComparison.OrdinalIgnoreCase))
            {
                Logging.Log.WriteMessage("Snapshot strategy have to be set to \"required\" when backuping Microsoft SQL Server databases. Changing to \"required\" to continue", Logging.LogMessageType.Warning);
                changedOptions["snapshot-policy"] = "required";
            }`

**Comment by robdplatt** [comment]
Was this ever resolved?

**Comment by drwtsn32x** [comment]
Doesn't look like MSSQLOptions.cs has been modified since September 2017, so I'm guessing nothing was done.

I don't think setting snapshot policy to Auto is a good idea, because snapshots really are required to do live MS SQL backups.  Instead I think your idea of splitting the backup sets is a better way to go.

In the future maybe the snapshot policy can be enhanced to allow different policies per drive letter, something like `--snapshot-policy=C:Required;F:Off;Z:Auto;`  Not sure if there is high enough demand though, especially since a straightforward workaround exists (separate backup jobs).

**Comment by robdplatt** [comment]
> Doesn't look like MSSQLOptions.cs has been modified since September 2017, so I'm guessing nothing was done.

Oops... I didn't even think to look at that. Thank you.

> I don't think setting snapshot policy to Auto is a good idea, because snapshots really are required to do live MS SQL backups. Instead I think your idea of splitting the backup sets is a better way to go.

Agreed.

> In the future maybe the snapshot policy can be enhanced to allow different policies per drive letter, something like `--snapshot-policy=C:Required;F:Off;Z:Auto;` Not sure if there is high enough demand though, especially since a straightforward workaround exists (separate backup jobs).

Maybe the current override could only apply to the drive where the database exists? That would solve the need for needing customizable snapshot policies, for now. Though, I agree it's low priority as workarounds exist.
