### ISSUE TITLE
Recreate Failed, Bug report attached.

### ISSUE THREAD

**Issue by ruifung** [duplicati/duplicati#2731]
Failure when attempting to recreate database from backup.

Bugreport.zip: https://www.dropbox.com/s/mkvkg00evz7j0m0/bugreport.zip?dl=0

Sep 17, 2017 1:35 PM: Failed while executing "Repair" with id: 11c31864-d3ec-4aa0-9eaa-79369ca0cfec

```
System.Exception: The recreate failed, please create a bug-report from this database and send it to the developers for further analysis
   at Duplicati.Library.Main.Database.LocalRecreateDatabase.FindMissingBlocklistHashes(Int64 hashsize, Int64 blocksize, IDbTransaction transaction)
   at Duplicati.Library.Main.Operation.RecreateDatabaseHandler.DoRun(LocalDatabase dbparent, Boolean updating, IFilter filter, NumberedFilterFilelistDelegate filelistfilter, BlockVolumePostProcessor blockprocessor)
   at Duplicati.Library.Main.Operation.RecreateDatabaseHandler.Run(String path, IFilter filter, NumberedFilterFilelistDelegate filelistfilter, BlockVolumePostProcessor blockprocessor)
   at Duplicati.Library.Main.Operation.RepairHandler.RunRepairLocal(IFilter filter)
   at Duplicati.Library.Main.Operation.RepairHandler.Run(IFilter filter)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Repair(IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
```

**Comment by ruifung** [comment]
Would there happen to be any updates on this?

**Comment by ts678** [comment]
Bug report with `.zip` file extension could not be opened in Windows or 7-Zip. Looking at it with a hex editor found `7z` at start.
Renaming it with a `.7z` extension still did not allow 7-Zip to open it. Even if were openable, it takes enormous expertise to study which is why I prefer other ways such as logs or, if necessary, requesting the user to assist doing some sort of directed file checks.

Is issue still of interest, and present currently?

**Comment by ruifung** [comment]
Oh wow. Uh. Well, it's been 7 years since I opened this bug report.

I don't even use duplicati anymore at present, and will not be able to reproduce anything.
I guess I'll close it from my end since It's hardly relevant anymore.
