### ISSUE TITLE
The database has version 7 but the largest supported version is 6.

### ISSUE THREAD

**Issue by raxod502** [duplicati/duplicati#2748]
I get the following error message:

> The database has version 7 but the largest supported version is 6. This is likely caused by upgrading to a newer version and then downgrading. If this is the case, there is likely a backup file of the previous database version in the folder /Users/raxod502/.config/Duplicati.

I've gotten it on several different occasions in the past, actually. But I have never downgraded Duplicati, so it does not seem to be an error on my part. What can I do to debug this?

**Comment by ctoynbee** [comment]
I also have this error. It happened a few day ago.

**Comment by kenkendk** [comment]
I think what happens is that you update the installation, and it starts the new versions. Then "something" goes wrong, and on the next start, Duplicati rejects the updated version and starts the older version, thus performing a "downgrade".

Why it rejects the update is not clear to me. The updated checks that the update folder matches exactly the signed manifest, such that it is not possible to hijack the update or make Duplicati load a tampered version.

If some tool were to modify the update folder in some way, this is what would happen. Do you have any idea as to what could possibly touch the update folder?

**Comment by raxod502** [comment]
I don't know of any tools on my system that mess with arbitrary directories. Is it possible for me to check the update folder for differences manually? Where is it?

**Comment by drewmilizia** [comment]
Same issue here. Please let me know if you need anything from me to troubleshoot.

**Comment by tomhatzer** [comment]
Got the message today too after starting duplicati. It was running smoothly 2 days ago and today it's not working anymore. In the meantime the system was shut down, so nothing could have done any harm. The startup went smooth like always.

**Comment by raxod502** [comment]
@kenkendk It appears that this is a common problem. If people get this problem, what can they do to help find the cause?

**Comment by raxod502** [comment]
For what it's worth, I got it again this morning.

**Comment by AdrienAdB** [comment]
Hi, same problem for me on Mac OS X 10.11.6.
For some reason, the last updater failed (2017-11-22 - 2.0.2.13_canary_2017-11-22) and I didn't pay attention, I was still on previous version (2017-10-20 - 2.0.2.12_canary_2017-10-20).
I went to "About", check for update and update again.
It solved the issue.

**Comment by tomhatzer** [comment]
Somehow my duplicati installation is jumping between version 2.0.1.35_experimental_2016-12-13 and 2.0.1.73_experimental_2017-07-15. When I update it on my own it's running for a few days on version .73 and then suddenly it's back to .35, without me doing anything.

**Comment by AdrienAdB** [comment]
Problem went back after a few days.
Today, I moved all unnecessary .sqlite and .backup files from ~/.config/Duplicati/ to another directory.
I only kept Duplicati-server.sqlite and XXXXXXX.sqlite (my current backup).
I updated Duplicati to the latest version.
Let's see in few days if it is solved.....

<pre>
The database has version 7 but the largest supported version is 6. This is likely caused by upgrading to a newer version and then downgrading. If this is the case, there is likely a backup file of the previous database version in the folder /Users/adrien/.config/Duplicati.
</pre>

**Comment by florianklumb** [comment]
So I am getting this error as well. I tried what @AdrienAdB suggested but it doesn't work for me. So I have to enter all my data again? Hopefully, this is gonna work. If not what can I do? In a way this is a red flag for me in what backup software should never ever do: shut out the user from their backups and settings.

**Comment by raxod502** [comment]
@kenkendk Is this issue on the roadmap? It seems like a common bug and a very very bad one.

**Comment by florianklumb** [comment]
I tried to setup the configuration by adding the path on my external hard drive, repairing and thus creating the local database and then overwriting it with the old sql lite db. And now I also get the error "The database has version 7 but the largest supported version is 6."

I am pretty angry about this. I think @raxod502 is right. But I would go further: IMO, downloads to Duplicati should disabled until this bug is fixed. I will certainly stop using it immediately.

**Comment by Nitonio** [comment]
Seem to have found a way around this on a Mac, at least for now. 

I deleted all the files in ~/.config/Duplicati/ except backup_xxxxxx.sqlite (my latest backup) as described by @AdrienAdB above. This allowed Duplicati to start but without any configured backups. 

Closed Duplicati, opened backup_xxxxxx.sqlite in TextEdit and copied the contents into the newly created Duplicati-server.sqlite file. Started Duplicati again, repaired the database and things seem to be back to normal. 

Agree with @florianklumb, this needs fixing asap for Duplicati to stay useful.
Thanks @raxod502 for linking this thread to my post at the Duplicati forum.

**Comment by warwickmm** [comment]
This is peculiar indeed.  However, it's quite difficult to replicate and debug.  Could one possibility be that an exception is caught when attempting to enumerate the update versions?  We then enter the empty `catch` [here](https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/SQLiteHelper/DatabaseUpgrader.cs#L170), and hence the `upgrades` collection does not contain the expected number of elements.  We then encounter the above described exception [here](https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/SQLiteHelper/DatabaseUpgrader.cs#L226).

Are most of the users encountering this issue are on Macs?  Could be a coincidence, but any information about users' setups would be helpful.

**Comment by raxod502** [comment]
I'm running macOS 10.11.6 El Capitan.

**Comment by jpdillingham** [comment]
I just experienced this bug and thought I'd share my symptoms and resolution.

I was prompted via the web interface to update, which I did.  After a while I was prompted again, and not thinking I again updated.  A little while later I was prompted a third time, and getting suspicious I restarted the service and the application failed to start, producing no errors.

I started the server application from the command line: 

```
C:\Users\Administrator>"C:\Program Files\Duplicati 2\Duplicati.Server.exe"
A serious error occurred in Duplicati: System.Exception: Failed to create, open or upgrade the database.
Error message:
The database has version 6 but the largest supported version is 4.

This is likely caused by upgrading to a newer version and then downgrading.
If this is the case, there is likely a backup file of the previous database version in the folder C:\Users\Administrator\AppData\Local\Duplicati.
   at Duplicati.Server.Program.GetDatabaseConnection(Dictionary`2 commandlineOptions)
   at Duplicati.Server.Program.RealMain(String[] _args)
```

This seems consistent with the narrative above, and perhaps if I would have upgraded a third time before restarting the service I wouldn't have been left in this state.

To fix the problem I took backups of both `%localappdata%\Duplicati` and the application directory `Program Files\Duplicati`, then installed the latest version from the website using the msi installer.  The application initially failed to start after the installation was complete:

```
C:\Users\Administrator>"C:\Program Files\Duplicati 2\Duplicati.Server.exe"
A serious error occurred in Duplicati: System.IO.FileNotFoundException: Could not load file or assembly 'CoCoL, Version=1.5.0.24305, Culture=neutral, Publ
icKeyToken=0983de3c914beeaa' or one of its dependencies. The system cannot find the file specified.
File name: 'CoCoL, Version=1.5.0.24305, Culture=neutral, PublicKeyToken=0983de3c914beeaa'
   at Duplicati.Library.UsageReporter.Reporter.Initialize()
   at Duplicati.Library.UsageReporter.Reporter.SetReportLevel(Nullable`1 maxreportlevel, Boolean disable)
   at Duplicati.Server.Program.StartOrStopUsageReporter()
   at Duplicati.Server.Program.RealMain(String[] _args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Crash!
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not loa
d file or assembly 'CoCoL, Version=1.5.0.24305, Culture=neutral, PublicKeyToken=0983de3c914beeaa' or one of its dependencies. The system cannot find the f
ile specified.
   at Duplicati.Library.UsageReporter.Reporter.ShutDown()
   at Duplicati.Server.Program.RealMain(String[] _args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Duplicati.Library.AutoUpdater.UpdaterManager.RunMethod(MethodInfo method, String[] args)

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'CoCoL, Version=1.5.0.24305, Culture=neutral, PublicKeyToken=0983de3
c914beeaa' or one of its dependencies. The system cannot find the file specified.
   at Duplicati.Library.AutoUpdater.UpdaterManager.RunMethod(MethodInfo method, String[] args)
   at Duplicati.Library.AutoUpdater.UpdaterManager.<>c__DisplayClass58_1.<RunFromMostRecentSpawn>b__0()
   at Duplicati.Library.AutoUpdater.UpdaterManager.WrapWithUpdater(AutoUpdateStrategy defaultstrategy, Action wrappedFunction)
   at Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecentSpawn(MethodInfo method, String[] cmdargs, AutoUpdateStrategy defaultstrategy)
   at Duplicati.Server.Program.Main(String[] args)
```

I then deleted the entire contents of the `Program Files\Duplicati` folder and did a repair installation using the downloaded msi.  The application succeeded in starting following this, and I then stopped it and copied the contents of `%localappdata%\Duplicati` and `Program Files\Duplicati\data` that I had backed up earlier.  The application started successfully and my previous configuration was retained.

Hope this helps someone!

**Comment by ts678** [comment]
> Then "something" goes wrong, and on the next start, Duplicati rejects the updated version and starts the older version, thus performing a "downgrade".

The link just above is one example of a "something" where a Windows install process pollutes the installed folder with new files.

I think user can also do this by inadvertently doing things like adding files into the current directory instead of using a full path.
Possibilities (not all verified) include a log file that was requested, something that a script that had been configured created, etc.

https://github.com/duplicati/duplicati/blob/e7c191389cdb3fdb9500d83ebd06e0ae99634fd1/Duplicati/Library/AutoUpdater/UpdaterManager.cs#L572-L572

contains a variety of possible complaints. The question is where to see them? In GUI, answer seems to be About --> Show log:

![image](https://github.com/duplicati/duplicati/assets/40771998/ae2e600e-5cde-489b-8b1a-cf99974e2ac4)

If that doesn't work, it takes more effort:

Please look at the folder with "lost" update. Additions should be especially easy to see, especially if at top of folder. Sort by date.

Exactly where your update might have been installed (then damaged) is unfortunately variable. There are some spots named in:

[Downgrading / reverting to a lower version](https://forum.duplicati.com/t/downgrading-reverting-to-a-lower-version/3393)

For the most serious study, you can move the damaged update into a subfolder, install again. Compare the two to see damage.

From a code enhancement point of view, Duplicati could possibly find a way to inform the user better about a damaged update.
GUI could maybe require an absolute path for more things (but that could be unwanted). Or maybe just forgive any excess files.
Missing Duplicati files are a more serious hazard, IMO, although I suppose extras that have any effect (e.g. config files) may hurt.

**Comment by kenkendk** [comment]
This was caused by the updater system used, which is no longer active
