### ISSUE TITLE
Fatal error after last update, System.ArgumentException: Object must be a root directory ("C:\") or a drive letter ("C"). 

### ISSUE THREAD

**Issue by Athep** [duplicati/duplicati#2786]
After last update, Duplicati - 2.0.2.9_canary_2017-10-01

Fatal error
System.ArgumentException: Object must be a root directory ("C:\") or a drive letter ("C").
   at System.IO.DriveInfo..ctor(String driveName)
   at Duplicati.Library.Backend.File.GetDrive()
   at Duplicati.Library.Backend.File.get_Quota()
   at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)
   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)

**Comment by tygill** [comment]
I'm guessing this is caused when a backup is being made to a UNC or other non-drive letter path on Windows (which the DriveInfo class doesn't support). In this case, the File backend should be pre-emptively detecting this, or catching this exception, and returning an unknown quota, or falling back to [GetFreeDiskSpaceEx](https://stackoverflow.com/questions/2050343/programmatically-determining-space-available-from-unc-path).
