### ISSUE TITLE
Error making request with Error Code SignatureDoesNotMatch and Http Status Code Forbidden. No further error information was returned by the service.

### ISSUE THREAD

**Issue by starrychloe** [duplicati/duplicati#2828]
- [x] I have searched open and closed issues for duplicates.
https://github.com/duplicati/duplicati/issues?utf8=%E2%9C%93&q=is%3Aissue%20Error%20making%20request%20with%20Error%20Code%20SignatureDoesNotMatch%20and%20Http%20Status%20Code%20Forbidden.%20No%20further%20error%20information%20was%20returned%20by%20the%20service.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Windows 8.1
- **Backend**: S3 compatiable - DreamHost DreamObjects

## Description
This popup keeps appearing, both in the system tray and in the web interface. It has 'Show' and 'Dismiss', but the 'Show' button only goes to the logs page and doesn't show any errors that match. The backup never finishes! It has "Next Scheduled Task..." in the progress bar, which is clear (0% progress). It's been running for 2 weeks and it hasn't completed a full backup yet! There is a last run time and backup size 111GB, but my files are _at least_ 173GB and 598k files! I have 0 confidence in Duplicati at this point!

Error making request with Error Code SignatureDoesNotMatch and Http Status Code Forbidden. No further error information was returned by the service.

## Steps to reproduce
1. Run backup

- **Actual result**:
Error message

- **Expected result**:
All files backed up. The size and count of the files matches ALT-ENTER of the folder in Windows Explorer. The last backup time shows a recent time and date.

## Screenshots
![image](https://user-images.githubusercontent.com/1039276/31723901-2289e5d8-b3ee-11e7-82c0-994f633bf233.png)

After you click 'Show'
![image](https://user-images.githubusercontent.com/1039276/31724044-9c4ca3a6-b3ee-11e7-9ee9-8eca4a3bf4f3.png)

## Debug log
There is no log file! I asked the forum and they said all errors are in a SQLITE3 database, which is locked from reading. You should really, really have a log file! Just use a default filter to exclude it.

**Comment by starrychloe** [comment]
I found these errors in the log page much later. I don't know why they weren't there before.

```
Oct 18, 2017 2:12 PM: Failed while executing "Backup" with id: 1
Amazon.S3.AmazonS3Exception: Error making request with Error Code SignatureDoesNotMatch and Http Status Code Forbidden. No further error information was returned by the service. ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (403) Forbidden. ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RedirectHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes)
   at Duplicati.Library.Main.Operation.BackupHandler.RunMainOperation(ISnapshotService snapshot, BackendManager backend)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass16_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
```


and


```
Oct 18, 2017 2:12 PM: Fatal error
{"ClassName":"Amazon.S3.AmazonS3Exception","Message":"Error making request with Error Code SignatureDoesNotMatch and Http Status Code Forbidden. No further error information was returned by the service.","Data":null,"InnerException":{"ClassName":"Amazon.Runtime.Internal.HttpErrorResponseException","Message":"The remote server returned an error: (403) Forbidden.","Data":null,"InnerException":{"ClassName":"System.Net.WebException","Message":"The remote server returned an error: (403) Forbidden.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.Net.HttpWebRequest.GetResponse()\r\n   at Amazon.Runtime.Internal.HttpRequest.GetResponse()","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nGetResponse\nSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxxxxxxxxxxx\nSystem.Net.HttpWebRequest\nSystem.Net.WebResponse GetResponse()","HResult":-2146233079,"Source":"System","WatsonBuckets":null},"HelpURL":null,"StackTraceString":"   at Amazon.Runtime.Internal.HttpRequest.GetResponse()\r\n   at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext)\r\n   at Amazon.Runtime.Internal.RedirectHandler.InvokeSync(IExecutionContext executionContext)\r\n   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext)\r\n   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeSync(IExecutionContext executionContext)\r\n   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nGetResponse\nAWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxxxxxxxxxxxxxx\nAmazon.Runtime.Internal.HttpRequest\nAmazon.Runtime.Internal.Transform.IWebResponseData GetResponse()","HResult":-2146233088,"Source":"AWSSDK.Core","WatsonBuckets":null,"Response":{"StatusCode":"Forbidden","IsSuccessStatusCode":false,"ContentType":"application/xml","ContentLength":230,"ResponseBody":{}}},"HelpURL":null,"StackTraceString":"   at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes)\r\n   at Duplicati.Library.Main.Operation.BackupHandler.RunMainOperation(ISnapshotService snapshot, BackendManager backend)\r\n   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)\r\n   at Duplicati.Library.Main.Controller.<>c__DisplayClass16_0.<Backup>b__0(BackupResults result)\r\n   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)\r\n   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)\r\n   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nHandleFilesystemEntry\nDuplicati.Library.Main, Version=2.0.2.1, Culture=neutral, PublicKeyToken=null\nDuplicati.Library.Main.Operation.BackupHandler\nBoolean HandleFilesystemEntry(Duplicati.Library.Snapshots.ISnapshotService, Duplicati.Library.Main.BackendManager, System.String, System.IO.FileAttributes)","HResult":-2146233088,"Source":"Duplicati.Library.Main","WatsonBuckets":null,"errorCode":"SignatureDoesNotMatch","errorType":"Sender","requestId":"tx000000000000000xxxxxxxxxxxxxxxxxxxxxxxxxx-default","statusCode":"Forbidden","AmazonId2":"19e36002-default-default","ResponseBody":null}
```

**Comment by starrychloe** [comment]
Hey have you fixed this yet? I'm going to have to uninstall Duplicati because it _won't back up my files_!

**Comment by rjrudman** [comment]
Having the same issue here. Though, @starrychloe - you do realize this is a free, open source project? You can't expect them to have fixed it in *less than a day*.

**Comment by kenkendk** [comment]
I do not have a DreamHosts account so I cannot test it. But the error does mention something with the signature not being correct.

You can try setting the advanced option `--s3-ext-signatureversion=3` to use signature v3. Other reasons could be a clock that is out-of-sync with DreamHosts.

This article suggests that it "just works":
https://help.dreamhost.com/hc/en-us/articles/215987857-Duplicati

**Comment by warwickmm** [comment]
Closing this due to lack of activity.
