### ISSUE TITLE
Duplicati 2.0.2.1 not using VSS 

### ISSUE THREAD

**Issue by naelr** [duplicati/duplicati#2868]
After being left out in the cold by crashplan.. I decided to go looking for something better and I came across Duplicati.  I am very pleased except for this issue. 

I am running Duplicait 2.0.2.1 on a windows 7 computer.  I am trying to backup the Quickbooks Point of Sale directory to an offsite location.   I have searched all over and other threads having the same issue seem to be very old.  I have rebooted the computer... to ensure no one is connected to the file... yes it is a shared Quickbooks file but I am using another backup solution that is able to utilize the VSS in windows 7 to backup the same files somewhere else. I have snapshot policy set to Auto 
 both in global setting and on the backup setting itself.   I have followed these instructions to make Duplicati run at startup as administrative user.

https://forum.duplicati.com/t/migrating-from-user-to-service-install-on-windows/660

no matter what I do I keep getting these errors on the same 2 files 

```
Failed to process path: C:\Users\Public\Documents\Intuit\QuickBooks Point of Sale 11.0\Data\HeritageFarmMuseum\qbpos.log
System.IO.IOException: The process cannot access the file 'C:\Users\Public\Documents\Intuit\QuickBooks Point of Sale 11.0\Data\HeritageFarmMuseum\qbpos.log' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Duplicati.Library.Snapshots.SystemIOWindows.FileOpenRead(String path)
   at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes)
```

and on the other file

```
Failed to process path: C:\Users\Public\Documents\Intuit\QuickBooks Point of Sale 11.0\Data\HeritageFarmMuseum\qbpos.db
System.IO.IOException: The process cannot access the file 'C:\Users\Public\Documents\Intuit\QuickBooks Point of Sale 11.0\Data\HeritageFarmMuseum\qbpos.db' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Duplicati.Library.Snapshots.SystemIOWindows.FileOpenRead(String path)
   at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes)
```

I appreciate any help you can give me.

**Comment by davegold24** [comment]
@naelr This is better handled as a support item at forum.duplicati.com

Answer is most likely that you need Virtual C++2015 redistributable
Make sure the version you download matches your bit-version (32 or 64-bit) of your version of Windows.

See https://github.com/duplicati/duplicati/wiki/FAQ#user-content-windows-vss

Make sure that you Set Snapshot policy to required, then that'll verify that VSS is properly being used; if it isn't, the job will fail.

**Comment by naelr** [comment]
@davegold24 

Before I post I will try that ... I have searched until I am blue in the face and never read (or realized in my haste I read) this package was needed.  Thank you very much I will test this out this evening.

**Comment by davegold24** [comment]
@naelr no worries. Please do update this ticket so we know that it works!

**Comment by naelr** [comment]
I couldn't wait and remoted the computer, after install of the C++ redistributable is installed is a reboot necessary?

**Comment by naelr** [comment]
I have just tested after a reboot and that seems to have fixed the problem... thank you so much!
