### ISSUE TITLE
Restore, UNC path

### ISSUE THREAD

**Issue by kongaa** [duplicati/duplicati#2906]
- **Duplicati version**: 2.0.2.1
- **Operating system**: Windows 10 Pro
- **Backend**: Microsoft OneDrive for Business

## Description
When using more than one UNC path as source, restore throws an Object reference not set to an instance of an object error.

## Steps to reproduce
1. Add backup
2. Set storage type to Microsoft OneDrive for Business
3. Source data added using the Add path option as multiple unc paths like \\mydrive\myfolder1\
4. backup scheduled and Options set
5. Backup started and completed with one warning, see below.
6. Restore selected
7. Restore source set as above created backup.
8. Clicking Next generates error, see error details below

Backup completed warning (yes I know. There is no warning but Duplicati still shows warning message):
ParsedResult: Success
EndTime: 22/11/2017 09.28.08
BeginTime: 22/11/2017 09.10.09
Duration: 00:17:59.3606898
Messages: [
    No remote filesets were deleted
]
Warnings: []
Errors: []

Restore log
System.ObjectDisposedException: Cannot write to a closed TextWriter.
   at System.IO.__Error.WriterClosed()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Duplicati.Library.Utility.FilterExpression.FilterEntry..ctor(String filter)
   at Duplicati.Library.Utility.FilterExpression.<>c.<.ctor>b__10_0(String n)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Duplicati.Library.Utility.FilterExpression.Compact(IEnumerable`1 items)
   at Duplicati.Library.Utility.FilterExpression..ctor(IEnumerable`1 filter, Boolean result)
   at Duplicati.Library.Main.Operation.ListFilesHandler.Run(IEnumerable`1 filterstrings, IFilter compositefilter)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.List(IEnumerable`1 filterstrings, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
   at Duplicati.Server.WebServer.RESTMethods.Backup.SearchFiles(IBackup backup, String filterstring, RequestInfo info)
   at Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Duplicati.Library.Utility.FilterExpression.FilterEntry..ctor(String filter)
   at Duplicati.Library.Utility.FilterExpression.<>c.<.ctor>b__10_0(String n)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Duplicati.Library.Utility.FilterExpression.Compact(IEnumerable`1 items)
   at Duplicati.Library.Utility.FilterExpression..ctor(IEnumerable`1 filter, Boolean result)
   at Duplicati.Library.Main.Operation.ListFilesHandler.Run(IEnumerable`1 filterstrings, IFilter compositefilter)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.List(IEnumerable`1 filterstrings, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

**Comment by ts678** [comment]
Not reproducible currently. I tested to Local folder Destination. Source was two folders on one share, two files on another.
Quite possibly something was fixed. This issue will close eventually unless some other information becomes available on it.
