### ISSUE TITLE
Arithmetic operation resulted in an overflow.

### ISSUE THREAD

**Issue by sffetlio** [duplicati/duplicati#2918]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Windows 10 Build 16299
- **Backend**: Filesystem

## Description

Backup was running fine for couple of months, then one day it started showing errors. The files that cause the errors are newly added.

## Debug log

```
Errors affected 29 file(s)

Warnings: [
    Failed to process path: D:\xxxxxxxx\node_modules\pg\node_modules\.bin\semver => Arithmetic operation resulted in an overflow.,
    Failed to process path: D:\xxxxxxxx\node_modules\nsp\node_modules\agent-base\node_modules\.bin\semver => Arithmetic operation resulted in an overflow.,
    Failed to process path: D:\xxxxxxxx\node_modules\nsp\node_modules\.bin\rc => Arithmetic operation resulted in an overflow.,
    Failed to process path: D:\xxxxxxxx\node_modules\nsp\node_modules\.bin\semver => Arithmetic operation resulted in an overflow.,
    Failed to process path: D:\xxxxxxxx\node_modules\loopback-connector-postgresql\node_modules\.bin\slt-globalize => Arithmetic operation resulted in an overflow.,
...
]
```

```
Failed to process path: D:\xxxxxxxx\node_modules\.bin\yaml2json
System.OverflowException: Arithmetic operation resulted in an overflow.
   at Alphaleonis.Win32.Filesystem.Device.GetLinkTargetInfoCore(SafeFileHandle safeHandle)
   at Alphaleonis.Win32.Filesystem.File.GetLinkTargetInfoCore(KernelTransaction transaction, String path, PathFormat pathFormat)
   at Duplicati.Library.Snapshots.NoSnapshotWindows.GetSymlinkTarget(String file)
   at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes)

Failed to process path: D:\xxxxxxxx\node_modules\.bin\uuid
System.OverflowException: Arithmetic operation resulted in an overflow.
   at Alphaleonis.Win32.Filesystem.Device.GetLinkTargetInfoCore(SafeFileHandle safeHandle)
   at Alphaleonis.Win32.Filesystem.File.GetLinkTargetInfoCore(KernelTransaction transaction, String path, PathFormat pathFormat)
   at Duplicati.Library.Snapshots.NoSnapshotWindows.GetSymlinkTarget(String file)
   at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes)
...
and a lot more like these
```

**Comment by sffetlio** [comment]
I believe this was related to #2171. I removed the node_modules and run npm install from cmd and now backup completes without errors.

Maybe also related: https://github.com/Microsoft/WSL/issues/353
