### ISSUE TITLE
System.InvalidOperationException: Duplicati.Library.Modules.Builtin.ConsolePasswordInput.ReadPassphraseFromConsole

### ISSUE THREAD

**Issue by jarmo** [duplicati/duplicati#2923]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.13_canary_2017-11-22
- **Operating system**: Windows 10 Professional
- **Backend**: Local disk

## Description

Running command like this produces an exception and does not end up with a successful backup:
```
c:\duplicati\Duplicati.CommandLine.exe backup "j:/test" "c:\bin\\" --dbpath="j:/test-db" --passphrase="123456"
Backup started at 10.12.2017 13:11.05

Enter encryption passphrase:
System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read.
   at System.Console.ReadKey(Boolean intercept)
   at Duplicati.Library.Modules.Builtin.ConsolePasswordInput.ReadPassphraseFromConsole(Boolean confirm)
   at Duplicati.Library.Modules.Builtin.ConsolePasswordInput.Configure(IDictionary`2 commandlineOptions)
   at Duplicati.Library.Main.Controller.SetupCommonOptions(ISetCommonOptions result, String[]& paths, IFilter& filter)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.CommandLine.Commands.Backup(TextWriter outwriter, Action`1 setup, List`1 args, Dictionary`2 options, IFilter filter)
   at Duplicati.CommandLine.Program.RunCommandLine(TextWriter outwriter, TextWriter errwriter, Action`1 setup, String[] args)
```

**Comment by tygill** [comment]
I'm now hitting this with 2.0.3.6_canary_2018-04-23 as well. Attempting to run from the GUI fails as well.

**Comment by jarmo** [comment]
I'm still hitting this or similar error when running without `--passphrase` argument so that passphrase would be asked via console. If adding that argument with the actual passphrase then everything works.

**Comment by alexlauerman** [comment]
I am getting this on  2.0.3.3_beta_2018-04-02 via the command line. I couldn't fix it by passing a CLI argument, but setting an environment variable fixed it.

`set PASSPHRASE=<pass>`

**Comment by ts678** [comment]
Not reproducible in current release. Maybe something changed. Any other recent findings? Testing various combinations got me:

```
--passphrase=password   --disable-module=console-password-input RESULT
Y                       Y                                       Fine
Y                       N                                       Fine
N                       N                                       Prompts for Enter and Confirm
N                       Y                                       PassphraseChangeNotSupported
```

**Comment by alexlauerman** [comment]
I think it would be safe to assume this issue is fixed if it's been quiet for this long. I feel like it's safe to close this based on that.
