### ISSUE TITLE
System.NullReferenceException on new machine trying to create the local database with the repair command

### ISSUE THREAD

**Issue by helgeklein** [duplicati/duplicati#2934]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Windows 10 Pro 1709 (Fall Creator's Update)
- **Backend**: Amazon S3

## Description

Recently I built a new PC. I transferred the data disk over from the old machine on which I had used Duplicati successfully for a long time. So all the files are exactly on the same paths they were on the old machine. I want to back up the new machine to the same remote repository I used from the old machine.

The local database is not located on the disk I transferred from the old machine. I understand that I need to recreate the local database from the remote data before I can back up data from the new machine. So I ran the repair command on the command line, which kept Duplicati busy for 20-30 minutes, during which it wrote 1.1 GB to the .sqlite file. Then it crashed with the following output:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Duplicati.Library.Main.Volumes.VolumeReaderBase.<ReadBlocklist>d__8.MoveNext()
   at Duplicati.Library.Main.Database.LocalRecreateDatabase.UpdateBlockset(String hash, IEnumerable`1 blocklisthashes, IDbTransaction transaction)
   at Duplicati.Library.Main.Operation.RecreateDatabaseHandler.DoRun(LocalDatabase dbparent, Boolean updating, IFilter filter, NumberedFilterFilelistDelegate filelistfilter, BlockVolumePostProcessor blockprocessor)
   at Duplicati.Library.Main.Operation.RecreateDatabaseHandler.Run(String path, IFilter filter, NumberedFilterFilelistDelegate filelistfilter, BlockVolumePostProcessor blockprocessor)
   at Duplicati.Library.Main.Operation.RepairHandler.RunRepairLocal(IFilter filter)
   at Duplicati.Library.Main.Operation.RepairHandler.Run(IFilter filter)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Repair(IFilter filter)
   at Duplicati.CommandLine.Commands.Repair(TextWriter outwriter, Action`1 setup, List`1 args, Dictionary`2 options, IFilter filter)
   at Duplicati.CommandLine.Program.RunCommandLine(TextWriter outwriter, TextWriter errwriter, Action`1 setup, String[] args)
```

Before the NullReferenceException shown above there were the following two additional messages (also see the attached log file below):

```
Zip archive appears to have a broken Central Record Header, switching to stream mode => System.NotSupportedException: Unknown header: 434398439
   at SharpCompress.Common.Zip.ZipHeaderFactory.ReadHeader(UInt32 headerBytes, BinaryReader reader, Boolean zip64)
   at SharpCompress.Common.Zip.SeekableZipHeaderFactory.<ReadSeekableHeader>d__3.MoveNext()
   at SharpCompress.Archives.Zip.ZipArchive.<LoadEntries>d__16.MoveNext()
   at SharpCompress.LazyReadOnlyCollection`1.LazyLoader.MoveNext()
   at Duplicati.Library.Compression.FileArchiveZip.LoadEntryTable()
Zip archive appears to have broken records, returning the 78 records that could be recovered => SharpCompress.Compressors.Deflate.ZlibException: Bad state (invalid block type)
   at SharpCompress.Compressors.Deflate.InflateManager.Inflate(FlushType flush)
   at SharpCompress.Compressors.Deflate.ZlibBaseStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at SharpCompress.Common.EntryStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at SharpCompress.Common.EntryStream.SkipEntry()
   at SharpCompress.Common.EntryStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at Duplicati.Library.Compression.FileArchiveZip.LoadEntryTable()
```

## Steps to reproduce

I do not think this can easily be reproduced.

- **Actual result**:
Duplicati crashed
- **Expected result**:
Duplicati recreates the local DB

## Debug log

Debug log attached. Please note that it does not contain the System.NullReferenceException stack trace. Apparently, it crashed before that could be written.

[duplicati.log](https://github.com/duplicati/duplicati/files/1577635/duplicati.log)

**Comment by ts678** [comment]
> I understand that I need to recreate the local database from the remote data before I can back up data from the new machine.

Moving the old database to the new machine is possible, if the intent is to keep basically the same backup on the new machine.

> I do not think this can easily be reproduced.

I wonder if it worked on the next try, unlike in above-linked issue where an operation that was working began repeated failures.
The comments there might apply somewhat here too. I'm not sure how much troubleshooting can be done after so much time.

A specific point would be whether the found-as-bad `.zip` file remained bad, e.g. was failure upload, download, or intermittent?
Not really expecting further history after so long, but those are the sorts of things that maybe could have been asked in 2017...


Thank you for the log of the lead-up to fail (and off-topic, thank you for DiskLED and SetACL which I use and used respectively).

Unless this issue happens currently, I'm not sure if it's actionable at this point. It will close automatically if no further posts occur.
