### ISSUE TITLE
Segfault when attempting to delete a backup

### ISSUE THREAD

**Issue by njfox** [duplicati/duplicati#2938]
I am getting a segmentation fault whenever I attempt to delete a backup job, including both the remote and local files. Here is the error from systemd:

```
$ systemctl --user status duplicati
● duplicati.service - Duplicati
   Loaded: loaded (/usr/lib/systemd/user/duplicati.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2017-12-22 20:55:36 EST; 24s ago
  Process: 2361 ExecStart=/usr/bin/mono /opt/duplicati-latest/Duplicati.GUI.TrayIcon.exe --webservice-port=8200 (code=exited, status=134)
 Main PID: 2361 (code=exited, status=134)

Dec 22 20:55:35 arch mono[2361]: #6  0x00007ffd6c060d90 in  ()
Dec 22 20:55:35 arch mono[2361]: #7  0x0000000000000000 in  ()
Dec 22 20:55:35 arch mono[2361]: =================================================================
Dec 22 20:55:35 arch mono[2361]: Got a SIGSEGV while executing native code. This usually indicates
Dec 22 20:55:35 arch mono[2361]: a fatal error in the mono runtime or one of the native libraries
Dec 22 20:55:35 arch mono[2361]: used by your application.
Dec 22 20:55:35 arch mono[2361]: =================================================================
Dec 22 20:55:36 arch systemd-coredump[2883]: Process 2369 (mono-sgen) of user 1000 dumped core.
                                             
                                             Stack trace of thread 2858:
                                             #0  0x00007ff40d2c1860 raise (libc.so.6)
                                             #1  0x00007ff40d2c2ec9 abort (libc.so.6)
                                             #2  0x0000559dc7ca870d n/a (mono-sgen)
                                             #3  0x0000559dc7d0fef1 n/a (mono-sgen)
                                             #4  0x00007ff3a9a959ac COMP_CTX_free (libcrypto.so.1.1)
                                             #5  0x0000559dc7caa86b n/a (mono-sgen)
                                             #6  0x00007ff39c002005 n/a (n/a)
                                             #7  0x0000000000000000 n/a (n/a)
Dec 22 20:55:36 arch systemd[1265]: duplicati.service: Main process exited, code=exited, status=134/n/a
Dec 22 20:55:36 arch systemd[1265]: duplicati.service: Failed with result 'exit-code'.
```
System is Arch Linux running the latest canary build 2.0.2.14_canary_2017-12-22 from AUR.

**Comment by Pectojin** [comment]
Does this still happen? 

As far as I could tell Duplicati doesn't use any unsafe operations that would cause a segfault (except for in the 7Z library). So segfaults may just be an issue in the mono binary that goes away after reinstalling/updating mono.

**Comment by njfox** [comment]
Looks like the problem is gone on the latest canary build. I'm not sure what would've caused it before--I was surprised to see a segfault in a C# app as well.
