### ISSUE TITLE
System.OverflowException: Negating the minimum value of a twos complement number is invalid. 

### ISSUE THREAD

**Issue by OronDF343** [duplicati/duplicati#2994]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.17_canary_2018-01-23
- **Operating system**: Windows 7 Pro x64
- **Backend**: Local

## Description

Every since updating to the new version, I can't back up anymore. See the first log below. Retrying results in the second log, and resolving that issue (repair/recreate db or delete files) results in the first one again...
I have a feeling that the log isn't telling the full story, but I have yet to find any way to directly read duplicati's debug log anywhere in the documentation.

P.S. Some operations can't be cancelled (such as "create bug report")
P.P.S. Is multi-threading being considered? Duplicati is really slow because it uses just a single thread at 100%...

## Debug log

Log 1:
```
Operation Put with file duplicati-id0c64c64036643f2841f428e855ebbce.dindex.zip.aes attempt 1 of 5 failed with message: Negating the minimum value of a twos complement number is invalid.
System.OverflowException: Negating the minimum value of a twos complement number is invalid.

   at System.Math.AbsHelper(Int64 value)

   at Duplicati.Library.Utility.Utility.FormatSizeString(Int64 size)

   at Duplicati.Library.Main.BackendManager.DoPut(FileEntryItem item)

   at Duplicati.Library.Main.BackendManager.ThreadRun()

Renaming "duplicati-id0c64c64036643f2841f428e855ebbce.dindex.zip.aes" to "duplicati-i8d6f25bbee3541518c42c2adea985544.dindex.zip.aes"

Operation Put with file duplicati-i344e1d7c11a74fe39ddcc3e76bc877c3.dindex.zip.aes attempt 1 of 5 failed with message: Negating the minimum value of a twos complement number is invalid.
System.OverflowException: Negating the minimum value of a twos complement number is invalid.

   at System.Math.AbsHelper(Int64 value)

   at Duplicati.Library.Utility.Utility.FormatSizeString(Int64 size)

   at Duplicati.Library.Main.BackendManager.DoPut(FileEntryItem item)

   at Duplicati.Library.Main.BackendManager.ThreadRun()

Renaming "duplicati-i344e1d7c11a74fe39ddcc3e76bc877c3.dindex.zip.aes" to "duplicati-iaab8e9917cee42179895afbdc532fbd9.dindex.zip.aes"

Operation Put with file duplicati-iaab8e9917cee42179895afbdc532fbd9.dindex.zip.aes attempt 2 of 5 failed with message: Negating the minimum value of a twos complement number is invalid.
System.OverflowException: Negating the minimum value of a twos complement number is invalid.

   at System.Math.AbsHelper(Int64 value)

   at Duplicati.Library.Utility.Utility.FormatSizeString(Int64 size)

   at Duplicati.Library.Main.BackendManager.DoPut(FileEntryItem item)

   at Duplicati.Library.Main.BackendManager.ThreadRun()

Renaming "duplicati-iaab8e9917cee42179895afbdc532fbd9.dindex.zip.aes" to "duplicati-i5824dd34c3964268b612237561ff7ecf.dindex.zip.aes"

Operation Put with file duplicati-i5824dd34c3964268b612237561ff7ecf.dindex.zip.aes attempt 3 of 5 failed with message: Negating the minimum value of a twos complement number is invalid.
System.OverflowException: Negating the minimum value of a twos complement number is invalid.

   at System.Math.AbsHelper(Int64 value)

   at Duplicati.Library.Utility.Utility.FormatSizeString(Int64 size)

   at Duplicati.Library.Main.BackendManager.DoPut(FileEntryItem item)

   at Duplicati.Library.Main.BackendManager.ThreadRun()

Renaming "duplicati-i5824dd34c3964268b612237561ff7ecf.dindex.zip.aes" to "duplicati-i30d20f9ad50c4b54afc0cf645fbaa74c.dindex.zip.aes"

Operation Put with file duplicati-iedac4ef4aa5e49c0bc3755341a055fc4.dindex.zip.aes attempt 1 of 5 failed with message: Negating the minimum value of a twos complement number is invalid.
System.OverflowException: Negating the minimum value of a twos complement number is invalid.

   at System.Math.AbsHelper(Int64 value)

   at Duplicati.Library.Utility.Utility.FormatSizeString(Int64 size)

   at Duplicati.Library.Main.BackendManager.DoPut(FileEntryItem item)

   at Duplicati.Library.Main.BackendManager.ThreadRun()

Renaming "duplicati-iedac4ef4aa5e49c0bc3755341a055fc4.dindex.zip.aes" to "duplicati-ie92418401ac54498a4fc2958f3fdbcc4.dindex.zip.aes"
```

Log 2: (incomplete, I will update it later)
```
Fatal error
Duplicati.Library.Interface.UserInformationException: Found 2 remote files that are not recorded in local storage, please run repair

   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)

   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend, String protectedfile)

   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
```

**Comment by Athep** [comment]
I’ve had a similar error, all was fine, even after the latest canary update (2.0.2.17_canary_2018-01-23)
But just suddenly: 

`Failed: Negating the minimum value of a twos complement number is invalid.
Details: System.OverflowException: Negating the minimum value of a twos complement number is invalid.
   at Duplicati.Library.Main.BackendManager.WaitForEmpty(LocalDatabase db, IDbTransaction transation)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass17_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
`
This was in the e-mail report. **Strange is that in the internal log, nothing at all. Just as if the backup not have been run.**

In the next run a got the following:

`Fatal error
Duplicati.Library.Interface.UserInformationException: Found 2 remote files that are not recorded in local storage, please run repair
   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)`

And I run repair..

`MainOperation: Repair
RecreateDatabaseResults: null
ParsedResult: Success
EndTime: 2018-01-29 11:04:10 (1517220250)
BeginTime: 2018-01-29 11:04:00 (1517220240)
Duration: 00:00:09.6928620
Messages: [
    Accepting new index file duplicati-i2fdc48c1e3f04256978c1d7b5d81b15c.dindex.zip.aes,
    Accepting new index file duplicati-i842814255cc24cd4b80bc359a78a020a.dindex.zip.aes
]
`

After this, everything is back to normal again..

**Comment by OronDF343** [comment]
> Strange is that in the internal log, nothing at all. Just as if the backup not have been run.

This happened to me in one instance as well

**Comment by TekkiWuff** [comment]
@OronDF343 Apprently `System.Math.AbsHelper(Int64 value)` is called with a value of -9223372036854775808 (`long.MinValue`) which cannot be converted to a positve number, since the maximum of a long is only 9223372036854775807 (`long.MaxValue`). Not sure what file size and duration in the following code caused that value though:
https://github.com/duplicati/duplicati/blob/851248ddbf4d92d3fd4952e7c0f8ccbaf039a509/Duplicati/Library/Main/BackendManager.cs#L722

@Athep Honestly not quite sure where yours crashes. The stacktrace does seem to miss the important part where the error occoured. Maybe it's something I'm not familiar with since I'm still somewhat of a novice in C# ^^

Anyway, using `double` instead of `long` for `FormatSizeString` should fix it, since floating point numbers have a seperate sign bit, thus being able to represent the same range for positve and negative numbers. And since the method is only used for printing rounded numbers anyway, the potential loss of precisions shouldn't matter.

**Comment by JonMikelV** [comment]
Thanks for your insight @TekkiWuff - I think you've found the issue.

The FormatSizeString() method takes a `long` for the `size` input variable but internally is using `double` with it.

I believe a change of mine recently got put in to fix a bug where string formatting wasn't occurring on negative values so I suspect this issue has been around for a while, we just never knew it because we weren't getting to the code.

**Comment by kenkendk** [comment]
Fixed with https://github.com/duplicati/duplicati/commit/f6bb6d3d4fb2e6c86ad62eece55c01f320743877
