### ISSUE TITLE
Negating the minimum value of a twos complement number is invalid.

### ISSUE THREAD

**Issue by Expro** [duplicati/duplicati#3025]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**:  2.0.2.17_canary_2018-01-23
- **Operating system**: Windows 10 x64
- **Backend**: Local HDD

## Description
Overflow exception during backup operation - most likely on scanning step.

## Steps to reproduce
Couldn't find easy steps to reproduce.

- **Actual result**:
Backup is interrupted with error.
- **Expected result**:
Backup gets done.

## Debug log
```System.OverflowException: Negating the minimum value of a twos complement number is invalid.
   at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes)
   at Duplicati.Library.Main.Operation.BackupHandler.RunMainOperation(ISnapshotService snapshot, BackendManager backend)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass17_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)```

**Comment by TekkiWuff** [comment]
This is _probably_ the same issue as #2994, which has be fixed already and will be in the next canary build.

Though, since your stacktrace is different than the other ones reported and there is no reference to the offending method in it, I'm keeping this issue open.

Please test this again, once the next build is out. Thanks!

**Comment by Expro** [comment]
Will do. Thanks for your hard work!

**Comment by ts678** [comment]
Did the mentioned fix resolve this? Running Canary is asking a lot, but there have been lots of Beta releases since that time.
