### ISSUE TITLE
Failed: Decoded stream has been corrupted.

### ISSUE THREAD

**Issue by skystis** [duplicati/duplicati#3034]
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1
- **Operating system**: Windows 2016 server
- **Backend**: FTP

## Description

Simple backup with 7z compression module. Once created not modified. No Encryption.
Backup worked fine until retention policy kicked in.
Afted that getting email messages about errors.
GUI showing error message:
![image](https://user-images.githubusercontent.com/12713033/36188857-a4f0820e-1157-11e8-9035-b99393ad1338.png)
But there is no such error message in logs:
2018 m. vasaris 14 d., 05:24 val.: Message
Compacting because there is 33,80% wasted space and the limit is 25%
 2018 m. vasaris 14 d., 05:24 val.: Message
Deleted 1 remote fileset(s)
2018 m. vasaris 14 d., 05:23 val.: Message
Deleting 1 remote fileset(s) ...
2018 m. vasaris 14 d., 05:00 val.: Message
removing file listed as Temporary: duplicati-i871339a9e2154970b10befe78df1b1bc.dindex.7z
2018 m. vasaris 14 d., 05:00 val.: Message
removing file listed as Temporary: duplicati-bf440a54bd49d416496300dda81bda498.dblock.7z
2018 m. vasaris 13 d., 05:23 val.: Message
Compacting because there is 29,86% wasted space and the limit is 25%
2018 m. vasaris 13 d., 05:23 val.: Message
Deleted 1 remote fileset(s)
2018 m. vasaris 13 d., 05:23 val.: Message
Deleting 1 remote fileset(s) ...
2018 m. vasaris 12 d., 05:01 val.: Result
DeletedFiles: 0
DeletedFolders: 0
ModifiedFiles: 29
ExaminedFiles: 1798
...

## Steps to reproduce

1. encryption-module: none
2. dblock-size: 2GB
3. keep-versions: 7
4. --no-encryption true
5. --synchronous-upload true
6. --auto-cleanup true
7. --compression-module 7z
8. --exclude-files-attributes temporary

7 versions created, later - errors.

- **Actual result**: Backup failed
Email: Failed: Decoded stream has been corrupted.
Details: System.IO.InvalidDataException: Decoded stream has been corrupted.
   at ManagedLzma._7zip.Decoder.FileBufferedDecoderStream.Fetch()
   at ManagedLzma._7zip.Decoder.FileBufferedDecoderStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at master._7zip.Utilities.UnpackSubStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Duplicati.Library.Utility.Utility.ForceStreamRead(Stream stream, Byte[] buf, Int32 count)
   at Duplicati.Library.Main.Volumes.BlockVolumeReader.ReadBlock(String hash, Byte[] blockbuffer)
   at Duplicati.Library.Main.Operation.CompactHandler.DoCompact(LocalDeleteDatabase db, Boolean hasVerifiedBackend, IDbTransaction& transaction)
   at Duplicati.Library.Main.Operation.DeleteHandler.DoRun(LocalDeleteDatabase db, IDbTransaction& transaction, Boolean hasVerifiedBacked, Boolean forceCompact)
   at Duplicati.Library.Main.Operation.BackupHandler.CompactIfRequired(BackendManager backend, Int64 lastVolumeSize)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass16_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
- **Expected result**: Old backups removed, new created.

## Screenshots
{
  "CreatedByVersion": "2.0.2.1",
  "Schedule": {
    "ID": 1,
    "Tags": [
      "ID=2"
    ],
    "Time": "2018-02-15T03:00:00Z",
    "Repeat": "1D",
    "LastRun": "2018-02-14T03:00:00Z",
    "Rule": "AllowedWeekDays=Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday",
    "AllowedDays": [
      "mon",
      "tue",
      "wed",
      "thu",
      "fri",
      "sat",
      "sun"
    ]
  },
  "Backup": {
    "ID": "2",
    "Name": "Monitor",
    "Tags": [],
    "TargetURL": "ftp://192.168.0.6//k-monitor/monitor?auth-username=whatewer&auth-password=whatever",
    "DBPath": "C:\\Windows\\system32\\config\\systemprofile\\AppData\\Local\\Duplicati\\HGPVQAQQVJ.sqlite",
    "Sources": [
      "C:\\Monwin\\"
    ],
    "Settings": [
      {
        "Filter": "",
        "Name": "encryption-module",
        "Value": "",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "dblock-size",
        "Value": "2GB",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "keep-versions",
        "Value": "7",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "--no-encryption",
        "Value": "true",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "--synchronous-upload",
        "Value": "true",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "--auto-cleanup",
        "Value": "true",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "--compression-module",
        "Value": "7z",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "--exclude-files-attributes",
        "Value": "temporary",
        "Argument": null
      }
    ],
    "Filters": [
      {
        "Order": 0,
        "Include": false,
        "Expression": "C:\\Monwin\\DB\\"
      }
    ],
    "Metadata": {
      "LastErrorDate": "20180214T033307Z",
      "LastErrorMessage": "Decoded stream has been corrupted.",
      "LastDuration": "00:00:00.1562445",
      "LastStarted": "20180213T051233Z",
      "LastFinished": "20180213T051233Z",
      "LastBackupDate": "20180212T030000Z",
      "BackupListCount": "7",
      "TotalQuotaSpace": "0",
      "FreeQuotaSpace": "0",
      "AssignedQuotaSpace": "-1",
      "TargetFilesSize": "6164558739",
      "TargetFilesCount": "31",
      "TargetSizeString": "5.74 GB",
      "SourceFilesSize": "11549821883",
      "SourceFilesCount": "1798",
      "SourceSizeString": "10.76 GB",
      "LastBackupStarted": "20180212T030000Z",
      "LastBackupFinished": "20180212T030150Z"
    },
    "IsTemporary": false
  },
  "DisplayNames": {
    "C:\\Monwin\\": "Monwin"
  }
}

## Debug log

[bugreport.zip](https://github.com/duplicati/duplicati/files/1722762/bugreport.zip)

**Comment by skystis** [comment]
Did database recreate.
Verify.
Run backup.
Seems, that new backup is created, but fails on finishing.
Result:
System.IO.InvalidDataException: Decoded stream has been corrupted.
   at ManagedLzma._7zip.Decoder.FileBufferedDecoderStream.Fetch()
   at ManagedLzma._7zip.Decoder.FileBufferedDecoderStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at master._7zip.Utilities.UnpackSubStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Duplicati.Library.Utility.Utility.ForceStreamRead(Stream stream, Byte[] buf, Int32 count)
   at Duplicati.Library.Main.Volumes.BlockVolumeReader.ReadBlock(String hash, Byte[] blockbuffer)
   at Duplicati.Library.Main.Operation.CompactHandler.DoCompact(LocalDeleteDatabase db, Boolean hasVerifiedBackend, IDbTransaction& transaction)
   at Duplicati.Library.Main.Operation.DeleteHandler.DoRun(LocalDeleteDatabase db, IDbTransaction& transaction, Boolean hasVerifiedBacked, Boolean forceCompact)
   at Duplicati.Library.Main.Operation.BackupHandler.CompactIfRequired(BackendManager backend, Int64 lastVolumeSize)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass16_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

**Comment by kenkendk** [comment]
Closing this issue as 7z has been removed
