### ISSUE TITLE
Can't view log, "database is locked"

### ISSUE THREAD

**Issue by Germs2004** [duplicati/duplicati#3040]
- [x] I have searched open and closed issues for duplicates.
There are tickets with the same error, but they all have different situations than mine.
----------------------------------------

## Environment info

- **Duplicati version**: 0.0.0.0
- **Operating system**: Windows Server 2016
- **Backend**: Windows Server 2016 shared folder on LAN

## Description
New user, new install.  I ran a small backup fine, so I then edited that job to add lots more files.  The job started as scheduled, and the next day, it is still running (slowly, it only created 86GB worth of backups after about 15 hours).  I wanted to see the log file to see if there was anything interesting about the current job in progress, so I clicked "Show log...", and after several seconds of "Loading...", I got an error popup:

Error
Failed to connect: database is locked database is locked

- **Actual result**:
Error message popped up, no log displayed.
- **Expected result**:
I expect to be able to view the log, even while a backup is in progress.  If an error occurs, it would be nice to have additional details in the error message, like why it is locked, how to fix it, the date/time the error occurred, and more verbose error text that explains exactly what it was trying to do ("failed to connect" is vague).

**Comment by kenkendk** [comment]
Yes, I am aware of the problem and have a plan for how to fix it.

**Comment by Germs2004** [comment]
Thank you for planning to fix this.  I've gained more experience with Duplicati since this ticket and had the error again, so I'm just providing additional error info in case it helps:

```
May 25, 2018 10:44 AM: Request for http://myhostname:8200/api/v1/backup/2/log?pagesize=100 gave error
System.Data.SQLite.SQLiteException (0x80004005): database is locked
database is locked
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at Duplicati.Server.WebServer.RESTMethods.LogData.DumpTable(IDbCommand cmd, String tablename, String pagingfield, String offset_str, String pagesize_str)
   at Duplicati.Server.WebServer.RESTMethods.Backup.FetchLogData(IBackup backup, RequestInfo info)
   at Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)

May 25, 2018 10:44 AM: Reporting error gave error
System.ObjectDisposedException: Cannot write to a closed TextWriter.
   at System.IO.__Error.WriterClosed()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)
```
