### ISSUE TITLE
Can't access file even with snapshot enabled, after installing MS Store app.

### ISSUE THREAD

**Issue by BlueNinja0** [duplicati/duplicati#3178]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.3_beta_2018-04-02
- **Operating system**: Windows 10 Pro version 1607 (x64) (also tested on version 1709)
- **Backend**: SSH (also tested on local folder)

## Description

When running a backup the following error occurs, with `snapshot-policy` set to Required or Off. This setting seems to make no difference in this case. This started happening after installing the CrystalDiskMark app from the official Microsoft Store.
Duplicati is running with administrator privileges.

`Failed to process path: C:\Users\nufpereira\AppData\Local\Packages\45313CrystalDewWorld.CrystalDiskMark5_kfjz01bcdaj9c\LocalCache\Local\Microsoft\Windows\Caches\{AFBF9F1A-8EE8-4C77-AF34-C647E37CA0D9}.1.ver0x0000000000000054.db
System.IO.IOException: (1920) The file cannot be accessed by the system: [\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy1\Users\nufpereira\AppData\Local\Packages\45313CrystalDewWorld.CrystalDiskMark5_kfjz01bcdaj9c\LocalCache\Local\Microsoft\Windows\Caches\{AFBF9F1A-8EE8-4C77-AF34-C647E37CA0D9}.1.ver0x0000000000000054.db]
   at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   at Alphaleonis.Win32.Filesystem.File.CreateFileCore(KernelTransaction transaction, String path, ExtendedFileAttributes attributes, FileSecurity fileSecurity, FileMode fileMode, FileSystemRights fileSystemRights, FileShare fileShare, Boolean checkPath, PathFormat pathFormat)
   at Alphaleonis.Win32.Filesystem.File.OpenCore(KernelTransaction transaction, String path, FileMode mode, FileSystemRights rights, FileShare share, ExtendedFileAttributes attributes, Nullable1 bufferSize, FileSecurity security, PathFormat pathFormat)
   at Duplicati.Library.Snapshots.SystemIOWindows.FileOpenRead(String path)
   at Duplicati.Library.Snapshots.WindowsSnapshot.OpenRead(String file)
   at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes)`

## Steps to reproduce

1. Install the CrystalDiskMark from the official Microsoft Store.
2. Execute a backup that contains the user's `AppData` folder.

- **Actual result**:
The above error occurs.
- **Expected result**:
The backup should complete successfully without errors.

## Debug log
The live log shows these warnings:
`Apr 13, 2018 11:57 AM: Failed to process path: C:\Users\nufpereira\AppData\Local\Packages\45313CrystalDewWorld.CrystalDiskMark5_kfjz01bcdaj9c\LocalCache\Local\Microsoft\Windows\Caches\{AFBF9F1A-8EE8-4C77-AF34-C647E37CA0D9}.1.ver0x0000000000000054.db
Apr 13, 2018 11:57 AM: Failed to process path: C:\Users\nufpereira\AppData\Local\Packages\45313CrystalDewWorld.CrystalDiskMark5_kfjz01bcdaj9c\LocalCache\Local\Microsoft\Windows\Caches\cversions.1.db`

**Comment by Taomyn** [comment]
Same problem here but with Windows 10 (1803) and canary build of Duplicati, and I have 3 WIndows Server 2016 all the the same backup configuration and none of them report any files that cannot be accessed:

```
Version: 2.0.3.11 (2.0.3.11_canary_2018-09-05)
EndTime: 28/09/2018 15:54:18 (1538142858)
BeginTime: 28/09/2018 15:52:20 (1538142740)
Duration: 00:01:57.9356030
Log data:
2018-09-28 15:53:17 +02 - [Warning-Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.FileEntry-PathProcessingFailed]: Failed to process path: C:\Users\Fernando\AppData\Local\Packages\1258EllAbi.MoveMouse_hjfwaxvfbwh7t\LocalCache\LocalLow\Microsoft\CryptnetUrlCache\MetaData\7D266D9E1E69FA1EEFB9699B009B34C8_0A9BFDD75B598C2110CBF610C078E6E6
System.IO.IOException: (1920) The file cannot be accessed by the system: [\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy14\Users\Fernando\AppData\Local\Packages\1258EllAbi.MoveMouse_hjfwaxvfbwh7t\LocalCache\LocalLow\Microsoft\CryptnetUrlCache\MetaData\7D266D9E1E69FA1EEFB9699B009B34C8_0A9BFDD75B598C2110CBF610C078E6E6]
   at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   at Alphaleonis.Win32.Filesystem.File.CreateFileCore(KernelTransaction transaction, String path, ExtendedFileAttributes attributes, FileSecurity fileSecurity, FileMode fileMode, FileSystemRights fileSystemRights, FileShare fileShare, Boolean checkPath, PathFormat pathFormat)
   at Alphaleonis.Win32.Filesystem.File.OpenCore(KernelTransaction transaction, String path, FileMode mode, FileSystemRights rights, FileShare share, ExtendedFileAttributes attributes, Nullable`1 bufferSize, FileSecurity security, PathFormat pathFormat)
   at Duplicati.Library.Snapshots.SystemIOWindows.FileOpenRead(String path)
   at Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.<>c__DisplayClass1_0.<<Run>b__0>d.MoveNext()
2018-09-28 15:53:17 +02 - [Warning-Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.FileEntry-PathProcessingFailed]: Failed to process path: C:\Users\Fernando\AppData\Local\Packages\1258EllAbi.MoveMouse_hjfwaxvfbwh7t\LocalCache\LocalLow\Microsoft\CryptnetUrlCache\MetaData\9A19ADAD9D098E039450ABBEDD5616EB_C4753E70B0D639C80CB575487E8A02AC
System.IO.IOException: (1920) The file cannot be accessed by the system: [\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy14\Users\Fernando\AppData\Local\Packages\1258EllAbi.MoveMouse_hjfwaxvfbwh7t\LocalCache\LocalLow\Microsoft\CryptnetUrlCache\MetaData\9A19ADAD9D098E039450ABBEDD5616EB_C4753E70B0D639C80CB575487E8A02AC]
   at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   at Alphaleonis.Win32.Filesystem.File.CreateFileCore(KernelTransaction transaction, String path, ExtendedFileAttributes attributes, FileSecurity fileSecurity, FileMode fileMode, FileSystemRights fileSystemRights, FileShare fileShare, Boolean checkPath, PathFormat pathFormat)
   at Alphaleonis.Win32.Filesystem.File.OpenCore(KernelTransaction transaction, String path, FileMode mode, FileSystemRights rights, FileShare share, ExtendedFileAttributes attributes, Nullable`1 bufferSize, FileSecurity security, PathFormat pathFormat)
   at Duplicati.Library.Snapshots.SystemIOWindows.FileOpenRead(String path)
   at Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.<>c__DisplayClass1_0.<<Run>b__0>d.MoveNext()
2018-09-28 15:53:17 +02 - [Warning-Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.FileEntry-PathProcessingFailed]: Failed to process path: C:\Users\Fernando\AppData\Local\Packages\1258EllAbi.MoveMouse_hjfwaxvfbwh7t\LocalCache\LocalLow\Microsoft\CryptnetUrlCache\MetaData\9A19ADAD9D098E039450ABBEDD5616EB_D562BC42E2F6DA98D09C80BB21CE89F9
System.IO.IOException: (1920) The file cannot be accessed by the system: [\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy14\Users\Fernando\AppData\Local\Packages\1258EllAbi.MoveMouse_hjfwaxvfbwh7t\LocalCache\LocalLow\Microsoft\CryptnetUrlCache\MetaData\9A19ADAD9D098E039450ABBEDD5616EB_D562BC42E2F6DA98D09C80BB21CE89F9]
   at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   at Alphaleonis.Win32.Filesystem.File.CreateFileCore(KernelTransaction transaction, String path, ExtendedFileAttributes attributes, FileSecurity fileSecurity, FileMode fileMode, FileSystemRights fileSystemRights, FileShare fileShare, Boolean checkPath, PathFormat pathFormat)
   at Alphaleonis.Win32.Filesystem.File.OpenCore(KernelTransaction transaction, String path, FileMode mode, FileSystemRights rights, FileShare share, ExtendedFileAttributes attributes, Nullable`1 bufferSize, FileSecurity security, PathFormat pathFormat)
   at Duplicati.Library.Snapshots.SystemIOWindows.FileOpenRead(String path)
   at Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.<>c__DisplayClass1_0.<<Run>b__0>d.MoveNext()
2018-09-28 15:53:17 +02 - [Warning-Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.FileEntry-PathProcessingFailed]: Failed to process path: C:\Users\Fernando\AppData\Local\Packages\1258EllAbi.MoveMouse_hjfwaxvfbwh7t\LocalCache\LocalLow\Microsoft\CryptnetUrlCache\MetaData\A89DFCC31C360BA5CBD616749B1B1C5D
System.IO.IOException: (1920) The file cannot be accessed by the system: [\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy14\Users\Fernando\AppData\Local\Packages\1258EllAbi.MoveMouse_hjfwaxvfbwh7t\LocalCache\LocalLow\Microsoft\CryptnetUrlCache\MetaData\A89DFCC31C360BA5CBD616749B1B1C5D]
   at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   at Alphaleonis.Win32.Filesystem.File.CreateFileCore(KernelTransaction transaction, String path, ExtendedFileAttributes attributes, FileSecurity fileSecurity, FileMode fileMode, FileSystemRights fileSystemRights, FileShare fileShare, Boolean checkPath, PathFormat pathFormat)
   at Alphaleonis.Win32.Filesystem.File.OpenCore(KernelTransaction transaction, String path, FileMode mode, FileSystemRights rights, FileShare share, ExtendedFileAttributes attributes, Nullable`1 bufferSize, FileSecurity security, PathFormat pathFormat)
   at Duplicati.Library.Snapshots.SystemIOWindows.FileOpenRead(String path)
   at Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.<>c__DisplayClass1_0.<<Run>b__0>d.MoveNext()
2018-09-28 15:53:17 +02 - [Warning-Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.FileEntry-PathProcessingFailed]: Failed to process path: C:\Users\Fernando\AppData\Local\Packages\1258EllAbi.MoveMouse_hjfwaxvfbwh7t\LocalCache\LocalLow\Microsoft\CryptnetUrlCache\MetaData\C8E7EC0C85688F4738F3BE49B104BA67
System.IO.IOException: (1920) The file cannot be accessed by the system: [\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy14\Users\Fernando\AppData\Local\Packages\1258EllAbi.MoveMouse_hjfwaxvfbwh7t\LocalCache\LocalLow\Microsoft\CryptnetUrlCache\MetaData\C8E7EC0C85688F4738F3BE49B104BA67]
   at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   at Alphaleonis.Win32.Filesystem.File.CreateFileCore(KernelTransaction transaction, String path, ExtendedFileAttributes attributes, FileSecurity fileSecurity, FileMode fileMode, FileSystemRights fileSystemRights, FileShare fileShare, Boolean checkPath, PathFormat pathFormat)
   at Alphaleonis.Win32.Filesystem.File.OpenCore(KernelTransaction transaction, String path, FileMode mode, FileSystemRights rights, FileShare share, ExtendedFileAttributes attributes, Nullable`1 bufferSize, FileSecurity security, PathFormat pathFormat)
   at Duplicati.Library.Snapshots.SystemIOWindows.FileOpenRead(String path)
   at Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.<>c__DisplayClass1_0.<<Run>b__0>d.MoveNext()
2018-09-28 15:53:17 +02 - [Warning-Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.FileEntry-PathProcessingFailed]: Failed to process path: C:\Users\Fernando\AppData\Local\Packages\1258EllAbi.MoveMouse_hjfwaxvfbwh7t\LocalCache\LocalLow\Microsoft\CryptnetUrlCache\Content\7D266D9E1E69FA1EEFB9699B009B34C8_0A9BFDD75B598C2110CBF610C078E6E6
System.IO.IOException: (1920) The file cannot be accessed by the system: [\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy14\Users\Fernando\AppData\Local\Packages\1258EllAbi.MoveMouse_hjfwaxvfbwh7t\LocalCache\LocalLow\Microsoft\CryptnetUrlCache\Content\7D266D9E1E69FA1EEFB9699B009B34C8_0A9BFDD75B598C2110CBF610C078E6E6]
   at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   at Alphaleonis.Win32.Filesystem.File.CreateFileCore(KernelTransaction transaction, String path, ExtendedFileAttributes attributes, FileSecurity fileSecurity, FileMode fileMode, FileSystemRights fileSystemRights, FileShare fileShare, Boolean checkPath, PathFormat pathFormat)
   at Alphaleonis.Win32.Filesystem.File.OpenCore(KernelTransaction transaction, String path, FileMode mode, FileSystemRights rights, FileShare share, ExtendedFileAttributes attributes, Nullable`1 bufferSize, FileSecurity security, PathFormat pathFormat)
   at Duplicati.Library.Snapshots.SystemIOWindows.FileOpenRead(String path)
   at Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.<>c__DisplayClass1_0.<<Run>b__0>d.MoveNext()
2018-09-28 15:53:17 +02 - [Warning-Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.FileEntry-PathProcessingFailed]: Failed to process path: C:\Users\Fernando\AppData\Local\Packages\1258EllAbi.MoveMouse_hjfwaxvfbwh7t\LocalCache\LocalLow\Microsoft\CryptnetUrlCache\Content\9A19ADAD9D098E039450ABBEDD5616EB_C4753E70B0D639C80CB575487E8A02AC
System.IO.IOException: (1920) The file cannot be accessed by the system: [\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy14\Users\Fernando\AppData\Local\Packages\1258EllAbi.MoveMouse_hjfwaxvfbwh7t\LocalCache\LocalLow\Microsoft\CryptnetUrlCache\Content\9A19ADAD9D098E039450ABBEDD5616EB_C4753E70B0D639C80CB575487E8A02AC]
   at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   at Alphaleonis.Win32.Filesystem.File.CreateFileCore(KernelTransaction transaction, String path, ExtendedFileAttributes attributes, FileSecurity fileSecurity, FileMode fileMode, FileSystemRights fileSystemRights, FileShare fileShare, Boolean checkPath, PathFormat pathFormat)
   at Alphaleonis.Win32.Filesystem.File.OpenCore(KernelTransaction transaction, String path, FileMode mode, FileSystemRights rights, FileShare share, ExtendedFileAttributes attributes, Nullable`1 bufferSize, FileSecurity security, PathFormat pathFormat)
   at Duplicati.Library.Snapshots.SystemIOWindows.FileOpenRead(String path)
   at Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.<>c__DisplayClass1_0.<<Run>b__0>d.MoveNext()
2018-09-28 15:53:17 +02 - [Warning-Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.FileEntry-PathProcessingFailed]: Failed to process path: C:\Users\Fernando\AppData\Local\Packages\1258EllAbi.MoveMouse_hjfwaxvfbwh7t\LocalCache\LocalLow\Microsoft\CryptnetUrlCache\Content\9A19ADAD9D098E039450ABBEDD5616EB_D562BC42E2F6DA98D09C80BB21CE89F9
System.IO.IOException: (1920) The file cannot be accessed by the system: [\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy14\Users\Fernando\AppData\Local\Packages\1258EllAbi.MoveMouse_hjfwaxvfbwh7t\LocalCache\LocalLow\Microsoft\CryptnetUrlCache\Content\9A19ADAD9D098E039450ABBEDD5616EB_D562BC42E2F6DA98D09C80BB21CE89F9]
   at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   at Alphaleonis.Win32.Filesystem.File.CreateFileCore(KernelTransaction transaction, String path, ExtendedFileAttributes attributes, FileSecurity fileSecurity, FileMode fileMode, FileSystemRights fileSystemRights, FileShare fileShare, Boolean checkPath, PathFormat pathFormat)
   at Alphaleonis.Win32.Filesystem.File.OpenCore(KernelTransaction transaction, String path, FileMode mode, FileSystemRights rights, FileShare share, ExtendedFileAttributes attributes, Nullable`1 bufferSize, FileSecurity security, PathFormat pathFormat)
   at Duplicati.Library.Snapshots.SystemIOWindows.FileOpenRead(String path)
   at Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.<>c__DisplayClass1_0.<<Run>b__0>d.MoveNext()
2018-09-28 15:53:17 +02 - [Warning-Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.FileEntry-PathProcessingFailed]: Failed to process path: C:\Users\Fernando\AppData\Local\Packages\1258EllAbi.MoveMouse_hjfwaxvfbwh7t\LocalCache\LocalLow\Microsoft\CryptnetUrlCache\Content\A89DFCC31C360BA5CBD616749B1B1C5D
System.IO.IOException: (1920) The file cannot be accessed by the system: [\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy14\Users\Fernando\AppData\Local\Packages\1258EllAbi.MoveMouse_hjfwaxvfbwh7t\LocalCache\LocalLow\Microsoft\CryptnetUrlCache\Content\A89DFCC31C360BA5CBD616749B1B1C5D]
   at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   at Alphaleonis.Win32.Filesystem.File.CreateFileCore(KernelTransaction transaction, String path, ExtendedFileAttributes attributes, FileSecurity fileSecurity, FileMode fileMode, FileSystemRights fileSystemRights, FileShare fileShare, Boolean checkPath, PathFormat pathFormat)
   at Alphaleonis.Win32.Filesystem.File.OpenCore(KernelTransaction transaction, String path, FileMode mode, FileSystemRights rights, FileShare share, ExtendedFileAttributes attributes, Nullable`1 bufferSize, FileSecurity security, PathFormat pathFormat)
   at Duplicati.Library.Snapshots.SystemIOWindows.FileOpenRead(String path)
   at Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.<>c__DisplayClass1_0.<<Run>b__0>d.MoveNext()
2018-09-28 15:53:17 +02 - [Warning-Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.FileEntry-PathProcessingFailed]: Failed to process path: C:\Users\Fernando\AppData\Local\Packages\1258EllAbi.MoveMouse_hjfwaxvfbwh7t\LocalCache\LocalLow\Microsoft\CryptnetUrlCache\Content\C8E7EC0C85688F4738F3BE49B104BA67
System.IO.IOException: (1920) The file cannot be accessed by the system: [\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy14\Users\Fernando\AppData\Local\Packages\1258EllAbi.MoveMouse_hjfwaxvfbwh7t\LocalCache\LocalLow\Microsoft\CryptnetUrlCache\Content\C8E7EC0C85688F4738F3BE49B104BA67]
   at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   at Alphaleonis.Win32.Filesystem.File.CreateFileCore(KernelTransaction transaction, String path, ExtendedFileAttributes attributes, FileSecurity fileSecurity, FileMode fileMode, FileSystemRights fileSystemRights, FileShare fileShare, Boolean checkPath, PathFormat pathFormat)
   at Alphaleonis.Win32.Filesystem.File.OpenCore(KernelTransaction transaction, String path, FileMode mode, FileSystemRights rights, FileShare share, ExtendedFileAttributes attributes, Nullable`1 bufferSize, FileSecurity security, PathFormat pathFormat)
   at Duplicati.Library.Snapshots.SystemIOWindows.FileOpenRead(String path)
   at Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.<>c__DisplayClass1_0.<<Run>b__0>d.MoveNext()
2018-09-28 15:53:20 +02 - [Warning-Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.FileEntry-PathProcessingFailed]: Failed to process path: C:\Users\Fernando\AppData\Local\Microsoft\WindowsApps\MicrosoftEdge.exe
System.IO.IOException: (1920) The file cannot be accessed by the system: [\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy14\Users\Fernando\AppData\Local\Microsoft\WindowsApps\MicrosoftEdge.exe]
   at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   at Alphaleonis.Win32.Filesystem.File.CreateFileCore(KernelTransaction transaction, String path, ExtendedFileAttributes attributes, FileSecurity fileSecurity, FileMode fileMode, FileSystemRights fileSystemRights, FileShare fileShare, Boolean checkPath, PathFormat pathFormat)
   at Alphaleonis.Win32.Filesystem.File.OpenCore(KernelTransaction transaction, String path, FileMode mode, FileSystemRights rights, FileShare share, ExtendedFileAttributes attributes, Nullable`1 bufferSize, FileSecurity security, PathFormat pathFormat)
   at Duplicati.Library.Snapshots.SystemIOWindows.FileOpenRead(String path)
   at Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.<>c__DisplayClass1_0.<<Run>b__0>d.MoveNext()
2018-09-28 15:53:20 +02 - [Warning-Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.FileEntry-PathProcessingFailed]: Failed to process path: C:\Users\Fernando\AppData\Local\Microsoft\WindowsApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdge.exe
System.IO.IOException: (1920) The file cannot be accessed by the system: [\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy14\Users\Fernando\AppData\Local\Microsoft\WindowsApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdge.exe]
   at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   at Alphaleonis.Win32.Filesystem.File.CreateFileCore(KernelTransaction transaction, String path, ExtendedFileAttributes attributes, FileSecurity fileSecurity, FileMode fileMode, FileSystemRights fileSystemRights, FileShare fileShare, Boolean checkPath, PathFormat pathFormat)
   at Alphaleonis.Win32.Filesystem.File.OpenCore(KernelTransaction transaction, String path, FileMode mode, FileSystemRights rights, FileShare share, ExtendedFileAttributes attributes, Nullable`1 bufferSize, FileSecurity security, PathFormat pathFormat)
   at Duplicati.Library.Snapshots.SystemIOWindows.FileOpenRead(String path)
   at Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.<>c__DisplayClass1_0.<<Run>b__0>d.MoveNext()

```

**Comment by joel0** [comment]
I encountered this exception (treated as a warning) on an "invalid" ReparsePoint (symlink).  In my case, it was a symlink created by the Windows Subsystem for Linux (the Nginx repository in Mercurial).  These types of symlinks are understood by WSL, but not Windows.

Based on the last entry from @Taomyn's log, I've checked my own copy of `C:\Users\jmay\AppData\Local\Microsoft\WindowsApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdge.exe` and see that it is also an invalid symlink.  I have not attempted to back up that folder, so I don't know if that would throw an exception for me.

Probably the best action in this case would be to archive an invalid symlink by reading the destination.  I don't know if Duplicati's design would support that though.

Here's some info about the Edge file:
```
C:\Users\jmay\AppData\Local\Microsoft\WindowsApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe> fsutil.exe reparsepoint query .\MicrosoftEdge.exe
Reparse Tag Value : 0x8000001b
Tag value: Microsoft

Reparse Data Length: 0x00000110
Reparse Data:
0000:  03 00 00 00 4d 00 69 00  63 00 72 00 6f 00 73 00  ....M.i.c.r.o.s.
0010:  6f 00 66 00 74 00 2e 00  4d 00 69 00 63 00 72 00  o.f.t...M.i.c.r.
0020:  6f 00 73 00 6f 00 66 00  74 00 45 00 64 00 67 00  o.s.o.f.t.E.d.g.
0030:  65 00 5f 00 38 00 77 00  65 00 6b 00 79 00 62 00  e._.8.w.e.k.y.b.
0040:  33 00 64 00 38 00 62 00  62 00 77 00 65 00 00 00  3.d.8.b.b.w.e...
0050:  4d 00 69 00 63 00 72 00  6f 00 73 00 6f 00 66 00  M.i.c.r.o.s.o.f.
0060:  74 00 2e 00 4d 00 69 00  63 00 72 00 6f 00 73 00  t...M.i.c.r.o.s.
0070:  6f 00 66 00 74 00 45 00  64 00 67 00 65 00 5f 00  o.f.t.E.d.g.e._.
0080:  38 00 77 00 65 00 6b 00  79 00 62 00 33 00 64 00  8.w.e.k.y.b.3.d.
0090:  38 00 62 00 62 00 77 00  65 00 21 00 4d 00 69 00  8.b.b.w.e.!.M.i.
00a0:  63 00 72 00 6f 00 73 00  6f 00 66 00 74 00 45 00  c.r.o.s.o.f.t.E.
00b0:  64 00 67 00 65 00 00 00  43 00 3a 00 5c 00 57 00  d.g.e...C.:.\.W.
00c0:  69 00 6e 00 64 00 6f 00  77 00 73 00 5c 00 53 00  i.n.d.o.w.s.\.S.
00d0:  79 00 73 00 74 00 65 00  6d 00 33 00 32 00 5c 00  y.s.t.e.m.3.2.\.
00e0:  53 00 79 00 73 00 74 00  65 00 6d 00 55 00 57 00  S.y.s.t.e.m.U.W.
00f0:  50 00 4c 00 61 00 75 00  6e 00 63 00 68 00 65 00  P.L.a.u.n.c.h.e.
0100:  72 00 2e 00 65 00 78 00  65 00 00 00 31 00 00 00  r...e.x.e...1...
C:\Users\jmay\AppData\Local\Microsoft\WindowsApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe> cat .\MicrosoftEdge.exe
cat : The file cannot be accessed by the system.
At line:1 char:1
+ cat .\MicrosoftEdge.exe
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ReadError: (C:\Users\jmay\A...crosoftEdge.exe:String) [Get-Content], IOException
    + FullyQualifiedErrorId : GetContentReaderIOError,Microsoft.PowerShell.Commands.GetContentCommand
```

And, my log messages on the symlink created from WSL:
```
2019-03-20 16:22:03 -05 - [Verbose-Duplicati.Library.Main.Operation.Backup.FilePreFilterProcess.FileEntry-CheckFileForChanges]: Checking file for changes C:\Users\jmay\Repos\nginx\.hg\cache\checklink, new: True, timestamp changed: True, size changed: True, metadatachanged: True, 2019-02-20 23:17:50 vs 0001-01-01 0:00:00
2019-03-20 16:22:03 -05 - [Warning-Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.FileEntry-PathProcessingFailed]: Failed to process path: C:\Users\jmay\Repos\nginx\.hg\cache\checklink
System.IO.IOException: (1920) The file cannot be accessed by the system: [\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy21\Users\jmay\Repos\nginx\.hg\cache\checklink]
   at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   at Alphaleonis.Win32.Filesystem.File.CreateFileCore(KernelTransaction transaction, String path, ExtendedFileAttributes attributes, FileSecurity fileSecurity, FileMode fileMode, FileSystemRights fileSystemRights, FileShare fileShare, Boolean checkPath, PathFormat pathFormat)
   at Alphaleonis.Win32.Filesystem.File.OpenCore(KernelTransaction transaction, String path, FileMode mode, FileSystemRights rights, FileShare share, ExtendedFileAttributes attributes, Nullable`1 bufferSize, FileSecurity security, PathFormat pathFormat)
   at Duplicati.Library.Snapshots.SystemIOWindows.FileOpenRead(String path)
   at Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.<>c__DisplayClass1_0.<<Run>b__0>d.MoveNext()
```

**Comment by ts678** [comment]
2.0.7.1 Beta gave a slightly different stack, run as Windows service as SYSTEM with snapshot-policy=required although one wouldn't know it from the stack, which is strange, but possibly ties in with reduced use of Alphaleonis in newer frameworks.

```
2023-07-10 06:21:03 -04 - [Warning-Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.FileEntry-PathProcessingFailed]: Failed to process path: C:\Users\me\AppData\Local\Microsoft\WindowsApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdge.exe
System.IO.IOException: The file cannot be accessed by the system.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Duplicati.Library.Common.IO.SystemIOWindows.FileOpenRead(String path)
   at Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.<>c__DisplayClass1_0.<<Run>b__0>d.MoveNext()
```

fsutil reparsepoint query on the path gave "Reparse Tag Value : 0x8000001b"

[2.1.2.1 Reparse Tags](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-fscc/c8e77b37-3909-4fe6-a4ea-2b9d423b1ee4)

IO_REPARSE_TAG_APPEXECLINK used by Universal Windows Platform (UWP) packages. Answer fits well with Store app.
Although a symlink is a reparse point, there are numerous unhandled reparse point tags (see reparse tags document).

[UnrecognizedReparsePointException #1727](https://github.com/duplicati/duplicati/issues/1727) is in that area, although once again Alphaleonis uses might have changed.

[JUNCTIONS not correctly restored #3870](https://github.com/duplicati/duplicati/issues/3870) is also in the reparse point area.
