### ISSUE TITLE
Stopping a backup job causes ThreadAbortException

### ISSUE THREAD

**Issue by Germs2004** [duplicati/duplicati#3235]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.3.3_beta_2018-04-02
- **Operating system**: Windows Server 2016

## Description
I clicked "Run Now" to start a backup job.  While it was still in the "Counting files" phase, I clicked the X to stop the job.  After a few seconds, the job stopped and I received an email notification saying that an exception was caught:

```
Failed: Thread was being aborted.
Details: System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort()
   at Duplicati.Library.Main.BasicResults.TaskControlRendevouz()
   at Duplicati.Library.Main.Operation.BackupHandler.RunMainOperation(ISnapshotService snapshot, BackendManager backend)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass17_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
```

- **Actual result**:
An exception is caught and a failure email is sent with a stack trace.

- **Expected result**:
No exception should be thrown nor caught.  It should send a "warning" email saying that a backup job was aborted by user command.

## Debug log

May 25, 2018 10:38 AM: Failed while executing "Backup" with id: 2
System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort()
   at Duplicati.Library.Main.BasicResults.TaskControlRendevouz()
   at Duplicati.Library.Main.Operation.BackupHandler.RunMainOperation(ISnapshotService snapshot, BackendManager backend)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass17_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

May 25, 2018 10:38 AM: Error in worker
System.Threading.ThreadAbortException: Thread was being aborted.
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
   at Duplicati.Library.Utility.WorkerThread`1.Runner()

**Comment by warwickmm** [comment]
Duplicates #3061.
