### ISSUE TITLE
Duplicati.WindowsService.exe error does not start windows 7

### ISSUE THREAD

**Issue by rdbox** [duplicati/duplicati#3401]
just downloaded your program but can not run it very many errors why ??

### version: duplicati-2.0.3.3_beta_2018-04-02-x64

log
```
 Duplicati 2 ./Duplicati.WindowsService.exe  install --webservice-interface=loopback --webservice-port=8200

Running a transacted installation.

Beginning the Install phase of the installation.
See the contents of the log file for the C:\Program Files\Duplicati 2\Duplicati.WindowsService.exe assembly's progress.
The file is located at C:\Program Files\Duplicati 2\Duplicati.WindowsService.InstallLog.
Installing assembly 'C:\Program Files\Duplicati 2\Duplicati.WindowsService.exe'.
Affected parameters are:
   logtoconsole =
   assemblypath = C:\Program Files\Duplicati 2\Duplicati.WindowsService.exe
   logfile = C:\Program Files\Duplicati 2\Duplicati.WindowsService.InstallLog
   commandline = "--webservice-interface=loopback" "--webservice-port=8200"
Installing service Duplicati...
Service Duplicati has been successfully installed.
Creating EventLog source Duplicati in log Application...

The Install phase completed successfully, and the Commit phase is beginning.
See the contents of the log file for the C:\Program Files\Duplicati 2\Duplicati.WindowsService.exe assembly's progress.
The file is located at C:\Program Files\Duplicati 2\Duplicati.WindowsService.InstallLog.
Committing assembly 'C:\Program Files\Duplicati 2\Duplicati.WindowsService.exe'.
Affected parameters are:
   logtoconsole =
   assemblypath = C:\Program Files\Duplicati 2\Duplicati.WindowsService.exe
   logfile = C:\Program Files\Duplicati 2\Duplicati.WindowsService.InstallLog
   commandline = "--webservice-interface=loopback" "--webservice-port=8200"

The Commit phase completed successfully.

The transacted install has completed.

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Недостаточно памяти для обработки команды.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__ConsoleStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.<>c.<BeginReadInternal>b__39_0(Object )
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.Stream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecentSpawn(MethodInfo method, String[] cmdargs, AutoUpdateStrategy defaultstrategy)
   at Duplicati.WindowsService.Program.Main(String[] args)
```

OS windows 7

**Comment by Pectojin** [comment]
Hmm, there's an error `Недостаточно памяти для обработки команды` -> `Not enough memory to process the command`. How much memory does the system have available?

**Comment by rdbox** [comment]
@Pectojin At me in system 16 Gb it is occupied no more than 35-40%

**Comment by warwickmm** [comment]
It sounds like other people have experienced similar issues with .NET programs, and the cause can be due to the lack of contiguous memory space.  Do you still experience this after a reboot?

**Comment by rdbox** [comment]
@warwickmm  yes the problem is still there (((

**Comment by ts678** [comment]
Error translations on the web vary, but I think this is referring to storage (as in on-disk) and not memory.
Also compare the intent of System.IO.IOException versus System.OutOfMemoryException. Main proof is:

[Duplicati.CommandLine.exe crash](https://forum.duplicati.com/t/duplicati-commandline-exe-crash/1928)
[Duplicati service won’t start after duplicati update on windows 7](https://forum.duplicati.com/t/duplicati-service-wont-start-after-duplicati-update-on-windows-7/3118)
[Setting up duplicati-2.0.3.3_beta as a Service Problem](https://forum.duplicati.com/t/setting-up-duplicati-2-0-3-3-beta-as-a-service-problem/3527)

There was some success at having the problem go away (with or without help) but it's still mysterious.
Searching the web with the correct message (if you agree above is correct) might find other thoughts.

Forum #3527 said things actually worked despite that error. Did Duplicati service work that way here?
Possibly cmd.exe can get more info, e.g. "sc query duplicati" for current, then try "start" or "stop", etc.
Does CommandLine or TrayIcon start any better? Of course, please also make sure your disk isn't full.

**Comment by warwickmm** [comment]
I'm guessing this was a disk space issue.  I think we can assume this has been resolved, based on the later issues opened by the OP.
