### ISSUE TITLE
Error "database is locked" when trying to run a backup after a force stop

### ISSUE THREAD

**Issue by mikaelmello** [duplicati/duplicati#3445]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: Latest
- **Operating system**: Windows 10
- **Backend**: Azure (for now)

## Description

It doesn't always happen, but it happened a few times since I've started to use Duplicati.

Whenever I force stop a currently running backup, there's a chance that when I try to run a new backup (could be the same recently stopped) an error notification will appear saying "database is locked"

Edit with new findings:

If you stop the backup before it starts to upload a remote file, nothing unusual happens. For example, my backup of 29GB and 2000 files that only amounts to 1 MB in remote size, because they are highly compressible, therefore when I pause, it will be still processing the files in the majority of the time.

However, if you stop the backup after a remote file starts to be uploaded, the next run will throw the 'database is locked' exception. For example, a backup of large `.exe` files, it starts to upload the first volume at the ~3rd file and if I stop after that, the error always happens.

This error seems to be introduced in the version `2.0.3.6`

Exact behavior described in the comments

## Debug log

```
System.Data.SQLite.SQLiteException (0x80004005): database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at Duplicati.Library.Main.Database.ExtensionMethods.ExecuteScalarInt64(IDbCommand self, Boolean writeLog, String cmd, Int64 defaultvalue, Object[] values) in C:\Users\xxx\Documents\duplicati\Duplicati\Library\Main\Database\ExtensionMethods.cs:line 150
   at Duplicati.Library.Main.Database.ExtensionMethods.ExecuteScalarInt64(IDbCommand self, String cmd, Int64 defaultvalue, Object[] values) in C:\Users\xxx\Documents\duplicati\Duplicati\Library\Main\Database\ExtensionMethods.cs:line 134
   at Duplicati.Library.Main.Database.LocalDatabase..ctor(IDbConnection connection, String operation) in C:\Users\xxx\Documents\duplicati\Duplicati\Library\Main\Database\LocalDatabase.cs:line 94
   at Duplicati.Library.Main.Database.LocalDatabase..ctor(String path, String operation, Boolean shouldclose) in C:\Users\xxx\Documents\duplicati\Duplicati\Library\Main\Database\LocalDatabase.cs:line 63
   at Duplicati.Library.Main.Database.LocalBackupDatabase..ctor(String path, Options options) in C:\Users\xxx\Documents\duplicati\Duplicati\Library\Main\Database\LocalBackupDatabase.cs:line 104
   at Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__19.MoveNext() in C:\Users\xxx\Documents\duplicati\Duplicati\Library\Main\Operation\BackupHandler.cs:line 370
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CoCoL.ChannelExtensions.WaitForTaskOrThrow(Task task)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter) in C:\Users\xxx\Documents\duplicati\Duplicati\Library\Main\Operation\BackupHandler.cs:line 321
   at Duplicati.Library.Main.Controller.<>c__DisplayClass13_0.<Backup>b__0(BackupResults result) in C:\Users\xxx\Documents\duplicati\Duplicati\Library\Main\Controller.cs:line 112
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method) in C:\Users\xxx\Documents\duplicati\Duplicati\Library\Main\Controller.cs:line 445
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter) in C:\Users\xxx\Documents\duplicati\Duplicati\Library\Main\Controller.cs:line 110
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue) in C:\Users\xxx\Documents\duplicati\Duplicati\Server\Runner.cs:line 507
```

**Comment by maxemilian** [comment]
mikaelmello, did you try to restart duplicati/duplicati service?
Max

**Comment by mikaelmello** [comment]
Yes I did, that fixes the problem but the fact that a restart is necessary
is what bothers me and actually the problem


Em sáb, 20 de out de 2018 19:48, Maxemilian Hilbrand <
notifications@github.com> escreveu:

**Comment by Pectojin** [comment]
I just replicated this by accident while testing something else.

I think there's some kind of regression in the way the "stop now" functionality. I definitely used to be able to do that without any locking issues.

When I have time it might be worth going back a number of releases and trying to replicate it to confirm/deny that.

**Comment by mikaelmello** [comment]
Any tips on how to reproduce it? I've been trying to but with no success.

**Comment by Pectojin** [comment]
It happened every time I stopped uploading yesterday.

**Comment by mikaelmello** [comment]
> When I have time it might be worth going back a number of releases and trying to replicate it to confirm/deny that.

I tested on 2.0.3.3, 2.0.3.5, 2.0.3.6, 2.0.3.7, 2.0.3.10, 2.0.3.13.

As expected, the bug started to occur on 2.0.3.6, the release with the big concurrency rewrite if I'm not mistaken.

**Comment by mikaelmello** [comment]
I think I've found the problem.

This code aborts the thread running the task:

https://github.com/duplicati/duplicati/blob/9bc1fe636a7dd31f3755502d74ab5ab4f028fe07/Duplicati/Library/Main/Controller.cs#L1091-L1093

Because the thread is abruptly aborted, both `finally` blocks never get to be executed:

https://github.com/duplicati/duplicati/blob/9bc1fe636a7dd31f3755502d74ab5ab4f028fe07/Duplicati/Library/Main/Operation/BackupHandler.cs#L479-L486

https://github.com/duplicati/duplicati/blob/9bc1fe636a7dd31f3755502d74ab5ab4f028fe07/Duplicati/Library/Main/Operation/BackupHandler.cs#L556-L565

**Comment by mikaelmello** [comment]
Any news?

**Comment by mikaelmello** [comment]
Update

Debugging a ~lot~ bit more I found out that after the thread is aborted, the program keeps on continuing, it is only after 50 seconds (I've only measured one time after testing this behavior a few times) that the line:

https://github.com/duplicati/duplicati/blob/9bc1fe636a7dd31f3755502d74ab5ab4f028fe07/Duplicati/Library/Main/Operation/BackupHandler.cs#L480

Throws an exception, the first `finally` block is executed:

https://github.com/duplicati/duplicati/blob/9bc1fe636a7dd31f3755502d74ab5ab4f028fe07/Duplicati/Library/Main/Operation/BackupHandler.cs#L482-L486

and in the following catch block, we can see the Exception thrown by `RunMainOperation()`:

https://github.com/duplicati/duplicati/blob/9bc1fe636a7dd31f3755502d74ab5ab4f028fe07/Duplicati/Library/Main/Operation/BackupHandler.cs#L547-L555

```
{"Unable to find log in lookup table, this may be caused by attempting to transport call contexts between AppDomains (eg. with remoting calls)"}

   at Duplicati.Library.Logging.Log.get_CurrentScope() in C:\\Users\\xxx\\Documents\\duplicati\\Duplicati\\Library\\Logging\\Log.cs:line 454
   at Duplicati.Library.Logging.Log.WriteMessage(LogMessageType type, String tag, String id, Exception ex, String message, Object[] arguments) in C:\\Users\\xxx\\Documents\\duplicati\\Duplicati\\Library\\Logging\\Log.cs:line 332
   at Duplicati.Library.Logging.Log.WriteProfilingMessage(String tag, String id, String message, Object[] arguments) in C:\\Users\\xxx\\Documents\\duplicati\\Duplicati\\Library\\Logging\\Log.cs:line 239
   at Duplicati.Library.Logging.Timer.Dispose() in C:\\Users\\xxx\\Documents\\duplicati\\Duplicati\\Library\\Logging\\Timer.cs:line 64
   at Duplicati.Library.Main.Operation.BackupHandler.<RunMainOperation>d__12.MoveNext() in C:\\Users\\xxx\\Documents\\duplicati\\Duplicati\\Library\\Main\\Operation\\BackupHandler.cs:line 240
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__19.MoveNext() in C:\\Users\\xxx\\Documents\\duplicati\\Duplicati\\Library\\Main\\Operation\\BackupHandler.cs:line 482
```

After the catch block, `finally` is finally executed (pun not intended) and the database is unlocked.

Now I guess the problem turned into finding out why the thread takes a minute to exit

**Comment by kenkendk** [comment]
> Now I guess the problem turned into finding out why the thread takes a minute to exit

If it takes 60s before the `finally` code is running, then there should be some kind of `Wait(60000)` in the code. One potential cultprit could be the snapshot. It would make sense if it takes a little time to "unmount" the snapshot.

**Comment by mikaelmello** [comment]
Apparently it hangs on `AzureBlobWrapper`, therefore I may have been wrong saying it happened on any backend, will test on a random one later to be sure.

![image](https://user-images.githubusercontent.com/17488630/48767918-f5f0ff80-ec9e-11e8-9367-e7ba9091ada9.png)

Called from `AzureBlobBackend`'s `Put()`, here:

https://github.com/duplicati/duplicati/blob/c7e78eed9296c9e114c55608b175863e8186bb69/Duplicati/Library/Main/Operation/Common/BackendHandler.cs#L462-L466

After the apparent upload takes 50 seconds to finish, it returns and the logging exception is thrown here:

https://github.com/duplicati/duplicati/blob/c7e78eed9296c9e114c55608b175863e8186bb69/Duplicati/Library/Main/Operation/Common/BackendHandler.cs#L470

A few lines after the calling of `Put()`

Now, what I get from this is:

1. Could 50s be the time it takes to upload 50MB to remote storage? Probably not since 1MB/s is not my upload speed, but I will check it again just to be sure. Could it be some sort of timeout? I did not find any information about this in the docs.
2. Does that mean it is impossible to "Stop now" a backup? Can we only "Stop after current upload"? I will also check if the latter works as expected.

**Comment by kenkendk** [comment]
> Solve the way scopes are closed before they should.

The log scopes require that the code has finished (the `using` constructs). It should not be possible for the code to return before all finalizers have been executed.

 I think the problem is that the backend process somehow has an extra thread that keeps running even when we abort the main thread.

> I can't seem to find any rendezvous points that check for the control state and whether they should proceed to upload/process files. Probably why "Stop after upload" is not working

Not all backends support cancellation. For the ones that are written for Duplicati, we can add support, but for some, like S3, we use a library and need an abort feature in that library. The control logic is not checked during uploads (in the backend code) but only in the manager code.

I think we need to look at the manager and see if we can get it to terminate the upload.

> Stopping a PUT operation after it has been started, so we can use "Stop now".

I have wanted to fix this for a while, and concluded that there is no good way to force stop a library call, as it is impossible to know which threads and tasks are created inside the library.

I have recently written an inter-process call library for solving this:
https://github.com/kenkendk/LeanIPC

With an IPC library, we can run the manager (or a slimmed down version of it) in another process. This allows us to kill the process, relying on the OS to kill whatever it has started.

I would like to also use the IPC feature to run each backup in an isolated process, as that makes it much simpler to control logging, throttling, locale and other settings on a per-process basis. If the entire backup is running in its own process, we just need to send progress back, and "stop now" is then just "kill process".

**Comment by mikaelmello** [comment]
> I think the problem is that the backend process somehow has an extra thread that keeps running even when we abort the main thread.

I guess that's what's happening. From my observations:

1. IIRC 3 scopes are created during the creation of the backup
2. The backup process uses Scope C for example.
3.  _Stop now_ is called and the thread is aborted.
4. All 3 scopes have their `Dispose()` method called.
5. The thread responsible for uploading and some others (such as RunAsync()) keep on running
6. The next time a log function is called, it will call the getter of `CurrentScope`
7. `CurrentScope` will get some GUID from its current scope and try to find it in the lookup table. The GUID is missing because that level was disposed.

> Not all backends support cancellation. For the ones that are written for Duplicati, we can add support, but for some, like S3, we use a library and need an abort feature in that library. The control logic is not checked during uploads (in the backend code) but only in the manager code.
> 
> I think we need to look at the manager and see if we can get it to terminate the upload.

My idea was in the manager, probably in the `BackendHandler` or any other functions that manage the various backup steps (the process is so much more complex than the restore which is basically linear, I'm still understanding how it all works together).

Perhaps checking if the thread has been aborted after each `dblock` upload, each processed file, I don't know, you name it.

> With an IPC library, we can run the manager (or a slimmed down version of it) in another process. This allows us to kill the process, relying on the OS to kill whatever it has started.
> 
> I would like to also use the IPC feature to run each backup in an isolated process, as that makes it much simpler to control logging, throttling, locale and other settings on a per-process basis. If the entire backup is running in its own process, we just need to send progress back, and "stop now" is then just "kill process".

This seems great, the apparent complexity makes me think it is a long term goal, is that right?

---

With the current limitations, what is the best way to proceed, in your opinion?

Also, would a forum topic get more attention than an issue?

**Comment by mikaelmello** [comment]
> That depends... it should not be too much work, but I am not sure how high-priority it is.

We've been testing Duplicati with a few clients and this error hasn't appeared yet, which honestly makes me surprised.

I guess I got this a lot only because I was developing and constantly testing new changes on backup runs.



> > Perhaps checking if the thread has been aborted after each dblock upload, each processed file, I don't know, you name it.
> 
> That would only fix the exception. Simply abort if the stop-flag is set after upload, and avoid logging.

At this quote I was talking about "Stop after upload", since this one seems to not work at all.

> For a quick fix, we can look into the BackendHandler and see if we can get it to abort the runner thread.

Seems good to me.

> Depends on who you want attention from :). I basically get too many inputs, but I can see if you tag me or PM me in the forum.

The community as a whole. In the previous OSS I worked with they suggested forums posts instead of issues because the ones really interested in improving the project were mostly there.

**Comment by youtux** [comment]
I'm experiencing the same problem

**Comment by warwickmm** [comment]
Pull request #3836 should fix some issues we've had with stopping a backup while allowing the current file to finish uploading.

**Comment by warwickmm** [comment]
I believe these issues have been fixed in #3836 and #4042.  Let us know if you continue to experience this and we can reopen this ticket.

**Comment by jeinstei** [comment]
Hi - just got started with Duplicati and are running in to this exact issues in 2.6.3 beta backing up on to an SMB share over a local network. What should I pass on to debug this issue?

**Comment by lapineige** [comment]
I've got a similar issue on a quite fresh backup (done twice, stopped on the 3rd start), which the same question : how to debug that issue ?
