### ISSUE TITLE
2.0.4.3 canary --snapshot-policy Windows VSS System.NullReferenceException regression

### ISSUE THREAD

**Issue by ts678** [duplicati/duplicati#3494]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.3 canary
- **Operating system**: Windows 10 Professional version 1803
- **Backend**: Local folder or drive

## Description

Windows VSS reports failure where 2.0.4.2 canary did not. Typical messages available in the web UI include "System.NullReferenceException: Object reference not set to an instance of an object.", but (as expected) it ranges from red Error popup to red Warning popup to no-UI-impact depending on the --snapshot-policy. Initial discussion in [Release: 2.0.4.3 (canary) 2018-11-13](https://forum.duplicati.com/t/release-2-0-4-3-canary-2018-11-13/5279) found an existing job impacted by 2.0.4.2-to-2.0.4.3 update followed by Windows service restart and another backup run. Testing for GitHub is more extensive.

## Steps to reproduce

1. Set up backup of a short file in a short path, backed up to local folder.
2. Set --snapshot-policy=Required (or On) if you want a popup in the UI. Others require looking in logs.
3. Run now.

- **Actual result**:
Red popup at bottom of screen. The title begins "Error while running" for Required level, with popup content "Object reference not set to an instance of an object". At "On" level the title begins "Warning" and content is "Got 1 warning(s)". See About --> Show log --> Stored, and I'll later show --log-file at --log-level=Profiling. Both are for the "Required" case which is the noisiest, but no case logs no issue.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Duplicati.Library.Common.IO.VssBackupComponents.SetupWriters(Guid[] includedWriters, Guid[] excludedWriters)
   at Duplicati.Library.Snapshots.WindowsSnapshot..ctor(IEnumerable`1 sources, IDictionary`2 options)
   at Duplicati.Library.Snapshots.SnapshotUtility.CreateWindowsSnapshot(IEnumerable`1 folders, Dictionary`2 options)
   at Duplicati.Library.Main.Operation.BackupHandler.GetSnapshot(String[] sources, Options options)
   at Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CoCoL.ChannelExtensions.WaitForTaskOrThrow(Task task)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass13_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
```

 Viewed from --log-file --log-level=Profiling log:

    2018-11-13 10:56:28 -05 - [Verbose-Duplicati.Library.Common.IO.VssBackupComponents-VSSTerminateError]: Failed to signal VSS completion
    Alphaleonis.Win32.Vss.VssBadStateException: The VSS object was in an incorrect state for the requested operation.
       at Alphaleonis.Win32.Vss.VssBackupComponents.BackupComplete()
       at Duplicati.Library.Common.IO.VssBackupComponents.Dispose()
    2018-11-13 10:56:28 -05 - [Verbose-Duplicati.Library.Common.IO.VssBackupComponents-VSSSnapShotDeleteCleanError]: Failed during VSS esnapshot closing
    System.NullReferenceException: Object reference not set to an instance of an object.
       at Duplicati.Library.Common.IO.VssBackupComponents.Dispose()
    2018-11-13 10:56:28 -05 - [Error-Duplicati.Library.Main.Operation.BackupHandler-FatalError]: Fatal error
    System.NullReferenceException: Object reference not set to an instance of an object.
       at Duplicati.Library.Common.IO.VssBackupComponents.SetupWriters(Guid[] includedWriters, Guid[] excludedWriters)
       at Duplicati.Library.Snapshots.WindowsSnapshot..ctor(IEnumerable`1 sources, IDictionary`2 options)
       at Duplicati.Library.Snapshots.SnapshotUtility.CreateWindowsSnapshot(IEnumerable`1 folders, Dictionary`2 options)
       at Duplicati.Library.Main.Operation.BackupHandler.GetSnapshot(String[] sources, Options options)
       at Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__19.MoveNext()
    2018-11-13 10:56:28 -05 - [Profiling-Timer.Finished-Duplicati.Library.Main.Controller-RunBackup]: Running Backup took 0:00:00:01.073

but --snapshot-policy=Off backs this down to:

```
2018-11-13 11:13:30 -05 - [Verbose-Duplicati.Library.Common.IO.VssBackupComponents-VSSTerminateError]: Failed to signal VSS completion
Alphaleonis.Win32.Vss.VssBadStateException: The VSS object was in an incorrect state for the requested operation.
   at Alphaleonis.Win32.Vss.VssBackupComponents.BackupComplete()
   at Duplicati.Library.Common.IO.VssBackupComponents.Dispose()
2018-11-13 11:13:30 -05 - [Verbose-Duplicati.Library.Common.IO.VssBackupComponents-VSSSnapShotDeleteCleanError]: Failed during VSS esnapshot closing
System.NullReferenceException: Object reference not set to an instance of an object.
   at Duplicati.Library.Common.IO.VssBackupComponents.Dispose()
```
- **Expected result**:
Backup uses VSS and makes no noise in web UI, UI server log, or (probably) even --log-file server log.

**Comment by Athep** [comment]
I have the same issue.

**Comment by verhoek** [comment]
Thanks for reporting this. I'm trying to reproduce it. From what you reported earlier, it looks like the vss objects do not get properly initialized.

**Comment by verhoek** [comment]
I found the error and will make a pull request. Thanks again for the bug report!
