### ISSUE TITLE
Onedrive is broken in 2.0.4.4_canary_2018-11-14

### ISSUE THREAD

**Issue by gabrielambuehl** [duplicati/duplicati#3499]
After updating to 2.0.4.4_canary_2018-11-14 I cannot backup to onedrive anymore.

Backup immediately fails with: 

Backend not supported: onedrive

Stacktrace:

Failed: Backend not supported: onedrive
Details: Duplicati.Library.Interface.UserInformationException: Backend not supported: onedrive
   at Duplicati.Library.Main.BackendManager..ctor(String backendurl, Options options, IBackendWriter statwriter, LocalDatabase database)
   at Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CoCoL.ChannelExtensions.WaitForTaskOrThrow(Task task)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass13_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)

**Comment by warwickmm** [comment]
Microsoft has stopped supporting the old One Drive API.  You will have to edit your backup configuration and change the storage type to Microsoft OneDrive v2, and generate a new AuthID.  Your backup should then resume normally.

See below for more details:

https://forum.duplicati.com/t/release-2-0-4-3-canary-2018-11-13/5279
https://forum.duplicati.com/t/setting-up-onedrive-personal/588/24?u=warwickmm
