### ISSUE TITLE
Unique constraints violation in 2.0.4.4

### ISSUE THREAD

**Issue by Kasheen** [duplicati/duplicati#3518]
- [x] I have searched open and closed issues for duplicates.
(Found other unique constraints violation bugs which apparently have been fixed in prior versions).

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.4_canary_2018-11-14
- **Operating system**: Windows 10 Pro Version	10.0.17134 Build 17134
- **Backend**: Stack (WebDAV)

## Description

Running a backup causes the following error since updating to 2.0.4.4:

> constraint failed UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID

## Steps to reproduce

Updated duplicati to 2.0.4.4 from a previous version, I'm not sure what I was running before - I don't update every version but rather every few versions.

Attempted to recreate database which completes successfully but backups still result in the same error.

## Debug log

```System.Data.SQLite.SQLiteException (0x80004005): constraint failed
UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at Duplicati.Library.Main.Database.ExtensionMethods.ExecuteNonQuery(IDbCommand self, Boolean writeLog, String cmd, Object[] values)
   at Duplicati.Library.Main.Database.LocalBackupDatabase.AddFile(String filename, DateTime lastmodified, Int64 blocksetID, Int64 metadataID, IDbTransaction transaction)
   at Duplicati.Library.Main.Operation.Backup.BackupDatabase.<>c__DisplayClass8_0.<AddDirectoryEntryAsync>b__0()
   at Duplicati.Library.Main.Operation.Common.SingleRunner.<>c__DisplayClass3_0.<RunOnMain>b__0()
   at Duplicati.Library.Main.Operation.Common.SingleRunner.<DoRunOnMain>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.Backup.MetadataPreProcess.<AddFolderToOutputAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.Backup.MetadataPreProcess.<ProcessMetadata>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.Backup.MetadataPreProcess.<>c__DisplayClass2_0.<<Run>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CoCoL.AutomationExtensions.<RunTask>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.BackupHandler.<RunMainOperation>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CoCoL.ChannelExtensions.WaitForTaskOrThrow(Task task)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass13_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)`

**Comment by Kasheen** [comment]
In some further troubleshooting I've exported the backup configuration and imported it (without meta) sending it to a different backup directory (full re-upload) and it reports the same constraint violation.

I've also manually re-made the backup (not via an import) and got the same result - constraint violation.

My other backup seems to run fine. I'll see if I can increase the log level to see if it will tell me what file is causing this issue.

**Comment by Kasheen** [comment]
Full un-install of duplicati, removed app data all databases, temp dir etc.

Installed 2.0.4.6_canary_2018-12-11 from releases.

Imported backup configuration with full re-upload: Same unique constraints violation error. Backup doesn't complete and no log is generated under the backup to get error details.

**Comment by Kasheen** [comment]
I've been able to do a bit more information gathering on this bug.

I've noticed the backup executes if I exclude the AppData folder in my user profile.

From there I enabled file logging as I've seen @kenkendk suggest in some forum posts with
`log-file-log-filter=+*.FileEntry*`

and

`log-file=somepath`

The lines of the log file directly preceding the exception are:
````
2019-01-07 13:27:45 +00 - [Verbose-Duplicati.Library.Main.Operation.Backup.FilePreFilterProcess.FileEntry-CheckFileForChanges]: Checking file for changes C:\Users\XXXXXX XXXXX\AppData\Local\Packages\Microsoft.Windows.Cortana_cw5n1h2txyewy\LocalState\AppIconCache\100\{D65231B0-B2F1-4857-A4CE-A8E7C6EA7D27}_WindowsPowerShell_v1_0_powershell_exe, new: True, timestamp changed: True, size changed: True, metadatachanged: True, 03/01/2019 21:21:01 vs 01/01/0001 00:00:00
2019-01-07 13:27:45 +00 - [Verbose-Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.FileEntry-NewFile]: New file C:\Users\XXXXXX XXXXX\AppData\Local\Packages\Microsoft.Windows.Cortana_cw5n1h2txyewy\LocalState\AppIconCache\100\{D65231B0-B2F1-4857-A4CE-A8E7C6EA7D27}_odbcad32_exe
2019-01-07 13:27:45 +00 - [Verbose-Duplicati.Library.Main.Operation.Backup.MetadataPreProcess.FileEntry-AddDirectory]: Adding directory C:\Users\XXXXXX XXXXX\AppData\Local\Packages\Microsoft.Windows.Cortana_cw5n1h2txyewy\LocalState\
2019-01-07 13:27:45 +00 - [Verbose-Duplicati.Library.Main.Operation.Backup.FilePreFilterProcess.FileEntry-CheckFileForChanges]: Checking file for changes C:\Users\XXXXXX XXXXX\AppData\Local\Packages\Microsoft.Windows.Cortana_cw5n1h2txyewy\LocalState\AppIconCache\100\{D65231B0-B2F1-4857-A4CE-A8E7C6EA7D27}_WindowsPowerShell_v1_0_PowerShell_ISE_exe, new: True, timestamp changed: True, size changed: True, metadatachanged: True, 03/01/2019 21:21:01 vs 01/01/0001 00:00:00
2019-01-07 13:27:45 +00 - [Verbose-Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.FileEntry-NewFile]: New file C:\Users\XXXXXX XXXXX\AppData\Local\Packages\Microsoft.Windows.Cortana_cw5n1h2txyewy\LocalState\AppIconCache\100\{D65231B0-B2F1-4857-A4CE-A8E7C6EA7D27}_WindowsPowerShell_v1_0_powershell_exe
2019-01-07 13:27:45 +00 - [Verbose-Duplicati.Library.Main.Operation.Backup.MetadataPreProcess.FileEntry-AddDirectory]: Adding directory C:\Users\XXXXXX XXXXX\AppData\Local\Packages\Microsoft.Windows.Cortana_cw5n1h2txyewy\LocalState\Signals\
2019-01-07 13:27:45 +00 - [Verbose-Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.FileEntry-NewFile]: New file C:\Users\XXXXXX XXXXX\AppData\Local\Packages\Microsoft.Windows.Cortana_cw5n1h2txyewy\LocalState\AppIconCache\100\{D65231B0-B2F1-4857-A4CE-A8E7C6EA7D27}_WindowsPowerShell_v1_0_PowerShell_ISE_exe
2019-01-07 13:31:07 +00 - [Error-Duplicati.Library.Main.Operation.BackupHandler-FatalError]: Fatal error
System.Data.SQLite.SQLiteException (0x80004005): constraint failed
UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID
````

So then I decided to just try to backup the directory causing the error:
`C:\Users\XXXXXX XXXXX\AppData\Local\Packages\Microsoft.Windows.Cortana_cw5n1h2txyewy\`

At which point the log changed slightly to:
````
2019-01-07 19:40:57 +00 - [Verbose-Duplicati.Library.Main.Operation.Backup.FilePreFilterProcess.FileEntry-CheckFileForChanges]: Checking file for changes C:\Users\XXXXXX XXXXX\AppData\Local\Packages\Microsoft.Windows.Cortana_cw5n1h2txyewy\LocalState\AppIconCache\100\{D65231B0-B2F1-4857-A4CE-A8E7C6EA7D27}_WindowsPowerShell_v1_0_powershell_exe, new: True, timestamp changed: True, size changed: True, metadatachanged: True, 03/01/2019 21:21:01 vs 01/01/0001 00:00:00
2019-01-07 19:40:57 +00 - [Verbose-Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.FileEntry-NewFile]: New file C:\Users\XXXXXX XXXXX\AppData\Local\Packages\Microsoft.Windows.Cortana_cw5n1h2txyewy\LocalState\AppIconCache\100\{D65231B0-B2F1-4857-A4CE-A8E7C6EA7D27}_odbcad32_exe
2019-01-07 19:40:57 +00 - [Verbose-Duplicati.Library.Main.Operation.Backup.FilePreFilterProcess.FileEntry-CheckFileForChanges]: Checking file for changes C:\Users\XXXXXX XXXXX\AppData\Local\Packages\Microsoft.Windows.Cortana_cw5n1h2txyewy\LocalState\AppIconCache\100\{D65231B0-B2F1-4857-A4CE-A8E7C6EA7D27}_WindowsPowerShell_v1_0_PowerShell_ISE_exe, new: True, timestamp changed: True, size changed: True, metadatachanged: True, 03/01/2019 21:21:01 vs 01/01/0001 00:00:00
2019-01-07 19:40:57 +00 - [Verbose-Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.FileEntry-NewFile]: New file C:\Users\XXXXXX XXXXX\AppData\Local\Packages\Microsoft.Windows.Cortana_cw5n1h2txyewy\LocalState\AppIconCache\100\{D65231B0-B2F1-4857-A4CE-A8E7C6EA7D27}_WindowsPowerShell_v1_0_powershell_exe
2019-01-07 19:40:57 +00 - [Verbose-Duplicati.Library.Main.Operation.Backup.MetadataPreProcess.FileEntry-AddDirectory]: Adding directory C:\Users\XXXXXX XXXXX\AppData\Local\Packages\Microsoft.Windows.Cortana_cw5n1h2txyewy\LocalState\
2019-01-07 19:40:57 +00 - [Verbose-Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.FileEntry-NewFile]: New file C:\Users\XXXXXX XXXXX\AppData\Local\Packages\Microsoft.Windows.Cortana_cw5n1h2txyewy\LocalState\AppIconCache\100\{D65231B0-B2F1-4857-A4CE-A8E7C6EA7D27}_WindowsPowerShell_v1_0_PowerShell_ISE_exe
2019-01-07 19:40:57 +00 - [Verbose-Duplicati.Library.Main.Operation.Backup.MetadataPreProcess.FileEntry-AddDirectory]: Adding directory C:\Users\XXXXXX XXXXX\AppData\Local\Packages\Microsoft.Windows.Cortana_cw5n1h2txyewy\LocalState\Signals\
2019-01-07 19:41:05 +00 - [Error-Duplicati.Library.Main.Operation.BackupHandler-FatalError]: Fatal error
System.Data.SQLite.SQLiteException (0x80004005): constraint failed
UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID
````

In other posts @kenkendk has mentioned the file directly before the exception is the offending file but in this case that's different in both logs. Not sure if the log is being written from two threads and a race condition is occurring when the log entries get serialised?

I'm not really bothered about backing up these files, but I'm concerned this points to some kind of bug in Duplicati so I'll keep the issue open for now in case anyone has any suggestions I can try for debugging.

When I get more time I'll see if I can narrow down the specific offending file causing the constraints violation, until then these are my findings so far.

**Comment by AntiBlueQuirk** [comment]
Actually, I don't think this is a file system corruption bug. Or if it is, it's consistent from the program that creates the folder. I've just had the exact same problem happen in 2.0.4.22_canary_2019-06-30, and it's happening because of the very same directory.

I get this stack trace, right before the UNIQUE constraint failed one:
```
2019-08-31 10:34:45 -05 - [Warning-Duplicati.Library.Main.Operation.Backup.MetadataGenerator.Metadata-MetadataProcessFailed]: Failed to process metadata for "C:\Users\Username\AppData\Local\Packages\Microsoft.Windows.Cortana_cw5n1h2txyewy\LocalState..\speech_onecorereg.bin", storing empty metadata
System.IO.FileNotFoundException: C:\Users\Username\AppData\Local\Packages\Microsoft.Windows.Cortana_cw5n1h2txyewy\LocalState..\speech_onecorereg.bin
   at System.Security.AccessControl.NativeObjectSecurity.CreateInternal(ResourceType resourceType, Boolean isContainer, String name, SafeHandle handle, AccessControlSections includeSections, Boolean createByName, ExceptionFromErrorCode exceptionFromErrorCode, Object exceptionContext)
   at System.Security.AccessControl.FileSystemSecurity..ctor(Boolean isContainer, String name, AccessControlSections includeSections, Boolean isDirectory)
   at System.Security.AccessControl.FileSecurity..ctor(String fileName, AccessControlSections includeSections)
   at System.IO.File.GetAccessControl(String path)
   at Duplicati.Library.Common.IO.SystemIOWindows.PathTooLongFuncWrapper[T](Func`2 nativeIOFunc, Func`2 alternativeIOFunc, String path, Boolean prefixWithUnc)
   at Duplicati.Library.Common.IO.SystemIOWindows.GetAccessControlFile(String path)
   at Duplicati.Library.Common.IO.SystemIOWindows.GetMetadata(String path, Boolean isSymlink, Boolean followSymlink)
   at Duplicati.Library.Main.Operation.Backup.MetadataGenerator.GenerateMetadata(String path, FileAttributes attributes, Options options, ISnapshotService snapshot)
```

I'm guessing something about the directory name is confusing Duplicati (or possibly something in the system/C# IO stack). Probably something in the filename handling is stripping the trailing dots and Duplicati ends up trying to process the same file/name twice. I'm not sure if this is Duplicati's bug or not, but the problem definitely needs to be handled more gracefully at least, since it's reproducible, and can cause whole backups to fail. Luckily, I'm on my first backup, so I haven't lost anything. (Except for two days uploading stuff to the cloud. :( Oh well.)

If nothing else, adding a filter for "Exclude directories whose name contains"="Microsoft.Windows.Cortana" seems to workaround the problem. I don't think there's anything really important in that folder.

**Comment by Kasheen** [comment]
If you're getting it on a similar path then it looks like the Cortana component of windows is somehow generating these directories, it's possibly a bug in that software.

I'd agree that it might be reasonable for Duplicati to make its path handling more robust now that we know these oddball paths an exist in the wild.

There's also [an article on MSDN](https://docs.microsoft.com/en-gb/windows/win32/fileio/naming-a-file) which states the following:

> Do not end a file or directory name with a space or a period. Although the underlying file system may support such names, the Windows shell and user interface does not. However, it is acceptable to specify a period as the first character of a name. For example, ".temp".

Which indicates that it may not necessarily be considered "corruption" to have such a path on the filesystem, but the article seems to recognise it's a bad idea and can lead to difficulties in software having to handle such paths.

**Comment by warwickmm** [comment]
Support for problematic paths (ending with spaces or periods) was added in pull request #4256.
