### ISSUE TITLE
Misleading error information when a source file or folder is missing

### ISSUE THREAD

**Issue by mikaelmello** [duplicati/duplicati#3522]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.5_beta 
- **Operating system**: Windows 10
- **Backend**: Any

## Description

Whenever a source file or folder is missing an exception is thrown with the following possible errors:

https://github.com/duplicati/duplicati/blob/1b54cd61077dabbd00b7fdb40ac8dda537b64c3a/Duplicati/Library/Main/Controller.cs#L925-L933

Their strings are very misleading as it says there are missing source *folders*, which led me to believe that the error I got because I deleted a zip file meant that Duplicati treated zip files as folders. In fact I wrote an entire issue before realizing this also happened with MSI files, and then exe files, and then any file.

It also does not give a hint on how to proceed from there. The error message should indicate whether it is a file or an entire folder missing and how to go from there. As far as I know you can either restore the files (if they were previously backup'ed) or remove them from the backup configuration.

```
System.IO.IOException: The source folder C:\xxx\yyy\zzz.manifest does not exist, aborting backup
   at Duplicati.Library.Main.Controller.ExpandInputSources(String[] inputsources, IFilter filter) in C:\lll\Duplicati\Library\Main\Controller.cs:line 934
   at Duplicati.Library.Main.Controller.<>c__DisplayClass13_0.<Backup>b__0(BackupResults result) in C:\lll\Duplicati\Library\Main\Controller.cs:line 118
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method) in C:\lll\Duplicati\Library\Main\Controller.cs:line 455
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter) in C:\lll\Duplicati\Library\Main\Controller.cs:line 115
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue) in C:\lll\Duplicati\Server\Runner.cs:line 509
```

**Comment by mikaelmello** [comment]
Adding to the issue: this is only thrown when the folder/file missing is explicitly marked as source. If it belongs to a source, the backup simply marks that file/folder as deleted.
