### ISSUE TITLE
Jottacloud upload is failing since November 19th

### ISSUE THREAD

**Issue by FredericMa** [duplicati/duplicati#3529]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.5_beta_2018-11-28
- **Operating system**: Windows Server 2012
- **Backend**: Jottacloud

## Description

Today I figured out that my backups are failing since November 19th.
I installed the new beta today but this doesn't solve the issue.

## Steps to reproduce

1. Run any backup to Jottacloud

- **Actual result**:
Error message
- **Expected result**:
Succesful backup

## Screenshots

![image](https://user-images.githubusercontent.com/7840263/49469100-ec22dc80-f806-11e8-946e-949eb0ca5499.png)

## Debug log

NOTE: if I run the backup manually I get the error message as seen in the screenshot above. If i check the log file, the last error message is from last night, triggered according to schedule: "Dec 4, 2018 12:00 PM: Message"
```
Fatal error
System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.ComponentModel.Win32Exception: The client and server cannot communicate, because they do not possess a common algorithm
   at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface SecModule, String package, CredentialUse intent, SecureCredential scc)
   at System.Net.Security.SecureChannel.AcquireCredentialsHandle(CredentialUse credUsage, SecureCredential& secureCredential)
   at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint)
   at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
   at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.BackendManager.List()
   at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)
   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
```

**Comment by mikaelmello** [comment]
@albertony, do you have any initial idea of why this could happen?

**Comment by mikaelmello** [comment]
I think I have it figured out. Do you use Duplicati as a service? It looks like this error is caused by not using TLS 1.2 and Duplicati only "activates" TLS 1.2 when running on a TrayIcon.

**Comment by albertony** [comment]
I was also just thinking if it could be related to TLS, and not Jottacloud authentication changes (https://blog.jottacloud.com/upcoming-changes-to-jottacloud-authentication-25e4d521c888). TLS 1.2 explanation sounds plausible.

**Comment by mikaelmello** [comment]
I encountered this problem when using Azure a couple months ago, fixed it by simply adding this on `Server` startup

https://github.com/LacunaSoftware/duplicati/commit/82aa76e7815dd5e0391cb7f25ffedfe134ebc33e

**Comment by FredericMa** [comment]
It's strange that this started at November 19th. As far as I can remember I didn't change something to the server.
I did install some Windows updated on November 16th but the server has already been restarted after installation so if that was the cause I would expect that the backup already started failing on November 17..

**Comment by mikaelmello** [comment]
> What will be the easiest way to solve this issue in this case?

I'm not sure there is an easy way for now. We could try to find some hacky way or even go as far as manually replacing one of your binaries. The safest option would be to wait for us to roll a PR and update to the next canary (if you are okay with the other changes).

> It's strange that this started at November 19th. As far as I can remember I didn't change something to the server.

Perhaps Jottacloud themselves restricted to TLS 1.2 only in that date.

**Comment by FredericMa** [comment]
>  The safest option would be to wait for us to roll a PR and update to the next canary (if you are okay with the other changes)

Sure, that's fine for me. So this commit you described above is not yet in the beta of duplicati? It will be that change that should fix the issue?

**Comment by mikaelmello** [comment]
This commit is from a fork of Duplicati that I maintain, at the time I
didn't think of suggesting a change here because I thought the error was
specific to my use case. I'll tag @kenkendk and see what he thinks about it

Em qua, 5 de dez de 2018 19:49, FredericMa <notifications@github.com
escreveu:

**Comment by FredericMa** [comment]
@mikaelmello , I downloaded the source code of the latest beta and added the change you mentioned above.
I compiled it and replaced the Duplicati.Server.exe.
It seems to be working now. One backup set already succeeded.
Note: on my server duplicati is running as a service but I use AlwaysUp to run several programs as a service so it is actually starting Duplicati.Server.exe.

**Comment by mikaelmello** [comment]
I'm glad to hear it worked!

**Comment by FredericMa** [comment]
Thank you for the help.
I think it is better to leave this issue open until a fix is in the master branch or shall I close it?

**Comment by mikaelmello** [comment]
I guess it's better to leave it open while the underlying cause isn't really fixed.

**Comment by FredericMa** [comment]
Hi,
Just wanted to let you guys know that I still experience this issue with the latest beta.
I applied the same change as I did with the previous beta.

**Comment by ts678** [comment]
On unpatched code, does adding Tls12 to option [--allowed-ssl-versions](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#allowed-ssl-versions) work? It'd beat patching.
We should consider changing the current default (which I think is Microsoft-historical-and-aging).

**Comment by mikaelmello** [comment]
@ts678, if I had to guess I'd say yes. Could you try it?

**Comment by FredericMa** [comment]
I'll check it out when I'm back from holiday. I guess somewhere within the next 3 days.

**Comment by FredericMa** [comment]
I tried to use the --allowed-ssl-versions parameter but it doesn't solve the issue.
To be complete, I ran this from a command prompt:
`Duplicati.Server.exe --allowed-ssl-versions=SystemDefault,Ssl3,Tls,Tls12`

**Comment by kenkendk** [comment]
Closing this as the SSL/TLS implementation is updated.
