### ISSUE TITLE
Report shows a lot of debug info and questionable info ("Could not find file")

### ISSUE THREAD

**Issue by Stift** [duplicati/duplicati#3530]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.5 (2.0.4.5_beta_2018-11-28)
- **Operating system**: Windows 10 x64
- **Backend**: AWS S3

## Description

I got an email report showing in the Log Data Field the following content (some data replaced for privacy reasons):
```
2018-12-05 19:00:53 +01 - [Warning-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-FileAccessError]: Error reported while accessing file: C:\Users\*replaced*\AppData\Local\Google\Chrome\User Data\Default\Cache\f_002eea
System.IO.FileNotFoundException: Could not find file 'C:\Users\*replaced*\AppData\Local\Google\Chrome\User Data\Default\Cache\f_002eea'.
File name: 'C:\Users\*replaced*\AppData\Local\Google\Chrome\User Data\Default\Cache\f_002eea'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.GetAttributes(String path)
   at Duplicati.Library.Snapshots.SystemIOWindows.GetFileAttributes(String path)
   at Duplicati.Library.Utility.Utility.<EnumerateFileSystemEntries>d__23.MoveNext()
```
This message appears for multiple times (~ 20 times) for multiple files

## Steps to reproduce

Nothing to reproduce

- **Actual result**:
Too many error messages which don't say what can be done to remediate the situation. And also the call stack is not very user friendly and not helpful for an end user.

- **Expected result**:
Either a good error message describing what the problem is, or when a missing file (which maybe vanished after creating a file list) is no problem, this error should not appear.

**Comment by olehj** [comment]
If it's all cache files (like the file above), I believe they get deleted during the backup. There's simply -no real- reason to backup cache files, just add them into "exclude".

**Comment by Stift** [comment]
Thanks for the clarification. I just reported it, because it's quite inconvenient to report stacktraces.

**Comment by mikaelmello** [comment]
Is this issue resolved?

**Comment by Stift** [comment]
I think @olehj answer is not related to sth else.
I don't know whether this qualifies as bug or inconvenience for you, it's definetely not a blocker. But I haven't seen a solution so far.

**Comment by kadavris** [comment]
Hello! I want to add my 2 cents.

The problem here is not only the missing clarification of an error, which is nice to have of course.
But for me it is mostly that:
1. There are flood of exception messages like these in every log and e-mails.
  IMHO for the end-user these are either:
  a) a clutter that masks any real problems because of the sheer volume of this matter.
  To highlight what I mean, look at this entry:

2021-11-03 14:01:45 +02 - [Warning-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-FileAccessError]: Error reported while accessing file: C:\Users\OVRLibraryService\
System.UnauthorizedAccessException: Access to the path '\\?\C:\Users\OVRLibraryService' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetDirectories(String path)
   at Duplicati.Library.Snapshots.NoSnapshotWindows.ListFolders(String localFolderPath)
   at Duplicati.Library.Utility.Utility.<EnumerateFileSystemEntries>d__21.MoveNext()

But that is not a temporary file. It is a folder that has very strict access rights. SYSTEM + service's user

And this is surprisingly followed by:

2021-10-06 12:45:10 +03 - [Warning-Duplicati.Library.Main.Operation.Backup.MetadataGenerator.Metadata-MetadataProcessFailed]: Failed to process metadata for "C:\Users\OVRLibraryService\", storing empty metadata
System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at System.Security.AccessControl.Win32.GetSecurityInfo(ResourceType resourceType, String name, SafeHandle handle, AccessControlSections accessControlSections, RawSecurityDescriptor& resultSd)
   at System.Security.AccessControl.NativeObjectSecurity.CreateInternal(ResourceType resourceType, Boolean isContainer, String name, SafeHandle handle, AccessControlSections includeSections, Boolean createByName, ExceptionFromErrorCode exceptionFromErrorCode, Object exceptionContext)
   at System.Security.AccessControl.FileSystemSecurity..ctor(Boolean isContainer, String name, AccessControlSections includeSections, Boolean isDirectory)
   at System.Security.AccessControl.DirectorySecurity..ctor(String name, AccessControlSections includeSections)
   at Duplicati.Library.Common.IO.SystemIOWindows.GetMetadata(String path, Boolean isSymlink, Boolean followSymlink)
   at Duplicati.Library.Main.Operation.Backup.MetadataGenerator.GenerateMetadata(String path, FileAttributes attributes, Options options, ISnapshotService snapshot)

And what's most annoying there are at least _two_ _pair_ of such messages per inaccessible entity in log.

b) a source of frustration and anxiety because for an instance, even while I'm well 30+ years into programming, I do not know java closely, so when I see exception in backup log I'm starting to be nervous, right?
God knows what are non-IT people start to imagine.

2. Another problem with windows in particular is that there are a wild zoo in the C:\Users\<username>\AppData.
   There are vital application data, logs, caches and just cryptic stuff everywhere.
   It is extremely difficult to put it all into exception lists with any level of flexibility. even regexp-based.

So the basic solution as I see it is just catch exceptions and log it w/o debug info for now.
Maybe it is a good idea to make exclude type that can suppress these at all in the given path.
This may lead to loss of data of course, if not managed correctly, but flooded log is not useful anyway as you cannot really assess what is the real problem and what is just noise

Thank you!
