### ISSUE TITLE
Unable to recover initial backup due to repair deadlock

### ISSUE THREAD

**Issue by stub42** [duplicati/duplicati#3546]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.5_beta_2018-11-28
- **Operating system**: Ubuntu 18.04
- **Backend**: Backblaze

## Description

Backup refuses to run because repair needs to run. eg. "The database was attempted repaired, but the repair did not complete. This database may be incomplete and the backup process cannot continue. You may delete the local database and attempt to repair it again."

Delete and repair fails because "No filelists found on the remote destination"

## Steps to reproduce

1. Kick of a new backup job
2. Shutdown the computer before the initial backup has completed, causing a database inconsistency requiring repair

- **Actual result**:

Backup is unrecoverable. Remote files need to be removed, or a new target used.

- **Expected result**:

Repair works, even if no initial backup has been made.

**Comment by Pectojin** [comment]
I think this is more an issue with the expectation of repair, rather than an actual deadlock.

No dlist files are produced in the backend until first backup is completed. Meanwhile the repair command seems to only work if at least 1 dlist file exists.

I think the resolution is to make repair accept there being no dlist files available so it's possible to recreate the DB and resume an initial upload. 

It should still throw a warning about no dlist being available since this is an issue if there used to be dlist files.

**Comment by Marv2190** [comment]
Having the same "Bug" right now. I think the problem is that Duplicati dont scan which files are on the source and destination. It just compares its databases. If the Database is lost on the Source (do to delete and recreate) and no database was ever written to the destination - everything is lost?
Why the destination Database is not written after each Block/Chunk upload?

**Comment by GiovanH** [comment]
I believe I've run into the same issue with Google Drive. 
When I attempt to backup, it asks me to run repair, because there are remote files.
When I attempt to run repair, it says there are no filelists found on the remote destination. 

The remote destination is a new directory that I created for duplicati. I ran a partial backup once, but I can't repair and continue due to this issue. 

Logs below
## Debug log
Failed while executing "Repair" with id: 6
```
Duplicati.Library.Interface.UserInformationException: No filelists found on the remote destination
   at Duplicati.Library.Main.Operation.RecreateDatabaseHandler.DoRun(LocalDatabase dbparent, Boolean updating, IFilter filter, NumberedFilterFilelistDelegate filelistfilter, BlockVolumePostProcessor blockprocessor)
   at Duplicati.Library.Main.Operation.RecreateDatabaseHandler.Run(String path, IFilter filter, NumberedFilterFilelistDelegate filelistfilter, BlockVolumePostProcessor blockprocessor)
   at Duplicati.Library.Main.Operation.RepairHandler.RunRepairLocal(IFilter filter)
   at Duplicati.Library.Main.Operation.RepairHandler.Run(IFilter filter)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Repair(IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
```

Failed while executing "Backup" with id: 6
```
Duplicati.Library.Interface.UserInformationException: Found 12832 remote files that are not recorded in local storage, please run repair
   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CoCoL.ChannelExtensions.WaitForTaskOrThrow(Task task)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass13_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
```
