### ISSUE TITLE
The version(s) being updated to, already exists

### ISSUE THREAD

**Issue by GSPP** [duplicati/duplicati#3587]
I tried to restore directly from source a large backup. This was a multi-day operation with multiple internet interruptions, laptop sleep times and many times I paused the server.

At the same time I did another restore from source but only to the point where the file list is shown. I can see that list now. This is relevant because I cannot determine which operation caused the errors I am about to mention.

At the end of this operation I now receive these errors:

![image](https://user-images.githubusercontent.com/12032350/50740261-30c9db00-11ec-11e9-871d-aadc69d4c53d.png)

The top popup leads to this log when I click show:

> {
>   "MainOperation": "Repair",
>   "ParsedResult": "Success",
>   "Version": "2.0.4.10 (2.0.4.10_canary_2018-12-29)",
>   "EndTime": "2019-01-04T11:41:33.5980016Z",
>   "BeginTime": "2019-01-04T11:40:46.5720416Z",
>   "Duration": "00:00:47.0259600",
>   "MessagesActualLength": 7,
>   "WarningsActualLength": 0,
>   "ErrorsActualLength": 0,
>   "Messages": [
>     "2019-01-04 12:40:46 +01 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Repair has started",
>     "2019-01-04 12:40:47 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  ()",
>     "2019-01-04 12:40:48 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (199 bytes)",
>     "2019-01-04 12:40:48 +01 - [Information-Duplicati.Library.Main.Operation.RecreateDatabaseHandler-RebuildStarted]: Rebuild database started, downloading 1 filelists",
>     "2019-01-04 12:40:48 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-20181109T112539Z.dlist.zip.aes (9.76 MB)",
>     "2019-01-04 12:40:55 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Completed: duplicati-20181109T112539Z.dlist.zip.aes (9.76 MB)",
>     "2019-01-04 12:41:33 +01 - [Information-Duplicati.Library.Main.Operation.RecreateDatabaseHandler-RecreateOrUpdateOnly]: Recreate/path-update completed, not running consistency checks"
>   ],
>   "Warnings": [],
>   "Errors": [],
>   "BackendStatistics": {
>     "RemoteCalls": 2,
>     "BytesUploaded": 0,
>     "BytesDownloaded": 10236557,
>     "FilesUploaded": 0,
>     "FilesDownloaded": 1,
>     "FilesDeleted": 0,
>     "FoldersCreated": 0,
>     "RetryAttempts": 0,
>     "UnknownFileSize": 0,
>     "UnknownFileCount": 0,
>     "KnownFileCount": 0,
>     "KnownFileSize": 0,
>     "LastBackupDate": "0001-01-01T00:00:00",
>     "BackupListCount": 0,
>     "TotalQuotaSpace": 0,
>     "FreeQuotaSpace": 0,
>     "AssignedQuotaSpace": 0,
>     "ReportedQuotaError": false,
>     "ReportedQuotaWarning": false,
>     "MainOperation": "Repair",
>     "ParsedResult": "Success",
>     "Version": "2.0.4.10 (2.0.4.10_canary_2018-12-29)",
>     "EndTime": "0001-01-01T00:00:00",
>     "BeginTime": "2019-01-04T11:40:46.5720416Z",
>     "Duration": "00:00:00",
>     "MessagesActualLength": 0,
>     "WarningsActualLength": 0,
>     "ErrorsActualLength": 0,
>     "Messages": null,
>     "Warnings": null,
>     "Errors": null
>   }
> }

![image](https://user-images.githubusercontent.com/12032350/50740280-7ab2c100-11ec-11e9-81b4-a78519b48bb3.png)

"List" has no errors in it.

![image](https://user-images.githubusercontent.com/12032350/50740274-5c4cc580-11ec-11e9-8b75-d5549730cbed.png)

The time stamp seems wrong. Only today (2019-01-06) did the errors show up and I know that both operations only completed today.

The other popups seem to lead to the same log.

<hr>

I know that this is not a lot of information but it seems that this is all there is.

## Environment info

- **Duplicati version**: 2.0.4.10 (2.0.4.10_canary_2018-12-29)
- **Operating system**: Windows 7 x64
- **Backend**: Mega

**Comment by GSPP** [comment]
I found more logs in `About`:

Duplicati.Library.Interface.UserInformationException: The version(s) being updated to, already exists
   at Duplicati.Library.Main.Operation.RecreateDatabaseHandler.RunUpdate(IFilter filter, NumberedFilterFilelistDelegate filelistfilter, BlockVolumePostProcessor blockprocessor)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass26_0.<UpdateDatabaseWithVersions>b__0(RecreateDatabaseResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.UpdateDatabaseWithVersions(IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

![image](https://user-images.githubusercontent.com/12032350/50740552-71c3ee80-11f0-11e9-845c-b627fd8843f3.png)


I don't know why the message would be there twice at the same timestamp.

**Comment by JonMikelV** [comment]
Is this the same as https://github.com/duplicati/duplicati/issues/2275?

This is pure speculation but I suspect one Duplicati database (likely the main db) was included in the backup but NOT the other (likely job db) and that the backed up version was from an ODER version of Duplicati.  The older DB causes an update attempt which likely succeeds on that DB but fails on the other one that is already at the newer version level.
