### ISSUE TITLE
Backup failed after a while, then missing files, then cant restore Database

### ISSUE THREAD

**Issue by Marv2190** [duplicati/duplicati#3627]
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.5_beta_2018-11-28
- **Operating system**: Win7
- **Backend**: GDrive

## Description

Hello Folks,
In my search for a good sync Programm i came across Duplicati. I started a Backup of one of my Drives (1TB) and my PC crashed as i was to crack the 600GB Mark. After rebbot i coulnd start the backup again : 
"Some missing files, please repair" I clicked repair Database but same error like before. After this I tried Delete and recreate Database but it end up with "No filelists found on the remote destination".

## Steps to reproduce

1. Start a Backup
2. Stop the Process of Duplicati (kill it)
3. 

- **Actual result**:
I cant start my backup, seems i need to restart from sratch
- **Expected result**:
Duplicati sees there are missing files, analyze which and tries to reupload them.
Or Database is recreated from the cloud.

**Comment by warwickmm** [comment]
I'm not sure if this is relevant, but I think Google Drive has a 750 GB daily upload limit.  Have you tried testing with a smaller configuration to see if that works?

**Comment by Marv2190** [comment]
Just found this : 
https://github.com/duplicati/duplicati/issues/3546

**Comment by GiovanH** [comment]
I believe I've run into the same issue with Google Drive. 
When I attempt to backup, it asks me to run repair, because there are remote files.
When I attempt to run repair, it says there are no filelists found on the remote destination. 

The remote destination is a new directory that I created for duplicati. I ran a partial backup once, but I can't repair and continue due to this issue. 

Logs below
## Debug log
Failed while executing "Repair" with id: 6
```
Duplicati.Library.Interface.UserInformationException: No filelists found on the remote destination
   at Duplicati.Library.Main.Operation.RecreateDatabaseHandler.DoRun(LocalDatabase dbparent, Boolean updating, IFilter filter, NumberedFilterFilelistDelegate filelistfilter, BlockVolumePostProcessor blockprocessor)
   at Duplicati.Library.Main.Operation.RecreateDatabaseHandler.Run(String path, IFilter filter, NumberedFilterFilelistDelegate filelistfilter, BlockVolumePostProcessor blockprocessor)
   at Duplicati.Library.Main.Operation.RepairHandler.RunRepairLocal(IFilter filter)
   at Duplicati.Library.Main.Operation.RepairHandler.Run(IFilter filter)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Repair(IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
```

Failed while executing "Backup" with id: 6
```
Duplicati.Library.Interface.UserInformationException: Found 12832 remote files that are not recorded in local storage, please run repair
   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CoCoL.ChannelExtensions.WaitForTaskOrThrow(Task task)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass13_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
```

**Comment by ts678** [comment]
Steps to reproduce do not cause any issue on current Duplicati backing up to a local folder, however I did enjoy a clean restart.

Kill of Duplicati was with less than 1 GB left on a 6 GB backup, so progress bar was way over on the right. On restart, it went to previous progress bar position quite rapidly (instead of working through the prior files), picked up where it left off, and finished.

I think the pick-up-where-left-off has been around for a long time, however the successful restart after interrupt got more likely partly thanks to an intensive test program of interrupting backups to see what kind of pain can be had. It's still not a great idea.

> Or Database is recreated from the cloud.

This is not possible because the `dlist` file which says what the backup contains isn't uploaded until the backup has completed. Without `dlist` information, all that is at the destination are blocks of data without the information on the files they came from.

It's possible through manual means to avoid uploading same blocks again. This relies on files being deduplicated, as blocks exist. Better plan if a really long backup is anticipated is to do it in smaller increments, so that there is a stable completion periodically.

If one is unlucky enough to have a missing file, the type of file matters. A name can be found in About --> Show log --> Stored.
[2.0.7.100_canary_2023-12-27](https://github.com/duplicati/duplicati/releases/tag/v2.0.7.100-2.0.7.100_canary_2023-12-27) is also better than old versions at putting information in the job log which is a more familiar spot.

I intentionally removed a dindex file. Repair replaced it, as it should. A dblock file has always been tougher, as it contains file data.
[2.0.3.10_canary_2018-08-30](https://github.com/duplicati/duplicati/releases/tag/v2.0.3.10-2.0.3.10_canary_2018-08-30)

> Removed automatic attempts to rebuild dblock files as it is slow and rarely finds all the missing pieces (can be enabled with --rebuild-missing-dblock-files).

In normal times, the more successful way to handle missing dblock files is for [purge-broken-files](https://duplicati.readthedocs.io/en/latest/04-using-duplicati-from-the-command-line/#the-purge-broken-files-command) to remove broken files from the backup, but that was not fixing that for me, and I suspect it's because there's no backup version in DB yet to remove them from.

Because there's possibly at least a little bit left of this issue. I'll leave it open awhile, but it seems things are mostly working nicely.
