### ISSUE TITLE
gpg: public key decryption failed: No pinentry gpg: decryption failed: No secret key 

### ISSUE THREAD

**Issue by numericOverflow** [duplicati/duplicati#3716]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.16_canary_2019-03-28  (though has applied to versions for about a year)
- **Operating system**: Win10x64 (v1703) 
- **Backend**: local (network drive), encrypted using GPG for windows.

## Description

When trying to backup or restore from a task using GPG encryption, the operation fails with a message 

I get this issue intermittently, but can't figure out why.  It seems like once I get the issue, it continues until either I restart.  

## Steps to reproduce

1. Run restore or backup
2. Backup Fails

- **Actual result**:
Backup/restore fails, no prompt for certificate passphrase is shown.  Gui implies it worked, but also says there was an error (confusing).  Log files show clearly the operation failed
- **Expected result**:
Popup from Kleopatra allowing me to enter the passphrase to unlock certificate for GPG operation, then successful backup/restore.

## Screenshots

![duplicati_error_no_pinentry_gpg](https://user-images.githubusercontent.com/3429424/55632286-998b0a00-577f-11e9-91f8-af3e2b227464.jpg)

## Debug log

```
System.Security.Cryptography.CryptographicException: Failed to decrypt data (invalid passphrase?): Decryption failed: gpg: encrypted with 4096-bit RSA key, ID [REDACTED], created 2018-03-02
      "REDACTED <REDACTED@mydomain.com>"
gpg: public key decryption failed: Timeout
gpg: decryption failed: No secret key
 ---> System.Security.Cryptography.CryptographicException: Decryption failed: gpg: encrypted with 4096-bit RSA key, ID [REDACTED], created 2018-03-02
      "REDACTED <REDACTED@mydomain.com>"
gpg: public key decryption failed: Timeout
gpg: decryption failed: No secret key
   at Duplicati.Library.Encryption.GPGStreamWrapper.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at Duplicati.Library.Encryption.EncryptionBase.Decrypt(Stream input, Stream output)
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.AsyncDownloader.AsyncDownloaderEnumerator.AsyncDownloadedFile.get_TempFile()
   at Duplicati.Library.Main.Operation.CompactHandler.DoCompact(LocalDeleteDatabase db, Boolean hasVerifiedBackend, IDbTransaction& transaction, BackendManager sharedBackend)
   at Duplicati.Library.Main.Operation.DeleteHandler.DoRun(LocalDeleteDatabase db, IDbTransaction& transaction, Boolean hasVerifiedBacked, Boolean forceCompact, BackendManager sharedManager)
   at Duplicati.Library.Main.Operation.BackupHandler.CompactIfRequired(BackendManager backend, Int64 lastVolumeSize)
   at Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CoCoL.ChannelExtensions.WaitForTaskOrThrow(Task task)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass13_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
```

**Comment by joel0** [comment]
Would you happen to have a passphrase on the private key used for the backup?  My guess is that when it works, your gpgagent has cached your credentials to the private key.  If this is the case, you'll either need to remove the key's passphrase or ensure the gpgagent has the key unlocked at the time of every backup.

The reasoning behind this theory is because `pinentry` is the program that interactively asks you for your gpg key passphrase.  `pinentry` is not called if the key is already unlocked with a gpgagent.

**Comment by numericOverflow** [comment]
Sorry for such a long delay in my reply.

I do have a passphrase on the private key.  Removing the passphrase is not an option/solution in my case.  For a while, I would see a pop-up entry box for passphrase when duplicati tried to encrypt, but that's not happening.  

You're right that once I unlock the key with passphrase in Kleopatra, then all subsequent backups work as expected and can access the encryption key.  As a stop-gap fix, I was just running Kleopatra and encrypting a dummy file at startup to force a prompt for passphrase on that private key.  Unfortunately, that's a bit of a manual pain and not something you want to be reliant on for an automated backup solution...

I did some digging and noticed that:
- C:\Program Files (x86)\Gpg4win\bin\
  - contains an instance of pinentry.exe
  - is *NOT* in system PATH
- C:\Program Files (x86)\GnuPG\bin\
  - does *NOT* contain an instance of pinentry.exe
  - is in system PATH

This might explain why duplicati can't find pinentry.exe when attempting to process the job.  I've recently added the "C:\Program Files (x86)\Gpg4win\bin\" folder to the system path environmental variable, so I'll be testing if that allows Duplicati to successfully find and prompt with pinentry.  A cursory test was promising, and I'm guessing this might be the fix but will post back after I collect more success data points.
