### ISSUE TITLE
"Create bug report ..." results in syntax error

### ISSUE THREAD

**Issue by KommX** [duplicati/duplicati#3725]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.16
- **Operating system**: Windows 10
- **Backend**: "Local folder or drive" (doesn't matter, I guess)

## Description

The option "Create bug report ..." doesn't work at all.

## Steps to reproduce

1. Open the options for a backup.
2. Click "Create bug report ..."

- **Actual result**:
I get an error message:
`Error while running JOBNAME`
`SQL logic error or missing database near ")": syntax error`

Here's the exception I found in the logs:
```
System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
near ")": syntax error
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at Duplicati.Library.Main.Database.ExtensionMethods.ExecuteNonQuery(IDbCommand self, Boolean writeLog, String cmd, Object[] values)
   at Duplicati.Library.Main.Database.LocalBugReportDatabase.Fix()
   at Duplicati.Library.Main.Operation.CreateBugReportHandler.Run()
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.CreateLogDatabase(String targetpath)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
```

- **Expected result**:
Something without an error

**Comment by ts678** [comment]
[No errors,but no backup for mssql 2005 database](https://forum.duplicati.com/t/no-errors-but-no-backup-for-mssql-2005-database/6301) was a similar report on 2.0.4.15. I'm kind of wondering whether the changes of [Feature/fix path storage2 #3468](https://github.com/duplicati/duplicati/pull/3468) introduced this in [2.0.4.13](https://github.com/duplicati/duplicati/releases/tag/v2.0.4.13-2.0.4.13_canary_2019-01-29) and it's just not seen much because it's not run much. I'll give @Pectojin a heads-up. Meanwhile, can you run a profiling log to catch the offending SQL? It may or may not work -- not everything is logged. Watching live at About --> Show log --> Live --> Profiling may be easier than setting your --log-file to --log-file-log-level=profiling.

**Comment by KommX** [comment]
@ts678 Here's the result of the profiling log you requested.

```
Apr 9, 2019 8:04 PM: The operation CreateLogDb has failed with error: SQL logic error or missing database
 near ")": syntax error
Apr 9, 2019 8:04 PM: Running CreateLogDb took 0:00:00:00.076
Apr 9, 2019 8:04 PM: ExecuteNonQuery: CREATE TABLE "FixedFile" AS SELECT "B"."ID" AS "ID", "A"."Obfuscated" AS "Path", "B"."BlocksetID" AS "BlocksetID", "B"."MetadataID" AS "MetadataID" FROM "PathMap-5BDE1E5B134CAD42A25179362C4C677A" "A", "File" "B" WHERE "A"."RealPath" = "B"."Path") took 0:00:00:00.000
Apr 9, 2019 8:04 PM: Starting - ExecuteNonQuery: CREATE TABLE "FixedFile" AS SELECT "B"."ID" AS "ID", "A"."Obfuscated" AS "Path", "B"."BlocksetID" AS "BlocksetID", "B"."MetadataID" AS "MetadataID" FROM "PathMap-5BDE1E5B134CAD42A25179362C4C677A" "A", "File" "B" WHERE "A"."RealPath" = "B"."Path")
Apr 9, 2019 8:04 PM: ExecuteNonQuery: UPDATE "LogData" SET "Exception" = "ERASED!" WHERE "Exception" LIKE "%/%" OR "Exception" LIKE "%:\%" took 0:00:00:00.000
Apr 9, 2019 8:04 PM: Starting - ExecuteNonQuery: UPDATE "LogData" SET "Exception" = "ERASED!" WHERE "Exception" LIKE "%/%" OR "Exception" LIKE "%:\%"
Apr 9, 2019 8:04 PM: ExecuteNonQuery: UPDATE "LogData" SET "Message" = "ERASED!" WHERE "Message" LIKE "%/%" OR "Message" LIKE "%:\%" took 0:00:00:00.000
Apr 9, 2019 8:04 PM: Starting - ExecuteNonQuery: UPDATE "LogData" SET "Message" = "ERASED!" WHERE "Message" LIKE "%/%" OR "Message" LIKE "%:\%"
Apr 9, 2019 8:04 PM: ExecuteNonQuery: UPDATE "PathMap-5BDE1E5B134CAD42A25179362C4C677A" SET "Obfuscated" = "X:\" || length("RealPath") || "\" || "ID" || (CASE WHEN substr("RealPath", length("RealPath")) = "\" THEN "\" ELSE ".bin" END) took 0:00:00:00.000
Apr 9, 2019 8:04 PM: Starting - ExecuteNonQuery: UPDATE "PathMap-5BDE1E5B134CAD42A25179362C4C677A" SET "Obfuscated" = "X:\" || length("RealPath") || "\" || "ID" || (CASE WHEN substr("RealPath", length("RealPath")) = "\" THEN "\" ELSE ".bin" END)
Apr 9, 2019 8:04 PM: ExecuteNonQuery: INSERT INTO "PathMap-5BDE1E5B134CAD42A25179362C4C677A" ("RealPath") SELECT DISTINCT "Path" FROM "File" ORDER BY "Path" took 0:00:00:00.000
Apr 9, 2019 8:04 PM: Starting - ExecuteNonQuery: INSERT INTO "PathMap-5BDE1E5B134CAD42A25179362C4C677A" ("RealPath") SELECT DISTINCT "Path" FROM "File" ORDER BY "Path"
Apr 9, 2019 8:04 PM: ExecuteNonQuery: CREATE TEMPORARY TABLE "PathMap-5BDE1E5B134CAD42A25179362C4C677A" ("ID" INTEGER PRIMARY KEY, "RealPath" TEXT NOT NULL, "Obfuscated" TEXT NULL) took 0:00:00:00.000
Apr 9, 2019 8:04 PM: Starting - ExecuteNonQuery: CREATE TEMPORARY TABLE "PathMap-5BDE1E5B134CAD42A25179362C4C677A" ("ID" INTEGER PRIMARY KEY, "RealPath" TEXT NOT NULL, "Obfuscated" TEXT NULL)
Apr 9, 2019 8:04 PM: ExecuteScalarInt64: INSERT INTO "Operation" ("Description", "Timestamp") VALUES ("BugReportCreate", 1554833096); SELECT last_insert_rowid(); took 0:00:00:00.031
Apr 9, 2019 8:04 PM: Starting - ExecuteScalarInt64: INSERT INTO "Operation" ("Description", "Timestamp") VALUES ("BugReportCreate", 1554833096); SELECT last_insert_rowid();
Apr 9, 2019 8:04 PM: Scrubbing filenames from database, this may take a while, please wait
Apr 9, 2019 8:04 PM: Starting - Running CreateLogDb
Apr 9, 2019 8:04 PM: The operation CreateLogDb has started
```

**Comment by ts678** [comment]
Does look unbalanced (one more right paren than left paren). Latest source below. Not sure what it intends.

https://github.com/duplicati/duplicati/blob/f4fdb880c04fea837c6136bc2fc592d3205a7c22/Duplicati/Library/Main/Database/LocalBugReportDatabase.cs#L68

**Comment by Pectojin** [comment]
The trailing parenthesis definitely looks misplaced. The query is only valid without it.

I queried my DB manually in SQLite without it and it works fine that way. I'll open a PR to remove it.

**Comment by Pectojin** [comment]
Ah, it's a little more complicated. New errors come up after fixing that :)
<img width="492" alt="Screenshot 2019-04-09 at 21 07 55" src="https://user-images.githubusercontent.com/1561484/55827939-a73be900-5b0b-11e9-823d-7b4c47f9478c.png">

The "table" file is a view now, so it can't be dropped.

But after changing that I can generate a bug report.
