### ISSUE TITLE
The remote server returned an error: (450) File unavailable

### ISSUE THREAD

**Issue by mapl** [duplicati/duplicati#3730]
- [ ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.15
- **Operating system**: Windows Server 2016

## Description
Backup to FTP hangs

## Debug log
Duplicati.CommandLine.BackendTester.exe ftp://.....
Starting run no 0
*** Remote folder is not empty, aborting
Unittest failed: System.Net.WebException: The remote server returned an error: (450) File unavailable (e.g., file busy).
   at System.Net.FtpWebRequest.DataStreamClosed(CloseExState closeState)
   at System.Net.FtpDataStream.System.Net.ICloseEx.CloseEx(CloseExState closeState)
   at System.Net.FtpDataStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at Duplicati.Library.Utility.OverrideableStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.StreamReader.Dispose(Boolean disposing)
   at System.IO.TextReader.Dispose()
   at Duplicati.Library.Backend.FTP.<List>d__20.<>m__Finally1()
   at Duplicati.Library.Backend.FTP.<List>d__20.System.IDisposable.Dispose()
   at Duplicati.CommandLine.BackendTester.Program.Run(List`1 args, Dictionary`2 options, Boolean first)
   at Duplicati.CommandLine.BackendTester.Program.RealMain(String[] _args)

#### Filezilla works fine browsing the backup folder on the remote FTP Server, around 600 files  (total 178GB) already uploaded from successful previous backups

**Comment by mapl** [comment]
switched to ftps (use ssl checkbox), error is gone
