### ISSUE TITLE
Tray icon no longer works/connects after switching the webserver to use an SSL certificate

### ISSUE THREAD

**Issue by Taomyn** [duplicati/duplicati#3794]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.4.18_canary
- **Operating system**: Windows 10/Server 2019
- **Backend**: Wasabi S3

## Description
Tray icon no longer works/connects after switching the webserver to use an SSL certificate

I have tried the **--hosturl** parameter but cannot get it to work

## Steps to reproduce
1. Enable webserver to use SSL certificate, switching it from HTTP to HTTPS
2. Attempt to run the tray icon

- **Actual result**:
```
"C:\Program Files\Duplicati 2\Duplicati.GUI.TrayIcon.exe" --no-hosted-server | more
Request error: System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
   at Duplicati.Library.Utility.AsyncHttpRequest.AsyncWrapper.GetResponseOrStream()
   at Duplicati.Library.Utility.AsyncHttpRequest.GetResponse()
   at Duplicati.GUI.TrayIcon.HttpServerConnection.PerformRequestInternal[T](String method, String endpoint, Dictionary`2 queryparams)
   at Duplicati.GUI.TrayIcon.HttpServerConnection.PerformRequest[T](String method, String urlfragment, Dictionary`2 queryparams)
   at Duplicati.GUI.TrayIcon.HttpServerConnection.UpdateStatus()
   at Duplicati.GUI.TrayIcon.HttpServerConnection..ctor(Uri server, String password, Boolean saltedpassword, PasswordSource passwordSource, Boolean disableTrayIconLogin, Dictionary`2 options)
   at Duplicati.GUI.TrayIcon.Program.StartTray(String[] _args, Dictionary`2 options, String toolkit, HostedInstanceKeeper hosted, String password, Boolean saltedpassword)
Request error: System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
   at Duplicati.Library.Utility.AsyncHttpRequest.AsyncWrapper.GetResponseOrStream()
   at Duplicati.Library.Utility.AsyncHttpRequest.GetResponse()
   at Duplicati.GUI.TrayIcon.HttpServerConnection.PerformRequestInternal[T](String method, String endpoint, Dictionary`2 queryparams)
   at Duplicati.GUI.TrayIcon.HttpServerConnection.PerformRequest[T](String method, String urlfragment, Dictionary`2 queryparams)
   at Duplicati.GUI.TrayIcon.HttpServerConnection.UpdateStatus()
   at Duplicati.GUI.TrayIcon.HttpServerConnection..ctor(Uri server, String password, Boolean saltedpassword, PasswordSource passwordSource, Boolean disableTrayIconLogin, Dictionary`2 options)
   at Duplicati.GUI.TrayIcon.Program.StartTray(String[] _args, Dictionary`2 options, String toolkit, HostedInstanceKeeper hosted, String password, Boolean saltedpassword)
Request error: System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
   at Duplicati.Library.Utility.AsyncHttpRequest.AsyncWrapper.GetResponseOrStream()
   at Duplicati.Library.Utility.AsyncHttpRequest.GetResponse()
   at Duplicati.GUI.TrayIcon.HttpServerConnection.PerformRequestInternal[T](String method, String endpoint, Dictionary`2 queryparams)
   at Duplicati.GUI.TrayIcon.HttpServerConnection.PerformRequest[T](String method, String urlfragment, Dictionary`2 queryparams)
   at Duplicati.GUI.TrayIcon.HttpServerConnection.UpdateStatus()
   at Duplicati.GUI.TrayIcon.HttpServerConnection..ctor(Uri server, String password, Boolean saltedpassword, PasswordSource passwordSource, Boolean disableTrayIconLogin, Dictionary`2 options)
   at Duplicati.GUI.TrayIcon.Program.StartTray(String[] _args, Dictionary`2 options, String toolkit, HostedInstanceKeeper hosted, String password, Boolean saltedpassword)
```
- **Expected result**:
Running tray icon

## Screenshots
n/a

## Debug log
n/a

**Comment by Taomyn** [comment]
Although I swear I tried the --hosturl with the FQDN of the machine and it still didn't work, a few hours later after someone on the forum suggested trying "localhost" which still didn't work, retrying with the FQDN did work. I'm somewhat confused.

Perhaps this should get added to the documentation, and my forum thread can be found [here](https://forum.duplicati.com/t/can-the-tray-icon-in-windows-connect-to-duplicati-webserver-set-as-https/7279)
