### ISSUE TITLE
Duplicati.Library.Main.Volumes.BlockVolumeWriter.AddBlock

### ISSUE THREAD

**Issue by fred-cardoso** [duplicati/duplicati#4036]
- [x] I have searched open and closed issues for duplicates. (and Google :D)

----------------------------------------

## Environment info
I am running Duplicati as a docker instance inside a Raspberry Pi 4 (under OpenMediaVault).
- **Duplicati version**: 2.0.4.23_beta_2019-07-14
- **Operating system**: Debian/GNU Linux 
- **Backend**: OneDrive (v2)

## Description
When I run a backup (first time installation and first time backup) it stops after a while with a error saying "Object reference not set to an instance of an object". I tested less folders locally and it works perfectly. (since I do not have enough space locally) Then I tested again with less folders in the OneDrive and also worked. For some reason if I select everything that I want to backup, eventually the error comes.

The error is somewhat identical to #3328 and #2436.

I also found [this](https://forum.duplicati.com/t/system-nullreferenceexception/8069) and [this](https://forum.duplicati.com/t/backup-fails-with-onedrive-v2-object-reference-not-set-to-an-instance-of-an-object/6240) on the forums. But no answers were given.

Also found out some more information when executing backup and live log (verbose). Apparently there is an error before "The channel is retired".

## Debug log
`System.NullReferenceException: Object reference not set to an instance of an object.
  at Duplicati.Library.Main.Volumes.BlockVolumeWriter.AddBlock (System.String hash, System.Byte[] data, System.Int32 offset, System.Int32 size, Duplicati.Library.Interface.CompressionHint hint) [0x00032] in <e2da9713f0974e76879d9f9aa7ce0e36>:0 
  at Duplicati.Library.Main.Operation.Backup.SpillCollectorProcess+<>c__DisplayClass0_0.<Run>b__0 (<>f__AnonymousType92[<Input>j__TPar,<Output>j__TPar] self) [0x003df] in <e2da9713f0974e76879d9f9aa7ce0e36>:0 
  at CoCoL.AutomationExtensions.RunTask[T] (T channels, System.Func2[T,TResult] method, System.Boolean catchRetiredExceptions) [0x000cc] in <6973ce2780de4b28aaa2c5ffc59993b1>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.RunMainOperation (System.Collections.Generic.IEnumerable1[T] sources, Duplicati.Library.Snapshots.ISnapshotService snapshot, Duplicati.Library.Snapshots.UsnJournalService journalService, Duplicati.Library.Main.Operation.Backup.BackupDatabase database, Duplicati.Library.Main.Operation.Backup.BackupStatsCollector stats, Duplicati.Library.Main.Options options, Duplicati.Library.Utility.IFilter sourcefilter, Duplicati.Library.Utility.IFilter filter, Duplicati.Library.Main.BackupResults result, Duplicati.Library.Main.Operation.Common.ITaskReader taskreader, System.Int64 lastfilesetid) [0x00349] in <e2da9713f0974e76879d9f9aa7ce0e36>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.RunAsync (System.String[] sources, Duplicati.Library.Utility.IFilter filter) [0x01031] in <e2da9713f0974e76879d9f9aa7ce0e36>:0 
  at CoCoL.ChannelExtensions.WaitForTaskOrThrow (System.Threading.Tasks.Task task) [0x00050] in <6973ce2780de4b28aaa2c5ffc59993b1>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.Run (System.String[] sources, Duplicati.Library.Utility.IFilter filter) [0x00008] in <e2da9713f0974e76879d9f9aa7ce0e36>:0 
  at Duplicati.Library.Main.Controller+<>c__DisplayClass13_0.<Backup>b__0 (Duplicati.Library.Main.BackupResults result) [0x00035] in <e2da9713f0974e76879d9f9aa7ce0e36>:0 
  at Duplicati.Library.Main.Controller.RunAction[T] (T result, System.String[]& paths, Duplicati.Library.Utility.IFilter& filter, System.Action1[T] method) [0x00271] in <e2da9713f0974e76879d9f9aa7ce0e36>:0 
  at Duplicati.Library.Main.Controller.Backup (System.String[] inputsources, Duplicati.Library.Utility.IFilter filter) [0x00068] in <e2da9713f0974e76879d9f9aa7ce0e36>:0 
  at Duplicati.Server.Runner.Run (Duplicati.Server.Runner+IRunnerData data, System.Boolean fromQueue) [0x00307] in <be73c239d77d4180b5147067144fc237>:0 `

`{"ClassName":"CoCoL.RetiredException","Message":"The channel is retired","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"  at CoCoL.Channel`1[T].WriteAsync (T value, System.TimeSpan timeout, CoCoL.ITwoPhaseOffer offer) [0x00196] in <6973ce2780de4b28aaa2c5ffc59993b1>:0 \n  at Duplicati.Library.Main.Operation.Backup.MetadataPreProcess+<>c__DisplayClass2_0.<Run>b__0 (<>f__AnonymousType7`3[<Input>j__TPar,<StreamBlockChannel>j__TPar,<Output>j__TPar] self) [0x004e2] in <e2da9713f0974e76879d9f9aa7ce0e36>:0 ","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233088,"Source":"mscorlib"}`

**Comment by warwickmm** [comment]
Version 2.0.4.23 is basically the same as 2.0.4.5 (except for a warning for Amazon Cloud Drive users), which is pretty old.  Are you willing to test the most recent [canary release](https://github.com/duplicati/duplicati/releases/tag/v2.0.4.38-2.0.4.38_canary_2019-12-29) to see if the issue might have been fixed since then?

**Comment by fred-cardoso** [comment]
@warwickmm Sure! Can you just give me a hint on how I can update Duplicati running inside a Docker (https://hub.docker.com/r/linuxserver/duplicati/)?

**Comment by warwickmm** [comment]
I'm not sure...you should be able to go to "Settings", change the update channel to "Canary", then go to "About", and click "Check for updates now".  However, I've never upgraded that way before.

**Note:**  Once you upgrade to 2.0.4.38, you won't be able to revert back to 2.0.4.23 since the internal database schema has changed.  If this is a critical backup, you may want to consider setting up a new instance to test with.  2.0.4.38 is behaving pretty well, and we are considering using it as a base for the next beta release.

**Comment by fred-cardoso** [comment]
@warwickmm Thanks for your help. Already upgrading and no worries about the backup. I started using Duplicati today and this is the first time I am trying to backup things to the Cloud :-)

I will try again I get back to you!

**Comment by warwickmm** [comment]
Great!  Thanks for the help testing.  At least one other user has [recently mentioned](https://forum.duplicati.com/t/duplicati-and-onedrive-der-objektverweis-wurde-nicht-auf-eine-objektinstanz-festgelegt/8618/17) a similar issue with 2.0.4.23, so it would be nice to know if the problem has been potentially resolved or not.

**Comment by fred-cardoso** [comment]
One thing I would like to leave here written before I forget it, is that using this new version the upload speed has increased a lot. Not sure why, I though it was some limitation on OneDrive side. Now is almost hiting my upload limit.

![rrd](https://user-images.githubusercontent.com/32043667/71644199-5fbe4400-2cbc-11ea-8c45-6a62660f1441.png)

On the image, you can see the first two tries (which failed) and the second one started a few minutes ago.

I guess that the download peak (in blue) was the Duplicati update download :D

**Comment by warwickmm** [comment]
Parallel uploads were implemented around version 2.0.4.16.

**Comment by fred-cardoso** [comment]
Hi again @warwickmm 

Until now, no issues (knock on wood). But since we are talking about a 300~GB backup, given my internet upload connection we are talking about two days of upload time. Rest assured I will leave you feedback/close the issue ASAP.

Thanks again. And keep up with the good work.

**Comment by warwickmm** [comment]
Great!  Please let us know what happens.  I don't know if OneDrive has any upload limits so that may be an issue...

**Comment by ts678** [comment]
[Duplicati and OneDrive: “Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt”](https://forum.duplicati.com/t/duplicati-and-onedrive-der-objektverweis-wurde-nicht-auf-eine-objektinstanz-festgelegt/8618/13?u=ts678) was me on a similar OneDrive problem, asking what led up to the failure. This can be hard to tell unless you run a log to see the retries. There are older logs of mine posted there that show how at least sometimes the retry exhaustion that you might not see leads to this one that you do. Reproducing bug is easy if you have an FTP server (I used FileZilla Server) that you turn off during upload. Below are the About --> Show log --> Stored and the About --> Show log --> Live --> Retry. This was 2.0.4.38 `FTP` but `FTP (Alternative)` does it too. My old logs saw SSH doing this. I suspect it's backend-independent, but see note at bottom.

```
Jan 1, 2020 9:44 PM: Failed while executing "Backup" with id: 4
System.AggregateException: One or more errors occurred. ---> System.AggregateException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Duplicati.Library.Main.Volumes.BlockVolumeWriter.AddBlock(String hash, Byte[] data, Int32 offset, Int32 size, CompressionHint hint)
   at Duplicati.Library.Main.Operation.Backup.SpillCollectorProcess.<>c__DisplayClass0_0.<<Run>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CoCoL.AutomationExtensions.<RunTask>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.BackupHandler.<RunMainOperation>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__20.MoveNext()
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__20.MoveNext()
   --- End of inner exception stack trace ---
   at CoCoL.ChannelExtensions.WaitForTaskOrThrow(Task task)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass14_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
---> (Inner Exception #0) System.AggregateException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Duplicati.Library.Main.Volumes.BlockVolumeWriter.AddBlock(String hash, Byte[] data, Int32 offset, Int32 size, CompressionHint hint)
   at Duplicati.Library.Main.Operation.Backup.SpillCollectorProcess.<>c__DisplayClass0_0.<<Run>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CoCoL.AutomationExtensions.<RunTask>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.BackupHandler.<RunMainOperation>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__20.MoveNext()
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__20.MoveNext()
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Duplicati.Library.Main.Volumes.BlockVolumeWriter.AddBlock(String hash, Byte[] data, Int32 offset, Int32 size, CompressionHint hint)
   at Duplicati.Library.Main.Operation.Backup.SpillCollectorProcess.<>c__DisplayClass0_0.<<Run>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CoCoL.AutomationExtensions.<RunTask>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.BackupHandler.<RunMainOperation>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__20.MoveNext()<---

---> (Inner Exception #1) System.AggregateException: One or more errors occurred. ---> System.Net.WebException: Unable to connect to the remote server
   at Duplicati.Library.Utility.AsyncHttpRequest.AsyncWrapper.GetResponseOrStream()
   at Duplicati.Library.Utility.AsyncHttpRequest.GetRequestStream(Int64 contentlength)
   at Duplicati.Library.Backend.FTP.<PutAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.Backup.BackendUploader.<DoPut>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.Backup.BackendUploader.<>c__DisplayClass17_0.<<UploadFileAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Duplicati.Library.Main.Operation.Backup.BackendUploader.<DoWithRetry>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Duplicati.Library.Main.Operation.Backup.BackendUploader.<DoWithRetry>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.Backup.BackendUploader.<UploadFileAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.Backup.BackendUploader.<UploadBlockAndIndexAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.Backup.BackendUploader.<<Run>b__13_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Duplicati.Library.Main.Operation.Backup.BackendUploader.<<Run>b__13_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CoCoL.AutomationExtensions.<RunTask>d__10`1.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: Unable to connect to the remote server
   at Duplicati.Library.Utility.AsyncHttpRequest.AsyncWrapper.GetResponseOrStream()
   at Duplicati.Library.Utility.AsyncHttpRequest.GetRequestStream(Int64 contentlength)
   at Duplicati.Library.Backend.FTP.<PutAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.Backup.BackendUploader.<DoPut>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.Backup.BackendUploader.<>c__DisplayClass17_0.<<UploadFileAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Duplicati.Library.Main.Operation.Backup.BackendUploader.<DoWithRetry>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Duplicati.Library.Main.Operation.Backup.BackendUploader.<DoWithRetry>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.Backup.BackendUploader.<UploadFileAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.Backup.BackendUploader.<UploadBlockAndIndexAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.Backup.BackendUploader.<<Run>b__13_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Duplicati.Library.Main.Operation.Backup.BackendUploader.<<Run>b__13_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CoCoL.AutomationExtensions.<RunTask>d__10`1.MoveNext()<---
<---
<---
```

```
Jan 1, 2020 9:44 PM: The operation Backup has failed with error: One or more errors occurred.
Jan 1, 2020 9:44 PM: Fatal error
Jan 1, 2020 9:44 PM: Backend event: Put - Failed: duplicati-b0be0111fd816455aa366410f0970117c.dblock.zip (50.00 MB)
Jan 1, 2020 9:44 PM: Operation Put with file duplicati-b0be0111fd816455aa366410f0970117c.dblock.zip attempt 6 of 5 failed with message: Unable to connect to the remote server
```

Clicking on the failure gets a long hard-to-read (due to wrap) message that starts like this:

> Jan 1, 2020 9:44 PM: The operation Backup has failed with error: One or more errors occurred.
{"ClassName":"System.AggregateException","Message":"One or more errors occurred.","Data":null,"InnerException":{"ClassName":"System.AggregateException","Message":"Object reference not set to an instance of an object.","Data":null,"InnerException":{"ClassName":"System.NullReferenceException","Message":"Object reference not set to an instance of an object.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at Duplicati.Library.Main.Volumes.BlockVolumeWriter.AddBlock(String hash, Byte[] data, Int32 offset, Int32 size, CompressionHint hint)\r\n   at Duplicati.Library.Main.Operation.Backup.SpillCollectorProcess.<>c__DisplayClass0_0.<<Run>b__0>d.MoveNext()\r\n

One reason OneDrive may be more prone to using up its [--number-of-retries](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#number-of-retries) is that it has a 100 second  [--http-operation-timeout](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#http-operation-timeout) which is sometimes not enough file transfer time. You can raise either number.

**Comment by fred-cardoso** [comment]
Hello again @warwickmm 

After a few days it finished! The error never appeared again. But unfortunately for some reason the backup stopped two times out of nowhere, upon checking the logs I couldn't find anything strange. Both I times I could restart the backup from where it stopped. I think that it has something to do with the Docker. I will check the docker logs, and find out what happened.

For now I will close this issue in particular. If needed I will open another for the other issue.

Thank you @warwickmm for your help and @ts678 for your input!

**Comment by warwickmm** [comment]
Thanks @fred-cardoso for the update.
