### ISSUE TITLE
if an exception occurs during backup no log is generated

### ISSUE THREAD

**Issue by habakuk007** [duplicati/duplicati#4072]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.1_beta_2020-01-18
- **Operating system**: Windows 10
- **Backend**: OneDrive v2

## Description
If an exception occours during a backup process the log is not written (Common Protocoll), but an email with the exception is sent.

## Steps to reproduce

1. Created Backup Job (OneDrive v2, encrypted, many files) 
2. When scheduled it runs
3. Any exception occours

- **Actual result**:
No Log is written, Exception is send by mail, Error-Popup is shown in Backend
- **Expected result**:
I would excpect that a log is written

## Screenshots

![2020-01-27Duplicati](https://user-images.githubusercontent.com/2253878/73211217-1e4e7680-414c-11ea-88cd-77017e83a8aa.png)
I would expect to see the log from today

## Debug log

Exception Info from Mail:
[Duplicati.log](https://github.com/duplicati/duplicati/files/4119209/Duplicati.log)

**Comment by warwickmm** [comment]
Does anything happen when you click on the log entry (18. Jan. 2020 18:05 - Operation: Result)?

**Comment by habakuk007** [comment]
The protocol is show, but I would expect that the protocol from 2020-01-27 (and the days before), where the job failed, would also be shown here.

![Duplicati](https://user-images.githubusercontent.com/2253878/73606996-f2e6e400-45b0-11ea-97af-6d9a4098885d.png)

**Comment by ts678** [comment]
@habakuk007 Please look in Home --> About --> Show log to see what's there. Click on entries to expand. My recent examples:

> Nov 17, 2020 8:06 PM: Failed while executing "Backup" with id: 1
System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Http.StreamToStreamCopy.BufferReadCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.AsyncDownloader.AsyncDownloaderEnumerator.AsyncDownloadedFile.get_TempFile()
   at Duplicati.Library.Main.Operation.CompactHandler.DoCompact(LocalDeleteDatabase db, Boolean hasVerifiedBackend, IDbTransaction& transaction, BackendManager sharedBackend)
   at Duplicati.Library.Main.Operation.DeleteHandler.DoRun(LocalDeleteDatabase db, IDbTransaction& transaction, Boolean hasVerifiedBackend, Boolean forceCompact, BackendManager sharedManager)
   at Duplicati.Library.Main.Operation.BackupHandler.CompactIfRequired(BackendManager backend, Int64 lastVolumeSize)
   at Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CoCoL.ChannelExtensions.WaitForTaskOrThrow(Task task)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass14_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

> Nov 17, 2020 6:53 PM: Failed while executing "Backup" with id: 1
System.TimeoutException: HTTP timeout 00:30:00 exceeded.
   at Duplicati.Library.Main.AsyncDownloader.AsyncDownloaderEnumerator.AsyncDownloadedFile.get_TempFile()
   at Duplicati.Library.Main.Operation.CompactHandler.DoCompact(LocalDeleteDatabase db, Boolean hasVerifiedBackend, IDbTransaction& transaction, BackendManager sharedBackend)
   at Duplicati.Library.Main.Operation.DeleteHandler.DoRun(LocalDeleteDatabase db, IDbTransaction& transaction, Boolean hasVerifiedBackend, Boolean forceCompact, BackendManager sharedManager)
   at Duplicati.Library.Main.Operation.BackupHandler.CompactIfRequired(BackendManager backend, Int64 lastVolumeSize)
   at Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CoCoL.ChannelExtensions.WaitForTaskOrThrow(Task task)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass14_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

[Combine logs in GUI #1152](https://github.com/duplicati/duplicati/issues/1152) is the unfortunate technical reason for mine. To make matters worse, `Show` button only knows job logs.

You'll have to look at the server log I named to see if you had the same issue. As a side note, both my errors were also mailed to me. One interesting thing is that the two above were called `Fatal`, whereas an earlier exception did an `Error` and went to the job logs. There were result statistics at its top, which possibly is what it takes for a log to be a job log. OTOH only email detailed the exception:

> Log data:
2020-11-17 17:39:01 -05 - [Error-Duplicati.Library.Main.Operation.TestHandler-FailedToProcessFile]: Failed to process file duplicati-b6ef018fc0c0244f1858aed637e16521a.dblock.zip.aes
System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)

So just above was an exception during a OneDrive backup that went to the job logs, but the first two named went to the server log...

[Viewing the log files of a backup job](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#viewing-the-log-files-of-a-backup-job) describes the log you showed.
[Viewing the Duplicati Server Logs](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#viewing-the-duplicati-server-logs) describes the log my error was in and I suspect yours is too. I can't detail the technical background.

**Comment by warwickmm** [comment]
Unfortunately there are 2 locations where logs can exist. The error you encountered most likely resided in the server logs. Consolidating the different logs and making it easier for users to discover them is a known issue.

It is strange that the log icons are gray rather than green or yellow.  If the server logs don't contain your error, please reopen this with more details.
