### ISSUE TITLE
Error on restoring a file from backup. Failed to restore files: SQL logic error table Notification has no column named LogEntryID

### ISSUE THREAD

**Issue by Rozenbahs** [duplicati/duplicati#4078]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
Windows 10 Pro running as a service, says I have 17 versions. All backups running daily with no errors. There is a passphrase set, but the Restore process did not ask for it.

Backend: WebDAV

- **Duplicati - 2.0.5.0_experimental_2020-01-03
- **Operating system**: Windows 10 Pro, v1909
- **Backend**: WebDAV

## Description
Decided to restore a single file from the last backup. The restore of a single file ends with an error message:  Failed to restore files: SQL logic error table Notification has no column named LogEntryID

## Steps to reproduce

1. Restore
2. Selected last of 3 options with my backup name > Next
3. Navigated to the file of interest in the last backup set and selected its checkbox > Continue
4. Original location; Initially tried with 'Save different versions with timestamp in file name'. Later tried to overwrite (made no difference) > Restore
5. Restoring files.. Verifying remote data... > ends with a modal errir message: Failed to restore files: SQL logic error table Notification has no column named LogEntryID

- **Actual result**:
Just an error message. No files affected.
- **Expected result**:
A file with a date of the backup in the file name.

## Screenshots
![Screenshot_4](https://user-images.githubusercontent.com/60525212/73575817-a9e44200-4481-11ea-9c59-a892d79504eb.png)

## Debug log
```
{
  "RestoredFiles": 0,
  "SizeOfRestoredFiles": 0,
  "RestoredFolders": 0,
  "RestoredSymlinks": 0,
  "PatchedFiles": 0,
  "DeletedFiles": 0,
  "DeletedFolders": 0,
  "DeletedSymlinks": 0,
  "MainOperation": "Restore",
  "RecreateDatabaseResults": null,
  "ParsedResult": "Error",
  "Version": "2.0.5.0 (2.0.5.0_experimental_2020-01-03)",
  "EndTime": "2020-01-31T21:25:47.3711854Z",
  "BeginTime": "2020-01-31T21:24:33.1121262Z",
  "Duration": "00:01:14.2590592",
  "MessagesActualLength": 16,
  "WarningsActualLength": 0,
  "ErrorsActualLength": 2,
  "Messages": [
    "2020-01-31 23:24:33 +02 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Restore has started",
    "2020-01-31 23:24:33 +02 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  ()",
    "2020-01-31 23:25:00 +02 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (3.59 KB)",
    "2020-01-31 23:25:00 +02 - [Information-Duplicati.Library.Main.Database.LocalRestoreDatabase-SearchingBackup]: Searching backup 0 (31.01.2020 00:00:00) ...",
    "2020-01-31 23:25:01 +02 - [Information-Duplicati.Library.Main.Operation.RestoreHandler-RemoteFileCount]: 1 remote files are required to restore",
    "2020-01-31 23:25:01 +02 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b419114f307e34c86a7d180ff378e1ab4.dblock.zip.aes (23.48 MB)",
    "2020-01-31 23:25:02 +02 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Retrying: duplicati-b419114f307e34c86a7d180ff378e1ab4.dblock.zip.aes (23.48 MB)",
    "2020-01-31 23:25:12 +02 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b419114f307e34c86a7d180ff378e1ab4.dblock.zip.aes (23.48 MB)",
    "2020-01-31 23:25:13 +02 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Retrying: duplicati-b419114f307e34c86a7d180ff378e1ab4.dblock.zip.aes (23.48 MB)",
    "2020-01-31 23:25:23 +02 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b419114f307e34c86a7d180ff378e1ab4.dblock.zip.aes (23.48 MB)",
    "2020-01-31 23:25:25 +02 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Retrying: duplicati-b419114f307e34c86a7d180ff378e1ab4.dblock.zip.aes (23.48 MB)",
    "2020-01-31 23:25:35 +02 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b419114f307e34c86a7d180ff378e1ab4.dblock.zip.aes (23.48 MB)",
    "2020-01-31 23:25:36 +02 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Retrying: duplicati-b419114f307e34c86a7d180ff378e1ab4.dblock.zip.aes (23.48 MB)",
    "2020-01-31 23:25:46 +02 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b419114f307e34c86a7d180ff378e1ab4.dblock.zip.aes (23.48 MB)",
    "2020-01-31 23:25:47 +02 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Failed: duplicati-b419114f307e34c86a7d180ff378e1ab4.dblock.zip.aes (23.48 MB)",
    "2020-01-31 23:25:47 +02 - [Information-Duplicati.Library.Main.Operation.RestoreHandler-RestoreFailures]: Failed to restore 1 files, additionally the following files failed to download, which may be the cause:\r\nduplicati-b419114f307e34c86a7d180ff378e1ab4.dblock.zip.aes"
  ],
  "Warnings": [],
  "Errors": [
    "2020-01-31 23:25:47 +02 - [Error-Duplicati.Library.Main.Operation.RestoreHandler-PatchingFailed]: Failed to patch with remote file: \"duplicati-b419114f307e34c86a7d180ff378e1ab4.dblock.zip.aes\", message: Failed to decrypt data (invalid passphrase?): Invalid password or corrupted data",
    "2020-01-31 23:25:47 +02 - [Error-Duplicati.Library.Main.Operation.RestoreHandler-RestoreFileFailed]: Failed to restore file: \"D:\\Projekti\\Roberts\\Rozenbahs\\2019. gada pārskats\\2019. gada bilance.xlsm\". File hash is C0QeU0euGrdf0oAYFKK4sL6NpQmM3Qwv5XRomAG9npw=, expected hash is 7utfWMaT8xv5ec5/rly1el8SfMHjZKAJnLF5tbW4wYM="
  ],
  "BackendStatistics": {
    "RemoteCalls": 6,
    "BytesUploaded": 0,
    "BytesDownloaded": 0,
    "FilesUploaded": 0,
    "FilesDownloaded": 0,
    "FilesDeleted": 0,
    "FoldersCreated": 0,
    "RetryAttempts": 4,
    "UnknownFileSize": 0,
    "UnknownFileCount": 0,
    "KnownFileCount": 3679,
    "KnownFileSize": 191237196819,
    "LastBackupDate": "2020-01-31T02:00:00+02:00",
    "BackupListCount": 17,
    "TotalQuotaSpace": 0,
    "FreeQuotaSpace": 0,
    "AssignedQuotaSpace": -1,
    "ReportedQuotaError": false,
    "ReportedQuotaWarning": false,
    "MainOperation": "Restore",
    "ParsedResult": "Success",
    "Version": "2.0.5.0 (2.0.5.0_experimental_2020-01-03)",
    "EndTime": "0001-01-01T00:00:00",
    "BeginTime": "2020-01-31T21:24:33.1121262Z",
    "Duration": "00:00:00",
    "MessagesActualLength": 0,
    "WarningsActualLength": 0,
    "ErrorsActualLength": 0,
    "Messages": null,
    "Warnings": null,
    "Errors": null
  }
}
```

Since the log pointed to a different error, I tried to restore also directly.
1. Pointed to the source. Tested connection - OK
2. Entered Passphrase
3. Selected the backup set and the file
4. Waited long on Recreating temporary database
5. Starting Restore -- ended with the same error: Failed to restore files: SQL logic error table Notification has no column named LogEntryID

Since the logs lead to think of Password/Passphrase error
```
Failed to patch with remote file: "duplicati-b419114f307e34c86a7d180ff378e1ab4.dblock.zip.aes", message: Failed to decrypt data (invalid passphrase?): Invalid password or corrupted data
{"ClassName":"System.Security.Cryptography.CryptographicException","Message":"Failed to decrypt data (invalid passphrase?): Invalid password or corrupted data
```
I downloaded the respective zip.aes file and decrypted it with AES decryptor tool. Tested the zip -- no errors. Looked inside -- lots of 102Kb files inside.

Any ideas?

```
Log data from the server
    Stored
    Feb 1, 2020 12:05 AM: Failed while executing "Restore" with id: da5d73ab-3759-48fd-a69e-ce33caf8453c
    code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
    table Notification has no column named LogEntryID
       at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
       at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
       at System.Data.SQLite.SQLiteDataReader.NextResult()
       at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
       at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
       at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
       at Duplicati.Server.Database.Connection.OverwriteAndUpdateDb[T](IDbTransaction transaction, String deleteSql, Object[] deleteArgs, IEnumerable`1 values, String insertSql, Func`2 f)
       at Duplicati.Server.Database.Connection.OverwriteAndUpdateDb[T](IDbTransaction transaction, String deleteSql, Object[] deleteArgs, IEnumerable`1 values, Boolean updateExisting)
       at Duplicati.Server.Database.Connection.RegisterNotification(NotificationType type, String title, String message, Exception ex, String backupid, String action, String logid, String messageid, String logtag, Func`3 conflicthandler)
       at Duplicati.Server.Runner.UpdateMetadata(IBackup backup, IBasicResults result)
       at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
       
    Feb 1, 2020 12:05 AM: Error in worker
    code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
    table Notification has no column named LogEntryID
       at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
       at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
       at System.Data.SQLite.SQLiteDataReader.NextResult()
       at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
       at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
       at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
       at Duplicati.Server.Database.Connection.OverwriteAndUpdateDb[T](IDbTransaction transaction, String deleteSql, Object[] deleteArgs, IEnumerable`1 values, String insertSql, Func`2 f)
       at Duplicati.Server.Database.Connection.OverwriteAndUpdateDb[T](IDbTransaction transaction, String deleteSql, Object[] deleteArgs, IEnumerable`1 values, Boolean updateExisting)
       at Duplicati.Server.Database.Connection.RegisterNotification(NotificationType type, String title, String message, Exception ex, String backupid, String action, String logid, String messageid, String logtag, Func`3 conflicthandler)
       at Duplicati.Server.Runner.UpdateMetadataError(IBackup backup, Exception ex)
       at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
       at Duplicati.Library.Utility.WorkerThread`1.Runner()

```

```

Log data from the server

    Live 

Select a log level and see messages as they happen:
Feb 1, 2020 12:05 AM: Could not find file 'D:\Projekti\Roberts\Rozenbahs.2020-01-31.xlsm'.
{"ClassName":"System.IO.FileNotFoundException","Message":"Could not find file '________.2020-01-31.xlsm'.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at Duplicati.Library.Common.IO.SystemIOWindows.<>c.<FileOpenRead>b__29_0(String p)\r\n   at Duplicati.Library.Common.IO.SystemIOWindows.PathTooLongFuncWrapper[T](Func`2 nativeIOFunc, Func`2 alternativeIOFunc, String path, Boolean prefixWithUnc)\r\n   at Duplicati.Library.Common.IO.SystemIOWindows.FileOpenRead(String path)\r\n   at Duplicati.Library.Main.Operation.RestoreHandler.DoRun(LocalDatabase dbparent, IFilter filter, RestoreResults result)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nWinIOError\nmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.IO.__Error\nVoid WinIOError(Int32, System.String)","HResult":-2147024894,"Source":"mscorlib","WatsonBuckets":null,"FileNotFound_FileName":"________.2020-01-31.xlsm","FileNotFound_FusionLog":null}
Feb 1, 2020 12:05 AM: Failed to patch with remote file: "duplicati-b419114f307e34c86a7d180ff378e1ab4.dblock.zip.aes", message: Failed to decrypt data (invalid passphrase?): Invalid password or corrupted data
{"ClassName":"System.Security.Cryptography.CryptographicException","Message":"Failed to decrypt data (invalid passphrase?): Invalid password or corrupted data","Data":null,"InnerException":{"ClassName":"SharpAESCrypt.SharpAESCrypt+WrongPasswordException","Message":"Invalid password or corrupted data","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at SharpAESCrypt.SharpAESCrypt.ReadEncryptionHeader(String password, Boolean skipFileSizeCheck)\r\n   at SharpAESCrypt.SharpAESCrypt..ctor(String password, Stream stream, OperationMode mode, Boolean skipFileSizeCheck)\r\n   at Duplicati.Library.Encryption.AESEncryption.Decrypt(Stream input)\r\n   at Duplicati.Library.Encryption.EncryptionBase.Decrypt(Stream input, Stream output)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nReadEncryptionHeader\nSharpAESCrypt, Version=1.3.3.0, Culture=neutral, PublicKeyToken=null\nSharpAESCrypt.SharpAESCrypt\nVoid ReadEncryptionHeader(System.String, Boolean)","HResult":-2146233296,"Source":"SharpAESCrypt","WatsonBuckets":null},"HelpURL":null,"StackTraceString":"   at Duplicati.Library.Main.AsyncDownloader.AsyncDownloaderEnumerator.AsyncDownloadedFile.get_TempFile()\r\n   at Duplicati.Library.Main.Operation.RestoreHandler.DoRun(LocalDatabase dbparent, IFilter filter, RestoreResults result)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nget_TempFile\nDuplicati.Library.Main, Version=2.0.5.0, Culture=neutral, PublicKeyToken=null\nDuplicati.Library.Main.AsyncDownloader+AsyncDownloaderEnumerator+AsyncDownloadedFile\nDuplicati.Library.Utility.TempFile get_TempFile()","HResult":-2146233296,"Source":"Duplicati.Library.Main","WatsonBuckets":null}

```

**Comment by waljohn** [comment]
What version do you have? In the GUI click about and look for a line like:

> You are currently running Duplicati - 2.0.5.0_experimental_2020-01-03

I checked my local duplicati-server.sqlite and there is a column "LogEntryId" in "Notification" (ironically: it only contains "NULL")

Please try the following, You can use a tool like https://sqlitebrowser.org/ drag-and-drop the "duplicati-server.sqlite" database file onto the app window and click the execute SQL tab; type or paste the SQL one-at-a-time into the editor and click the play button


```
select * from version;

--RESULT:
1	6
```
```
select sql from sqlite_master
where name = "Notification";

--RESULT: 
CREATE TABLE "Notification" (
    "ID" INTEGER PRIMARY KEY,
    "Type" TEXT NOT NULL,
    "Title" TEXT NOT NULL,
    "Message" TEXT NOT NULL, 
    "Exception" TEXT NOT NULL, 
    "BackupID" TEXT NULL,
    "Action" TEXT NOT NULL,
    "Timestamp" INTEGER NOT NULL,
   "LogEntryID" TEXT NULL,
   "MessageID" TEXT NULL, <<< here it is
   "MessageLogTag" TEXT NULL
)
```

It sounds like you have Windows so the database is ciphered and can't be read by any tool. you may need to follow these instructions if you use the  trayicon
https://forum.duplicati.com/t/which-tool-can-open-encrypted-db/2372/4
or if you have it set up as a Windows service, open "services.msc", right click the "Duplicati Service" > Properties and add "--unencrypted-database" in the "Start parameters"; then restart it and it will decode it. Please be sure to reverse this change for SECURITY reasons as soon as you are done! It contains cleartext authentication data and it's vulnerable to leave it unencoded.

It is safest to copy the (decrypted) database file to another folder and only work on this copy.

**Comment by ts678** [comment]
I'm only finding that error message in one place on the Internet -- here. Is this still of interest and issue present on current release?
