### ISSUE TITLE
Running any Commandline from GUI fails with System.FormatException

### ISSUE THREAD

**Issue by TeeTeeHaa** [duplicati/duplicati#4082]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: Duplicati - 2.0.5.1_beta_2020-01-18
- **Operating system**: Windows 7 64 Bit, US language with German keyboard layout
- **Backend**: sftp to commercial webhosting provider

## Description

Within the browser-based GUI the option "Commandline …" does not work at all but results in an error (see below).

## Steps to reproduce

1. In browser-based GUI use the option "Commandline …" with any command ("verify" in my example here). The screenshot was taken after clicking "Edit as text".

- **Actual result**:

**Command**
verify

**Target URL >**
ssh://www.MYDOMAIN.de:23//MYDIRECTORY/MYSUBDIRECTORY?auth-username=MYUSER&auth-password=MYPASSWORD&ssh-fingerprint=ssh-rsa%202048%20f1MORECHARACTERS%3Ab4%3Aff

**Commandline arguments**
E:\Repositories\

**Advanced options**
--backup-name=Subversion Repositories
--dbpath=C:\Users\MYLOCALWINDOWSUSER\AppData\Roaming\Duplicati\RANDOMSTRING.sqlite
--encryption-module=aes
--compression-module=zip
--dblock-size=50mb
--keep-time=3Y
--passphrase=MYPASSPHRASE
--disable-module=console-password-input

**Running commandline entry**
Finished!  
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Convert.ToInt64(String value)
   at Duplicati.CommandLine.Commands.Test(TextWriter outwriter, Action`1 setup, List`1 args, Dictionary`2 options, IFilter filter)
   at Duplicati.CommandLine.Program.ParseCommandLine(TextWriter outwriter, Action`1 setup, Boolean& verboseErrors, String[] args)
   at Duplicati.CommandLine.Program.RunCommandLine(TextWriter outwriter, TextWriter errwriter, Action`1 setup, String[] args)
Return code: 100

- **Expected result**:
In this case the result of the verify command.

## Screenshots

![2020-02-03 Duplicati command line error](https://user-images.githubusercontent.com/739754/73652018-1596fc80-4686-11ea-823d-dfc41c7279b1.png)

## Debug log

No log is created.

**Comment by drwtsn32x** [comment]
For some of the commands you need to clear the default contents of the Commandline arguments box (which is usually a list of folders you have selected for backup).  This appears to be the case for verify / test.

**Comment by TeeTeeHaa** [comment]
@drwtsn32x Thank you very much! This does work and solves my problem.
I'd leave this issue open because it looks like obscure behavior in my eyes. Duplicati should know itself which arguments it needs for which of its commands (and leave them out/blank if not needed).
