### ISSUE TITLE
Missing Error in log

### ISSUE THREAD

**Issue by vitekf** [duplicati/duplicati#4120]
## Environment info
- **Duplicati version**: 2.0.5.1_beta_2020-01-18
- **Operating system**: Windows 10
- **Backend**: CIFS (irrelevant)

## Description

Errors are not shown in log & http report

## Steps to reproduce

1. Simulate error, for example set unexisting path to destination (c:\UnexistingFolder)
2. Run backup
3. See backup log

- **Actual result**:
Error not showed
- **Expected result**:
-- Line with error details
-- "**ParsedResult: Error**", timestamp  and another values in http report

## Screenshots
![dupl-error-missing](https://user-images.githubusercontent.com/23286396/75433426-37676480-5950-11ea-94b7-3d9e023fce8e.png)

## Http reporting module

Example of Success report:
```
Array
(
    [_POST] => Array
        (
            [message] => Duplicati Backup report for TEST

DeletedFiles: 181
DeletedFolders: 23
ModifiedFiles: 3193
ExaminedFiles: 196997
OpenedFiles: 3538
AddedFiles: 345
SizeOfModifiedFiles: 1034268659
SizeOfAddedFiles: 172026253
SizeOfExaminedFiles: 50222191716
SizeOfOpenedFiles: 1207876763
NotProcessedFiles: 0
AddedFolders: 37
TooLargeFiles: 0
FilesWithError: 0
ModifiedFolders: 0
ModifiedSymlinks: 0
AddedSymlinks: 0
DeletedSymlinks: 0
PartialBackup: False
Dryrun: False
MainOperation: Backup
ParsedResult: Success
Version: 2.0.5.1 (2.0.5.1_beta_2020-01-18)
EndTime: 23.02.2020 23:04:56 (1582495496)
BeginTime: 23.02.2020 22:48:08 (1582494488)
Duration: 00:16:48.4422357
MessagesActualLength: 35
WarningsActualLength: 0
ErrorsActualLength: 0
LimitedMessages: [
...
]
LimitedWarnings: []
LimitedErrors: []
        )
```

Example of Error report:
```
Array
(
    [_POST] => Array
        (
            [message] => Duplicati Backup report for Backup_DATA

Failed: SloĹľka \\192.168.1.220\backups\Duplicati\ neexistuje
Details: Duplicati.Library.Interface.FolderMissingException: SloĹľka \\192.168.1.220\backups\Duplicati\ neexistuje
   at Duplicati.Library.Main.BackendManager.List()
   at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)
   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CoCoL.ChannelExtensions.WaitForTaskOrThrow(Task task)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass14_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)

Log data:
2020-02-23 22:01:02 +01 - [Warning-Duplicati.Library.Main.BackendManager-FolderCreateError]: Failed to create folder: SloĹľka \\192.168.1.220\backups\Duplicati\ neexistuje
System.IO.IOException: The user name or password is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at Duplicati.Library.Common.IO.SystemIOWindows.<>c__DisplayClass17_0`2.<PathTooLongVoidFuncWrapper>b__0(String p)
   at Duplicati.Library.Common.IO.SystemIOWindows.PathTooLongFuncWrapper[T](Func`2 nativeIOFunc, Func`2 alternativeIOFunc, String path, Boolean prefixWithUnc)
   at Duplicati.Library.Common.IO.SystemIOWindows.DirectoryCreate(String path)
   at Duplicati.Library.Main.BackendManager.ThreadRun()
2020-02-23 22:01:13 +01 - [Warning-Duplicati.Library.Main.BackendManager-FolderCreateError]: Failed to create folder: SloĹľka \\192.168.1.220\backups\Duplicati\ neexistuje
System.IO.IOException: The user name or password is incorrect.
...
        )
```

**Comment by ts678** [comment]
The http report is an added angle (which I don't have set up to test), but just changing destination to a bad folder logs to server log.

[Viewing the Duplicati Server Logs](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#viewing-the-duplicati-server-logs) versus the usual spot (and what GUI `Show` button uses) is at [Viewing the log files of a backup job](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#viewing-the-log-files-of-a-backup-job).

Please check yours at Home --> About --> Show log and click the summary to see its detail.

[Combine logs in GUI #1152](https://github.com/duplicati/duplicati/issues/1152) should fix this, although HTTP report would need to be checked. I know email reports go out regardless.

Here's the server log where my missing file error was logged, however if you're saying that no log has great details, I'd agree to that.
Sometimes you have to hope problem is reproducible to run About --> Show log --> Live., but that didn't sound like the issue here.

```Nov 19, 2020 3:13 PM: Failed while executing "Backup" with id: 3
Duplicati.Library.Interface.UserInformationException: Found 9 files that are missing from the remote storage, please run repair
   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, IEnumerable`1 protectedFiles)
   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CoCoL.ChannelExtensions.WaitForTaskOrThrow(Task task)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass14_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)```

**Comment by warwickmm** [comment]
Unfortunately there are 2 locations where logs can exist. The error you encountered most likely resided in the server logs. Consolidating the different logs and making it easier for users to discover them is a known issue.

If the server log does not contain your error, please reopen and provide more details.
