### ISSUE TITLE
"UNIQUE constraint failed" error trying to back up Firefox profile in Windows

### ISSUE THREAD

**Issue by dferreyra** [duplicati/duplicati#4229]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.1
- **Operating system**: Windows 10
- **Backend**: Amazon S3

## Description

My backups started failing with the following error:
```
UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID
```
I've narrowed it down to directories that end with a dot; e.g., "https+++www.example.com." -- notice the dot after the "com".

The directories are being created by Firefox in the "storage" directory in my Firefox profile.  Here's what a simplified reproduction I have looks like:
```
    C:\Temp>dir storage /b /s
    C:\Temp\storage\default
    C:\Temp\storage\default\https+++www.example.com
    C:\Temp\storage\default\https+++www.example.com\cache
    C:\Temp\storage\default\https+++www.example.com\cache\caches.sqlite
    C:\Temp\storage\default\https+++www.example.com.
    C:\Temp\storage\default\https+++www.example.com.\cache
    C:\Temp\storage\default\https+++www.example.com.\cache\caches.sqlite
```

Maybe it's related to #3642 or #3839.

My workaround is to exclude the "storage" directory in my Firefox profile.

## Steps to reproduce

1. Create a tree like the one described above; i.e., two directories where they only differ in that one ends in a dot, each containing a file with the same name.  To create directories that end in a dot, you can use the following syntax, `mkdir \\?\C:\Temp\storage\default\https+++www.example.com.`.
2. Configure a backup of the tree in Duplicati.  The backend you choose probably doesn't matter.
3. Run the backup.

- **Actual result**:
The backup fails with this error:
```
UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID
```
- **Expected result**:
A good backup with no errors.

## Debug log

```
2020-06-14 21:23:45 -07 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Backup has started
2020-06-14 21:23:45 -07 - [Verbose-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-IncludingSourcePath]: Including source path: C:\Temp\storage\
2020-06-14 21:23:45 -07 - [Verbose-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-IncludingPath]: Including path as no filters matched: C:\Temp\storage\default\
2020-06-14 21:23:45 -07 - [Verbose-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-IncludingPath]: Including path as no filters matched: C:\Temp\storage\default\https+++www.example.com\
2020-06-14 21:23:45 -07 - [Verbose-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-IncludingPath]: Including path as no filters matched: C:\Temp\storage\default\https+++www.example.com.\
2020-06-14 21:23:45 -07 - [Verbose-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-IncludingPath]: Including path as no filters matched: C:\Temp\storage\default\https+++www.example.com\cache\
2020-06-14 21:23:45 -07 - [Verbose-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-IncludingPath]: Including path as no filters matched: C:\Temp\storage\default\https+++www.example.com\cache\caches.sqlite
2020-06-14 21:23:45 -07 - [Verbose-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-IncludingPath]: Including path as no filters matched: C:\Temp\storage\default\https+++www.example.com\cache\
2020-06-14 21:23:45 -07 - [Verbose-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-IncludingPath]: Including path as no filters matched: C:\Temp\storage\default\https+++www.example.com\cache\caches.sqlite
2020-06-14 21:23:45 -07 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  ()
2020-06-14 21:23:45 -07 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (30 bytes)
2020-06-14 21:23:45 -07 - [Verbose-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-IncludingSourcePath]: Including source path: C:\Temp\storage\
2020-06-14 21:23:45 -07 - [Verbose-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-IncludingPath]: Including path as no filters matched: C:\Temp\storage\default\
2020-06-14 21:23:45 -07 - [Verbose-Duplicati.Library.Main.Operation.Backup.MetadataPreProcess.FileEntry-AddDirectory]: Adding directory C:\Temp\storage\
2020-06-14 21:23:45 -07 - [Verbose-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-IncludingPath]: Including path as no filters matched: C:\Temp\storage\default\https+++www.example.com\
2020-06-14 21:23:45 -07 - [Verbose-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-IncludingPath]: Including path as no filters matched: C:\Temp\storage\default\https+++www.example.com.\
2020-06-14 21:23:45 -07 - [Verbose-Duplicati.Library.Main.Operation.Backup.MetadataPreProcess.FileEntry-AddDirectory]: Adding directory C:\Temp\storage\default\
2020-06-14 21:23:45 -07 - [Verbose-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-IncludingPath]: Including path as no filters matched: C:\Temp\storage\default\https+++www.example.com\cache\
2020-06-14 21:23:45 -07 - [Verbose-Duplicati.Library.Main.Operation.Backup.MetadataPreProcess.FileEntry-AddDirectory]: Adding directory C:\Temp\storage\default\https+++www.example.com.\
2020-06-14 21:23:45 -07 - [Verbose-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-IncludingPath]: Including path as no filters matched: C:\Temp\storage\default\https+++www.example.com\cache\caches.sqlite
2020-06-14 21:23:45 -07 - [Verbose-Duplicati.Library.Main.Operation.Backup.MetadataPreProcess.FileEntry-AddDirectory]: Adding directory C:\Temp\storage\default\https+++www.example.com\cache\
2020-06-14 21:23:45 -07 - [Verbose-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-IncludingPath]: Including path as no filters matched: C:\Temp\storage\default\https+++www.example.com\cache\
2020-06-14 21:23:45 -07 - [Verbose-Duplicati.Library.Main.Operation.Backup.FilePreFilterProcess.FileEntry-CheckFileForChanges]: Checking file for changes C:\Temp\storage\default\https+++www.example.com\cache\caches.sqlite, new: True, timestamp changed: True, size changed: True, metadatachanged: True, 6/15/2020 2:38:40 AM vs 1/1/0001 12:00:00 AM
2020-06-14 21:23:45 -07 - [Verbose-Duplicati.Library.Main.Operation.Backup.MetadataPreProcess.FileEntry-AddDirectory]: Adding directory C:\Temp\storage\default\https+++www.example.com\
2020-06-14 21:23:45 -07 - [Verbose-Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.FileEntry-NewFile]: New file C:\Temp\storage\default\https+++www.example.com\cache\caches.sqlite
2020-06-14 21:23:45 -07 - [Verbose-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-IncludingPath]: Including path as no filters matched: C:\Temp\storage\default\https+++www.example.com\cache\caches.sqlite
2020-06-14 21:23:45 -07 - [Verbose-Duplicati.Library.Main.Operation.Backup.MetadataPreProcess.FileEntry-AddDirectory]: Adding directory C:\Temp\storage\default\https+++www.example.com\cache\
2020-06-14 21:23:45 -07 - [Retry-Duplicati.Library.Main.Operation.Backup.BackendUploader-RetryPut]: Operation Put with file duplicati-b9a5a8d8ecc0842ff90d50df7354100e3.dblock.zip attempt 1 of 5 failed with message: The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Duplicati.Library.Main.Operation.Common.SingleRunner.<DoRunOnMain>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.Backup.BackendUploader.<DoPut>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.Backup.BackendUploader.<>c__DisplayClass17_0.<<UploadFileAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Duplicati.Library.Main.Operation.Backup.BackendUploader.<DoWithRetry>d__18.MoveNext()
2020-06-14 21:23:45 -07 - [Error-Duplicati.Library.Main.Operation.BackupHandler-FatalError]: Fatal error
code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x800027AF): constraint failed
UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at Duplicati.Library.Main.Database.ExtensionMethods.ExecuteNonQuery(IDbCommand self, Boolean writeLog, String cmd, Object[] values)
   at Duplicati.Library.Main.Database.LocalBackupDatabase.AddFile(Int64 pathprefixid, String filename, DateTime lastmodified, Int64 blocksetID, Int64 metadataID, IDbTransaction transaction)
   at Duplicati.Library.Main.Database.LocalBackupDatabase.AddFile(String filename, DateTime lastmodified, Int64 blocksetID, Int64 metadataID, IDbTransaction transaction)
   at Duplicati.Library.Main.Operation.Backup.BackupDatabase.<>c__DisplayClass8_0.<AddDirectoryEntryAsync>b__0()
   at Duplicati.Library.Main.Operation.Common.SingleRunner.<>c__DisplayClass3_0.<RunOnMain>b__0()
   at Duplicati.Library.Main.Operation.Common.SingleRunner.<DoRunOnMain>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.Backup.MetadataPreProcess.<AddFolderToOutputAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.Backup.MetadataPreProcess.<ProcessMetadata>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Duplicati.Library.Main.Operation.Backup.MetadataPreProcess.<>c__DisplayClass2_0.<<Run>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CoCoL.AutomationExtensions.<RunTask>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.BackupHandler.<RunMainOperation>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__20.MoveNext()
```

**Comment by dferreyra** [comment]
It looks like this is a duplicate of #3518.  I suppose this is another example, then, of programs under Windows that create directories that end in a dot.

**Comment by warwickmm** [comment]
Yes, directories that end with a dot [are invalid](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions):

> Do not end a file or directory name with a space or a period. Although the underlying file system may support such names, the Windows shell and user interface does not. However, it is acceptable to specify a period as the first character of a name. For example, ".temp".

Unfortunately, I don't think there's much we can do about this at the moment.

**Comment by warwickmm** [comment]
Support for problematic paths (ending with spaces or periods) was added in pull request #4256.
