### ISSUE TITLE
Duplicati does not understand A records with multiple IP Addresses

### ISSUE THREAD

**Issue by Germs2004** [duplicati/duplicati#4238]
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.107_canary_2020-05-26
- **Operating system**: Windows 10 Pro
- **Backend**: remote SFTP server

## Description

My remote SFTP server uses a public A-Record with 2 IP addresses on it.  That way, if a remote client detects that one IP is down (it times out), the client software can automatically try the other IP.  Duplicati doesn't do that - it just fails completely if the first IP it tries is down.

## Steps to reproduce

1. Create an A-Record that has multiple public IPs.
2. Set up an SFTP server and point your NAT router to forward connections from either of those public WAN interfaces to your internal SFTP server.
3. Point a Duplicati backup job to that A-record for its remote SFTP server destination
4. Verify that the backup works fine
5. Now, cause one of those IPs to be down.  Maybe disable the interface on your firewall, or edit the A-record to have a fake IP, etc.
6. Now, run the backup job.  50% of the time, Duplicati will get the bad IP, try to connect to it, and then give up.  The other 50% of the time, Duplicati will get the working IP so it will work fine.

- **Actual result**:
If Duplicati fails to connect via the first IP it tries, then it displays a red error popup that says "A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond".  Duplicati does not even attempt to connect to the other IP that was returned from the A-Record query.
- **Expected result**:
If Duplicati fails to connect to an IP belonging to an A-Record with multiple IPs, Duplicati should log a warning message for this backup job instance so that we can see later that there was an issue with that IP, but it should then continue running with the other IP(s) on the A-Record.  Duplicati should only log an ERROR and give up if every IP on the A-Record fail.  If at least one of the IPs works, Duplicati should only have warnings for the failed IPs and the backup job should be a success.

## Debug log

```
System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at Duplicati.Library.Main.BackendManager.List()
   at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, IEnumerable`1 protectedFiles)
   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, IEnumerable`1 protectedFiles)
   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CoCoL.ChannelExtensions.WaitForTaskOrThrow(Task task)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass14_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
```

**Comment by warwickmm** [comment]
I'm not very familiar with this part of the code, but it looks like we attempt something here:
https://github.com/duplicati/duplicati/blob/7a0ffd46e121970b4c6e38c8639803cdb46e1269/Duplicati/Library/Main/BackendManager.cs#L524-L535

However, this only occurs for certain `WebExceptions`, and not for a `SocketException` like you encountered.

**Comment by Germs2004** [comment]
I would think that, if a user specifies a DNS name for a backend server, then when Duplicati runs that backup job, it should:

1) query that A record to get a LIST of ip addresses
2) loop through each of those IPs, attempting to establish a connection with the backend server
3) if Duplicati is able to successfully connect to the backend server, then exit the loop and continue with the backup job.  Otherwise, continue looping through the other ips returned from the A Record until it finds an ip that successfully connects.  Each time it fails to connect to an ip, it should log a warning.  If it fails to connect to every ip from the A Record, it should log an error and fail the backup job.
4) Now that Duplicati has found a working IP address from that A Record, it can continue the backup job using that IP.

That method should allow Duplicati to try each IP from an A Record until it finds one that works instead of getting stuck after attempting only the first ip.

I might be able to write the loop code for a pull request if you don't mind pointing me to the correct file.  I searched for GetHostName but only found the file you referred to, which doesn't appear to be the correct place to do this loop.

**Comment by warwickmm** [comment]
I'm not sure where the best place is for this.  Each backend is free to implement their own connections.  Many of the implementations use `AsyncHttpRequest`, which utilizes `WebRequest` and `HttpWebRequest` underneath.

**Comment by Xavron** [comment]
Interesting. Looks like its partially true with the above code involving GetHostEntry() with a mention here with the intention of looking up records (not necessarily A records) https://stackoverflow.com/questions/2669841/how-to-get-mx-records-for-a-dns-name-with-system-net-dns

Probably wouldn't take much time to do this. But, I don't have that time as it was spent on looking at this. Maybe someday.

**Comment by ts678** [comment]
This enhancement probably won't need special measures such as used in the MX records example. [DNS.GetHostEntry](https://docs.microsoft.com/en-us/dotnet/api/system.net.dns.gethostentry?view=netframework-4.8) looks like it returns an [IPHostEntry.AddressList](https://docs.microsoft.com/en-us/dotnet/api/system.net.iphostentry.addresslist?view=netframework-4.8) with all the addresses. A simple system might just use the first. A complex one may try others.

You could still get hurt by protocols that involve interacting with multiple servers, such as Backblaze B2 which [passes you around](https://www.backblaze.com/b2/docs/calling.html).

> I'm not sure where the best place is for this

I'm not either, but because the enhancement needs IP forced on the backend, maybe it could be chosen/forced on backend URLs:

https://github.com/duplicati/duplicati/blob/24990a4011d207ce610b6d5998cdc79c24506e02/Duplicati/Library/Interface/IBackend.cs#L27-L37

**Comment by C1618A** [comment]
This continues to be a problem on Duplicati - 2.0.7.1_beta_2023-05-25
