### ISSUE TITLE
"Show" log button takes you to page with no logs

### ISSUE THREAD

**Issue by Germs2004** [duplicati/duplicati#4239]
- [ x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.107_canary_2020-05-26
- **Operating system**: Windows 10 Pro
- **Backend**: remote SFTP server

## Description

My backup job failed recently because the remote IP address for the SFTP server was down.  Duplicati showed a red error popup that says "A connection attempt failed because the connected party did not properly respond..." and has a "Show" and "Dismiss" button.  When I click Show, it takes me to the backup job's log page, but there are no logs there for the failed job instance.  Apparently, Duplicati does not log anything in the job instance section when this type of error happens.  Instead, if I click About > Show Log, then I can see a log entry for this failure event.

Either Duplicati needs to write a log to the job log page so that the Show button's link takes the user to a relevant page, or the Show button should take the user to the About > Log page where Duplicati currently writes this log.

## Steps to reproduce

1. Run a backup job where the remote server is inaccessible.
2. You should see a red error at the bottom of the page saying "A connection attempt failed because the..."
3. Click the Show button on that error box.
4. Notice that it takes you to the job's log list, but there is no log info there related to the error you just saw.

- **Actual result**:
The Show button takes you to an irrelevant page because there are no logs there mentioning the error you just got.
- **Expected result**:
The Show button should take you to a page where you can see actual details for the error you got.  Either Duplicati should add a log to the job page, and not just the About > Log page, or the Show button should take the user to the About > Log page.

I prefer that Duplicati add a log to the job log page in this case because it's important for a user to see that the job was attempted and failed.  Currently, there's no sign that the job ran at all in the job log.

## Screenshots

Notice in this screenshot that there's an error from a failed job, but there are no errors in the job log:
![image](https://user-images.githubusercontent.com/5519340/85956148-edb87600-b951-11ea-96f5-246372f3970c.png)

## Debug log

Here's the log found in About > Show Log
```
System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at Duplicati.Library.Main.BackendManager.List()
   at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, IEnumerable`1 protectedFiles)
   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, IEnumerable`1 protectedFiles)
   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CoCoL.ChannelExtensions.WaitForTaskOrThrow(Task task)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass14_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
```

**Comment by warwickmm** [comment]
Thanks.  I believe this is related to issue #3895.

**Comment by warwickmm** [comment]
Closing this in favor of #1152.
