### ISSUE TITLE
exe file corruption

### ISSUE THREAD

**Issue by cosmopol** [duplicati/duplicati#4339]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.1_beta_2020-01-18
- **Operating system**: Win 8.1 Pro 64-bit
- **Backend**: SD card 32GB

## Description

Executable files are corrupted and crash the system on invocation

## Steps to reproduce

The Quantum xTalk executable is one example of a half-corrupted file that was OK on backup, but got destroyed on restore!
"5-00555-14_xTalk-6.7.0.0_QUANTUM_Setup.exe"

- **Actual result**:
exe file corruption!
- **Expected result**:
No exe file corruption!

## Debug log

(There was no error message posted nowhere!)
System.IO.DirectoryNotFoundException: Could not find a part of the path '{X}.exe.local'.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)

   at System.IO.File.Create(String path)

   at Duplicati.Library.Common.IO.SystemIOWindows.PathTooLongFuncWrapper[T](Func`2 nativeIOFunc, Func`2 alternativeIOFunc, String path, Boolean prefixWithUnc)

   at Duplicati.Library.Common.IO.SystemIOWindows.FileCreate(String path)

   at Duplicati.Library.Main.Operation.RestoreHandler.DoRun(LocalDatabase dbparent, IFilter filter, RestoreResults result)

   at Duplicati.Library.Main.Operation.RestoreHandler.Run(String[] paths, IFilter filter)

   at Duplicati.Library.Main.Controller.<>c__DisplayClass15_0.<Restore>b__0(RestoreResults result)

   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)

   at Duplicati.Library.Main.Controller.Restore(String[] paths, IFilter filter)

   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

###

System.Security.Cryptography.CryptographicException: Failed to decrypt data (invalid passphrase?): Invalid password or corrupted data ---> SharpAESCrypt.SharpAESCrypt+WrongPasswordException: Invalid password or corrupted data

   at SharpAESCrypt.SharpAESCrypt.ReadEncryptionHeader(String password, Boolean skipFileSizeCheck)

   at SharpAESCrypt.SharpAESCrypt..ctor(String password, Stream stream, OperationMode mode, Boolean skipFileSizeCheck)

   at Duplicati.Library.Encryption.AESEncryption.Decrypt(Stream input)

   at Duplicati.Library.Encryption.EncryptionBase.Decrypt(Stream input, Stream output)

   --- End of inner exception stack trace ---

   at Duplicati.Library.Main.AsyncDownloader.AsyncDownloaderEnumerator.AsyncDownloadedFile.get_TempFile()

   at Duplicati.Library.Main.Operation.ListFilesHandler.CreateResultSequence(IEnumerable`1 filteredList, BackendManager backendManager, Options options)

   at Duplicati.Library.Main.Operation.ListFilesHandler.Run(IEnumerable`1 filterstrings, IFilter compositefilter)

   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)

   at Duplicati.Library.Main.Controller.List(IEnumerable`1 filterstrings, IFilter filter)

   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
   
###

System.Security.Cryptography.CryptographicException: Failed to decrypt data (invalid passphrase?): Invalid password or corrupted data ---> SharpAESCrypt.SharpAESCrypt+WrongPasswordException: Invalid password or corrupted data

   at SharpAESCrypt.SharpAESCrypt.ReadEncryptionHeader(String password, Boolean skipFileSizeCheck)

   at SharpAESCrypt.SharpAESCrypt..ctor(String password, Stream stream, OperationMode mode, Boolean skipFileSizeCheck)

   at Duplicati.Library.Encryption.AESEncryption.Decrypt(Stream input)

   at Duplicati.Library.Encryption.EncryptionBase.Decrypt(Stream input, Stream output)

   --- End of inner exception stack trace ---

   at Duplicati.Library.Main.AsyncDownloader.AsyncDownloaderEnumerator.AsyncDownloadedFile.get_TempFile()

   at Duplicati.Library.Main.Operation.ListFilesHandler.CreateResultSequence(IEnumerable`1 filteredList, BackendManager backendManager, Options options)

   at Duplicati.Library.Main.Operation.ListFilesHandler.Run(IEnumerable`1 filterstrings, IFilter compositefilter)

   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)

   at Duplicati.Library.Main.Controller.List(IEnumerable`1 filterstrings, IFilter filter)

   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

   at Duplicati.Server.WebServer.RESTMethods.Backup.ListFileSets(IBackup backup, RequestInfo info)

   at Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)
   
###

System.ObjectDisposedException: Cannot write to a closed TextWriter.

   at System.IO.__Error.WriterClosed()

   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)

   at Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)

**Comment by warwickmm** [comment]
> System.Security.Cryptography.CryptographicException: Failed to decrypt data (invalid passphrase?): Invalid password or corrupted data ---> SharpAESCrypt.SharpAESCrypt+WrongPasswordException: Invalid password or corrupted data

This is often due to the browser automatically filling in an incorrect password.  Can try again after ensuring that your browser is not filling in any passwords in the restore step?

**Comment by warwickmm** [comment]
Closing due to lack of feedback.  If this is still an issue, please re-open with more details.
