### ISSUE TITLE
Deleting remote .dblock.zip.aes files despite unlimited retention

### ISSUE THREAD

**Issue by przerull** [duplicati/duplicati#4355]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati**: Duplicati.GUI.TrayIcon, Version=2.0.5.1, Culture=neutral, PublicKeyToken=null (Duplicati.Library.Main, Version=2.0.5.1, - Culture=neutral, PublicKeyToken=null)
- **Autoupdate urls**: https://updates.duplicati.com/beta/latest.manifest;https://alt.updates.duplicati.com/beta/latest.manifest
- **Update folde**r: C:\ProgramData\Duplicati\updates
- **Base install folder**: C:\Program Files\Duplicati 2
- **Version name**: "2.0.5.1_beta_2020-01-18" (2.0.5.1)
- **Current Version folder**: C:\Program Files\Duplicati 2
- **OS**: Microsoft Windows NT 10.0.18363.0
- **Uname**: 
- **64bit**: True (True)
- **Machinename**: ZEUS
- **Processors**: 8
- **.Net Version**: 4.0.30319.42000
- **Mono**: False (0.0) ()
- **Locale**: en-US, en-US, en-US
- **Date/time strings**: dddd, MMMM d, yyyy - h:mm:ss tt
- **Tempdir**: C:\Users\Philip Zerull\AppData\Local\Temp\
- **SQLite**: 3.28.0 - System.Data.SQLite.SQLiteConnection
- **SQLite assembly**: C:\Program Files\Duplicati 2\SQLite\win64\System.Data.SQLite.dll

### Backend info
- **Storage Type**: Amazon S3
- **Use SSL**: True
- **Server**: s3.us-east-2.wasabisys.com
- **Bucket create region**: US East (ohio) (us-east-2)
- **Storage Class**: (default)()
- **Client Library to Use**: Amazon AWS SDK

## Description

Despite the fact that I have unlimited version retention (daily backups) configured for this backup, duplicati will occasionally try to delete some of the .dblock.zip.aes files.

For security reasons, I have the AWS user assigned to perform these backups to only have read and write access, but not delete access (the reasoning here is that even if this user's AWS credentials are compromised, no damage can be done to backups.  Backups are encrypted so even if an attacker gains access they'd have to decrypt the backup files).  Because of my desired premission requirements and duplicati's behavior of deleting some of the .dblock.zip.aes files, the backup jobs fail.

Granting the wasabi policy entitled "AmazonS3FullAccess" grants the delete permission and allows the backups to proceed.  I've found that if I just turn it on and successfully get one backup (which performs some .dblock.zip.aes file deletions), then I can remove the AmazonS3FullAccess permissions and backups continue to run successfully for about a month until the same issue re-occurs.

I suspect this is happening during backend verification.  I have also noticed that setting the advanced option "no-backend-verification" to True, then the backup completes (but with warnings).

Any help is greatly appreciated.

## Steps to reproduce

1. Since wasabi is not a free service, I'd be willing to help set up a bucket and user credentials to help in testing (probably not a good idea to post credentials here lol).  I suspect that a similar issue could be re-created with a similar amazon S3 setup.
2. The bucket has versioning but was basically wasabi's defaults for buckets (it seemed reasonable).
3. The user has the following policies: WasabiReadOnlyAccess, WasabiWriteOnlyAccess. [This document](https://assets.wasabi.com/wp-content/uploads/2018/07/Wasabi_User_Guide.pdf?x68053) describes the wasabi pre-defined policies.
4. The backup should use a wasabi bucket (the bucket name must not be prefixed with the username)
5. The retention policy should be set to unlimited.
6. Let the backup run for a while 

- **Actual result**:
Job fails under current configuration. Job finishes but with warnings if no-backend-verification is turned on.  Job succeeds if AWS user has delete permissions.
- **Expected result**:
Perhaps I'm missing something and this is all intended behavior and I'm actually asking for a new feature here.  It'd be nice if I could get the jobs to run successfully without having delete access nor having no-backup-verification turned on.   Perhaps I've missed some advanced configuration setting (but I've spent a few hours this morning making attempts with different options).

## Debug log

Hopefully this is helpful, but they just look like stack traces saying the same thing I'm saying above.   Please let me know if any additional information is needed.

This is from About -> Show Log -> Live -> Verbose
```
{"ClassName":"Amazon.S3.AmazonS3Exception","Message":"Access Denied","Data":null,"InnerException":{"ClassName":"Amazon.Runtime.Internal.HttpErrorResponseException","Message":"The remote server returned an error: (403) Forbidden.","Data":null,"InnerException":{"ClassName":"System.Net.WebException","Message":"The remote server returned an error: (403) Forbidden.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.Net.HttpWebRequest.GetResponse()\r\n   at Amazon.Runtime.Internal.HttpRequest.GetResponse()","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nGetResponse\nSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Net.HttpWebRequest\nSystem.Net.WebResponse GetResponse()","HResult":-2146233079,"Source":"System","WatsonBuckets":null},"HelpURL":null,"StackTraceString":"   at Amazon.Runtime.Internal.HttpRequest.GetResponse()\r\n   at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext)\r\n   at Amazon.Runtime.Internal.RedirectHandler.InvokeSync(IExecutionContext executionContext)\r\n   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext)\r\n   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeSync(IExecutionContext executionContext)\r\n   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nGetResponse\nAWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604\nAmazon.Runtime.Internal.HttpRequest\nAmazon.Runtime.Internal.Transform.IWebResponseData GetResponse()","HResult":-2146233088,"Source":"AWSSDK.Core","WatsonBuckets":null,"Response":{"StatusCode":"Forbidden","IsSuccessStatusCode":false,"ContentType":"application/xml","ContentLength":-1,"ResponseBody":{}}},"HelpURL":null,"StackTraceString":"   at Duplicati.Library.Main.BackendManager.Delete(String remotename, Int64 size, Boolean synchronous)\r\n   at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)\r\n   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)\r\n   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend, String protectedfile)\r\n   at Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__20.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at CoCoL.ChannelExtensions.WaitForTaskOrThrow(Task task)\r\n   at Duplicati.Library.Main.Controller.<>c__DisplayClass14_0.<Backup>b__0(BackupResults result)\r\n   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)\r\n   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)\r\n   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nDelete\nDuplicati.Library.Main, Version=2.0.5.1, Culture=neutral, PublicKeyToken=null\nDuplicati.Library.Main.BackendManager\nVoid Delete(System.String, Int64, Boolean)","HResult":-2146233088,"Source":"Duplicati.Library.Main","WatsonBuckets":null,"errorCode":"AccessDenied","errorType":"Sender","requestId":"E122A134840208C6","statusCode":"Forbidden","AmazonId2":"I_AM_MANUALLY_REACTING_THIS","ResponseBody":null}
```

This is from the backup's remote log:

```
Oct 30, 2020 8:36 AM: delete duplicati-b641998c37909455091bc88ebdf9e8e08.dblock.zip.aes
Amazon.S3.AmazonS3Exception: Access Denied ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (403) Forbidden. ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RedirectHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.AmazonServiceClient.Invoke[TResponse](AmazonWebServiceRequest request, InvokeOptionsBase options)
   at Duplicati.Library.Main.BackendManager.DoDelete(FileEntryItem item)
```

**Comment by drwtsn32x** [comment]
Unless you disable automatic compaction, Duplicati may attempt to repackage some dblock files in an effort to reduce wasted space or to reduce the number of files.

In your case since you have unlimited retention, it's probably not that first thing (wasted space).  Wasted space happens when some data is expired.  So it's probably the second thing (reduce the number of files).  Some dblocks may not be full size (50MiB by default) so when there are several smaller ones Duplicati may decide to repackage.

You can disable this behavior with the `--no-auto-compact` option.

**Comment by przerull** [comment]
Hmmm, so I turned on no-auto-compact.  It still seems to be trying to delete the remote .dblock.zip.aes files

![image](https://user-images.githubusercontent.com/304209/97770050-5f721d80-1b06-11eb-9e26-c66f15e1e3dc.png)

```
Oct 30, 2020 11:16 PM: delete duplicati-b641998c37909455091bc88ebdf9e8e08.dblock.zip.aes
Amazon.S3.AmazonS3Exception: Access Denied ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (403) Forbidden. ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RedirectHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.AmazonServiceClient.Invoke[TResponse](AmazonWebServiceRequest request, InvokeOptionsBase options)
   at Duplicati.Library.Main.BackendManager.DoDelete(FileEntryItem item)
```

**Comment by drwtsn32x** [comment]
Ok yeah this actually came up recently on the forum:

https://forum.duplicati.com/t/50-bounty-attempting-deletion-of-files-before-retention-span-is-over/10932/6?u=drwtsn32

I believe Duplicati already did the compaction and uploaded a new volume, and "knows" it needs to delete the old volumes.  So it will continue to try and do so at this point.

If possible, could you enable deletions temporarily just to make Duplicati happy?  You can then lock it back down and this shouldn't happen again if you leave the `--no-auto-compact` option enabled.

**Comment by przerull** [comment]
Thanks.  That was super helpful.   I temporarily added the delete authorization.  The job ran fine.  Then I removed the delete authorization and subsequent jobs have been running fine as well.

Thanks again!
