### ISSUE TITLE
Command purge-broken-files throws SQLiteException 0x80004005 unknown error

### ISSUE THREAD

**Issue by KarbyCZ** [duplicati/duplicati#4379]
- [x] I have searched open and closed issues for duplicates.

## Environment info
- **Duplicati version**: 2.0.5.111_canary_2020-09-26
- **Operating system**: Windows 10 Enterprise, version 20H2 
- **Backend**: Local (network mapped drive to another Windows 10 machine on the same LAN)

## Description
Command **purge-broken-files** fails with System.Data.SQLite.SQLiteException (0x80004005): unknown error.

## Steps to reproduce
1. Open the Duplicati UI, go to the backup, command line...
2. Pick purge-broken-files, provide one command-line argument --dry-run
3. Scroll to bottom, click **Run "purge-broken-files" command now** button

- **Actual result**:

```
  Listing remote folder ...

code = Unknown (-1), message = System.Data.SQLite.SQLiteException (0x80004005): unknown error
No transaction is active on this connection
   at System.Data.SQLite.SQLiteTransactionBase.IsValid(Boolean throwError)
   at System.Data.SQLite.SQLiteTransactionBase.Rollback()
   at Duplicati.Library.Main.Operation.PurgeBrokenFilesHandler.Run(IFilter filter)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.PurgeBrokenFiles(IFilter filter)
   at Duplicati.CommandLine.Commands.PurgeBrokenFiles(TextWriter outwriter, Action`1 setup, List`1 args, Dictionary`2 options, IFilter filter)
   at Duplicati.CommandLine.Program.ParseCommandLine(TextWriter outwriter, Action`1 setup, Boolean& verboseErrors, String[] args)
   at Duplicati.CommandLine.Program.RunCommandLine(TextWriter outwriter, TextWriter errwriter, Action`1 setup, String[] args)
Return code: 100
```

- **Expected result**:
Command should complete successfully and delete broken files from the existing backups.

## Full Story

I created a new backup of my user home directory on Windows, approx. 30 GB, 190 thousand files. First backup got stuck because of #1797 or #4308. So i rebooted the computer, added an exclusion for `AppData\Local\Duplicati\`, started the backup again and it completed successfully. Few days later, out of curiosity, I restored some selected files (worked fine) and also ran a command `test all --full-remote-verification`. That returned one broken dblock. I confirmed with SharpAESCrypt.exe that the file is really corrupted (other files are good).

I renamed the file on the target storage (read: deleted). Now backup fails with error

> Found 1 files that are missing from the remote storage, please run repair

Okay, so I ran the repair command, which failed with error:

> The backup storage destination is missing data files. You can either enable `--rebuild-missing-dblock-files` or run the purge command to remove these files. The following files are missing: duplicati-bdc7e234b7b5f40c5869f459d72a0e88a.dblock.zip.aes

Okay, rebuilding missing dblock files sounds great, but it failed with:

> Failed to perform cleanup for missing file: duplicati-bdc7e234b7b5f40c5869f459d72a0e88a.dblock.zip.aes, message: Repair not possible, missing 595 blocks. If you want to continue working with the database, you can use the "list-broken-files" and "purge-broken-files" commands to purge the missing data from the database and the remote storage.

Since repair is not getting me anywhere, let's purge the existing backups (with a limited data loss), the future backups should fix the missing/purged files, that's okay with me. However, the purge command fails with the SQLiteException -- which is this GitHub issue.

**Comment by warwickmm** [comment]
I am unable to reproduce this.  Can you make sure that your disk (in particular, where the temporary files are being stored) has sufficient free space?

You may want to try posting in the forums to see if anyone has experienced a similar issue.

https://forum.duplicati.com/

**Comment by ts678** [comment]
> I am unable to reproduce this.

While the `Full Story` sequence is a lot, did you at least do the ending, e.g. have a `repair` fail before the `purge-broken-files`?

> You may want to try posting in the forums to see if anyone has experienced a similar issue.

Might work, however [Recreating database logic/understanding/issue/slow](https://forum.duplicati.com/t/recreating-database-logic-understanding-issue-slow/6496/54?u=ts678) was the similar case I found.

My steps:

Backup short file to local folder.

Delete the dblock.

Repair, and notice its complaint.

purge-broken-files with dry-run

```
Running commandline entry
Finished!

            
  Listing remote folder ...

code = Unknown (-1), message = System.Data.SQLite.SQLiteException (0x80004005): unknown error
No transaction is active on this connection
   at System.Data.SQLite.SQLiteTransactionBase.IsValid(Boolean throwError)
   at System.Data.SQLite.SQLiteTransactionBase.Rollback()
   at Duplicati.Library.Main.Operation.PurgeBrokenFilesHandler.Run(IFilter filter)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.PurgeBrokenFiles(IFilter filter)
   at Duplicati.CommandLine.Commands.PurgeBrokenFiles(TextWriter outwriter, Action`1 setup, List`1 args, Dictionary`2 options, IFilter filter)
   at Duplicati.CommandLine.Program.ParseCommandLine(TextWriter outwriter, Action`1 setup, Boolean& verboseErrors, String[] args)
   at Duplicati.CommandLine.Program.RunCommandLine(TextWriter outwriter, TextWriter errwriter, Action`1 setup, String[] args)
Return code: 100
```

2.0.5.111 on Windows 10 20H2

**Comment by warwickmm** [comment]
Thanks @ts678, I missed that detail.  I'm seeing this specific exception being thrown when we call `Rollback` here:

https://github.com/duplicati/duplicati/blob/9b977b7ba04a940868754fd15a37b99fbd77f1bd/Duplicati/Library/Main/Operation/PurgeBrokenFilesHandler.cs#L170-L173

```
{Mono.Data.Sqlite.SqliteException (0x80004005): Library used incorrectly
No transaction is active on this connection
  at Mono.Data.Sqlite.SqliteTransaction.IsValid (System.Boolean throwError) [0x00028] in /build/mono/src/mono/mcs/class/Mono.Data.Sqlite/Mono.Data.Sqlite_2.0/SQLiteTransaction.cs:154 
  at Mono.Data.Sqlite.SqliteTransaction.Rollback () [0x00000] in /build/mono/src/mono/mcs/class/Mono.Data.Sqlite/Mono.Data.Sqlite_2.0/SQLiteTransaction.cs:127 
  at Duplicati.Library.Main.Operation.PurgeBrokenFilesHandler.Run (Duplicati.Library.Utility.IFilter filter) [0x00744] in /home/ken/documents/code/duplicati/Duplicati/Library/Main/Operation/PurgeBrokenFilesHandler.cs:173 }
	base: {System.Data.Common.DbException}
	ErrorCode: Mono.Data.Sqlite.SQLiteErrorCode.Misuse
	Static members: 
	Non-public members: 
```

Here is where the exception is generated in mono:

https://github.com/mono/mono/blob/c5b88ec4f323f2bdb7c7d0a595ece28dae66579c/mcs/class/Mono.Data.Sqlite/Mono.Data.Sqlite_2.0/SQLiteTransaction.cs#L144-L168

**Comment by warwickmm** [comment]
Pull request #4380 has a proposed fix.  I'm not entirely confident in it though, as I have limited database/SQLite knowledge.  But I was able to write a test that failed with the error described in this issue, and the proposed fix does appear to resolve it.
