### ISSUE TITLE
Error: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#443]
_From [jimmille...@gmail.com](https://code.google.com/u/117235207450525669508/) on July 05, 2011 20:22:06_

What steps will reproduce the problem? 1. Configure a recurring backup job over ftp to onlinestoragesolution.com
2. Shortly after starting the backup fail. What is the expected output? What do you see instead? Fails with the following message:
Error: Index was outside the bounds of the array.

Error: System.Security.Cryptography.CryptographicException: Index was outside the bounds of the array. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Security.Cryptography.RijndaelManagedTransform.DecryptData(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[]& outputBuffer, Int32 outputOffset, PaddingMode paddingMode, Boolean fLast)
   at System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.Stream.Dispose()
   at Duplicati.Library.Encryption.EncryptionBase.Decrypt(Stream input, Stream output)
   at Duplicati.Library.Encryption.EncryptionBase.Decrypt(String inputfile, String outputfile)
   at Duplicati.Library.Main.BackendWrapper.GetInternal(BackupEntryBase remote, Manifestfile manifest, String filename, HashEntry hash)
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.BackendWrapper.ProtectedInvoke(String methodname, Object[] arguments)
   at Duplicati.Library.Main.Interface.GetManifest(BackendWrapper backend, ManifestEntry entry)
   at Duplicati.Library.Main.Interface.VerifyBackupChainWithFiles(BackendWrapper backend, ManifestEntry entry)
   at Duplicati.Library.Main.Interface.Backup(String[] sources)
   at Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
InnerError: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Security.Cryptography.RijndaelManagedTransform.DecryptData(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[]& outputBuffer, Int32 outputOffset, PaddingMode paddingMode, Boolean fLast)
   at System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.Stream.Dispose()
   at Duplicati.Library.Encryption.EncryptionBase.Decrypt(Stream input, Stream output)
   at Duplicati.Library.Encryption.EncryptionBase.Decrypt(String inputfile, String outputfile)
   at Duplicati.Library.Main.BackendWrapper.GetInternal(BackupEntryBase remote, Manifestfile manifest, String filename, HashEntry hash)
Cleanup output: What version of the product are you using? On what operating system? 1.2. Windows Server 2003 SP2 32 bit

What backend (destination) are you using?  onlinestoragesolution.com Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=443_

**Comment by JeffreyPFD** [comment]
I am having the same error code.  Can you please help?

I am running: 
Duplicati - 2.0.1.49_experimental_2017-02-23
Onedrive
Windows 10, 32bit

I am trying to run the back-up for the first time, but am getting nowhere.  Any help would be appreciated.  Thanks

Here is a screen shot of the log
![image](https://cloud.githubusercontent.com/assets/26304387/23824651/dac08b0a-063f-11e7-9649-09eeb630f2fc.png)

**Comment by MaximilianKohler** [comment]
Same as JeffreyPFD, I'm also getting this error when trying for the first time with OneDrive. 

System.IndexOutOfRangeException: Index was outside the bounds of the array. at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes) at Duplicati.Library.Main.Operation.BackupHandler.RunMainOperation(ISnapshotService snapshot, BackendManager backend) at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter) at Duplicati.Library.Main.Controller.<>c__DisplayClass16_0.<Backup>b__0(BackupResults result) at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method) at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter) at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
