### ISSUE TITLE
Duplicati.CommandLine.RecoveryTool recompress mangles its own filenames and so fails to find them

### ISSUE THREAD

**Issue by ts678** [duplicati/duplicati#4490]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.1 and many more, back to 2.0.2.1
- **Operating system**: Windows 10 20H2 or Linux Mint 19.3
- **Backend**: Folder

## Description

Duplicati.CommandLine.RecoveryTool recompress seems completely broken. Initially I was trying to see if it could be persuaded to recreate the `volumehash` field in dindex files after I manually re-encrypted all the files with a different passphrase for forum topic: 

[Passphrase cannot be changed for an existing backup](https://forum.duplicati.com/t/passphrase-cannot-be-changed-for-an-existing-backup/8866/11?u=ts678)

but it kept failing because it couldn't find the dblock. The messages looked kind of weird, missing the dots somehow. This was on Windows originally, so I thought maybe Linux would work, but that doesn't either. Originally I was using --reupload, --reencrypt, --passphrase, but it turns out it fails without those, so I'll give the simple test case below.

## Steps to reproduce

1. Backup a short file, no encryption
2. Run Duplicati.CommandLine.RecoveryTool recompress zip \<remoteurl> \<localfolder>

- **Actual result**:
Can't find its dblockzip file because it should (I think) be looking for a dblock.zip file with dots in the filename, as usually done.
- **Expected result**:
I guess it should recompress backup and leave results in localfolder without uploads?

## Debug log
```
$ mono Duplicati.CommandLine.RecoveryTool.exe recompress zip /home/me/DuplicatiBackups/reencrypt /tmp/reencrypt
Listing files on backend: file ...
Found 3 files at remote storage
Found 3 files which belongs to backup with prefix duplicati
1/3: duplicati-20210425T214600Z.dlist.zip - downloading (628 bytes)... recompressing ... done!
2/3: duplicati-b9f9d23e774d64eba87a3e2420695ff07.dblock.zip - downloading (715 bytes)... recompressing ... done!
3/3: duplicati-i63ff2dde06cd431683cf1b3eedd0a4c2.dindex.zip - downloading (608 bytes)... recompressing ... error: System.IO.FileNotFoundException: Could not find file "/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07dblockzip"
File name: '/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07dblockzip'
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <d13c8b563008422a8c5aaec0a74089cc>:0 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) [0x00000] in <d13c8b563008422a8c5aaec0a74089cc>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
  at System.IO.FileInfo.Open (System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) [0x00006] in <d13c8b563008422a8c5aaec0a74089cc>:0 
  at System.IO.FileInfo.Open (System.IO.FileMode mode) [0x00000] in <d13c8b563008422a8c5aaec0a74089cc>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileInfo.Open(System.IO.FileMode)
  at Duplicati.CommandLine.RecoveryTool.Recompress.Run (System.Collections.Generic.List`1[T] args, System.Collections.Generic.Dictionary`2[TKey,TValue] options, Duplicati.Library.Utility.IFilter filter) [0x00747] in <e9be12affb6f47979004129a9a3a1473>:0 
Download complete, of 3 remote files, 3 were downloaded with 1 errors
There were errors during recompress of remote backend files!
```

Note above weird dot removal in `duplicati-b9f9d23e774d64eba87a3e2420695ff07dblockzip`. It's not just a message glitch below, where I'm keeping an eye on the correct file (which is written) and the dotless version of it (which gives the `Could not find file` ):

```
$ strace -f -P /tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07.dblock.zip -P /tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07dblockzip mono Duplicati.CommandLine.RecoveryTool.exe recompress zip /home/me/DuplicatiBackups/reencrypt /tmp/reencrypt
strace: Process 13334 attached
strace: Process 13335 attached
strace: Process 13336 attached
[pid 13336] +++ exited with 0 +++
[pid 13333] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=13336, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
strace: Process 13337 attached
strace: Process 13338 attached
strace: Process 13339 attached
strace: Process 13340 attached
[pid 13340] +++ exited with 0 +++
[pid 13337] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=13340, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
strace: Process 13341 attached
Listing files on backend: file ...
Found 3 files at remote storage
Found 3 files which belongs to backup with prefix duplicati
1/3: duplicati-20210425T214600Z.dlist.zip - downloading (628 bytes)... recompressing ... done!
2/3: duplicati-b9f9d23e774d64eba87a3e2420695ff07.dblock.zip[pid 13337] stat("/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07.dblock.zip", 0x7ffe4269c280) = -1 ENOENT (No such file or directory)
[pid 13337] lstat("/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07.dblock.zip", 0x7ffe4269c2a0) = -1 ENOENT (No such file or directory)
[pid 13337] stat("/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07.dblock.zip", 0x7ffe4269c280) = -1 ENOENT (No such file or directory)
[pid 13337] lstat("/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07.dblock.zip", 0x7ffe4269c2a0) = -1 ENOENT (No such file or directory)
 - downloading (715 bytes)...[pid 13337] stat("/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07.dblock.zip", 0x7ffe4269c210) = -1 ENOENT (No such file or directory)
[pid 13337] lstat("/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07.dblock.zip", 0x7ffe4269c230) = -1 ENOENT (No such file or directory)
[pid 13337] stat("/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07.dblock.zip", 0x7ffe4269c050) = -1 ENOENT (No such file or directory)
[pid 13337] lstat("/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07.dblock.zip", 0x7ffe4269c070) = -1 ENOENT (No such file or directory)
[pid 13337] stat("/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07.dblock.zip", 0x7ffe4269c270) = -1 ENOENT (No such file or directory)
[pid 13337] lstat("/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07.dblock.zip", 0x7ffe4269c270) = -1 ENOENT (No such file or directory)
[pid 13337] openat(AT_FDCWD, "/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07.dblock.zip", O_RDWR|O_CREAT|O_EXCL, 0666) = 6
[pid 13337] fstat(6, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
[pid 13337] fchmod(6, 0644)             = 0
[pid 13337] sendfile(6, 5, NULL, 715)   = 715
[pid 13337] utimensat(6, NULL, [{tv_sec=1619387161, tv_nsec=531482403} /* 2021-04-25T17:46:01.531482403-0400 */, {tv_sec=1619387161, tv_nsec=259482407} /* 2021-04-25T17:46:01.259482407-0400 */], 0) = 0
[pid 13337] close(6)                    = 0
[pid 13337] lstat("/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07.dblock.zip", {st_mode=S_IFREG|0644, st_size=715, ...}) = 0
[pid 13337] utimes("/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07.dblock.zip", [{tv_sec=1619387161, tv_usec=531482} /* 2021-04-25T17:46:01.531482-0400 */, {tv_sec=1619387161, tv_usec=259482} /* 2021-04-25T17:46:01.259482-0400 */]) = 0
 recompressing ...[pid 13337] stat("/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07.dblock.zip", {st_mode=S_IFREG|0644, st_size=715, ...}) = 0
[pid 13337] lstat("/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07.dblock.zip", {st_mode=S_IFREG|0644, st_size=715, ...}) = 0
[pid 13337] rename("/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07.dblock.zip", "/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07.dblock.zip.same") = 0
[pid 13337] stat("/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07.dblock.zip", 0x7ffe4269c190) = -1 ENOENT (No such file or directory)
[pid 13337] lstat("/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07.dblock.zip", 0x7ffe4269c1b0) = -1 ENOENT (No such file or directory)
[pid 13337] stat("/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07.dblock.zip", 0x7ffe4269c3b0) = -1 ENOENT (No such file or directory)
[pid 13337] lstat("/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07.dblock.zip", 0x7ffe4269c3b0) = -1 ENOENT (No such file or directory)
[pid 13337] openat(AT_FDCWD, "/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07.dblock.zip", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 6
[pid 13337] fstat(6, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
[pid 13337] lseek(6, 0, SEEK_SET)       = 0
[pid 13337] write(6, "PK\3\4\24\0\0\0\10\0\300\215\231R\0\0\0\0\0\0\0\0\0\0\0\0\10\0\0\0ma"..., 156) = 156
[pid 13337] lseek(6, 6, SEEK_SET)       = 6
[pid 13337] lseek(6, 6, SEEK_SET)       = 6
[pid 13337] write(6, "\0", 1)           = 1
[pid 13337] lseek(6, 14, SEEK_SET)      = 14
[pid 13337] lseek(6, 14, SEEK_SET)      = 14
[pid 13337] write(6, ",\\\36\264v\0\0\0\222\0\0\0", 12) = 12
[pid 13337] lseek(6, 156, SEEK_SET)     = 156
[pid 13337] lseek(6, 156, SEEK_SET)     = 156
[pid 13337] write(6, "PK\3\4\24\0\0\0\10\0\300\215\231R\0\0\0\0\0\0\0\0\0\0\0\0,\0\0\0005x"..., 106) = 106
[pid 13337] lseek(6, 162, SEEK_SET)     = 162
[pid 13337] lseek(6, 162, SEEK_SET)     = 162
[pid 13337] write(6, "\0", 1)           = 1
[pid 13337] lseek(6, 170, SEEK_SET)     = 170
[pid 13337] lseek(6, 170, SEEK_SET)     = 170
[pid 13337] write(6, "\230K\24\21 \0\0\0\36\0\0\0", 12) = 12
[pid 13337] lseek(6, 262, SEEK_SET)     = 262
[pid 13337] lseek(6, 262, SEEK_SET)     = 262
[pid 13337] write(6, "PK\3\4\24\0\0\0\10\0\300\215\231R\0\0\0\0\0\0\0\0\0\0\0\0,\0\0\0hS"..., 197) = 197
[pid 13337] lseek(6, 268, SEEK_SET)     = 268
[pid 13337] lseek(6, 268, SEEK_SET)     = 268
[pid 13337] write(6, "\0", 1)           = 1
[pid 13337] lseek(6, 276, SEEK_SET)     = 276
[pid 13337] lseek(6, 276, SEEK_SET)     = 276
[pid 13337] write(6, "\355@M\177{\0\0\0\277\0\0\0", 12) = 12
[pid 13337] lseek(6, 459, SEEK_SET)     = 459
[pid 13337] lseek(6, 459, SEEK_SET)     = 459
[pid 13337] write(6, "PK\1\2\24\0\24\0\0\0\10\0\300\215\231R,\\\36\264v\0\0\0\222\0\0\0\10\0\0\0"..., 256) = 256
[pid 13337] close(6)                    = 0
[pid 13337] lstat("/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07.dblock.zip", {st_mode=S_IFREG|0644, st_size=715, ...}) = 0
[pid 13337] utimes("/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07.dblock.zip", [{tv_sec=1619388069, tv_usec=663469} /* 2021-04-25T18:01:09.663469-0400 */, {tv_sec=1619387161, tv_usec=259482} /* 2021-04-25T17:46:01.259482-0400 */]) = 0
 done!
3/3: duplicati-i63ff2dde06cd431683cf1b3eedd0a4c2.dindex.zip - downloading (608 bytes)... recompressing ...[pid 13337] stat("/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07dblockzip", 0x7ffe4269c110) = -1 ENOENT (No such file or directory)
[pid 13337] lstat("/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07dblockzip", 0x7ffe4269c130) = -1 ENOENT (No such file or directory)
[pid 13337] stat("/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07dblockzip", 0x7ffe4269c330) = -1 ENOENT (No such file or directory)
[pid 13337] lstat("/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07dblockzip", 0x7ffe4269c330) = -1 ENOENT (No such file or directory)
[pid 13337] openat(AT_FDCWD, "/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07dblockzip", O_RDWR) = -1 ENOENT (No such file or directory)
 error: System.IO.FileNotFoundException: Could not find file "/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07dblockzip"
File name: '/tmp/reencrypt/duplicati-b9f9d23e774d64eba87a3e2420695ff07dblockzip'
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <d13c8b563008422a8c5aaec0a74089cc>:0 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) [0x00000] in <d13c8b563008422a8c5aaec0a74089cc>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
  at System.IO.FileInfo.Open (System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) [0x00006] in <d13c8b563008422a8c5aaec0a74089cc>:0 
  at System.IO.FileInfo.Open (System.IO.FileMode mode) [0x00000] in <d13c8b563008422a8c5aaec0a74089cc>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileInfo.Open(System.IO.FileMode)
  at Duplicati.CommandLine.RecoveryTool.Recompress.Run (System.Collections.Generic.List`1[T] args, System.Collections.Generic.Dictionary`2[TKey,TValue] options, Duplicati.Library.Utility.IFilter filter) [0x00747] in <e9be12affb6f47979004129a9a3a1473>:0 
Download complete, of 3 remote files, 3 were downloaded with 1 errors
There were errors during recompress of remote backend files!
[pid 13341] --- SIGRT_5 {si_signo=SIGRT_5, si_code=SI_TKILL, si_pid=13337, si_uid=1000} ---
[pid 13341] --- SIGRT_4 {si_signo=SIGRT_4, si_code=SI_TKILL, si_pid=13337, si_uid=1000} ---
[pid 13341] +++ exited with 0 +++
[pid 13338] +++ exited with 0 +++
[pid 13339] +++ exited with 0 +++
[pid 13337] +++ exited with 200 +++
[pid 13333] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=13337, si_uid=1000, si_status=200, si_utime=109, si_stime=7} ---
[pid 13334] +++ exited with 0 +++
[pid 13335] +++ exited with 0 +++
+++ exited with 200 +++
```

If you think it's weird to recompress zip to zip, here's Windows trying to make a 7z, with the same missing dots failing file access:

```
C:\ProgramData\Duplicati\duplicati-2.0.5.1_beta_2020-01-18>Duplicati.CommandLine.RecoveryTool.exe recompress 7z "C:\ProgramData\Duplicati\duplicati-2.0.5.114_canary_2021-03-10\RUN\reencrypt" "C:\tmp\reencrypt"
Listing files on backend: file ...
Found 3 files at remote storage
Found 3 files which belongs to backup with prefix duplicati
1/3: duplicati-20210425T210421Z.dlist.zip - downloading (643 bytes)... recompressing ... done!
2/3: duplicati-b39e21741c0914567874f73b2067eb332.dblock.zip - downloading (680 bytes)... recompressing ... done!
3/3: duplicati-i643599cd649a45598a36fe0d346e2fa6.dindex.zip - downloading (608 bytes)... recompressing ... error: System.IO.FileNotFoundException: Could not find file 'C:\tmp\reencrypt\duplicati-b39e21741c0914567874f73b2067eb332dblock7z'.
File name: 'C:\tmp\reencrypt\duplicati-b39e21741c0914567874f73b2067eb332dblock7z'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.FileInfo.Open(FileMode mode)
   at Duplicati.CommandLine.RecoveryTool.Recompress.Run(List`1 args, Dictionary`2 options, IFilter filter)
Download complete, of 3 remote files, 3 were downloaded with 1 errors
There were errors during recompress of remote backend files!
```

**Comment by drwtsn32x** [comment]
Maybe this is the problem:

https://github.com/duplicati/duplicati/blob/master/Duplicati/CommandLine/RecoveryTool/Recompress.cs#L199-L200

If you aren't re-encrypting, and the current files do not have encryption, this Replace will end up removing all the dots in the filename.

**Comment by ts678** [comment]
Good observation! I guess the idea is if it doesn't know encryption extension to append to dot to strip, it strips dots alone.
Starting with .zip files and using --reencrypt left me with files ending in .zip and .7z depending on which result I requested.
Starting with .zip.aes files and using --reencrypt and --passphrase=\<passphrase> left .zip.aes and .7z.aes files as it should,
but going back to my original Windows test on Linux and adding --reupload failed with a different FileNotFoundException:

```
$ mono Duplicati.CommandLine.RecoveryTool.exe recompress 7z /home/me/DuplicatiBackups/reencrypt /tmp/reencrypt --reupload --reencrypt --passphrase=password
Listing files on backend: file ...
Found 3 files at remote storage
Found 3 files which belongs to backup with prefix duplicati
1/3: duplicati-20210426T160932Z.dlist.zip.aes - downloading (941 bytes)... decrypting ... recompressing ... reencrypting ... reuploading ... done!
2/3: duplicati-ba3c7621dd311452f9e360bb57f09c6f8.dblock.zip.aes - downloading (1021 bytes)... decrypting ... recompressing ... reencrypting ... reuploading ... done!
3/3: duplicati-ia987710f89034eefba6eb77d0ec820ed.dindex.zip.aes - downloading (925 bytes)... decrypting ... recompressing ... error: System.IO.FileNotFoundException: Could not find file "/tmp/reencrypt/duplicati-ba3c7621dd311452f9e360bb57f09c6f8.dblock.7z.aes"
File name: '/tmp/reencrypt/duplicati-ba3c7621dd311452f9e360bb57f09c6f8.dblock.7z.aes'
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <d13c8b563008422a8c5aaec0a74089cc>:0 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) [0x00000] in <d13c8b563008422a8c5aaec0a74089cc>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
  at System.IO.FileInfo.Open (System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) [0x00006] in <d13c8b563008422a8c5aaec0a74089cc>:0 
  at System.IO.FileInfo.Open (System.IO.FileMode mode) [0x00000] in <d13c8b563008422a8c5aaec0a74089cc>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileInfo.Open(System.IO.FileMode)
  at Duplicati.CommandLine.RecoveryTool.Recompress.Run (System.Collections.Generic.List`1[T] args, System.Collections.Generic.Dictionary`2[TKey,TValue] options, Duplicati.Library.Utility.IFilter filter) [0x00747] in <e9be12affb6f47979004129a9a3a1473>:0 
Download complete, of 3 remote files, 3 were downloaded with 1 errors
There were errors during recompress of remote backend files!
```

On Windows, I was watching with Process Monitor, and seeing it delete the file then try to open it. I see the same on Linux:

```
$ strace -f -y -P /tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes -P /home/me/DuplicatiBackups/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes mono Duplicati.CommandLine.RecoveryTool.exe recompress 7z /home/me/DuplicatiBackups/reencrypt /tmp/reencrypt --reupload --reencrypt --passphrase=password
...
[pid 19605] openat(AT_FDCWD, "/tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes", O_RDWR|O_CREAT|O_TRUNC, 0666) = 5</tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes>
[pid 19605] fstat(5</tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes>,  <unfinished ...>
[pid 19615] +++ exited with 0 +++
[pid 19605] <... fstat resumed> {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
[pid 19605] lseek(5</tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes>, 0, SEEK_SET) = 0
[pid 19605] write(5</tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes>, "AES\2\0\0!CREATED_BY\0SharpAESCrypt "..., 1068) = 1068
[pid 19605] lseek(5</tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes>, 1068, SEEK_SET) = 1068
[pid 19605] write(5</tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes>, "\5\t\267\256\301,\212\351\362\232C@'\340\215\347\n2\312x\246\335\374Z$\226pK\353\340\203\212"..., 33) = 33
[pid 19605] close(5</tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes>) = 0
[pid 19605] lstat("/tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes", {st_mode=S_IFREG|0644, st_size=1101, ...}) = 0
[pid 19605] utimes("/tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes", [{tv_sec=1619457372, tv_usec=800668} /* 2021-04-26T13:16:12.800668-0400 */, {tv_sec=1619454304, tv_usec=388712} /* 2021-04-26T12:25:04.388712-0400 */]) = 0
 reuploading ...[pid 19605] stat("/home/me/DuplicatiBackups/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes", 0x7fff06cca7a0) = -1 ENOENT (No such file or directory)
[pid 19605] lstat("/home/me/DuplicatiBackups/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes", 0x7fff06cca7c0) = -1 ENOENT (No such file or directory)
[pid 19605] stat("/tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes", {st_mode=S_IFREG|0644, st_size=1101, ...}) = 0
[pid 19605] stat("/tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes", {st_mode=S_IFREG|0644, st_size=1101, ...}) = 0
[pid 19605] stat("/tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes", {st_mode=S_IFREG|0644, st_size=1101, ...}) = 0
[pid 19605] lstat("/tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes", {st_mode=S_IFREG|0644, st_size=1101, ...}) = 0
[pid 19605] openat(AT_FDCWD, "/tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes", O_RDONLY) = 4</tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes>
[pid 19605] fstat(4</tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes>, {st_mode=S_IFREG|0644, st_size=1101, ...}) = 0
[pid 19605] fstat(4</tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes>, {st_mode=S_IFREG|0644, st_size=1101, ...}) = 0
[pid 19605] stat("/home/me/DuplicatiBackups/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes", 0x7fff06cca5e0) = -1 ENOENT (No such file or directory)
[pid 19605] lstat("/home/me/DuplicatiBackups/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes", 0x7fff06cca600) = -1 ENOENT (No such file or directory)
[pid 19605] stat("/home/me/DuplicatiBackups/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes", 0x7fff06cca800) = -1 ENOENT (No such file or directory)
[pid 19605] lstat("/home/me/DuplicatiBackups/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes", 0x7fff06cca800) = -1 ENOENT (No such file or directory)
[pid 19605] openat(AT_FDCWD, "/home/me/DuplicatiBackups/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes", O_RDWR|O_CREAT|O_TRUNC, 0666) = 5</home/me/DuplicatiBackups/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes>
[pid 19605] fstat(5</home/me/DuplicatiBackups/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes>, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
[pid 19605] fstat(4</tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes>, {st_mode=S_IFREG|0644, st_size=1101, ...}) = 0
[pid 19605] fchmod(5</home/me/DuplicatiBackups/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes>, 0644) = 0
[pid 19605] sendfile(5</home/me/DuplicatiBackups/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes>, 4</tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes>, NULL, 1101) = 1101
[pid 19605] utimensat(5</home/me/DuplicatiBackups/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes>, NULL, [{tv_sec=1619457372, tv_nsec=800668000} /* 2021-04-26T13:16:12.800668000-0400 */, {tv_sec=1619454304, tv_nsec=388712000} /* 2021-04-26T12:25:04.388712000-0400 */], 0) = 0
[pid 19605] close(5</home/me/DuplicatiBackups/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes>) = 0
[pid 19605] close(4</tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes>) = 0
[pid 19605] unlink("/tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes") = 0
 done!
3/3: duplicati-ieab39926dc694c21b0a1b75e7f758954.dindex.zip.aes - downloading (925 bytes)... decrypting ...[pid 19609] --- SIGRT_3 {si_signo=SIGRT_3, si_code=SI_TKILL, si_pid=19605, si_uid=1000} ---
[pid 19609] --- SIGRT_4 {si_signo=SIGRT_4, si_code=SI_TKILL, si_pid=19605, si_uid=1000} ---
 recompressing ...strace: Process 19620 attached
strace: Process 19621 attached
strace: Process 19622 attached
[pid 19605] stat("/tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes", 0x7fff06cca6e0) = -1 ENOENT (No such file or directory)
[pid 19605] lstat("/tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes", 0x7fff06cca700) = -1 ENOENT (No such file or directory)
[pid 19605] stat("/tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes", 0x7fff06cca900) = -1 ENOENT (No such file or directory)
[pid 19605] lstat("/tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes", 0x7fff06cca900) = -1 ENOENT (No such file or directory)
[pid 19605] openat(AT_FDCWD, "/tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes", O_RDWR) = -1 ENOENT (No such file or directory)
[pid 19621] +++ exited with 0 +++
[pid 19622] +++ exited with 0 +++
strace: Process 19623 attached
strace: Process 19624 attached
[pid 19623] +++ exited with 0 +++
[pid 19624] +++ exited with 0 +++
 error: System.IO.FileNotFoundException: Could not find file "/tmp/reencrypt/duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes"
```

In above, the unlink is a file delete, the sendfile is a copy (args start with destination, source), so it looks like it made the file in the tmp area, copied data to original location, deleted tmp copy, then got surprised that tmp copy wasn't there any more, and raised an error.

What it seems to have left me (looking at compression and at `ls -lc` info, is these in the expected upload area:
duplicati-20210426T162504Z.dlist.7z.aes
duplicati-b1aaef1082adc43c6949af96854a28f6d.dblock.7z.aes
and this in the temporary area:
duplicati-ieab39926dc694c21b0a1b75e7f758954.dindex.7z

**Comment by drwtsn32x** [comment]
Ok, I see the problem.  The files are processed in this order:  dlist, dblock, and then finally dindex.  When you use reupload, the tool is deleting the file immediately after upload is complete. The problem is that when a dindex file is processed, it tries to read the associated dblock to compute the new hash.  But it can't because the dblock was deleted earlier.

One solution is to just not delete the files after reupload.

**Comment by drwtsn32x** [comment]
There is still a deeper issue with this tool.  After recompressing, reencrypting, and reuploading, a database recreation failed.  It failed to process the index file.

**Comment by drwtsn32x** [comment]
Another issue - reupload is dangerous when the new filenames are the same (eg, recompressing zip to zip).  After it does the reupload, it deletes the "old" backend file - which is of course the file it just reuploaded!  End result is you lose all the files in your backend.

**Comment by warwickmm** [comment]
For anyone trying to debug the recompress issue, [here's](https://github.com/warwickmm/duplicati/commit/751fb578afc2653be1e0b848b21245fc4d4837d1) a simple unit test that may help. It fails when `noEncryption` is `true`, and passes when it's `false`.
