### ISSUE TITLE
Command Line Build Errors on Windows/Visual Studio Community 2019

### ISSUE THREAD

**Issue by SeanMengis** [duplicati/duplicati#4573]
- [X ] I have searched open and closed issues for duplicates.
- [X ] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info
- **Duplicati version**: Forked the most recent master branch (with the visual studio community functionality)
- **Operating system**: Windows 10
- **Backend**: Local & SMB

## Description
I'm trying to set up Visual Studio Community 2019 to work on a command line feature to get current backup progress percentage in one command (and maybe a couple of other stats).  Which later could be contributed to the project if it is deemed useful.
I managed to implement a simple function that prints "Hello World" but I am running into warnings and errors when trying to execute the "backup" command.

## Steps to reproduce
**My default run configuration:** Debug, (Any CPU, x64 or x86),  Duplicati.CommandLine

**Command line arguments 1:** backup `"E:\Arbeit\Share" "E:\Arbeit\BackupTestBigISOFiles\TestFiles"` + Passphrase prompt
**Command line arguments 2:**  backup `"E:\Arbeit\Share" "E:\Arbeit\BackupTestBigISOFiles\TestFiles"  --backup-name="TestBackup" --passphrase="123" --encryption-module="aes" --compression-module="zip" --dbpath="C:\Users\Sean\AppData\Local\Duplicati\MVOCQHCVDE.sqlite"`

I tried different combinations but it didn't change much.

**Resulting errors:** I have two different situations where I get two different errors but I don't know exactly why and when one or the other comes up. Both have a common part:

Common part: 
```
Backup started at 02/07/2021 10:52:00
Failed to load process type Duplicati.Library.Backend.MicrosoftGroup assembly E:\Arbeit\duplicati\Duplicati\CommandLine\bin\Debug\Duplicati.Library.Backend.OneDrive.dll, error message: Exception has been thrown by the target of an invocation. => Exception has been thrown by the target of an invocation.
Failed to load process type Duplicati.Library.Backend.OneDriveV2 assembly E:\Arbeit\duplicati\Duplicati\CommandLine\bin\Debug\Duplicati.Library.Backend.OneDrive.dll, error message: Exception has been thrown by the target of an invocation. => Exception has been thrown by the target of an invocation.
Failed to load process type Duplicati.Library.Backend.SharePointV2 assembly E:\Arbeit\duplicati\Duplicati\CommandLine\bin\Debug\Duplicati.Library.Backend.OneDrive.dll, error message: Exception has been thrown by the target of an invocation. => Exception has been thrown by the target of an invocation.
Failed to load connection. => The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
```
I've checked to see if the specified One Drive dll's are present. (Yes they are)

Error 1: 
```
System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at Duplicati.Library.SQLiteHelper.SQLiteLoader.get_SQLiteConnectionType() in E:\Arbeit\duplicati\Duplicati\Library\SQLiteHelper\SQLiteLoader.cs:line 229
   at Duplicati.Library.SQLiteHelper.SQLiteLoader.LoadConnection() in E:\Arbeit\duplicati\Duplicati\Library\SQLiteHelper\SQLiteLoader.cs:line 116
   at Duplicati.Library.SQLiteHelper.SQLiteLoader.LoadConnection(String targetpath) in E:\Arbeit\duplicati\Duplicati\Library\SQLiteHelper\SQLiteLoader.cs:line 132
   at Duplicati.Library.Main.Database.LocalDatabase.CreateConnection(String path) in E:\Arbeit\duplicati\Duplicati\Library\Main\Database\LocalDatabase.cs:line 57
   at Duplicati.Library.Main.Database.LocalDatabase..ctor(String path, String operation, Boolean shouldclose) in E:\Arbeit\duplicati\Duplicati\Library\Main\Database\LocalDatabase.cs:line 70
   at Duplicati.Library.Main.Database.LocalBackupDatabase..ctor(String path, Options options) in E:\Arbeit\duplicati\Duplicati\Library\Main\Database\LocalBackupDatabase.cs:line 48
   at Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__20.MoveNext() in E:\Arbeit\duplicati\Duplicati\Library\Main\Operation\BackupHandler.cs:line 402
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CoCoL.ChannelExtensions.WaitForTaskOrThrow(Task task)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter, CancellationToken token) in E:\Arbeit\duplicati\Duplicati\Library\Main\Operation\BackupHandler.cs:line 349
   at Duplicati.Library.Main.Controller.<>c__DisplayClass14_0.<Backup>b__0(BackupResults result) in E:\Arbeit\duplicati\Duplicati\Library\Main\Controller.cs:line 128
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method) in E:\Arbeit\duplicati\Duplicati\Library\Main\Controller.cs:line 468
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter) in E:\Arbeit\duplicati\Duplicati\Library\Main\Controller.cs:line 124
   at Duplicati.CommandLine.Commands.Backup(TextWriter outwriter, Action`1 setup, List`1 args, Dictionary`2 options, IFilter filter) in E:\Arbeit\duplicati\Duplicati\CommandLine\Commands.cs:line 656
   at Duplicati.CommandLine.Program.ParseCommandLine(TextWriter outwriter, Action`1 setup, Boolean& verboseErrors, String[] args) in E:\Arbeit\duplicati\Duplicati\CommandLine\Program.cs:line 217
   at Duplicati.CommandLine.Program.RunCommandLine(TextWriter outwriter, TextWriter errwriter, Action`1 setup, String[] args) in E:\Arbeit\duplicati\Duplicati\CommandLine\Program.cs:line 238
Press any key to continue . . .
```

Error 2: 
```
Backup started at 02/07/2021 10:57:09
Failed to load process type Duplicati.Library.Backend.MicrosoftGroup assembly E:\Arbeit\duplicati\Duplicati\CommandLine\bin\x64\Debug\Duplicati.Library.Backend.OneDrive.dll, error message: Exception has been thrown by the target of an invocation. => Exception has been thrown by the target of an invocation.
Failed to load process type Duplicati.Library.Backend.OneDriveV2 assembly E:\Arbeit\duplicati\Duplicati\CommandLine\bin\x64\Debug\Duplicati.Library.Backend.OneDrive.dll, error message: Exception has been thrown by the target of an invocation. => Exception has been thrown by the target of an invocation.
Failed to load process type Duplicati.Library.Backend.SharePointV2 assembly E:\Arbeit\duplicati\Duplicati\CommandLine\bin\x64\Debug\Duplicati.Library.Backend.OneDrive.dll, error message: Exception has been thrown by the target of an invocation. => Exception has been thrown by the target of an invocation.
Fatal error => Encryption method not supported: aes

ErrorID: EncryptionMethodNotSupported
Encryption method not supported: aes
Press any key to continue . . .
```

I also get some warnings that Tardigrade/TencentCOS could not be found. I double checked to see if the folders and dlls are missing by any chance. But they are present.

Thank you in advance for any help :) 

## Screenshots
![image](https://user-images.githubusercontent.com/70524315/124249930-a2b4de00-db24-11eb-8163-e810848c52cb.png)
![image](https://user-images.githubusercontent.com/70524315/124249828-8ca71d80-db24-11eb-9359-693f003463f4.png)
![image](https://user-images.githubusercontent.com/70524315/124250399-279ff780-db25-11eb-8ac3-062ff6bc75ae.png)

**Comment by warwickmm** [comment]
Did you run nuget restore?  Are you building the entire solution?

**Comment by SeanMengis** [comment]
Hi warwickmm :)

Sorry for not getting back to you sooner. I moved to a new place this weekend.

- I managed to fix the warnings. The missing projects were actually present but not added to the solution.
- I tried to run nuget restore but I get: "All packages are already installed and there is nothing to restore."
- I am building the "Duplicati CommandLine Only.sln". Although I get the same error when trying to run the command line from "Duplicati.sln".
- Just to see if it works I also started the regular application (TrayIcon). It does build and start but the browser tells me: "Resource not found: http://localhost:8200/index.html". I havn't put any time into this since I don't need the graphical interface but am happy to do so if you need me to.

**Comment by warwickmm** [comment]
Thanks @SeanMengis.  `Duplicati CommandLine Only.sln` has been a bit neglected, but `Duplicati.sln` should build and run without any issues.  Are you still encountering errors?

**Comment by SeanMengis** [comment]
Thanks @warwickmm. Sadly the error happens with Duplicati.sln and the command line only solution. The version I'm working with should be a clean master version. Tomorrow I'll try once more with a new one just to be sure.

**Comment by SeanMengis** [comment]
Thanks for the wait @warwickmm. So I built the solution again and still encounter the same problem. Here are the exact steps I did: 

1) git clone https://github.com/duplicati/duplicati.git
2) open Duplicati.sln in VS Community 2019
3) set Duplicati.CommandLine as Startup Project
4) start with default configuration: Debug, Any CPU, Duplicati CommandLine
--> Build starts
--> Help page is shown
5) I have a couple of Warnings: most are mismatches between configured processor architectures, which I believe are not a problem (read that in another issue). The reference Mono.Security could not be found.
6) I take the default backup command from the docs and adjust it:
--> backup "E:\Arbeit\BackupTestFiles\BackupFolder" "E:\Arbeit\BackupTestFiles\TestFiles" --backup-name="TestBackup" --dbpath="C:\Users\Sean\AppData\Local\Duplicati\MVOCQHCVDE.sqlite" --encryption-module="aes" --compression-module="zip" --dblock-size="50mb" --keep-time="3M" --passphrase="123" --skip-files-larger-than="2GB" --default-filters="Windows" --exclude-files-attributes="temporary" --disable-module="console-password-input" --exclude="desktop.ini"
7) I get the FileNotFoundException as mentionned in the first post.

![image](https://user-images.githubusercontent.com/70524315/124552766-3db6fc00-de34-11eb-9e3f-1e6ecea86e34.png)

**Comment by warwickmm** [comment]
Can you try using `Duplicati.CommandLine.exe` from the TrayIcon project?  There are a many dependencies that are dynamically loaded and the TrayIcon project is the main entry point.

**Comment by SeanMengis** [comment]
Directly using the `Duplicati.CommandLine.exe` that is built in `E:\duplicati\Duplicati\GUI\Duplicati.GUI.TrayIcon\bin\` worked! :) Also managed to test it with a dummy function which worked as well. Thanks a lot for the help @warwickmm!
