### ISSUE TITLE
"The version(s) being updated to, already exists" on page reload of Direct restore from backup files

### ISSUE THREAD

**Issue by ts678** [duplicati/duplicati#4604]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.114 Canary
- **Operating system**: Windows 10 Version 21H1
- **Backend**: Local folder

## Description

"The version(s) being updated to, already exists" red popup error and Windows notification raised after reopening browser did its reload of tabs that were open at prior browser close. Seemingly a tab from middle of a direct restore set things off when restored.
Further testing was done in Edge and Firefox, including using the browser refresh button, and copying/pasting URL into browser.

## Steps to reproduce

1. Backup a short file to a folder
2. Direct restore from the folder
3. After `Connect` and progress to screen 3 `Select files`, refresh tab.

- **Actual result**:
"The version(s) being updated to, already exists" error box pops up on screen, and I get same error in Windows notification list.
- **Expected result**:
Screen 3, without any errors.

There are a number of similar symptom reports filed, though cause was generally unknown. I open this as a simple path to get error although there are probably other ways. Some others might become more obvious after a developer traces how this problem arises.

[The version(s) being updated to, already exists #3587](https://github.com/duplicati/duplicati/issues/3587)
[Corrupted data after restoring a newly created backup #2275](https://github.com/duplicati/duplicati/issues/2275)
[The version(s) being updated to, already exists](https://forum.duplicati.com/t/the-version-s-being-updated-to-already-exists/6192)
[Unable to restore my data from one drive backup](https://forum.duplicati.com/t/unable-to-restore-my-data-from-one-drive-backup/10281)
[Regenerating database freezes at ~75%](https://forum.duplicati.com/t/regenerating-database-freezes-at-75/5588)
[Restore restores folder structure but no files](https://forum.duplicati.com/t/restore-restores-folder-structure-but-no-files/9994)

https://github.com/duplicati/duplicati/blob/017911eb3debc39ab6026370b8fcfafc67ef6937/Duplicati/Library/Main/Operation/RecreateDatabaseHandler.cs#L51-L76

One can find temporary database in the temp folder. Look for a `dup-*` file with right timestamp. Try opening it with sqlitebrowser.

![image](https://user-images.githubusercontent.com/40771998/133259385-ee0b666d-dabf-45d4-b8d1-8c1f60a4d583.png)

An example URL for screen 3 is below. Somehow this seems mapped persistently to same database as long as Duplicati server is up:

> http://127.0.0.1:8200/ngax/index.html#/restore/8f583eaa-80d5-4a5d-982d-dd53845acb68

One can see network activity with F12 web developer tools, however I also caught an example with Wireshark. The trigger might be:

> POST /api/v1/backup/178a8fef-8b37-4661-a2b1-f4e7fd3bf5eb/repairupdate HTTP/1.1

An example error in About --> Show log --> Stored:

> Sep 14, 2021 7:11 AM: Failed while executing "RepairUpdate" with id: 178a8fef-8b37-4661-a2b1-f4e7fd3bf5eb
Duplicati.Library.Interface.UserInformationException: The version(s) being updated to, already exists
   at Duplicati.Library.Main.Operation.RecreateDatabaseHandler.RunUpdate(IFilter filter, NumberedFilterFilelistDelegate filelistfilter, BlockVolumePostProcessor blockprocessor)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass26_0.<UpdateDatabaseWithVersions>b__0(RecreateDatabaseResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.UpdateDatabaseWithVersions(IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

**Comment by Jojo-1000** [comment]
The issue is that before displaying the files, the restore page runs a `repairupdate` operation on temporary databases.
This is supposed to update paths in the database only for the specified version, so that if only version 0 is looked at (in the version selection), the other versions don't have to be added to the temporary database. Once version 1 is selected, the existing database containing version 0 is extended with paths for version 1. But, this throws that error if the version is already in the database.

I am pretty sure this can just be ignored, because it makes no changes to the database. Another way would be to implement a check whether a version is already in the database and then skip the update.
