### ISSUE TITLE
Cannot found the destination path. The folder \\xxxxxx\xxxxxx does not exist

### ISSUE THREAD

**Issue by Athep** [duplicati/duplicati#4621]
Duplicati is running on a Windows 10 machine. Another Windows 10 machine is the destination in the same network.

After a Windows update (i think) the destination path is suddenly no longer found. 

I can browse the path in windows file explorer without any issues.

I upgraded from the latest beta to 2.0.6.100_canary_2021-08-11. It did not help.

I copied the path from windows explorer into the settings, but it is just not working. "Test Connection" gives the same error. 

Duplicati.Library.Interface.FolderMissingException: The folder \\xxxxxx\xxxxxx does not exist
   at Duplicati.Library.Main.BackendManager.List()
   at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, IEnumerable 1 protectedFiles)
   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, IEnumerable 1 protectedFiles)
   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CoCoL.ChannelExtensions.WaitForTaskOrThrow(Task task)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass14_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action 1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

**Comment by ts678** [comment]
Forum topic [Cannot found the destination path. The folder \\xxxxxx\xxxxxx does not exist](https://forum.duplicati.com/t/cannot-found-the-destination-path-the-folder-xxxxxx-xxxxxx-does-not-exist/13204)
