### ISSUE TITLE
I can't delete the backup job

### ISSUE THREAD

**Issue by FeiLZX3Km** [duplicati/duplicati#5187]
Please help me troubleshoot the problem so that I can delete the backup job.
![Animation2](https://github.com/duplicati/duplicati/assets/21981195/0e957829-411e-42fd-a2af-73db3fd9f225)

Duplicati.Library.Interface.FolderMissingException: 文件夹 /dav/H/VideoBackupfiles/ 未找到，信息：The remote server returned an error: (404) Not Found. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at Duplicati.Library.Utility.AsyncHttpRequest.AsyncWrapper.GetResponseOrStream()
   at Duplicati.Library.Utility.AsyncHttpRequest.GetResponse()
   at Duplicati.Library.Backend.WEBDAV.ListWithouExceptionCatch()
   at Duplicati.Library.Backend.WEBDAV.List()
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.BackendManager.List()
   at Duplicati.Library.Main.Controller.<DeleteAllRemoteFiles>b__24_0(ListRemoteResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.DeleteAllRemoteFiles()
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

**Comment by FeiLZX3Km** [comment]
I had solved this problem by relogging.
