### ISSUE TITLE
Missing null check in WindowsSnapshot.Dispose

### ISSUE THREAD

**Issue by Jojo-1000** [duplicati/duplicati#5190]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 4.0.8.
- **Operating system**: Windows
- **Backend**: -

## Description
`WindowsSnapshot.Dispose()` calls Dispose on a variable that is null if the constructor failed.

## Steps to reproduce

1. Set snapshot policy to required
2. Run backup without admin permissions

- **Actual result**:
Backup fails as expected, but verbose log shows cleanup error:
```
2024-05-14 18:29:20 +02 - [Verbose-Duplicati.Library.Snapshots.WindowsSnapshot-VSSCleanupOnError]: Failed during VSS error cleanup
System.NullReferenceException: Object reference not set to an instance of an object.
   at Duplicati.Library.Snapshots.WindowsSnapshot.Dispose(Boolean disposing) in Duplicati\Library\Snapshots\WindowsSnapshot.cs:line 324
   at Duplicati.Library.Snapshots.SnapshotBase.Dispose() in Duplicati\Library\Snapshots\SnapshotBase.cs:line 197
   at Duplicati.Library.Snapshots.WindowsSnapshot..ctor(IEnumerable`1 sources, IDictionary`2 options) in Duplicati\Library\Snapshots\WindowsSnapshot.cs:line 94
```

- **Expected result**:
The cleanup should succeed, because nothing needs to be done.

**Comment by kenkendk** [comment]
Good find, it will be nice when #5166 is implemented
