### ISSUE TITLE
Genarating of captcha image fails on Debian due to lack of Arial font family

### ISSUE THREAD

**Issue by luixxiul** [duplicati/duplicati#5363]
- [x] I have searched open and closed issues for duplicates.
- [ ] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: Debug
- **Operating system**: Debian
- **Backend**: irrelevant

## Description

Deleting a backup task with deleting remote files too does not proceed as a Captcha image is not generated due to the issue related to the lack of a proper font. Here is the log on the console:

````
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      SixLabors.Fonts.FontFamilyNotFoundException: The "Arial" font family could not be found in the following directories:
       * /usr/local/share/fonts/
       * /usr/share/fonts/
         at SixLabors.Fonts.FontCollection.GetImpl(String name, CultureInfo culture)
         at SixLabors.Fonts.FontCollection.Get(String name, CultureInfo culture)
         at SixLabors.Fonts.SystemFontCollection.Get(String name, CultureInfo culture)
         at SixLabors.Fonts.SystemFontCollection.Get(String name)
         at SixLabors.Fonts.SystemFonts.CreateFont(String name, Single size)
         at Duplicati.WebserverCore.Services.CaptchaService.CaptchaUtil.ApproxTextWidth(String text, String fontFamily, Single fontSize) in /home/user/Duplicati/WebserverCore/Services/CaptchaService.cs:line 109
         at Duplicati.WebserverCore.Services.CaptchaService.CaptchaUtil.CreateCaptcha(String answer, Size size, Single fontsize) in /home/user/Duplicati/WebserverCore/Services/CaptchaService.cs:line 142
         at Duplicati.WebserverCore.Services.CaptchaService.GetCaptchaImage(String token) in /home/user/Duplicati/WebserverCore/Services/CaptchaService.cs:line 75
         at Duplicati.WebserverCore.Endpoints.V1.Captcha.<>c.<Map>b__0_0(ICaptchaProvider captchaProvider, IHttpContextAccessor httpContextAccessor, String token, CancellationToken ct) in /home/user/Duplicati/WebserverCore/Endpoints/V1/Captcha.cs:line 12
         at lambda_method215(Closure, EndpointFilterInvocationContext)
         at Duplicati.WebserverCore.Middlewares.LanguageFilter.InvokeAsync(EndpointFilterInvocationContext context, EndpointFilterDelegate next) in /home/user/Duplicati/WebserverCore/Middlewares/LanguageFilter.cs:line 14
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<ExecuteValueTaskOfObject>g__ExecuteAwaited|129_0(ValueTask`1 valueTask, HttpContext httpContext, JsonTypeInfo`1 jsonTypeInfo)
         at Duplicati.WebserverCore.Middlewares.WebsocketExtensions.<>c__DisplayClass0_0.<<UseNotifications>b__0>d.MoveNext() in /home/user/Duplicati/WebserverCore/Middlewares/WebsocketExtensions.cs:line 21

````

## Steps to reproduce

1. Run the backup task on Debian
2. Proceed to remove the backup task and files

- **Actual result**: it was not proceeded because the Captcha image was not generated

- **Expected result**: the Captcha image should be generated.

## Screenshots

![1](https://github.com/user-attachments/assets/3efd0a64-2030-4c55-a7ff-eac00e030590)

**Comment by ts678** [comment]
Some related issues:

[Difficult to delete a backup job using screen reader #5098](https://github.com/duplicati/duplicati/issues/5098)

[Please Remove the Captcha Added in #1201 #4625](https://github.com/duplicati/duplicati/issues/4625)

**Comment by luixxiul** [comment]
The thing is that the captcha is generated on Ubuntu on one of my other computers, and I guess a font on Ubuntu is recognized as one which belongs to Arial family.

**Comment by luixxiul** [comment]
The only solution I could find for now for Debian is to install https://packages.debian.org/bookworm/ttf-mscorefonts-installer to have free version of Microsoft True Type Core Fonts be installed.

![1](https://github.com/user-attachments/assets/45917925-42ec-4cc3-9e7b-3d3d7572b614)

**Comment by RobHofmann** [comment]
This fixes it indeed!
