### ISSUE TITLE
Duplicati downgrade Windows service server database mismatch is hard to spot

### ISSUE THREAD

**Issue by ts678** [duplicati/duplicati#5723]
- [x] I have searched open and closed issues for duplicates.
- [ ] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.8.1 Beta
- **Operating system**: Windows 10
- **Backend**: N/A

## Description

Downgrade of Duplicati can cause failure to start, which is especially hard to see in a service.
This is presumably due to a server database downgrade causing an exit, with restart looping.

## Steps to reproduce

1. Install 2.1.0.2 Beta from .msi
1. WindowsService install
1. Downgrade by uninstall then install from 2.0.8.1 .msi
1. Start service

- **Actual result**:
Windows says service is Running. Task Manager shows Server starting repeatedly, presumably by WindowsService.
Application event log says "Attempting to restart server process: C:\Program Files\Duplicati 2\Duplicati.Server.exe"
There is no Duplicati.crash-log.txt
- **Expected result**:
I'd hope for something helpful, but I'm not sure what. Regardless, I suspect the issue has been around a long time.
Server database version not having changed in awhile may hide it, but recent version changes make it easier to hit.

One way to spot the problem, if one knows to try this:

```
C:\Program Files\Duplicati 2>Duplicati.Server.exe --server-datafolder=C:\Windows\System32\config\systemprofile\AppData\Local\Duplicati
A serious error occurred in Duplicati: System.Exception: Failed to create, open or upgrade the database.
Error message:
The database has version 8 but the largest supported version is 6.

This is likely caused by upgrading to a newer version and then downgrading.
If this is the case, there is likely a backup file of the previous database version in the folder C:\Users\REDACTED\AppData\Local\Duplicati.
   at Duplicati.Server.Program.GetDatabaseConnection(Dictionary`2 commandlineOptions)
   at Duplicati.Server.Program.RealMain(String[] _args)
```

and this leads into what to do about that, as there are a few paths, some of which lead into greater issues than this one.
Fortunately some downgrade guidance was released today, but I tested earlier, plus not everyone will see the guidance.

**Comment by kenkendk** [comment]
I think the solution here is to make the service detection a bit "smarter".
Instead of blindly restarting the server, it could apply some throttling to at least not keep spawning a crashing process.
We can also add a fatal exit code, so the service knows that it does not help to restart the application.

**Comment by kenkendk** [comment]
This was "fixed" a bit by having the service rely on Windows Service instead of having its own runner.
This means it will be visible if the service restarts frequently.
