### ISSUE TITLE
Duplicati downgrade can leave leftover database table that breaks new upgrade

### ISSUE THREAD

**Issue by ts678** [duplicati/duplicati#5724]
- [x] I have searched open and closed issues for duplicates.
- [ ] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.1.0.2 Beta
- **Operating system**: Windows 10
- **Backend**: N/A

## Description

Downgrading Duplicati by adjusting the version without deleting new table breaks upgrade, as CREATE fails.
An unfortunate additional pain is a series of backup server databases being created in the server datafolder.

## Steps to reproduce

1. Install 2.1.0.2 Beta from .msi
1. WindowsService uninstall (if service exists)
1. Downgrade by uninstall then install from 2.0.8.1 .msi
1. WindowsService install --unencrypted-database (saving some steps, as a later database edit needs that)
1. Start service, note it doesn't really come up, but just loop trying to restart the server. See separate issue.
1. Edit the Version in Version table down to the value the non-service server start complained of, such as 6.
1. Start service. All seems well, but there's a hidden problem because a newly added table was not deleted.
1. Stop service.
1. Upgrade by uninstall then install from 2.1.0.2 .msi
1. Start service

- **Actual result**:
Windows says service is Running. Task Manager shows Server starting repeatedly, presumably by WindowsService.
Application event log says "Attempting to restart server process: C:\Program Files\Duplicati 2\Duplicati.Server.exe"
There is no Duplicati.crash-log.txt
This is similar to the basic restart problem, but DB upgrade trying to go from 6 to 8 finds the existing TokenFamily.
New wrinkle is a backup copy of the server database every time the Server tries to restart. 1 per second in my case.

- **Expected result**:
It starts and stays with a proper database. In this case, a version 8 and leaving TokenFamily alone might be correct.
[CREATE TABLE](https://www.sqlite.org/lang_createtable.html) might benefit from `IF NOT EXISTS`.

The server datafolder being protected makes it hard to look at. One can move it if desired, or this seems to find issue::

> PS C:\Windows\System32\config\systemprofile\AppData\Local\Duplicati> Get-Item 'backup*' | sort CreationTime | Select-Object CreationTime,Name

Example, and I don't know why the two timestamps appear misaligned:

```
12/2/2024 5:29:10 PM   backup Duplicati-server 20241202052924.sqlite
12/2/2024 5:29:11 PM   backup Duplicati-server 20241202052925.sqlite
12/2/2024 5:29:12 PM   backup Duplicati-server 20241202052926.sqlite
12/2/2024 5:29:13 PM   backup Duplicati-server 20241202052927.sqlite
12/2/2024 5:29:14 PM   backup Duplicati-server 20241202052928.sqlite
12/2/2024 5:29:15 PM   backup Duplicati-server 20241202052929.sqlite
12/2/2024 5:29:16 PM   backup Duplicati-server 20241202052930.sqlite
12/2/2024 5:29:22 PM   backup Duplicati-server 20241202052931.sqlite
```

It took some work to figure out I needed to look at CreationTime, so if I got some steps wrong, just edit yourself a database with TokenFamily table and version 6 and try something like the below in Run as Administrator Command Prompt to see the suspect:

```
C:\Program Files\Duplicati 2>Duplicati.Server --server-datafolder=C:\Windows\System32\config\systemprofile\AppData\Local\Duplicati
A serious error occurred in Duplicati: System.Exception: Failed to create, open or upgrade the database.
Error message: Failed to execute SQL: /*
Token Family table
*/
CREATE TABLE "TokenFamily" (
    "ID" TEXT PRIMARY KEY,
    "UserId" TEXT NOT NULL,
    "Counter" INTEGER NOT NULL,
    "LastUpdated" INTEGER NOT NULL
)
Error: SQL logic error
table "TokenFamily" already exists
Database is NOT upgraded.
 ---> System.Exception: Failed to execute SQL: /*
Token Family table
*/
CREATE TABLE "TokenFamily" (
    "ID" TEXT PRIMARY KEY,
    "UserId" TEXT NOT NULL,
    "Counter" INTEGER NOT NULL,
    "LastUpdated" INTEGER NOT NULL
)
Error: SQL logic error
table "TokenFamily" already exists
Database is NOT upgraded.
 ---> code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
table "TokenFamily" already exists
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at Duplicati.Library.SQLiteHelper.DatabaseUpgrader.UpgradeDatabase(IDbConnection connection, String sourcefile, String schema, IList`1 versions)
   --- End of inner exception stack trace ---
   at Duplicati.Library.SQLiteHelper.DatabaseUpgrader.UpgradeDatabase(IDbConnection connection, String sourcefile, String schema, IList`1 versions)
   at Duplicati.Library.SQLiteHelper.DatabaseUpgrader.UpgradeDatabase(IDbConnection connection, String sourcefile, Type eltype)
   at Duplicati.Server.Program.GetDatabaseConnection(Dictionary`2 commandlineOptions, Boolean silentConsole)
   --- End of inner exception stack trace ---
   at Duplicati.Server.Program.GetDatabaseConnection(Dictionary`2 commandlineOptions, Boolean silentConsole)
   at Duplicati.Server.Program.Main(String[] _args)

C:\Program Files\Duplicati 2>
```

[Duplicati downgrade Windows service server database mismatch is hard to spot #5723](https://github.com/duplicati/duplicati/issues/5723) is a related issue on the service looping, except on 2.0.8.1 Beta getting upset by high DB version after code downgrade, whereas this one is on code upgrade having a low DB version trigger upgrade code which trips up on an existing table.

**Comment by kenkendk** [comment]
There is now a database tool in the distribution that can downgrade (and upgrade) databases.
