### ISSUE TITLE
vss fails to load the .dll on win2003

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#580]
_From [james.co...@gmail.com](https://code.google.com/u/105829900405594709437/) on March 04, 2012 04:26:56_

What steps will reproduce the problem? 1. install latest beta on win2003 server sp1
2. run Duplicati.Library.Snapshots.exe What is the expected output? What do you see instead? C:\Program Files\Duplicati>Duplicati.Library.Snapshots.exe
Creating file C:\Program Files\Duplicati\testfile.bin
Attempting to read locked file C:\Program Files\Duplicati\testfile.bin
The file C:\Program Files\Duplicati\testfile.bin was correctly locked, message:
The process cannot access the file 'C:\Program Files\Duplicati\testfile.bin' bec
ause it is being used by another process.
Creating snapshot for folder: C:\Program Files\Duplicati
If this fails, try to run as Administrator
The snapshot tester failed: System.IO.FileLoadException: Could not load file or
assembly 'AlphaVSS.Win2003.x86, Version=1.0.9156.0, Culture=neutral, PublicKeyTo
ken=3033cf2dbd31cad3' or one of its dependencies. This application has failed to
 start because the application configuration is incorrect. Reinstalling the appl
ication may fix this problem. (Exception from HRESULT: 0x800736B1)
File name: 'AlphaVSS.Win2003.x86, Version=1.0.9156.0, Culture=neutral, PublicKey
Token=3033cf2dbd31cad3' ---> System.Runtime.InteropServices.COMException (0x8007
36B1): This application has failed to start because the application configuratio
n is incorrect. Reinstalling the application may fix this problem. (Exception fr
om HRESULT: 0x800736B1)
   at System.Reflection.Assembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Di
ctionary`2 options)
   at Duplicati.Library.Snapshots.Program.Main(String[] _args)

* Test failed

C:\Program Files\Duplicati>

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=580_

**Comment by OMEN79** [comment]
Duplicati 2.0.0.81
Windows Server 2003 R2

Still have the same issue:

System.IO.FileNotFoundException: Could not load file or assembly 'AlphaVSS.52.x86.dll' or one of its dependencies. Не найден указанный модуль.
 File name: 'AlphaVSS.52.x86.dll'
 at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
 at System.Reflection.Assembly.LoadFile(String path)
 at Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Dictionary`2 options)
 at Duplicati.Library.Snapshots.SnapshotUtility.CreateSnapshot(String[] folders, Dictionary`2 options)
 at Duplicati.Library.Main.Operation.BackupHandler.GetSnapshot(String[] sources, Options options, ILogWriter log)
 at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
 at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
 at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, Action`1 method)
 at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
 at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

Any help is very appreciated.
