### ISSUE TITLE
backblaze b2 out of memory

### ISSUE THREAD

**Issue by wjansenw** [duplicati/duplicati#5810]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.1.0.2_beta_2024-11-29
- **Operating system**: DSM 7.x (synology)
- **Backend**: backblaze B2

## Description

Upload to backblaze b2 (sometimes) gives OutOfMemory exception

## Steps to reproduce

I have 2 duplicati instances running. One in docker container on an odroid. One in DSM7.x on synology.
The docker was always up-to-date, but since a few days noticed an issue when uploading to Backblaze B2 storage. It gives sometimes on OutOfMemory exception. Switched there to rclone backend, but that also gave errors, and I noticed that uploaded files were reported at 0 size. So my issue *could* be related to the backend itself as well.
However, the DSM7.x was running Duplicati fine on the last mono release. Noticed yesterday that there is an ARM7 version available, so installed that on DSM7.x, and ran a backup. It gave the same out of memory exception.

I will finetune some parameters on the DSM version (disable concurrency etc) and get more logs to hopefully be able to pinpoint the rootcause of the issue.

## Debug log
```
System.AggregateException: One or more errors occurred. (Exception of type 'System.OutOfMemoryException' was thrown. (Exception of type 'System.OutOfMemoryException' was thrown.) (One or more errors occurred. (Exception of type 'System.OutOfMemoryException' was thrown.)))
 ---> System.AggregateException: Exception of type 'System.OutOfMemoryException' was thrown. (Exception of type 'System.OutOfMemoryException' was thrown.) (One or more errors occurred. (Exception of type 'System.OutOfMemoryException' was thrown.))
 ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at CoCoL.AutomationExtensions.RunTask[T](T channels, Func`2 method, Boolean catchRetiredExceptions)
   at Duplicati.Library.Main.Operation.BackupHandler.FlushBackend(BackupResults result, IWriteChannel`1 uploadtarget, Task uploader)
   at Duplicati.Library.Main.Operation.BackupHandler.RunAsync(String[] sources, IFilter filter, CancellationToken token)
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.Operation.BackupHandler.RunAsync(String[] sources, IFilter filter, CancellationToken token)
 ---> (Inner Exception #1) System.AggregateException: One or more errors occurred. (Exception of type 'System.OutOfMemoryException' was thrown.)
 ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at CoCoL.AutomationExtensions.RunTask[T](T channels, Func`2 method, Boolean catchRetiredExceptions)
   at Duplicati.Library.Main.Operation.BackupHandler.FlushBackend(BackupResults result, IWriteChannel`1 uploadtarget, Task uploader)
   at Duplicati.Library.Main.Operation.BackupHandler.RunAsync(String[] sources, IFilter filter, CancellationToken token)
   --- End of inner exception stack trace ---<---

   --- End of inner exception stack trace ---
   at CoCoL.ChannelExtensions.WaitForTaskOrThrow(Task task)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter, CancellationToken token)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass17_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
```

**Comment by wjansenw** [comment]
- ran it again and storing all to the log files (profiling), but the same error without more context is generated
- tried the duplicati-backend-tool with a reasonably size file (~800 Mbyte):
```
./duplicati-backend-tool PUT "b2://duplicati-XXXX/?auth-username=00XXXXX&auth-password=K00YYYY
FWMEmxp8" /volume1/duplicati/myfile3.bin
Command failed: Exception of type 'System.OutOfMemoryException' was thrown.
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.MemoryStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Duplicati.Library.Utility.Utility.CopyStreamAsync(Stream source, Stream target, Boolean tryRewindSource, CancellationToken cancelToken, Byte[] buf)
   at Duplicati.Library.Utility.Utility.CopyStreamAsync(Stream source, Stream target, CancellationToken cancelToken)
   at Duplicati.Library.Backend.Backblaze.B2.<>c__DisplayClass28_0.<<PutAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Duplicati.Library.JSONWebHelper.GetJSONDataAsync[T](String url, CancellationToken cancelToken, Action`1 setup, Func`3 setupbodyreq)
   at Duplicati.Library.Backend.Backblaze.B2.PutAsync(String remotename, Stream stream, CancellationToken cancelToken)
   at Duplicati.Library.Backend.Backblaze.B2.PutAsync(String remotename, String filename, CancellationToken cancelToken)
   at Duplicati.Library.Utility.Utility.Await(Task task)
   at Duplicati.CommandLine.BackendTool.Program.Main(String[] _args)
```
- runnning it on a device with more RAM did not give an error
- it used to work OK on the low-RAM Synology device, but now gives memory errors.

**Comment by marceloduplicati** [comment]
I was able to replicate this by giving the docker specific memory limits and using the 800MB file.

For a 800 MB file, 2GB fails, 3GB+ works. (docker stats show 1.8GB memory usage)
For a 400 MB file, 1GB fails, 2GB+ works.  (docker stats show 900MB memory usage)

If you have RAM increase that on the docker.

```
   deploy:
      resources:
        limits:
          memory: **XXX**MB
```

If you don't have RAM experiment with a lower Remote volume size setting. What is the current setting you have configured for that?

I will further investigate the memory usage on B2 backend.

**Comment by wjansenw** [comment]
Tnx for the replication. 
On my Synology, I can't increase memory (it does not run on docker). But in the mono-release it was working within the limited amount of memory the box has.

On my docker install, I have deleted everything in the remote, and started from scratch with a reduced volume size. It is working OK with following settings:

```
--concurrency-max-threads=1
--synchronous-upload=true
--asynchronous-upload-limit=1
--dblock-size=50MB 
```

Removing the concurrency restrictions might be possible, but I'm OK with a slower but working backup.

On docker:

```
    deploy:
      resources:
        limits:
          memory: 512MB
          cpus: '1'
```

**Comment by kenkendk** [comment]
This is likely related to WebRequest being deprecated. From a quick trace, it looks like the code is copying from the stream into the WebRequest's RequestStream, which should map directly to the socket, but instead it looks like the WebRequest is buffering the request in memory.

This should be fixed once we get rid of the deprecated WebRequest's.

**Comment by marceloduplicati** [comment]
That is what seems to me as well. I am already working on B2 feature to [soft delete files](https://github.com/duplicati/duplicati/issues/5727), but did not intend to switch to HttpClient just yet.

If I can fix it without changing to HttpClient first I will send in the same PR as 5727, if not I will push the soft delete feature and since all backends will be refactored to replace WebRequest, B2's would be the first in line.

**Comment by marceloduplicati** [comment]
@wjansenw FYI the new [Canary Release](https://github.com/duplicati/duplicati/releases/tag/v2.1.0.107_canary_2025-01-17) has a refactored Backblaze B2 backend that from has the high memory usage (caused by using the deprecated WebClient) solved.

**Comment by wjansenw** [comment]
Thanks, will test once I have some time to reconfigure back to B2.

Op za 18 jan 2025 11:56 schreef marceloduplicati ***@***.***>:

**Comment by wjansenw** [comment]
Issue not fixed. Still getting the error message:

```
2025-01-18 17:07:17 +01 - [Error-Duplicati.Library.Main.Controller-FailedOperation]: The operation Backup has failed with error: Exception of type 'System.OutOfMemoryException' was thrown. (Exception of type 'System.OutOfMemoryException' was thrown.) (One or more errors occurred. (Exception of type 'System.OutOfMemoryException' was thrown.))
AggregateException: Exception of type 'System.OutOfMemoryException' was thrown. (Exception of type 'System.OutOfMemoryException' was thrown.) (One or more errors occurred. (Exception of type 'System.OutOfMemoryException' was thrown.))
```

**Comment by marceloduplicati** [comment]
@wjansenw Would you mind double checking that.

I have made another test, using docker and even after transferring 2GB files to B2 the memory usage never went over 250 Mb as can be seen on the graph

![Image](https://github.com/user-attachments/assets/f6991548-c30b-4bcc-8b04-c6cd9d943801)

On my docker, I am using the latest canary.

`
services:
  duplicati:
    container_name: duplicati
    image: duplicati/duplicati:canary
`

When using docker-compose don't forget to add **--pull always** to make sure it pulls the latest canary.

**Comment by wjansenw** [comment]
Memory usage seems to be OK, however it does give memory exceptions every now and then

![Image](https://github.com/user-attachments/assets/7c8678d3-e632-482e-bafe-453cd4bf796b)

What I seem to have observed: 
- multiple attempts to upload, and it might work after some attempts
- but in the end, one of the files might not upload and give a final memory error

Note that I have remote volume size set to 50 Mbyte - so the size of the files is not what is giving the memory exception. 

See attached for a recent log. In the end, all files uploaded succesfully - but some had several attemtps.

`grep -C 20 OutOfMemoryException /data/Duplicati/docker.log > /data/Duplicati/log_context.txt`

[log_context.txt](https://github.com/user-attachments/files/18536792/log_context.txt)

**Comment by marceloduplicati** [comment]
Thanks again for the data. I will experiment with limiting memory on the docker to see if I can replicate.

**Comment by marceloduplicati** [comment]
I was able to reproduce the out of memory when really pushing the docker down to 128MB only of memory.

Since you can't change the docker memory, I experimented tweaking the garbage collector via environment variables. When using these, even with only 128MB of memory, it no longer runs out of memory.

```
DOTNET_gcServer=0
DOTNET_gcConcurrent=0
DOTNET_GCHighMemPercent=50
DOTNET_GCConserveMemory=9
DOTNET_GCHeapHardLimit=67108864
```
