### ISSUE TITLE
Error: Attempted to perform an unauthorized operation

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#638]
_From [pcegghead](https://code.google.com/u/pcegghead/) on June 03, 2012 19:48:33_

Getting the below error whil trying to backup locked Outlook PST files on windwows Pro 7. VSS services is running. Running Duplicati as Admin.
Have snapshot-policy=required in options. This worked under Windows XP.
("vssadmin list writers" lists 11 writers)

Error: Attempted to perform an unauthorized operation.

Error: System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at Alphaleonis.Win32.Vss.VssBackupComponents..ctor()
   at Alphaleonis.Win32.Vss.VssImplementation.CreateVssBackupComponents()
   at Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Dictionary`2 options)
   at Duplicati.Library.Snapshots.SnapshotUtility.CreateSnapshot(String[] folders, Dictionary`2 options)
   at Duplicati.Library.Main.RSync.RSyncDir.InitiateMultiPassDiff(Boolean full, Options options)
   at Duplicati.Library.Main.Interface.Backup(String[] sources)
   at Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
Cleanup output:

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=638_

**Comment by rlweiner** [comment]
I started getting this error with Duplicati 1.3.4 after upgrading to Windows 10. The answer was simple: the Volume Shadow Copy (VSS) service had changed to Manual during the upgrade and wasn't starting. I changed it to Automatic, started it manually, and all is well.

**Comment by agrajaghh** [comment]
good that you got it running again :)

I'll close this, since Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
