### ISSUE TITLE
error: failed to retrieve file listing: invalid server's version string

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#700]
_From [trav...@pccaresupport.com](https://code.google.com/u/112583280704320742432/) on August 20, 2012 17:36:38_

What steps will reproduce the problem? 1.  Create a duplicati backup using ssh as backup source
2.  Run a full initial backup
2.  At a later time, run an incremental (i.e. non-full) backup What is the expected output? What do you see instead? Instead of running, the backup fails and reports the following error output in the log:

Error: Failed to retrieve file listing: invalid server's version String

Error: System.Exception: Failed to retrieve file listing: invalid server's version String ---> Tamir.SharpSsh.jsch.JSchException: invalid server's version String
   at Tamir.SharpSsh.jsch.Session.connect(Int32 connectTimeout)
   at Tamir.SharpSsh.SshBase.ConnectSession(Int32 tcpPort)
   at Tamir.SharpSsh.SshBase.Connect(Int32 tcpPort)
   at Duplicati.Library.Backend.SSH.CreateManagedConnection(Boolean changeDir)
   at Duplicati.Library.Backend.SSH.ListManaged()
   at Duplicati.Library.Backend.SSH.List()
   at Duplicati.Library.Main.BackendWrapper.ListInternal()
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.BackendWrapper.ProtectedInvoke(String methodname, Object[] arguments)
   at Duplicati.Library.Main.BackendWrapper.List(Boolean filter)
   at Duplicati.Library.Main.BackendWrapper.GetBackupSets()
   at Duplicati.Library.Main.Interface.Backup(String[] sources)
   at Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
InnerError: Tamir.SharpSsh.jsch.JSchException: invalid server's version String
   at Tamir.SharpSsh.jsch.Session.connect(Int32 connectTimeout)
   at Tamir.SharpSsh.SshBase.ConnectSession(Int32 tcpPort)
   at Tamir.SharpSsh.SshBase.Connect(Int32 tcpPort)
   at Duplicati.Library.Backend.SSH.CreateManagedConnection(Boolean changeDir)
   at Duplicati.Library.Backend.SSH.ListManaged()
   at Duplicati.Library.Backend.SSH.List()
   at Duplicati.Library.Main.BackendWrapper.ListInternal()
Cleanup output:
Error: System.Exception: Failed to retrieve file listing: invalid server's version String ---> Tamir.SharpSsh.jsch.JSchException: invalid server's version String
   at Tamir.SharpSsh.jsch.Session.connect(Int32 connectTimeout)
   at Tamir.SharpSsh.SshBase.ConnectSession(Int32 tcpPort)
   at Tamir.SharpSsh.SshBase.Connect(Int32 tcpPort)
   at Duplicati.Library.Backend.SSH.CreateManagedConnection(Boolean changeDir)
   at Duplicati.Library.Backend.SSH.ListManaged()
   at Duplicati.Library.Backend.SSH.List()
   at Duplicati.Library.Main.BackendWrapper.ListInternal()
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.BackendWrapper.ProtectedInvoke(String methodname, Object[] arguments)
   at Duplicati.Library.Main.BackendWrapper.List(Boolean filter)
   at Duplicati.Library.Main.BackendWrapper.GetBackupSets()
   at Duplicati.Library.Main.Interface.DeleteAllButNFull()
   at Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
InnerError: Tamir.SharpSsh.jsch.JSchException: invalid server's version String
   at Tamir.SharpSsh.jsch.Session.connect(Int32 connectTimeout)
   at Tamir.SharpSsh.SshBase.ConnectSession(Int32 tcpPort)
   at Tamir.SharpSsh.SshBase.Connect(Int32 tcpPort)
   at Duplicati.Library.Backend.SSH.CreateManagedConnection(Boolean changeDir)
   at Duplicati.Library.Backend.SSH.ListManaged()
   at Duplicati.Library.Backend.SSH.List()
   at Duplicati.Library.Main.BackendWrapper.ListInternal() What version of Duplicati are you using? On what operating system? 64 bit duplicati on windows 7 64 bit.  newest version of duplicati, 1.3.2 What backend (destination) are you using? ubuntu server 12.04 64 bit with open ssh. Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=688_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
