### ISSUE TITLE
 Message has been altered, do not trust content

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#831]
_From [m0sm...@gmail.com](https://code.google.com/u/111456164863504157848/) on March 21, 2013 16:58:50_

What steps will reproduce the problem? 1. Just try and run a backup 2. 3. What is the expected output? What do you see instead? Instead of the backup, I get an error message:
Error: Message has been altered, do not trust content

Error: System.Security.Cryptography.CryptographicException: Message has been altered, do not trust content ---> System.IO.InvalidDataException: Message has been altered, do not trust content
   at SharpAESCrypt.SharpAESCrypt.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Duplicati.Library.Utility.Utility.CopyStream(Stream source, Stream target, Boolean tryRewindSource)
   at Duplicati.Library.Encryption.EncryptionBase.Decrypt(Stream input, Stream output)
   at Duplicati.Library.Encryption.EncryptionBase.Decrypt(String inputfile, String outputfile)
   at Duplicati.Library.Main.BackendWrapper.GetInternal(BackupEntryBase remote, Manifestfile manifest, String filename, HashEntry hash)
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.BackendWrapper.ProtectedInvoke(String methodname, Object[] arguments)
   at Duplicati.Library.Main.BackendWrapper.Get(BackupEntryBase remote, Manifestfile manifest, String filename, HashEntry hash)
   at Duplicati.Library.Main.Interface.GetManifest(BackendWrapper backend, ManifestEntry entry)
   at Duplicati.Library.Main.Interface.VerifyManifestChain(BackendWrapper backend, ManifestEntry entry)
   at Duplicati.Library.Main.Interface.VerifyBackupChainWithFiles(BackendWrapper backend, ManifestEntry entry)
   at Duplicati.Library.Main.Interface.Backup(String[] sources)
   at Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
InnerError: System.IO.InvalidDataException: Message has been altered, do not trust content
   at SharpAESCrypt.SharpAESCrypt.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Duplicati.Library.Utility.Utility.CopyStream(Stream source, Stream target, Boolean tryRewindSource)
   at Duplicati.Library.Encryption.EncryptionBase.Decrypt(Stream input, Stream output)
   at Duplicati.Library.Encryption.EncryptionBase.Decrypt(String inputfile, String outputfile)
   at Duplicati.Library.Main.BackendWrapper.GetInternal(BackupEntryBase remote, Manifestfile manifest, String filename, HashEntry hash)
Cleanup output: What version of Duplicati are you using? On what operating system? Windows 7 64
Duplicati 1.3.4 What backend (destination) are you using? SSH Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=804_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
