### ISSUE TITLE
Error: Failed to decrypt data (invalid passphrase?): Invalid password or corrupted data

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#838]
_From [tanyap...@gmail.com](https://code.google.com/u/106235702908873606950/) on April 05, 2013 20:37:05_

What steps will reproduce the problem? 1. automatically running backup
2. forcing backup What is the expected output? What do you see instead? Run backup. Does not backup What version of Duplicati are you using? On what operating system? Version 2.1; Windows 7 What backend (destination) are you using? File Please provide any additional information below. Error: Failed to decrypt data (invalid passphrase?): Invalid password or corrupted data

Error: System.Security.Cryptography.CryptographicException: Failed to decrypt data (invalid passphrase?): Invalid password or corrupted data ---> System.Security.Cryptography.CryptographicException: Invalid password or corrupted data
   at SharpAESCrypt.SharpAESCrypt.ReadEncryptionHeader(String password)
   at SharpAESCrypt.SharpAESCrypt..ctor(String password, Stream stream, OperationMode mode)
   at Duplicati.Library.Encryption.AESEncryption.Decrypt(Stream input)
   at Duplicati.Library.Encryption.EncryptionBase.Decrypt(Stream input, Stream output)
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.BackendWrapper.ProtectedInvoke(String methodname, Object[] arguments)
   at Duplicati.Library.Main.Interface.GetManifest(BackendWrapper backend, ManifestEntry entry)
   at Duplicati.Library.Main.Interface.VerifyManifestChain(BackendWrapper backend, ManifestEntry entry)
   at Duplicati.Library.Main.Interface.VerifyBackupChainWithFiles(BackendWrapper backend, ManifestEntry entry)
   at Duplicati.Library.Main.Interface.Backup(String[] sources)
   at Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
InnerError: System.Security.Cryptography.CryptographicException: Invalid password or corrupted data
   at SharpAESCrypt.SharpAESCrypt.ReadEncryptionHeader(String password)
   at SharpAESCrypt.SharpAESCrypt..ctor(String password, Stream stream, OperationMode mode)
   at Duplicati.Library.Encryption.AESEncryption.Decrypt(Stream input)
   at Duplicati.Library.Encryption.EncryptionBase.Decrypt(Stream input, Stream output)
Cleanup output:

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=811_

**Comment by babaz8** [comment]
> _From [pcoolw...@gmail.com](https://code.google.com/u/107476657228052373605/) on November 08, 2013 17:56:50_
> 
> It says password incorrect or corrupted files.
> Both things are impossible.
> 
> 1. The password had been entered in clear through the command line, and verified by running decrypt, months ago.
> 2. The files with the encryption software had been also backed up in a ZIP archive.
>    This means checksums granting genuinity of the files.
> 
> Now if I encrypt I can also decrypt files, just as it happened months ago.
> But I am not going to wait some months to discover that the decryption no longer works.
> 
> I shall stay away 1000 miles from this software and from this algorithm.

I, unfortunately, experienced the same today. It was really a nightmare and that could have been a disaster if I haven't got another backup a manual one that I did.
How is possible to have this type of bugs in software. I thought it was a reliable software I also donate to the developers and used for so many installations. Now I need to get rid of it because is clearly unreliable.

**Comment by drwtsn32x** [comment]
@babaz8 - are you using a password manager?  There is a known problem where browser password managers can foul up the hidden password input box during a restore operation.  Try temporarily disabling your password manager and try again.

**Comment by babaz8** [comment]
> @babaz8 - are you using a password manager? There is a known problem where browser password managers can foul up the hidden password input box during a restore operation. Try temporarily disabling your password manager and try again.

I've opened a private / incognito browsing window and it works. I've lost years of my life with this scary thing ...
Are the developers aware of this ?
Thank you anyway for your feedback.

**Comment by drwtsn32x** [comment]
@babaz8 - yes, issue https://github.com/duplicati/duplicati/issues/4102 here in the project and also discussions on the web forums.  this does bite a lot of people so hopefully it can be resolved soon!

**Comment by drwtsn32x** [comment]
also issue https://github.com/duplicati/duplicati/issues/3363

there may be more!
