### ISSUE TITLE
Skydrive Login failure (Internal Server Error)

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#872]
_From [cpmdxe...@gmail.com](https://code.google.com/u/101206181693377932143/) on July 10, 2013 13:19:43_

What steps will reproduce the problem? 1. Create a new backup that uploads to SkyDrive. Run this backup. What is the expected output? What do you see instead? Expected: It works.
Actual:

Error: Failed to retrieve file listing: The remote server returned an error: (500) Internal Server Error.

Error: System.Exception: Failed to retrieve file listing: The remote server returned an error: (500) Internal Server Error. ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at Duplicati.Library.Utility.Utility.SafeGetRequestOrResponseStream(WebRequest req, Boolean getRequest)
   at Duplicati.Library.Utility.Utility.SafeGetResponse(WebRequest req)
   at Duplicati.Library.Backend.SkyDriveSession.GetLoginUrl()
   at Duplicati.Library.Backend.SkyDriveSession..ctor(String username, String password, String rootfolder, String prefix, Boolean createFolders)
   at Duplicati.Library.Backend.SkyDrive.CreateSession(Boolean createFolders)
   at Duplicati.Library.Backend.SkyDrive.List()
   at Duplicati.Library.Main.BackendWrapper.ListInternal()
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.BackendWrapper.ProtectedInvoke(String methodname, Object[] arguments)
   at Duplicati.Library.Main.BackendWrapper.List(Boolean filter)
   at Duplicati.Library.Main.BackendWrapper.GetBackupSets()
   at Duplicati.Library.Main.Interface.Backup(String[] sources)
   at Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
InnerError: System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at Duplicati.Library.Utility.Utility.SafeGetRequestOrResponseStream(WebRequest req, Boolean getRequest)
   at Duplicati.Library.Utility.Utility.SafeGetResponse(WebRequest req)
   at Duplicati.Library.Backend.SkyDriveSession.GetLoginUrl()
   at Duplicati.Library.Backend.SkyDriveSession..ctor(String username, String password, String rootfolder, String prefix, Boolean createFolders)
   at Duplicati.Library.Backend.SkyDrive.CreateSession(Boolean createFolders)
   at Duplicati.Library.Backend.SkyDrive.List()
   at Duplicati.Library.Main.BackendWrapper.ListInternal()
Cleanup output:
Error: System.Exception: Failed to retrieve file listing: The remote server returned an error: (500) Internal Server Error. ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at Duplicati.Library.Utility.Utility.SafeGetRequestOrResponseStream(WebRequest req, Boolean getRequest)
   at Duplicati.Library.Utility.Utility.SafeGetResponse(WebRequest req)
   at Duplicati.Library.Backend.SkyDriveSession.GetLoginUrl()
   at Duplicati.Library.Backend.SkyDriveSession..ctor(String username, String password, String rootfolder, String prefix, Boolean createFolders)
   at Duplicati.Library.Backend.SkyDrive.CreateSession(Boolean createFolders)
   at Duplicati.Library.Backend.SkyDrive.List()
   at Duplicati.Library.Main.BackendWrapper.ListInternal()
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.BackendWrapper.ProtectedInvoke(String methodname, Object[] arguments)
   at Duplicati.Library.Main.BackendWrapper.List(Boolean filter)
   at Duplicati.Library.Main.BackendWrapper.GetBackupSets()
   at Duplicati.Library.Main.Interface.DeleteAllButNFull()
   at Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
InnerError: System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at Duplicati.Library.Utility.Utility.SafeGetRequestOrResponseStream(WebRequest req, Boolean getRequest)
   at Duplicati.Library.Utility.Utility.SafeGetResponse(WebRequest req)
   at Duplicati.Library.Backend.SkyDriveSession.GetLoginUrl()
   at Duplicati.Library.Backend.SkyDriveSession..ctor(String username, String password, String rootfolder, String prefix, Boolean createFolders)
   at Duplicati.Library.Backend.SkyDrive.CreateSession(Boolean createFolders)
   at Duplicati.Library.Backend.SkyDrive.List()
   at Duplicati.Library.Main.BackendWrapper.ListInternal() What version of Duplicati are you using? On what operating system? 1.3.4 What backend (destination) are you using? SkyDrive Please provide any additional information below. This started happening only yesterday, and nothing has changed since a long time.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=845_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
