### ISSUE TITLE
Could not load file

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#962]
_From [BBGMetal...@gmail.com](https://code.google.com/u/108231728428989651467/) on January 07, 2014 16:02:56_

Backup abort this is the message of the error:
Could not load file:
"duplicati-full-content.20140107T143710Z.vol1.zip.aes": The request was aborted: The request was canceled.

Error: System.Exception: Impossibile caricare il file "duplicati-full-content.20140107T143710Z.vol1.zip.aes": The request was aborted: The request was canceled. ---> System.Net.WebException: The request was aborted: The request was canceled. ---> System.IO.IOException: Cannot close stream until all bytes are written.
   at System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean aborting)
   --- End of inner exception stack trace ---
   at System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean aborting)
   at System.Net.ConnectStream.System.Net.ICloseEx.CloseEx(CloseExState closeState)
   at System.Net.ConnectStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.Stream.Dispose()
   at Duplicati.Library.Backend.GoogleDocs.Put(String remotename, Stream stream)
   at Duplicati.Library.Main.BackendWrapper.PutInternal(BackupEntryBase remote, String filename)
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.BackendWrapper.Put(BackupEntryBase remote, String filename, Boolean forcesync)
   at Duplicati.Library.Main.Interface.Backup(String[] sources)
   at Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
InnerError: System.Net.WebException: The request was aborted: The request was canceled. ---> System.IO.IOException: Cannot close stream until all bytes are written.
   at System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean aborting)
   --- End of inner exception stack trace ---
   at System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean aborting)
   at System.Net.ConnectStream.System.Net.ICloseEx.CloseEx(CloseExState closeState)
   at System.Net.ConnectStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.Stream.Dispose()
   at Duplicati.Library.Backend.GoogleDocs.Put(String remotename, Stream stream)
   at Duplicati.Library.Main.BackendWrapper.PutInternal(BackupEntryBase remote, String filename)
InnerError: System.IO.IOException: Cannot close stream until all bytes are written.
   at System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean aborting)
Risultato della pulizia:

Thanks a lot 
Fabrizio (Italy)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=935_
##

**Comment by kenkendk** [comment]
We are no longer maintaining 1.3.x
