### ISSUE TITLE
Snap-shot policy resulting Error

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#963]
_From [vinod.aa...@gmail.com](https://code.google.com/u/102558265682829445326/) on January 09, 2014 14:40:51_

What steps will reproduce the problem? 1.Installed MS Visual C++ in my Windows 7 32-bit, working with as member of machine administrator
2.Enabled the snap-shot policy with "required" parameter 
3.Any new or exisiting backup job getting failed. What is the expected output? What do you see instead? The existing backup jobs should not get affected, new bcackup for outlook.pst should also get started succesfully. Instead getting-Error: Attempted to perform an unauthorized operation. What version of Duplicati are you using? On what operating system? Version1.3.4, Windows7 32Bit and Windows 2003 Server What backend (destination) are you using? FTP (on local network) Please provide any additional information below. Error: Attempted to perform an unauthorized operation.

Error: System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at Alphaleonis.Win32.Vss.ThrowException(Int32 errorCode)
   at Alphaleonis.Win32.Vss.VssBackupComponents..ctor()
   at Alphaleonis.Win32.Vss.VssImplementation.CreateVssBackupComponents()
   at Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Dictionary`2 options)
   at Duplicati.Library.Snapshots.SnapshotUtility.CreateSnapshot(String[] folders, Dictionary`2 options)
   at Duplicati.Library.Main.RSync.RSyncDir.InitiateMultiPassDiff(Boolean full, Options options)
   at Duplicati.Library.Main.Interface.Backup(String[] sources)
   at Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
Cleanup output:

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=936_
##

**Comment by kenkendk** [comment]
Closing for lack of feedback
